(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,200,200);


(lib.Symbol28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEF8F0").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Symbol27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiGCSQgOgFgJgGQgJgFgFgIQgFgIAAgJQAAgLAHgHQAHgJAMgEQgGgDgEgGQgEgGAAgJQAAgIAFgIQAGgIALgFQgMgHgIgLQgHgLAAgPQAAgNAFgKQAFgKAJgHQAJgGAMgEQAMgEAPABQAVgBAQAJIAxAAIAAAQQAAAEgCACQgDACgFACIgNACQADAIAAAJQAAAMgFAKQgFAJgJAHQgJAHgMAEQgMAEgOAAQgJAAgIgBQgHADAAAGQAAAFAFABQAFADAHABIARABIATAAQALABAJACQAJACAIAFQAIAFAEAHQAFAIAAALQAAAMgGAKQgFAKgKAJQgLAIgPAFQgPAFgUAAQgTAAgOgDgAiFBZQgEAEAAAGQAAAFACACQACAFAEACQAEACAIABQAHACAKAAQALAAAIgCQAIgBAEgDQAFgDACgDQACgEAAgEQAAgFgDgDIgHgDQgFgDgGAAIgOgBIgOAAIgPgCQgGADgDAFgAh6goQgHAGAAAMQAAALAHAHQAGAGAOAAQANAAAHgGQAGgHAAgLQAAgMgGgGQgHgGgNgBQgOABgGAGgAAECRIAAjbIAbAAQAJAAACAIIAEAOIALgKQAFgFAHgEIANgEIAQgCQAOAAALAGQALAFAIALQAIALAFAQQAFAPAAAUQAAATgFAQQgGAPgJAMQgJALgOAHQgNAGgQABQgNAAgKgFQgJgDgIgIIAABDgABAgmQgIAEgIAKIAABIQAHAHAHADQAIACAIAAQAIAAAHgCQAGgDAFgHQAFgGACgLQADgKAAgOQAAgNgDgJQgBgKgFgGQgDgGgGgDQgGgCgHAAQgLgBgIAFgAKCBcQgFgDgDgDQgEgDgCgGQgCgEAAgFQAAgFACgFQACgFAEgEIAIgGQAFgBAFAAQAGAAAFABIAIAGQAEAEACAFQACAFAAAFQAAAFgCAEQgCAGgEADQgEADgEADQgFACgGAAQgFAAgFgCgAGYBXQgQgFgLgMQgLgLgGgQQgGgPAAgUQAAgTAGgQQAGgQALgLQALgKAQgHQAPgFATAAQASAAAQAFQAPAHALAKQALALAGAQQAGAQAAATQAAAUgGAPQgGAQgLALQgLAMgPAFQgQAHgSAAQgTAAgPgHgAGdgeQgJANAAAZQAAAaAJANQAJANAUAAQATAAAJgNQAJgNAAgaQAAgZgJgNQgJgNgTAAQgUAAgJANgAnoBXQgPgFgLgMQgLgLgGgQQgGgPAAgUQAAgTAGgQQAGgQALgLQALgKAPgHQAQgFATAAQASAAAQAFQAPAHALAKQALALAFAQQAGAQAAATQAAAUgGAPQgFAQgLALQgLAMgPAFQgQAHgSAAQgTAAgQgHgAnigeQgKANAAAZQAAAaAKANQAJANAUAAQASAAAKgNQAJgNAAgaQAAgZgJgNQgKgNgSAAQgUAAgJANgAqnBZQgKgFgHgIQgHgIgEgMQgEgMAAgNIAAhpIAtAAIAABpQAAANAGAIQAGAIANAAQAJAAAIgEQAJgFAHgHIAAh2IAsAAIAAClIgbAAQgIAAgDgHIgDgMIgKAIIgLAHQgGADgHACIgPACQgOgBgLgEgAvMBaQgJgDgGgGQgGgGgDgJQgDgJAAgKIAAhZIgQAAQgDAAgDgCQgCgDAAgEIAAgRIAagGIAKgrQABgGAIAAIAYAAIAAAyIAqAAIAAAfIgqAAIAABVQAAAIADADQADAFAGAAIAGgBIADgCIADgCIADAAIADAAIADAEIAOAVQgKAHgLAEQgMADgNABQgLgBgIgDgAPUBbIAAhoQAAgOgHgIQgGgIgNABQgJAAgIADQgJAEgHAIIAAB2IgsAAIAAilIAbAAQAJAAACAIIADALIAKgJIAMgHQAGgCAHgCQAHgCAIABQAOAAAKAEQAKAFAIAIQAHAJADALQAEAMAAAOIAABogALzBbIhBilIAkAAQAFAAAEACQADACABAEIAcBRIAEARIAFAQQABgJACgHIAFgRIAdhRQABgEADgCQAEgCAEAAIAjAAIhBClgAIoBbIAAilIAsAAIAAClgAEhBbIAAhoQAAgOgGgIQgGgIgNABQgKAAgHADQgJAEgHAIIAAB2IgtAAIAAjvIAtAAIAABbIAKgIQAFgEAFgCQAGgDAHgBQAGgCAHABQAOAAALAEQAKAFAHAIQAIAJADALQAEAMAAAOIAABogAjyBbIAAhoQAAgOgGgIQgHgIgNABQgJAAgIADQgIAEgIAIIAAB2IgsAAIAAilIAbAAQAJAAACAIIAEALIAKgJIALgHQAGgCAHgCQAHgCAIABQAOAAALAEQAKAFAHAIQAHAJAEALQADAMAAAOIAABogAsTBbIAAhoQAAgOgGgIQgHgIgNABQgJAAgIADQgIAEgIAIIAAB2IgsAAIAAjvIAsAAIAABbIAKgIQAFgEAGgCQAFgDAHgBQAHgCAHABQAOAAALAEQAKAFAHAIQAHAJAEALQADAMAAAOIAABogAIzhgQgFgCgDgEQgEgDgCgGQgCgEAAgGQAAgGACgEQACgGAEgDQADgEAFgCQAFgCAGAAQAGAAAEACQAGACADAEQAEADACAGQADAEAAAGQAAAGgDAEQgCAGgEADQgDAEgGACQgEACgGAAQgGAAgFgCg");
	this.shape.setTransform(126.525,236.15);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFCC66","#FF915C"],[0,0.502],-126.8,0,126.8,0).s().p("AzBE4QgyAAAAg1IAAoFQAAg1AyAAMAmDAAAQAyAAAAA1IAAIFQAAA1gyAAg");
	this.shape_1.setTransform(126.0285,236.4898,0.9949,1.2954);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.1,196.1,252.29999999999998,80.79999999999998);


(lib.Symbol25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#007E9E").s().p("AELCkQgNgOAAgYIAAiMQAAgJARAAIAGAAQARAAAAAJIAACFQgBANAGAGQAFAGAMAAQALAAAJgGQAKgGAFgKIAAiIQAAgJARAAIAGAAQAQAAAAAJIAACCQAAAXADALIACAPQgBADgFACQgGADgGABIgKABQgHAAgBgGIgGgUQgIAMgNAJQgOAIgPAAQgYAAgMgOgAJ4BNQAAg1AUgYQAUgaAlAAQAiAAAQAaQARAZAAAxQAAARgOAAIhZAAQAAAcALANQAKANAUAAQANAAAKgDIAQgHIAJgDQADAAACADIADAJIABAIQAAAFgIAGQgJAGgOAEQgNAEgPAAQhQAAAAhkgAKrASQgKAOAAAeIBBAAQAAg5geAAQgRAAgIANgABLBNQAAg1AVgYQAUgaAkAAQAjAAAQAaQAQAZAAAxQAAARgOAAIhYAAQAAAcAKANQAKANAUAAQAOAAAJgDIARgHIAIgDQADAAACADIAEAJIABAIQAAAFgJAGQgJAGgOAEQgNAEgPAAQhQAAAAhkgAB+ASQgJAOAAAeIBAAAQAAg5geAAQgQAAgJANgAIUCvQgFAAgFgBQgFgCgBgGIguixIgBgGQABgHAQAAIAIAAQAGAAAFACQAEABABAEIAfCZIABAAIAgiZQAAgEAEgBQAFgCAGAAIAIAAQAPAAAAAHIAAADIAAADIguCxQgCAGgFACQgDABgGAAgAAQCvQgJAAgEgCQgDgDAAgEIAAi0QAAgFADgCQAEgDAJAAIAFAAQAKAAAEADQADACAAAFIAAC0QAAAEgDADQgEACgKAAgAhECvQgJAAgEgCQgEgDAAgEIAAiEQAAgNgFgHQgHgHgNAAQgJAAgGAEQgHADgEAGIgHAJIAACJQAAAEgEADQgEACgJAAIgGAAQgJAAgDgCQgEgDAAgEIAAkLQAAgJAQAAIAGAAQARAAAAAJIAABlQAHgKANgIQANgIAPAAQAVAAAOANQAPAMAAAbIAACMQAAAEgEADQgEACgJAAgAkrCvQgKAAgEgCQgEgDAAgEIAAiEQAAgNgFgHQgGgHgMAAQgKAAgJAHQgIAHgEAIIAAADIAACGQAAAEgEADQgEACgJAAIgGAAQgJAAgEgCQgDgDgBgEIAAiEQABgNgGgHQgFgHgMAAQgIAAgHAEQgGADgEAGIgHAJIAACJQAAAEgDADQgEACgKAAIgFAAQgJAAgEgCQgEgDAAgEIAAiCQAAgYgCgLIgCgPQAAgDAGgCQAFgCAGgBIALgBQAGAAACAGIAFATQAJgLAMgIQANgJAPAAQAOAAAMAHQANAHAFAQQAIgMANgJQANgJAQAAQATAAAOANQAOAMAAAbIAACMQAAAEgEADQgEACgJAAgAo9CvQgJAAgDgCQgFgDAAgEIAAi0QAAgFAFgCQADgDAJAAIAGAAQAKAAADADQAEACAAAFIAAC0QAAAEgEADQgDACgKAAgAq7CvQgRAAAAgJIAAjdIgzAAQgIAAAAgOIAAgIQAAgNAIAAICQAAQAIAAAAANIAAAIQAAAOgIAAIgzAAIAADdQAAAJgRAAgALYgtQgFgCgDgGIgMgTIgMATQgDAGgEACQgEACgIAAQgKAAAAgFIABgFIACgHIANgbQACgGAHgCQAGgCAKAAQALAAAGACQAGACADAGIAMAbIACAHIACAFQAAAFgLAAQgHAAgEgCgACsgtQgFgCgDgGIgMgTIgMATQgDAGgEACQgFACgIAAQgKAAAAgFIABgFIADgHIAMgbQADgGAGgCQAHgCAKAAQAKAAAHACQAGACADAGIALAbIADAHIABAFQABAFgLAAQgIAAgDgCgAo7gsQgEgCgFgHIgRgWIgHgKQgDgDAAgDQABgDAEgCQAEgBAIAAQANAAAFACQAGADACAFIAMAbIADAHIABAFQAAAFgKAAQgJAAgEgBgAADgzQgDgCAAgEIAAgZQAAgFADgCQAFgDALAAQAKAAAFADQAFACAAAFIAAAZQAAAEgFACQgFADgKAAQgLAAgFgDgACOhuQgEgEAAgCQAAgDAFgEIAJgJQAFgFgBgIQAAgGgDgDQgDgCgFAAQgFAAgDABIgFACQgCAAgEgFQgEgFAAgDQAAgDAJgEQAJgEAKAAQALAAALAHQAKAGAAAPQAAAJgEAIQgFAIgFAFQgHAGgFADQgFAEgDAAQgDAAgDgEgALDhwQgEgBgFgHIgRgXIgHgJQgCgEAAgCQAAgEADgBIANgBQANAAAFACQAGACACAGIAMAbIADAHIABAFQAAAFgKAAQgJAAgEgCg");
	this.shape.setTransform(93.1,11.775);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(15.5,-6,155.2,35.6);


(lib.Symbol23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#007E9E").s().p("AGoBeQgOgTAAgnQAAgmAOgTQAOgSAbAAQAbAAAOASQAOATAAAmQAAAngOATQgOATgbAAQgbAAgOgTgAG6gGQgIANAAAdQAAAeAIAOQAHANAQAAQAQAAAHgNQAIgOAAgeQAAgdgIgNQgHgOgQAAQgQAAgHAOgAA0BeQgOgSAAgoQAAgmAPgSQAOgTAeAAIANABIAKACQAFACAAAEIgBAJQgDAEgCAAIgIgBQgFgBgIAAQgUAAgIANQgJAMABAeQAAAfAIANQAIANARAAIAIAAIAHgCIAAgrIgSAAQgFAAAAgIIAAgEQAAgIAFAAIAiAAQAGAAABAHIAAA+IgCAEIgEAEQgGADgJADQgKACgJAAQgbAAgOgTgAjHBeQgOgTgBgnQABgmAOgTQANgSAbAAQAQAAALAGIABAAQAGAAACgCQACgCAAgDQAAgFgDgDQgCgEAAgCIACgDIAEgDIAEgBQADAAABADIAEAGIABAHQAAAJgFAGQgDAEgHABIAEAEQAOATgBAmQABAngOATQgOATgbAAQgbAAgNgTgAi3gGQgHANAAAdQAAAeAHAOQAIANAQAAQAQAAAIgNQAGgOAAgeQAAgdgGgNQgIgOgQAAQgQAAgIAOgAlCBmQgMgLAAgWIAAhmQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAABgBQACgBAFAAIADAAQAGAAACABQABABAAAAQABABAAAAQAAABAAAAQAAABAAAAIAABnQAAALAHAGQAHAGAMAAQAMAAAGgGQAIgGAAgLIAAhnQgBgFAKAAIAFAAQAFAAACgCIACgFQAAgFgDgEIgCgFQAAAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAIAFgDIADgCQACAAADADIADAHIABAHQAAAJgEAGQgEADgGACIAABjQAAAWgNALQgNALgXAAQgXAAgOgLgAIpBwQgFAAgDgBQAAgBgBAAQAAAAAAgBQgBgBAAAAQAAgBAAAAIAAiMQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAgBQADgBAFAAIAEAAQAFAAADABQAAABAAAAQABABAAAAQAAABAAAAQABABAAAAIAACMQAAAAgBABQAAAAAAABQAAABgBAAQAAAAAAABQgDABgFAAgAF1BwQgFAAgDgBQAAgBAAAAQgBAAAAgBQAAgBAAAAQgBgBAAAAIAAg/IguAAIAAA/QgBAAAAABQAAAAAAABQAAABgBAAQAAAAgBABQgCABgFAAIgEAAQgFAAgCgBQgBgBgBAAQAAAAAAgBQgBgBAAAAQAAgBAAAAIAAiMQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAABgBQACgBAFAAIAEAAQAFAAACABQABABAAAAQABABAAAAQAAABAAAAQAAABABAAIAAA6IAuAAIAAg6QAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQADgBAFAAIAEAAQAFAAADABQAAABAAAAQABABAAAAQAAABAAAAQABABAAAAIAACMQAAAAgBABQAAAAAAABQAAABgBAAQAAAAAAABQgDABgFAAgADGBwQgFAAgDgBQgBgBAAAAQgBAAAAgBQAAgBAAAAQAAgBAAAAIAAiKQgBgHAIAAIAhAAQAqAAAAAsQAAAsgqAAIgRAAIAAA5QAAAAAAABQAAAAgBABQAAABAAAAQgBAAAAABQgDABgFAAgADTAeIARAAQAKAAAFgFQAEgGAAgNQAAgMgEgGQgFgGgKAAIgRAAgAgBBwIgHgBQgCgBgCgDIgphXIgDgGIgCgIIgBABIAAAHIABAHIAABWQAAAAAAABQAAAAgBABQAAABAAAAQgBAAgBABQgCABgFAAIgDAAQgFAAgDgBQAAgBgBAAQAAAAAAgBQgBgBAAAAQAAgBAAAAIAAiMQAAgFAKAAIAFAAIAHABQADABACADIApBVIADAHIACAHIABAAIAAgHIgBgHIAAhVQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAgBQACgBAFAAIADAAQAFAAACABQABABAAAAQABABAAAAQAAABAAAAQAAABAAAAIAACMQAAAFgJAAgAl5BwQgFAAgDgBQgBgBAAAAQAAAAgBgBQAAgBAAAAQAAgBAAAAIAAg/IgvAAIAAA/QAAAAAAABQAAAAgBABQAAABAAAAQgBAAgBABQgCABgFAAIgEAAQgEAAgDgBQgBgBAAAAQgBAAAAgBQAAgBAAAAQAAgBAAAAIAAiMQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQADgBAEAAIAEAAQAFAAACABQABABABAAQAAABAAAAQABABAAAAQAAABAAAAIAAA6IAvAAIAAg6QAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQADgBAFAAIADAAQAFAAADABQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAIAACMQAAAAAAABQAAAAAAABQgBABAAAAQAAAAgBABQgDABgFAAgAoKBwQgKAAAAgFIAAh9IgdAAQgEAAAAgIIAAgEQAAgIAEAAIBRAAQAFAAAAAIIAAAEQAAAIgFAAIgdAAIAAB9QAAAFgJAAgAHfgvIgEgCIgJgJIgLAJIgDACIgGABQgFAAAAgDIABgDIACgEIAIgLIAFgDIAJgBIAHABQAEABABACIAJALIACAEIABADIgCACIgEABIgFgBgAHMhOQgBAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBIADgDIAGgEQADgDAAgDQAAgBgBgBQAAAAAAgBQAAAAgBgBQAAAAgBAAQgCgCgDAAIgFABIgDABQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBIgCgFQAAgBAEgCQAGgCAGAAQAHAAAGADQAFADAAAIQAAAFgCAEIgGAHQgDADgDABIgFACQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBg");
	this.shape.setTransform(24.6,84.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF915C").s().p("AA2CTIgCgBIgEgCQgPgEgKgNQgKgNAAgQIAAjXQAAgGgDgDQgFgFgFAAQgMAAAAAOIAADXQAAAQgJANQgKANgQAEIgGACIgEgPQAFgBABgBQAKgDAHgIQAHgJAAgLIAAjXQAAgMAIgIQAIgJALAAIABAAQALAAAIAJQAIAIAAAMIAADXQAAALAHAJQAGAIALADIABAAIAFACQgBAQgCAAIgBAAg");
	this.shape_1.setTransform(24.725,-7.3472);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer_1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AkNE0IgEAAQgHgCABgIQACgIAHACIABAAQA0AKAggXQAdgUAQg1QAJgdAJhAIACgNIADgNIgSANQgSALgYAGIAAAAIgdAaQgZAiALAtQABAHgHABIgCABQgFAAgCgGQgMgzAcgnQgLAGgJAJQgNALgGAKQgCAEgEAAIgEgCIgBAAQgHgDAFgHIACgDQAHgKAMgLQAbgYAngLIAEgCIAGgCQAwgPAPghIABgCQAEgQAEgHIABgCQgNAFgLAAQgJAAgHgCQgDABgDgCQgLgDgOABQgbADgKAXQgDAFgFAAIgCgBQgHgDACgHQAMgbAcgGIAEgBQgPgKgEgIQgCgCABgEQABgCADgCQAHgFADAHQADAHAMAIQAMAIAMAEIAFABQAIACAJAAQAVAAAfgYQAHgGAIgFQANgIAPgEIAGgCQAKgDAHgIQAHgJAAgLIAAjYQAAgMAHgIQAIgJALAAIACAAQALAAAIAJQAIAIAAAMIAADYQAAALAHAJQAGAIALADIABAAIAFACQAYAGASARQAhAYAVAAQAIAAAJgCIAIgCQAWgHANgTQAEgGAHAEQAHADgGAHQgHAKgKAJIADAAQAcAHALAaQADAGgGAEIgEABQgFAAgBgFQgLgXgagDQgJgBgGABIgMADIgBAAIgBAAIgSACIgBAAQgLAAgNgFIABACIAGAPQACACABACIACAFIABACQAMAcAYATIABABQAgAYAhgIQAHgBACAHQACAIgIACIgSACQgiAAgegaIgKgJIgHgHIACAHIACANQAKA9AJAfQAQAyAaAYIALAKQgFgDgFAFQgEAGAGAFIgOgLQgcgagRg1IgLgwQgIAqgYAXQgBACgEAAQgDAAgCgCQgFgFAFgGQAegdgBhEIgCgVIgEgjQgFgVgFgLQgKgQgMgMIgEgCIgLgIQgMgIgOgEIgCgBIgEgBQgPgEgKgNQgKgNAAgQIAAjYQAAgGgDgDQgFgFgFAAQgNAAAAAOIAADYQAAAQgJANQgJANgQAEIgGACQgMADgKAGIgCABIgOAKIgCABQgNAMgJARIgIAXIAAABIgBAFIgDAmIgBAVQABBFAaAcQAFAGgFAFQgCACgEAAIgFgCQgWgYgGgvQgHAkgGAUQgRA3ghAXQgaATgmAAQgPAAgOgDg");
	this.shape_2.setTransform(22.0325,9.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#007E9E").s().p("AAZBbIACgiIgGAAQgVAAgTgDIgCAhQgCAIgGAAIgBAAQgIAAAAgIIADgkQgZgHgYgMQgGgEADgHQABgDADgBQADgBADACQAVALAWAGIADgsQgZgIgTgPQgGgFAEgGQAEgFAFADIACABQAQAMAUAGIAEhBQACgHAHAAQAIABgBAHIgFBFQAWAFAZAAIAFhGQAAgIAIAAQAHACAAAGIgEBFIAYgDIAHgCQAHgCACAJQACAHgIABIgaAFIgFAAIgEABIgDAqIAcgFQAIgCABAHQACAIgHACQgQAEgRACIgDAjQAAAHgIAAQgHgBAAgHgAgSAnQAWAFAYgBIADgsIgDAAQgYAAgTgEg");
	this.shape_3.setTransform(53.9507,42.575);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF915C").s().p("AFYFcIgOgDQhXgUhLgnQhKgngZgoQgYgmgEiAIADieIAAgHQAChNAHgnIABgCQAOAEAMAIIALAIIAEADQAMAMAKAQQAFAKAFAWIAEAjIACAUQABBEgeAdQgFAGAFAEQACADADAAQAEAAABgDQAYgWAIgqIALAwQARA0AcAbIAOALQAUAPAZAHIgEAuQgVgGgWgLQgCgCgEABQgCABgCACQgCAIAGADQAYAMAYAHIgCAkQAAAJAIAAIAAAAQAGAAACgIIADghQATADAWAAIAGAAIgDAhQAAAHAIACQAIAAAAgIIACgjQARgCARgEQAGgCgBgHQgCgHgIACIgcAFIADgrIAFgBIAEAAIAbgFQAHgCgBgHQgCgIgIABIgHACIgYAEIAFhFQAAgHgHgCQgJAAAAAIIgEBGQgaAAgWgFIAEhEQACgHgJgCQgGAAgCAIIgEBBQgUgHgQgMIgCgBIgLgJQgagYgQgyQgJgfgKg8IgCgNIgCgHIAHAHIAKAIQAeAaAiAAIASgCQAIgBgCgIQgCgIgHACQghAIgggYIgBgBQgYgTgMgcIgBgCIgCgFQgBgDgCgCIgGgPIgBgCQANAFALAAIABAAIASgBIABAAIABAAIAMgEQAGgBAJABQAaAEALAWQABAFAFAAIAEgBQAGgDgDgHQgLgagcgHIgDAAQAKgIAHgLQAGgHgHgDQgHgFgEAGQgNAVgWAHIgIABQgJACgIAAQgVAAghgZQgSgQgYgHQAShHAugPQA+gTBSBYQArAvAjA/QALATAJAWQAUArAPAwQA1ChgSBzQgQBphDAAIgHAAgAmqEUQgFgQgCgRQgLhKAShfQAJgzASg4QAwiWBWhcQBRhYA/ATQAuAPASBHQgPAEgNAIQgIAFgHAGQgfAZgVAAQgJAAgIgCIgFgBQgMgEgMgIQgMgJgDgHQgDgHgHAGQgDABgBADQgBADACADQAEAIAPALIgEAAQgcAGgMAbQgCAIAHACIACABQAFAAADgFQAKgWAbgEQAOgBALAEQADACADgBQAHABAJAAQALAAANgFIgBACQgEAIgEAPIgBADQgPAggwAQIgGABIgEACQgnALgbAYQgMALgHALIgCACQgFAHAHAEIABAAIAEABQAEAAACgEQAGgJANgMQAJgIALgHQgcAnAMAzQACAGAFAAIACgBQAHgCgBgGQgLgtAZghIAdgaIAAAAQAYgHASgKIASgNIgDANIgCANQgJBAgJAdQgQAzgdAVQggAXg0gKIgBAAQgHgCgCAIQgBAHAHACIAEABQAOADAPAAQAmAAAagTQAhgXARg2QAGgVAHgkQAGAvAWAXIAFADQAEAAACgDQAFgEgFgGQgagbgBhGIABgUIADgnIABgEIAAgCIAIgWQAJgRANgMIACgCIAOgKIACgBQAKgGAMgDIAAACQAIAmACBOIAAAHQADBzgBArQgCB/gYAnQgZAohLAnQg9AghEATQgQAFgSADQgLADgKAAQg3AAgUhIgAESCUIACgsQAVAEAYAAIACAAIgCAsIgIABQgUAAgTgFg");
	this.shape_4.setTransform(24.7212,31.6136);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-32,-22,113.3,117.4);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#007E9E").s().p("AgFCHQgNgOAAgZIAAiRQAAgJARAAIAFAAQASAAAAAJIAACKQAAANAGAGQAEAHANAAQAMAAAJgHQAKgGAGgKIAAiNQAAgJARAAIAHAAQALAAAEgFQADgDAAgGQABgJgGgGQgFgFAAgEQAAgCADgEIAIgGQAFgCADAAQAEAAAEAEQAFAGACAIQADAHgBAGQAAASgKAKQgHAHgLADIAAB+QAAAZACALIADAPQAAAEgGACQgFACgIACIgLAAQgGAAgCgGQgCgFgDgQQgJAOgOAIQgNAJgRAAQgYAAgMgPgAvYCSQgMgEgIgGQgHgFAAgGQAAgEACgFQADgGAEgEQAEgEADAAQABAAAEADIANAHQAIAEAJAAQANAAAHgHQAHgGAAgMQAAgNgJgIQgJgIgPgHQgSgKgLgMQgMgNAAgXQAAgbARgPQARgQAaAAIAUACQALADAHAEQAHAEAAAFQAAAEgCAGQgCAFgDAFQgDAFgCAAQgCAAgIgFQgHgEgMAAQgLAAgGAFQgIAGAAAJQAAAMAKAIQAJAHALAGQAVAKALANQALAOAAAaQAAAbgRARQgSARgbAAQgOAAgNgEgAH7CFQgQgQAAgdQAAgbAOgQQANgPAXgHQAYgHAdAAIAAgQQAAgLgHgIQgHgJgRAAQgOAAgMAEQgMADgHADQgHAEgDAAQgDAAgCgFIgDgKIgBgJQAAgEAKgFQAJgFAQgFQAPgEAPAAQAkAAARARQASAQAAAcIAABVQAAAZACALIADAPQgBAEgFACQgHADgGABIgLABQgFAAgDgGIgEgSQgJAMgMAHQgMAHgSAAQgaAAgOgQgAIiA3QgNAIAAAXQgBAOAHAJQAGAIAMAAQALAAALgGQAIgFAHgLIAAgyQgiAAgOAKgAGpCQQgLgEgGgLQgHgLAAgUIAAjsQAAgFAEgDQADgDAKAAIAGAAQAKAAADADQAEADABAFIAADoQAAAMACAFQAEAFAHAAIAJgBIAGgBQADAAABAEIADAKIABAHQAAAFgGADIgMAFIgOABQgLAAgKgFgACuCFQgPgQAAgdQAAgbANgQQAOgPAXgHQAYgHAdAAIAAgQQAAgLgHgIQgHgJgRAAQgOAAgMAEQgMADgHADQgHAEgDAAQgDAAgCgFIgEgKIAAgJQAAgEAKgFQAJgFAQgFQAPgEAPAAQAkAAARARQASAQAAAcIAABVQAAAZACALIACAPQAAAEgGACQgFADgHABIgLABQgGAAgCgGIgFgSQgIAMgMAHQgMAHgSAAQgZAAgQgQgADWA3QgNAIAAAXQAAAOAGAJQAGAIANAAQAKAAALgGQAJgFAGgLIAAgyQgiAAgOAKgAlRB6QgTgaAAg0QAAgyATgbQAVgcAoAAQAKAAALADQALACAHAEQAHADABAEIgCAKIgDAJQgCAEgDAAQgFAAgIgCQgJgEgNAAQgVAAgKARQgKAQAAAmQAAAmAKARQAKASAVAAQAPAAAJgEQAKgEAEAAQADAAACAEQACAEAAAGIABAJQAAAEgHAEQgHAFgLACQgMADgLAAQgoAAgVgbgAtSB6QgUgbAAgzQAAgyAUgbQAUgcAlAAQAdAAARAQQAKgBADgEQAEgDAAgGQAAgJgFgFQgFgGgBgEQABgCADgDQADgEAEgDQAFgDADAAQAFAAAEAGQAEAFADAIQACAHAAAGQAAASgLALQgGAGgMADQAQAbABAtQAAAzgUAbQgTAbgmAAQgmAAgTgbgAs1gLQgHARgBAlQABAmAHARQAJASASAAQASAAAJgSQAJgRAAgmQAAglgJgRQgJgRgSAAQgSAAgJARgAPdCTQgLAAgDgDQgFgCAAgFIAAiJQABgMgGgHQgHgHgOAAQgIAAgHAEQgHAEgFAFIgGAKIAACMQAAAFgFACQgEADgJAAIgGAAQgKAAgDgDQgEgCAAgFIAAkTQAAgLARAAIAGAAQASAAAAALIAABoQAHgLANgIQAOgIAQAAQAVAAAPANQAPANAAAcIAACQQAAAFgEACQgEADgJAAgAMhCTQgLAAgDgDQgEgCgBgFIAAiJQABgMgGgHQgGgHgOAAQgJAAgHAEQgIAEgEAFIgGAKIAACMQAAAFgFACQgDADgKAAIgGAAQgKAAgDgDQgEgCAAgFIAAiHQAAgYgCgLIgCgQQAAgDAFgCIANgDIAKgBQAGAAADAGQACAFAEAQQAIgNAOgIQAOgJAQAAQAVAAAPANQAPANAAAcIAACQQAAAFgEACQgEADgKAAgAhVCTQgLAAgEgDQgEgCAAgFIAAiJQAAgMgGgHQgGgHgOAAQgIAAgIAEQgHAEgEAFIgHAKIAACMQAAAFgEACQgEADgKAAIgFAAQgKAAgEgDQgEgCABgFIAAkTQgBgLASAAIAFAAQASAAAAALIAABoQAIgLANgIQANgIARAAQAUAAAQANQAOANAAAcIAACQQAAAFgEACQgEADgJAAgAnUCTQgJAAgFgDQgEgCAAgFIAAiJQAAgMgFgHQgGgHgMAAQgLAAgJAHQgIAHgFAJIAAADIAACJQAAAFgDACQgEADgKAAIgGAAQgKAAgEgDQgDgCAAgFIAAiJQAAgMgGgHQgGgHgMAAQgIAAgHAEQgGAEgFAFIgHAKIAACMQAAAFgDACQgEADgKAAIgFAAQgKAAgEgDQgEgCAAgFIAAiHQAAgYgCgLIgCgQQAAgDAFgCIANgDIALgBQAGAAACAGQACAFADAQQAJgNANgIQANgJAQAAQAOAAANAHQANAHAGARQAIgNANgJQANgJARAAQAUAAAOANQAOANAAAcIAACQQAAAFgDACQgFADgJAAgAI2hQQgDgCgGgHIgSgYIgGgKQgDgDAAgCQAAgEAEgCIANgBQANAAAGADQAGACACAFIAMAdIAEAHIABAFQAAAFgLAAIgOgBgAswhUIACgFIACgHIANgdQACgFAFgCQAHgDAMAAIAOABQAEACAAAEQAAACgDADIgHAKIgSAYQgEAHgFACIgNABQgLAAAAgFgAgBhYQgFgDAAgDIABgIQAFgNAJgGQAJgFALAAQAKAAAIADIARAHQAJADAFAAQAIAAADgEIAGgGQACgEADAAQADAAAGACQAFAEAAACQAAAEgEAIQgFAJgHAFQgHAGgNAAQgKAAgJgDIgSgIQgIgDgFAAQgIAAgDAEIgGAHQgCADgDAAIgHgBg");
	this.shape.setTransform(77.85,37.425);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.3,22.5,202.4,29.9);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#007E9E").s().p("AHxDGQgSgMAAgZQAAgQAIgNQAIgLAOgIIAAgBQgNgJAAgTQAAgLAFgJQAEgJAJgGQgPgIgHgNQgGgPAAgRQAAgfARgSQARgRAeAAQAKAAALACIA2AAQAJAAAAANIAAAFQAAAMgJAAIgKAAIgJgBIgBABQAKAPAAATQAAAagQASQgRARgcABQgLABgHAFQgHAFAAAKQAAAJAHAEQAHAEAJACIAWAEQAVADAPAMQAOALAAAYQAAAbgTAQQgUAPglAAQgiAAgRgMgAIHCJQgFAIAAAKQAAAaAlAAQAnAAAAgaQAAgKgGgFQgFgFgKgDIgTgDIgTgEQgHAEgFAIgAIRgiQgJAHAAAWQAAAUAJAHQAIAHANAAQAMAAAJgHQAJgGAAgVQAAgWgJgHQgJgIgMAAQgNAAgIAIgANjDQQgQAAAAgGIABgGIAWhAIg3i8IgBgGQAAgGAQAAIAJAAIAJABQAFABABAEIAgCOIACAAIAeiOQAAgEAFgBIAKgBIAIAAQAPAAAAAGIAAADIAAADIhGECQgBAEgFABQgDABgHAAgAPMCuQgEgCAAgEIACgFIADgHIADgLQACgGABgMQABgMAAgUQAAgLARAAIAGAAQARAAAAAKQAAARgFAOQgEAPgHALQgGALgHAGQgGAHgGAAIgHgBgAlPCBQgNgEgHgFQgHgFAAgGQAAgEACgFQADgFAEgFQADgEADAAQACAAAEAEQAFADAHADQAHAEAJAAQANAAAGgGQAIgGAAgMQAAgMgJgIQgJgIgOgHQgSgIgLgNQgLgNAAgWQAAgZARgPQAQgPAZAAQAKAAAKACQAKACAHADQAHAFAAAFQAAAEgCAFIgFAKQgEAFgCAAQgCAAgHgFQgHgEgLAAQgLAAgGAFQgHAFAAAKQAAAMAJAHQAJAGALAGQATAKALANQAMAOAAAYQAAAbgSAQQgRAQgaAAQgOAAgLgEgAKXB1QgOgQAAgcQAAgaAMgPQANgPAWgHQAXgHAdAAIAAgNQAAgMgHgIQgHgIgQAAQgOAAgLADIgTAGQgHADgDAAQgCAAgCgEQgDgEAAgGIgBgIQAAgFAJgEQAJgGAPgDQAPgEAPAAQAiAAARAPQASARAAAbIAABSQAAAYABAKIACAPQAAAEgFACQgGACgGABIgLABQgFAAgDgFIgEgSQgJALgLAHQgMAHgRAAQgZAAgOgPgAK+ApQgOAJAAAVQAAAPAGAHQAGAIAMAAQALAAAJgFQAKgGAGgKIAAgwQghAAgNAJgACxCAQgKgEgHgLQgHgLAAgTIAAh3IgNAAQgIAAAAgNIAAgFQAAgOAIAAIANAAIAGgmQABgKAMAAIAGAAQAIAAAEACQADACAAAGIAAAmIAXAAQAJAAAAAOIAAAFQAAANgJAAIgXAAIAABzQAAAMADAFQADAEAHAAQAGAAADgBIAFgBQADAAACAEIACAKIAAAHQAAAEgEADQgFADgHACIgNABQgLAAgKgEgAgfB1QgOgQAAgcQAAgaAMgPQANgPAWgHQAWgHAdAAIAAgNQAAgMgHgIQgGgIgRAAQgOAAgKADIgTAGQgHADgDAAQgCAAgCgEQgDgEAAgGIgBgIQAAgFAJgEQAJgGAPgDQAOgEAPAAQAjAAARAPQARARAAAbIAABSQAAAYACAKIABAPQAAAEgFACQgGACgGABIgLABQgFAAgDgFIgEgSQgJALgLAHQgMAHgRAAQgYAAgOgPgAAHApQgNAJAAAVQAAAPAGAHQAFAIAMAAQALAAAKgFQAJgGAGgKIAAgwQghAAgNAJgAjMBqQgTgZAAgyQAAgwATgbQATgaAkAAQAlAAASAaQATAbAAAwQAAAygTAZQgSAaglAAQgkAAgTgagAivgWQgIARAAAjQAAAlAIAQQAIARASAAQARAAAJgRQAIgQAAglQAAgjgIgRQgJgQgRAAQgSAAgIAQgAtOB1QgPgQAAgcQAAgaANgPQANgPAWgHQAWgHAdAAIAAgNQAAgMgGgIQgHgIgQAAQgPAAgLADIgSAGQgHADgDAAQgDAAgCgEQgCgEgBgGIgBgIQAAgFAKgEQAJgGAPgDQAPgEAPAAQAiAAARAPQARARAAAbIAABSQAAAYACAKIACAPQAAAEgGACQgFACgHABIgKABQgFAAgDgFIgFgSQgIALgMAHQgMAHgQAAQgaAAgNgPgAsoApQgNAJAAAVQAAAPAFAHQAGAIANAAQALAAAJgFQAJgGAGgKIAAgwQghAAgNAJgAGqCCQgJAAgEgCQgFgDAAgEIAAiDQAAgNgFgHQgGgHgOAAQgHAAgIADQgGAEgFAFQgEAGgCAEIAACIQAAAEgEADQgEACgJAAIgGAAQgJAAgEgCQgEgDAAgEIAAiBQAAgYgCgLIgCgQQAAgDAGgCIALgDIAMgBQAFAAACAGIAFAUQAJgMANgJQANgHAQAAQAUAAAPAMQAOAMAAAcIAACLQAAAEgEADQgEACgJAAgAnWCCQgKAAgDgCQgEgDAAgEIAAiDQAAgNgGgHQgGgHgLAAQgLAAgIAHQgIAHgEAIIAAAEIAACEQAAAEgEADQgEACgJAAIgGAAQgJAAgEgCQgEgDAAgEIAAiDQAAgNgFgHQgGgHgMAAQgIAAgGADQgGAEgFAFIgGAKIAACIQAAAEgEADQgEACgJAAIgFAAQgKAAgEgCQgDgDAAgEIAAiBQAAgYgCgLIgCgQQAAgDAFgCIAMgDIALgBQAFAAADAGIAFAUQAJgMAMgJQAMgHAQAAQANAAANAGQAMAHAGARQAIgNANgJQAMgIAQAAQATAAAPAMQAOAMAAAcIAACLQAAAEgEADQgEACgJAAgAuvCCQgRAAAAgJIAAjeIgzAAQgIAAAAgNIAAgHQAAgOAIAAICQAAQAIAAAAAOIAAAHQAAANgIAAIgzAAIAADeQAAAJgRAAgAAFhdIACgFIACgGIANgcQACgFAFgDQAGgCAMAAQAKAAADACQAEABAAADQAAADgCADIgHAKIgRAWQgFAHgEACIgNABQgLAAAAgFgAr/hZQgFgCgDgHIgMgUIgMAUQgDAHgEACIgMABQgLAAAAgFIACgFIACgGIANgcQACgGAGgCQAHgCAKAAQALAAAGACQAGACADAGIAMAcIACAGIACAFQAAAFgLAAIgLgBgAsUidQgFgBgEgHIgRgXIgHgJQgDgEAAgCQAAgEAEgBQAEgBAJAAQANAAAFACQAGACACAGIAMAbIADAHIABAFQAAAFgLAAQgIAAgEgCg");
	this.shape.setTransform(78.525,29.525);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.5,8.5,204.1,42.1);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF915C").s().p("ALzCfQgYggAAhCQAAhBAYggQAXgfAuAAQAtAAAXAfQAYAgAABBQAABCgYAgQgXAggtAAQguAAgXgggAMQgKQgMAWAAAxQAAAyAMAYQANAXAbAAQAbAAAMgXQANgYAAgyQAAgxgNgWQgMgYgbAAQgbAAgNAYgABbCsQgWgTABgkIAAitQAAgEADgDQAFgCAJAAIAFAAQAJAAAFACQADADAAAEIAACuQAAATAMALQALAKAUAAQAVAAALgKQAMgLAAgTIAAiuQAAgJARAAIAHAAQAJAAADgEQADgEAAgEQAAgIgEgGQgFgGAAgDQAAgDAEgDIAHgFIAHgCQAEAAADAFQAEAEACAHQACAGAAAGQAAAPgJAKQgEAGgLACIAACpQAAAkgVATQgWATgoAAQgoAAgVgTgAokCgQgXggAAhDQAAhAAYggQAZggAzAAQAMAAAKACQALACAGACQAIADAAAHQAAAHgDAIQgDAHgEAAIgOgCQgHgCgPAAQghAAgOAWQgOAWAAAyQAAA0ANAWQAOAXAeAAIANgBIALgDIAAhJIgeAAQgIAAAAgNIAAgHQAAgOAIAAIA4AAQAMAAAAANIAABnQAAAEgCADQgCAEgEADQgKAGgQAEQgQAEgQAAQgvAAgXgfgAvSCsQgWgTAAgkIAAitQAAgEAEgDQAFgCAJAAIAFAAQAJAAAEACQAEADAAAEIAACuQAAATAMALQALAKAUAAQAVAAALgKQALgLAAgTIAAiuQABgJARAAIAFAAQAJAAAEACQAEADAAAEIAACtQAAAkgWATQgVATgoAAQgoAAgVgTgAPSC9QgJAAgEgCQgEgCAAgFIAAjsQAAgEAEgDQAEgCAJAAIAGAAQAJAAAEACQADADAAAEIAADsQAAAFgDACQgEACgJAAgAKYC9QgJAAgFgCQgEgCAAgFIAAhpIhPAAIAABpQAAAFgDACQgFACgJAAIgFAAQgKAAgDgCQgEgCAAgFIAAjsQAAgEAEgDQADgCAKAAIAFAAQAJAAAFACQADADAAAEIAABiIBPAAIAAhiQAAgEAEgDQAFgCAJAAIAFAAQAJAAAEACQAEADAAAEIAADsQAAAFgEACQgEACgJAAgAFpC9QgIAAgEgCQgEgCAAgFIAAjoQAAgMAMAAIA4AAQBHAAAABJQAABMhHAAIgcAAIAABfQAAAFgFACQgDACgJAAgAGBAzIAcAAQARAAAIgKQAHgJAAgXQAAgUgHgKQgIgKgRAAIgcAAgAgIC9QgJAAgEgCQgEgCAAgFIAAhpIhPAAIAABpQAAAFgEACQgEACgJAAIgGAAQgJAAgDgCQgFgCAAgFIAAjsQAAgEAFgDQADgCAJAAIAGAAQAJAAAEACQAEADAAAEIAABiIBPAAIAAhiQAAgEAEgDQAEgCAJAAIAGAAQAHAAAEACQAFADAAAEIAADsQAAAFgFACQgEACgHAAgAkDC9QgPAAAAgJIAAjTIgyAAQgHAAgBgNIAAgHQABgNAHAAICJAAQAJAAgBANIAAAHQABANgJAAIgwAAIAADTQAAAJgQAAgAqEC9QgIAAgDgBQgEgCgCgFIhHiSIgEgLIgEgNIgCAAIABAMIABANIAACQQgBAFgDACQgEACgJAAIgFAAQgJAAgEgCQgDgCAAgFIAAjsQAAgJAQAAIAJAAQAIAAAEACQAEACACAEIBHCRIAFAMIADAMIACAAIgBgMIgBgNIAAiPQAAgEAFgDQADgCAJAAIAFAAQAJAAAEACQADADAAAEIAADsQAAAJgQAAgANPhQQgDAAgDgDIgQgPIgRAPQgEADgDAAIgIABQgLAAAAgEIACgFIAFgHIANgSQADgEAFgCQAEgCALAAQAJAAAEACQAFACADAEIAOASIAEAHIACAFQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBABQgCABgGAAIgIgBgAMviEQgFgEAAgDQAAgCAGgDIAJgHQAFgFgBgGQABgEgEgCQgEgCgEAAQgGAAgEABIgFABQgCAAgDgEQgEgFAAgEQAAgDAJgDQAJgDAKAAQALAAALAFQAKAGgBAOQAAAHgDAHQgFAGgGAFQgFAGgGACIgHADQgDAAgDgDg");
	this.shape.setTransform(100.45,12.75,1.31,1.31,0,0,0,-0.1,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30.4,-12.1,262.09999999999997,50.1);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.logo();
	this.instance.setTransform(-222,1,0.125,0.125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FCAF17").s().p("AgSBbIgCAAIgGgCQgLgCABgKIACgHIABAAIAAgBIABAAQAJgOAegTQAhgVAEgDQADgFgKgEIhAgbIAAgBIgBABQABAIAMAPQAKAOAFAEQAFADABgBQACgBAAgHIAAgCIgBgRIARAHIgCANIgBACQgCAOgKAAQgHAAgIgKQgUgUgIgTQgGgPAQACQAcAFAtAPQAbAJgBAMQAAAIgLAKIg/AqIgFAFIAEgBIAmgCIACAAQAAAAABAAQAAgBAAAAQAAAAAAgBQAAAAgBAAIgSgMIAFgDIAWANQAJAHgOAGQgJAEgVAFQgUAEgKAAIgCAAgAhAAIQgKgEAAgFQABgGAWgdQAtg4ANACQAJACAEAMQAEAOABAmIgUgGIgDgXQAAgGgCAAQgBAAgKAJIgOAOQgJAAgCAEQgDADACAFIgJAJQgOANgBACQAAADAIAEIA2AeIgEADg");
	this.shape.setTransform(37.2256,9.024);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#860052").s().p("AEAAkQgGgFAAgIQAAgGADgDQAGgKAWgBIAJgBIAAgCQAAgPgNAAQgLAAgCAIIgJgEIAAgCQAGgKAQgBQALABAGAFQAHAGAAAKIAAAeIACAMIgLAAIgBgJIgHAGQgGADgHAAQgJAAgGgEgAESAMQgNACAAAJQAAAJAMAAQAMAAAEgKQACgDgBgKgADIAfQgGgJAAgNQAAgNAHgJQAHgKAPAAQAPAAAJANIgKADQgFgIgIAAQgTAAAAAYQAAAYATAAQALAAADgIIAIADQgGAMgQAAQgQABgIgKgACHAIQgBgPAKgIQAIgIALAAQATAAAHAWIAAALIgsAAQAAAYATAAQAHgBAFgGIAKABQgFAMgSAAQgdAAABgggACRADIAiAAQgBgSgQAAQgOAAgDASgAASAIQAAgPAKgIQAHgIALAAQAUAAAGAWQABAFAAAGIgtAAQABAYASAAQAIgBAFgGIAKABQgHAMgRAAQgcAAAAgggAAdADIAhAAQgBgSgPAAQgPAAgCASgAhhAkQgHgFAAgIQAAgGADgDQAEgJAYgCIAKgBIAAgCQAAgPgPAAQgKAAgBAIIgKgEIABgCQAFgKAPgBQAMABAGAFQAHAGAAAKIAAAeIACAMIgKAAIgBgJQgMAKgJgBQgJAAgFgEgAhPAMQgOACAAAJQAAAJAMAAQAMAAAEgKQACgDAAgKgABPAoIAAg8IAKAAIAAAJQAGgLANAAQAQAAAEAOIABAvIgKAAIgBgrQgCgJgLAAQgGAAgGAFQgEAFAAAIIAAAjgAgsAoIAAgLIAtg7IgtAAIAAgKIA5AAIAAAKIgsA8IAtAAIAAAKgAiHAoIAAg8IAKAAIAAALQAGgNAPAAIAAALQgOAAgFAIQgCADAAALIAAAdgAilAkQgBgCgBgIIAAgnIgJAAIAAgHIAJAAIAAgPIALgFIAAAUIAMAAIAAAHIgMAAIAAAiQAAALAFAAIAHgBIAAAHIgKACQgJAAgCgEgAjmAbIALgBQAEAGALAAQAPAAABgKQAAgGgTgFQgVgEAAgNQAAgRAXgBQARABAFAMIgJAEQgCgJgMAAQgMAAAAAJQAAAHAOACQAaAFAAAOQAAAHgHAHQgHAFgMAAQgTAAgHgNgAjyAoIgJgZIgfAAIgJAZIgLAAIAehQIALAAIAdBQgAkXAGIAAABIAYAAIgMghg");
	this.shape_1.setTransform(0.3,13.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-222,0,266.7,26);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF915C").s().p("AnqDNQgRgNAAgZQgBgQAJgMQAHgMAOgIIAAgBQgNgIAAgUQAAgLAFgIQAFgJAIgHQgOgHgIgOQgGgOAAgUQAAgdARgRQAQgTAgABQAKAAAKACIA2AAQAJABAAANIAAAEQAAAMgJAAIgKAAIgJgBIAAABQAJAPAAASQAAAcgQARQgQARgcABQgLABgIAFQgGAFAAAKQAAAKAGAEQAHAEAKACIAVADQAVAEAPALQAPALAAAZQAAAbgTAPQgVAQgkgBQgiABgSgMgAnUCPQgFAIABAKQgBAaAmAAQAnAAgBgZQAAgLgFgFQgGgFgJgCQgJgCgKgCIgUgDQgHAEgFAHgAnKgcQgJAHAAAVQAAAWAJAGQAJAHAMAAQAMAAAJgHQAJgGAAgWQAAgVgJgHQgJgIgMABQgMgBgJAIgABWB+QgMgOAAgZIAAiMQAAgJAQAAIAGAAQARAAAAAJIAACFQAAANAGAGQAFAHALAAQAMAAAJgHQAJgGAFgKIAAiIQAAgJARAAIAHAAQALAAADgEQAEgDAAgGQAAgJgFgFQgFgGAAgDQAAgDADgDIAIgGQAFgCADAAQAEAAAEAFQAEAFACAHQACAIABAFQAAASgLAKQgGAFgLADIAAB7QAAAYACAKIACAPQAAAEgFACQgGACgHABIgKABQgGAAgCgFIgFgVQgJAMgNAJQgNAIgPAAQgZAAgMgNgAKyBxQgSgaAAgyQgBgwAUgbQATgbAkABQAkgBATAbQAUAbAAAwQAAAygUAaQgTAZgkAAQgkAAgUgZgALQgQQgIAQABAkQgBAlAIARQAIAQARABQASgBAIgQQAJgRgBglQABgkgJgQQgIgQgSAAQgRAAgIAQgAtsB2QgWgTAAgmIAAi1QAAgFAEgCQAEgDAJAAIAGAAQAKAAAEADQAEACAAAFIAAC2QAAAUAMALQANALAUAAQAWAAAMgLQAMgLgBgUIAAi2QAAgKASAAIAGAAQAJAAAFADQAEACAAAFIAAC1QAAAmgXATQgWAVgqgBQgpABgXgVgANsCIQgJAAgEgCQgEgCAAgFIAAi0QAAgFAEgCQAEgCAJAAIAFAAQAKAAAEACQADACAAAFIAAC0QAAAFgDACQgEACgKAAgAJjCIQgKAAgDgCQgFgCAAgFIAAiDQABgNgGgHQgGgHgNAAQgJAAgGAEQgIAEgEAFIgGAJIAACIQAAAFgFACQgDACgJAAIgGAAQgJAAgEgCQgEgCAAgFIAAkLQAAgJAQAAIAHAAQAQAAABAJIAABmQAHgLANgHQANgJAPABQAUAAAPAMQAPANAAAbIAACLQAAAFgFACQgDACgJAAgAFLCIQgJAAgEgCQgEgCAAgFIAAj0QAAgMANAAIA5AAQBMAAgBBOQABBOhMAAIgdAAIAABkQAAAFgEACQgEACgKAAgAFjgHIAdAAQASAAAIgKQAJgKAAgYQAAgXgJgKQgIgKgSAAIgdAAgAAFCIQgIAAgFgCQgEgCABgFIAAiDQgBgNgFgHQgGgHgOAAQgIAAgGAEQgIAEgEAFIgGAJIAACIQgBAFgEACQgDACgJAAIgGAAQgKAAgDgCQgEgCAAgFIAAkLQAAgJAQAAIAHAAQARAAAAAJIAABmQAHgLANgHQAMgJAQABQAVAAANAMQAOANAAAbIAACLQAAAFgEACQgEACgIAAgAjcCIQgRABAAgKIAAjdIg0AAQgHAAgBgNIAAgJQABgNAHAAICQAAQAIAAAAANIAAAJQAAANgIAAIgzAAIAADdQAAAKgQgBgAoxCIQgJAAgFgCQgEgCABgFIAAiDQgBgNgFgHQgGgHgOAAQgIAAgGAEQgIAEgEAFIgGAJIAACIQgBAFgEACQgDACgJAAIgGAAQgKAAgDgCQgEgCAAgFIAAiBQAAgYgCgLIgCgQQAAgDAFgCQAGgCAHgBIAKgBQAGABACAFIAFAVQAJgNAOgIQAMgIAQAAQAVAAAOAMQAOANAAAbIAACLQAAAFgEACQgEACgIAAgAL+hTQgEgCgDgGIgNgUIgMAUQgDAGgEACQgEACgIAAQgKAAAAgGIABgEIACgIIAMgaQAEgGAFgDQAHgCAKAAQALAAAGACQAGADADAGIAMAaIADAIIABAEQAAAGgKAAQgJAAgDgCgANfhaQgEgCAAgEIAAgZQAAgEAEgDQAFgDALAAQAKAAAFADQAFADAAAEIAAAZQAAAEgFACQgFADgKAAQgLAAgFgDgALgiVQgEgEABgCQAAgDAEgDIAJgKQAFgFAAgIQAAgGgDgCQgEgDgEAAQgFAAgDABIgGACQgCAAgEgFQgEgFABgDQgBgDAJgEQAKgDAJgBQAMABAKAGQALAHAAAOQAAAJgFAIQgEAIgGAFQgGAHgFACQgFAEgDAAQgDAAgEgEg");
	this.shape.setTransform(89.9,21.65);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,179.8,43.3);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#007E9E").s().p("AlSCiQgRgMAAgZQAAgRAIgLQAIgNAOgHIAAgBQgOgJAAgTQAAgLAFgJQAFgJAIgGQgOgIgHgNQgHgOAAgTQAAgfARgRQARgSAfAAQAKAAAKADIA3AAQAIAAAAANIAAAEQAAANgIAAIgLgBIgIAAIgBABQAJAPAAASQAAAcgQAQQgQASgcABQgLABgHAFQgHAEAAALQAAAJAHAEQAGAEAKACIAWADQAVAEAPALQAOALAAAZQAAAbgTAQQgUAPglAAQgiAAgSgMgAk8BkQgEAJAAAKQAAAaAlAAQAnAAAAgaQAAgKgGgGQgGgEgJgCQgJgDgKgBIgUgEQgHAEgFAHgAkyhHQgIAIAAAWQAAAVAIAGQAJAIAMgBQAMABAKgIQAIgGAAgVQAAgWgIgIQgKgHgMAAQgMAAgJAHgAAdCsQgPAAAAgHIABgFIAVhBIg2i7IAAgGQAAgHAQAAIAHAAQAGAAAEABQAFACABAEIAgCOIACAAIAdiOQABgEAFgCQAEgBAGAAIAIAAQAPAAAAAHIAAACIgBAEIhFEBQgBAFgFABIgKABgAFkCaIAAgUQAAgKASAAQASAAAAAKIAAAUQAAAJgSAAQgSAAAAgJgAE9BRQgPgQAAgcQAAgaANgOQANgPAXgHQAWgGAcgBIAAgOQAAgMgGgJQgGgHgRgBQgOABgLADIgTAGIgKADQgCAAgDgEQgCgEAAgGIgBgJQAAgEAJgFQAKgFAOgEQAPgEAPAAQAiAAARARQARAQAAAbIAABSQAAAXACALIACAOQAAAEgFADIgMADIgLABQgFAAgDgFIgEgSQgIALgMAHQgMAHgRAAQgZAAgOgPgAFjAEQgNAJAAAXQAAANAGAIQAGAIAMAAQALAAAJgGQAJgFAGgKIAAgvQggAAgOAHgADnBcQgKgFgGgKQgHgLAAgTIAAh3IgNAAQgJAAAAgOIAAgEQAAgOAJAAIANAAIAFgnQABgJANAAIAGAAQAIgBADADQAEADAAAEIAAAnIAWAAQAJAAAAAOIAAAEQAAAOgJAAIgWAAIAABzQAAALACAFQADAFAHAAIAJgBIAGgBQACAAACAEQACAFAAAEIABAIQAAAEgFADQgFADgHABIgNACQgLAAgKgEgAisBRQgPgQAAgcQAAgaANgOQANgPAXgHQAWgGAcgBIAAgOQAAgMgGgJQgGgHgRgBQgOABgLADIgTAGIgKADQgCAAgDgEQgCgEAAgGIgBgJQAAgEAJgFQAKgFAOgEQAPgEAPAAQAiAAARARQARAQAAAbIAABSQAAAXACALIACAOQAAAEgFADIgMADIgLABQgFAAgDgFIgEgSQgIALgMAHQgMAHgRAAQgZAAgOgPgAiGAEQgNAJAAAXQAAANAGAIQAGAIAMAAQALAAAJgGQAJgFAGgKIAAgvQggAAgOAHgAH5BeQgKAAgDgCQgEgDAAgEIAAi1QAAgEAEgDQADgCAKAAIAFAAQAKAAADACQAEADAAAEIAAC1QAAAEgEADQgDACgKAAgAmYBeQgJAAgEgCQgEgDAAgEIAAiDQAAgNgGgIQgGgGgNAAQgJAAgGADQgHAEgFAGIgGAJIAACIQAAAEgEADQgEACgJAAIgGAAQgJAAgEgCQgEgDAAgEIAAiBQAAgYgCgLIgCgQQAAgDAGgCQAFgDAHAAIAKgBQAGAAACAGIAFAUQAKgNANgHQAMgJAQAAQAVAAAOAMQAPANAAAcIAACLQAAAEgEADQgEACgJAAgAHsiEQgEgDAAgEIAAgYQAAgFAEgCQAFgDALAAQAKAAAFADQAFACAAAFIAAAYQAAAEgFADQgFACgKAAQgLAAgFgCg");
	this.shape.setTransform(52.775,17.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,105.6,34.8);


(lib.Symbol26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol27("synched",0);
	this.instance.setTransform(126,237.3,1,1,0,0,0,126,237.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(19).to({scaleX:1.1,scaleY:1.1,y:237.25},0).wait(20));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.7,192,277.59999999999997,88.80000000000001);


(lib.Symbol24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.instance = new lib.Symbol1("synched",0);
	this.instance.setTransform(93.4,91.55,1,1,0,0,0,52.8,17.4);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).to({y:113.15,alpha:1},10,cjs.Ease.get(1)).to({y:111.55},8,cjs.Ease.get(1)).wait(91).to({startPosition:0},0).to({_off:true},1).wait(848));

	// Layer_2
	this.instance_1 = new lib.Symbol2("synched",0);
	this.instance_1.setTransform(93.95,41.2,1,1,0,0,0,89.9,21.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({_off:false},0).to({y:62.8,alpha:1},10,cjs.Ease.get(1)).to({y:61.2},8,cjs.Ease.get(1)).wait(96).to({startPosition:0},0).to({_off:true},1).wait(848));

	// Layer_1
	this.instance_2 = new lib.Symbol25("synched",0);
	this.instance_2.setTransform(92.6,-7.9,1,1,0,0,0,92.3,16.1);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:17.9,alpha:1},10,cjs.Ease.get(1)).to({y:16.1},8,cjs.Ease.get(1)).wait(100).to({startPosition:0},0).to({_off:true},1).wait(848));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.1,-30,179.8,160.6);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol23("synched",0);
	this.instance.setTransform(25.6,25.8,1,1,0,0,0,25.6,25.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},15,cjs.Ease.get(1)).wait(203).to({startPosition:0},0).to({_off:true},1).wait(3760));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-32,-22,113.3,117.4);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.instance = new lib.Symbol21("synched",0);
	this.instance.setTransform(127.35,100.3,1,1,0,0,0,77.3,11.4);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(26).to({_off:false},0).to({x:98.15},14,cjs.Ease.get(1)).to({x:99.35},6,cjs.Ease.get(1)).wait(172).to({startPosition:0},0).to({_off:true},1).wait(1777));

	// Layer_2
	this.instance_1 = new lib.Symbol20("synched",0);
	this.instance_1.setTransform(71.6,66.05,1,1,0,0,0,77.9,16.1);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(26).to({_off:false},0).to({x:100.8},14,cjs.Ease.get(1)).to({x:99.6},6,cjs.Ease.get(1)).wait(172).to({startPosition:0},0).to({_off:true},1).wait(1777));

	// Layer_1
	this.instance_2 = new lib.Symbol19("synched",0);
	this.instance_2.setTransform(100.05,27.1,0.3,0.3,0,0,0,100.2,19.2);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regX:100,regY:18.9,scaleX:1.07,scaleY:1.07,x:100.1,y:19.1,alpha:1},15,cjs.Ease.get(1)).to({y:19},11,cjs.Ease.get(1)).to({regY:19.1,scaleX:1,scaleY:1,x:100,y:19.1},14,cjs.Ease.get(1)).wait(178).to({startPosition:0},0).to({_off:true},1).wait(1777));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-39.4,-14.2,280.5,155.5);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_218 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(218).call(this.frame_218).wait(1));

	// logo
	this.instance = new lib.Symbol13("synched",0);
	this.instance.setTransform(253.5,27.5,1,1,0,0,0,15.5,15.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},14,cjs.Ease.get(1)).wait(205));

	// phoi
	this.instance_1 = new lib.Symbol22("synched",0);
	this.instance_1.setTransform(149.6,490.8,1,1,0,0,0,25.6,25.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(219));

	// cta
	this.instance_2 = new lib.Symbol26();
	this.instance_2.setTransform(150.8,131.2,1,1,0,0,0,126.8,31.2);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(124).to({_off:false},0).to({alpha:1},19,cjs.Ease.get(1)).wait(76));

	// Layer_10
	this.instance_3 = new lib.Symbol24("synched",0);
	this.instance_3.setTransform(151.3,150.1,1,1,0,0,0,92.3,16.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(100).to({_off:false},0).wait(119));

	// bg copy
	this.instance_4 = new lib.Symbol28("synched",0);
	this.instance_4.setTransform(150,125,1,1,0,0,0,150,125);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(85).to({_off:false},0).to({alpha:1},16,cjs.Ease.get(1)).wait(118));

	// Layer_5
	this.instance_5 = new lib.Symbol17("synched",0);
	this.instance_5.setTransform(150,199.1,1,1,0,0,0,100,19.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(219));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEF8F0").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(219));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,300,150,300);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/logo.png?1700213148664", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;