(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bg1 = function() {
	this.initialize(img.bg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,800,1270);


(lib.bg2 = function() {
	this.initialize(img.bg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,800,1256);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,700,543);


(lib.Symbol29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AuEDOQgFgGAAgIQAAgJAFgFQAEgGAHgBQAHABAFAGQAFAFAAAJQAAAIgFAGQgFAHgHAAQgHAAgEgHgAPABfQgRgeAAgtQAAgtARgfQAVgjAjAAQAXAAAQARQALgQAAgNIgBgBQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQgPgEADgSQADgQANAAQATAAgBAXQAAAVgRAXIgDAEIgDAEQAXAgAAA1QAAAtgRAgQgTAjgjABQgjAAgTgkgAPdhAQgPAYAAA7QAABkAngBQApAAAAhhQAAhlgoAAQgPAAgKAQgAuuBhQgSgfAAguQAAgxAUgfQAUgfAhgBQAgABATAgQASAgAAAtQAAAwgTAfQgTAighAAQghAAgUgigAuShAQgQAYAAA7QAABkApgBQAQAAALgRQANgYAAg4QAAhlgoAAQgPAAgKAQgAGcBkQgUgfAAgyQAAgwAUggQAUgeAgAAQAZAAARAUQAXAaACA7IhtAAIAAAKQAAAmAKAaQALAbAbAAQAbAAAMgcQAFgNACgRIAPAAQgDAZgLASQgRAegiAAQgjAAgTgegAGngBIBOAAQgDhOgjAAQgjAAgFBOgATNB6QgHgHAAgLQAAgLAHgHQAGgIAJAAQAIAAAGAIQAGAHAAALQAAALgGAHQgGAIgJAAQgIAAgGgIgABpBoQgEgKAAgQIgBgXIAAh9IgWAAIAAgNQAJgBAHgEQAUgMAHgyIAJAAIAABAIArAAIAAAQIgrAAIAACCQAAAcAEAJQAEAPAOAAQAJAAAPgJIAAANQgTAOgRAAQgaAAgJgagAnIByQgPgRAAgaQAAgoApgVQAYgLAfgFIAAgbQAAgXgGgJQgIgNgRAAQgOAAgKAKQgGAGAAAKIAAAFIAAAGQAAAUgPAAQgMAAAAgQQAAgUAQgQQATgRAZAAQASAAAOAJQASAMAEAWQADAMAAATIAABbQAAAVACAJQADAKAJAAIAJgBIAAALQgMADgIABQgQAAgHgPQgEgIgBgQQgIARgGAHQgOAQgVAAQgWAAgOgQgAmhAUQgZAQAAAhQAAAUAJAKQAIALAOAAQAXAAAJgaQAEgNAAgbIAAgnQgZAFgRAKgAoxBoQgEgKAAgQIgBgXIAAh9IgWAAIAAgNQAJgBAHgEQAUgMAHgyIAJAAIAABAIArAAIAAAQIgrAAIAACCQAAAcAEAJQAEAPAOAAQAJAAAPgJIAAANQgTAOgRAAQgaAAgJgagAr+BoQgDgKgBgQIAAgXIAAh9IgXAAIAAgNQAKgBAGgEQAVgMAHgyIAJAAIAABAIAqAAIAAAQIgqAAIAACCQAAAcADAJQAFAPAOAAQAJAAAOgJIAAANQgSAOgRAAQgbAAgJgagASAB8QgPAAgaADIAAgJQAMgBAGgDQAGgCABgIIABgKIAAiNQAAgNgCgGQgDgGgKgBIgLgBIAAgIQAegDAZgJIAAC8QAAAKACAFQAFAIATABIAAAJQgagDgOAAgANwB8QgQAAgYADIAAgJQALgBAGgDQAGgDABgHIAAgJIAAhzQAAgYgEgKQgHgQgSAAQglAAAAA1IAABwQAAAKACAEQAFAJARAAIAAAJQgXgDgPAAQgPAAgYADIAAgJQALgBAGgDQAFgDABgHIABgJIAAhyQAAgZgFgKQgHgPgRgBQgVAAgKAVQgGAMAAAaIAABqQAAAKACAEQAEAJASAAIAAAJQgXgDgRAAQgQAAgYADIAAgJQANgBAGgDQAGgCABgIIABgKIAAiLIgBgQQgBgIgEgCQgEgBgQgBIAAgIQAfgFARgIQADASABAUQAHgMAHgHQAOgPAVAAQAgAAAMAjQAHgNAGgGQAPgQAWAAQAgAAAMAaQAHAPAAAeIAABxQAAAKACAFQAEAHAUACIAAAJQgYgDgQAAgAFKB8QgRAAgXADIAAgJQALgBAGgDQAGgDABgHIAAgJIAAhuQAAgbgFgLQgJgQgSgBQgUAAgLASQgHAMAAAbIAABsQAAAKACAEQAEAJARAAIAAAJQgXgDgQAAQgQAAgYADIAAgJQANgBAFgDQAHgCABgIIAAgKIAAjjQAAgNgCgFQgDgGgJgBIgMAAIAAgIQAdgEAbgJIAAB3QARgeAdAAQAeAAAOAcQAJAQAAAhIAABrQAAAKADAFQAEAIAUABIAAAJQgYgDgQAAgAhHB8QgRAAgXADIAAgJQALgBAGgDQAFgDABgHIABgJIAAhzQAAgYgEgKQgIgQgSAAQgkAAAAA1IAABwQAAAKACAEQAEAJASAAIAAAJQgYgDgPAAQgPAAgXADIAAgJQAKgBAGgDQAGgDABgHIABgJIAAhyQAAgZgFgKQgIgPgRgBQgUAAgKAVQgHAMAAAaIAABqQAAAKACAEQAFAJASAAIAAAJQgYgDgQAAQgQAAgYADIAAgJQANgBAFgDQAGgCACgIIAAgKIAAiLIAAgQQgBgIgFgCQgEgBgQgBIAAgIQAfgFASgIQADASAAAUQAIgMAGgHQAOgPAVAAQAgAAANAjQAHgNAGgGQAOgQAXAAQAgAAAMAaQAGAPAAAeIAABxQAAAKACAFQAEAHAVACIAAAJQgYgDgQAAgAwIB7QgRABgdADIAAgLQAOgBAIgDQAHgEABgKIABgKIgDjqIg9DHIgJAgIgJAfIgGAAIhOkHIgHDpIAAAEQAAAKACAFQAEAIAYADIAAALQgXgCgNgBQgNABgYACIAAgLQAQgCAFgDQAGgDACgKIABgMIAIjcIAAgCQAAgLgCgGQgFgJgXgCIAAgKIAeABQARAAARgCIBEDiIBFjiQAVACAOAAIAdgBIAAAKQgPACgGACQgJAGAAARIAAADIAEDcQAAAOACAFQAFAJAXACIAAALQgdgDgRgBgAHxhxIgighIgjAhIgKAAIAlg1IARAAIAlA1gAlxhxIgighIgiAhIgKAAIAlg1IARAAIAkA1gAtYhxIgighIgiAhIgKAAIAlg1IARAAIAkA1gAPlh8IAeg4IAeAAIgzA4gARwiDQgGgIAAgKQAAgLAGgGQAGgIAJABQAIgBAFAIQAGAHAAAKQAAAKgFAIQgGAGgJAAQgIAAgGgGgAH0ibIAfg4IAdAAIgzA4g");
	this.shape.setTransform(49.125,12.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77.3,-8.4,252.89999999999998,42.5);


(lib.Symbol28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkMCeQgcgagOgyQgJglAAgsQAAhPAeg0QAPgbAZgOQAUgLAZAAQAoAAAbAgIAPgfIAIAAIAABoIgKAAQgRhYg6AAQgrAAgTAvQgUAuAABIQAABDASAsQAUAxArAAQAcAAAUgWQAXgaADg2IAQAAQgCAogMAcQgMAcgXAQQgVANgZAAQgjAAgcgZgAG4C3IAAhZIAJAAQAEAXAGAOQAGAQANAKQAMAJAPAAQAUAAANgPQAMgOAAgTQAAgTgOgMQgIgGgYgOIgggSQgegTAAglQAAggASgSQATgUAcAAQAXAAAVARIAHgWIAIAAIAABSIgKAAQgFg+goAAQgTAAgLAOQgLANAAARQAAAPAJAJQAGAHAWAMIAbAPQAWALAKAMQANAQAAAbQAAAfgSAVQgUAYggAAQgcAAgXgXIgLAYgAEAC3IAAhZIAKAAQADAXAGAOQAHAQAMAKQANAJAPAAQATAAANgPQAMgOAAgTQAAgTgOgMQgIgGgYgOIgggSQgdgTAAglQAAggASgSQATgUAcAAQAXAAAVARIAHgWIAIAAIAABSIgKAAQgGg+gnAAQgTAAgMAOQgKANAAARQAAAPAJAJQAGAHAVAMIAcAPQAVALAKAMQANAQAAAbQAAAfgSAVQgTAYggAAQgcAAgYgXIgKAYgAJ4CtQgHgJAAgNQAAgMAHgJQAHgJALAAQAJAAAIAJQAHAJAAAMQAAANgHAJQgIAIgKAAQgKAAgHgIgABDCjQgSgTAAgfQAAgvAxgZQAcgPAkgFIAAgfQAAgbgGgLQgKgPgTAAQgRAAgMALQgHAHAAANIAAAFIAAAHQAAAXgRAAQgPAAAAgRQAAgYATgTQAWgUAeAAQAVAAARALQAVAOAFAaQADANAAAWIAABsQAAAZADALQADAMAKAAIALgCIAAAOQgOADgKAAQgSAAgIgQQgFgKgCgTQgJATgIAJQgPASgaAAQgaAAgQgSgAByA1QgeASAAAnQAAAXAKANQAKAMAQAAQAcAAAJgfQAFgPAAggIAAguQgdAHgTAMgAgYCvQgRAAgfADIAAgKQAPgBAHgDQAHgEACgJIAAgMIAAkKQAAgPgCgGQgEgIgLgCIgNAAIAAgJQAigEAfgKIAAFAQAAANACAFQAEAKAYABIAAAKQgegDgSAAgAqhCxIAAgNQASgCAHgDQAJgFABgLIABgOIAAkAQAAgRgDgFQgFgMgcgCIAAgMIC8AAIAIBPIgKAAQgIgkgKgNQgKgOgXAAIg+AAIAACRIA9AAQAMAAAEgFQAIgIACgfIAKAAIAABnIgKAAQgBgYgGgKQgFgKgQAAIg7AAIAACAQAAAPABAEQAFAMAWAAIAfAAQAZAAALgLQAOgRAIgpIAKAAIgKBWgAnEAvIAAgYIBuAAIAAAYg");
	this.shape.setTransform(66.275,-7.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.1,-26.2,134.79999999999998,36.6);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg2();
	this.instance.parent = this;
	this.instance.setTransform(3,0,0.3787,0.3787);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(3,0,303,475.7);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkSBtQgDgDgBgFQABgFADgDQADgEAFAAQAFAAADAEQAEADAAAFQAAAFgEADQgEADgEAAQgFAAgDgDgAF/BAQgNgKAAgQQAAgaAcgKQAPgFAdgEIAAgFQAAgNgDgFQgHgHgOAAQgWAAgEATIgRAAQABgPAKgIQALgLAWAAQATAAALAIQAIAHACAPIAAAQIAAAsQABAVADAKIgQAAIgEgQQgKATgYAAQgQAAgKgIgAGWAPQgRAHAAAOQAAAKAHAGQAFAFALAAQARAAAJgOQAEgIAAgTIAAgLQgZAEgLAGgABhBBQgMgIgCgPQgBgGgBgNIAAhIIASAAIAABIQAAASAEAGQAGAJAPAAQAQAAAHgNQAGgIAAgSIAAhCIARAAIAAAJIACgBIAFgGIADgHIgBgBQgDAAgDgCQgEgEACgGQACgFAEgCQAEgCAEABQAFABACAFQADAFgCAGQgEAPgTAOIAAA+IAAAMIAAAIQAAAJADAHIgSAAIgBgIIgBgIQgEAIgFAEQgJAHgOAAQgOAAgKgHgAkpBAQgNgKAAgQQAAgaAdgKQAPgFAcgEIAAgFQAAgNgDgFQgGgHgOAAQgXAAgEATIgRAAQABgPAJgIQAMgLAWAAQATAAALAIQAIAHACAPIAAAQIAAAsQAAAVAEAKIgQAAIgDgQQgKATgZAAQgQAAgKgIgAkTAPQgQAHAAAOQAAAKAGAGQAHAFAJAAQASAAAJgOQAEgIAAgTIAAgLQgZAEgMAGgAALA8QgCgDAAgGIAAhWIgRAAIAAgOIARAAIAAgiIASAAIAAAiIAcAAIAAAOIgcAAIAAA8IAAAVQABAKALAAQAJAAAJgEIAAAPQgLAEgKAAQgSAAgHgLgAEoBGIgrh3IATAAIAhBjIAhhjIASAAIgqB3gAI5BFIAAhDQAAgUgDgHQgFgLgQAAQgRAAgJAOQgFAJgBAQIAABCIgRAAIAAhNIAAgeIgCgLIAQAAQACAHABAKQAMgUAYAAQAPAAALAIQAJAIACAPIAAAWIAABEgAhvBFIAAhDQAAgUgDgHQgGgLgPAAQgRAAgJAOQgGAJAAAQIAABCIgRAAIAAhNIgBgeIgCgLIARAAQADAHgBAKQAMgUAYAAQAQAAAKAIQAKAIABAPIABAWIAABEgAlkBFIAAhDQABgUgEgHQgGgLgPAAQgQAAgJAOQgFAJgBARIAABBIgRAAIAAinIARAAIAAA/QANgRAVAAQAOAAAKAGQAKAHADANQACAHAAAUIAABEgAnoBFIhQiKIAACKIgRAAIAAimIATAAIBRCKIAAiKIASAAIAACmgAG2g/IgRgSIgSASIgOAAIAXgcIARAAIAWAcgAj0g/IgRgSIgRASIgOAAIAXgcIAQAAIAWAcgAG6hUIAVgbIASAAIgbAbg");
	this.shape.setTransform(52.6,12.125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1,1,1).p("AtPjdIafAAIAAG7I6fAAg");
	this.shape_1.setTransform(53.65,12.35);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-32.1,-10.8,171.6,46.400000000000006);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMvBzIgKgjIgfhoQgDgKgFgCQgDgCgIAAIAAgIIAcACIAbgCIAAAIIgIAAQgGABAAAGIABAHIAcBkIAdhiIACgKQAAgFgFgBIgIAAIAAgIIAUACIATgCIAAAIQgIAAgDACQgFADgDALIgeBlIgLAkgAJHBzIAAg3IAGAAQACAOAEAIQAEAKAHAGQAIAGAJAAQAMgBAIgIQAHgJAAgMQAAgMgIgIQgFgDgPgJIgTgLQgSgMAAgWQAAgUALgMQALgMARAAQAPAAAMALIAFgPIAEAAIAAAzIgGAAQgDgmgYAAQgMAAgHAJQgGAIAAALQAAAJAFAGQAEAEANAHIARAJQANAIAGAHQAIAKAAAQQAAATgLAOQgMAPgTAAQgRgBgPgOIgGAQgAwaBzIgKgjIgfhoQgDgKgFgCQgDgCgIAAIAAgIIAcACIAbgCIAAAIIgIAAQgGABAAAGIABAHIAcBkIAdhiIACgKQAAgFgFgBIgIAAIAAgIIAUACIATgCIAAAIQgIAAgDACQgFADgDALIgeBlIgLAkgAINBUQgFAMgGAGQgKALgPAAQgVAAgLgSQgHgMAAgYIAAhMQAAgJgBgDQgCgGgHAAIgIgBIAAgGQAUgCAUgGIAABtQAAAUAEAIQAGALANAAQAPAAAHgOQAFgJAAgVIAAhHQAAgJgBgDQgCgGgHAAIgIgBIAAgGQAUgCATgGIAACFQAAAIACAEQACAEAHAAIAJAAIAAAGQgWADgOAGIgCgegAEKBbQgNgVAAgkQAAglAPgYQAOgWAXABQAPAAALANIAHgQIAFAAIAAA1IgGAAQgCgOgEgIQgEgJgGgGQgHgEgHAAQgRgBgHAWQgHAUAAAgQAABFAeAAQAYAAAFgrIALAAQgCASgGAMQgLAYgXAAQgXAAgPgXgAvBBYQgMgWAAghQAAghANgWQAOgaAaAAQARAAALAMQAIgLAAgKIgBAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgLgEACgMQACgMAKAAQANAAgBAQQAAAQgMARIgCACIgCAEQARAXAAAnQAAAhgNAXQgOAagZAAQgYAAgPgagAusgcQgLASAAArQAABIAdABQAdgBAAhHQAAhKgdABQgKAAgIALgAOLBcQgPgXAAgkQAAgkAPgXQAOgWAXABQASAAAMAOQARATABArIhPAAIAAAGQAAAcAIAUQAIAUATAAQATAAAJgVQAEgJABgNIALAAQgCASgIAOQgMAVgZABQgZgBgNgVgAOSARIA5AAQgCg4gaAAQgZAAgEA4gAjRBUQgPgfAAgxQAAgzAQggQAOgcAbAAQAQAAAMANQANAOAHAeQAGAZAAAcQAAAugNAfQgOAigcAAQgcgBgNgdgAi7hTQgOAWAABCQAAAtAIAcQAEAMAHAHQAGAHAIAAQAgAAAAhkQAAgxgIgaQgIgagRAAQgKAAgIAOgAlaBUQgPgfAAgxQAAgzAQggQAOgcAbAAQAQAAAMANQANAOAHAeQAGAZAAAcQAAAugNAfQgOAigcAAQgcgBgNgdgAlEhTQgOAWAABCQAAAtAIAcQAEAMAHAHQAGAHAIAAQAgAAAAhkQAAgxgIgaQgIgagRAAQgKAAgIAOgALOBtIgdADIAAgHQAJgBAEgBQAFgDABgFIAAgIIAAhoQAAgJgCgDQgCgGgGAAIgJgBIAAgGQAWgCASgGIAACJQAAAIACADQADAGAOABIAAAHQgTgDgLAAgAGJBtIgdADIAAgHQAJgBAEgBQAEgDABgFIAAgIIAAimQAAgJgBgDQgCgFgHgCIgIAAIAAgFQAUgDATgGIAADHQAAAIACADQADAGAOABIAAAHQgSgDgLAAgADRBtQgLAAgRADIAAgHQANgBAAgGQAAgDgDgGIgVguIgYAsQgFAHAAAEQAAAEAGACIAIABIAAAHIgVgCIgWACIAAgHQAJgBAEgDQAFgEAHgLIAdg0Igcg7QgEgJgFgCQgEgDgIABIAAgIQARACALAAQALAAAQgCIAAAIQgMAAAAAGIACAHIARAkIAUgiQADgGAAgDQAAgFgFgBIgIAAIAAgIIAVACIAWgCIAAAIQgIAAgEACQgGADgFAIIgaAtIAgBEQAFALAFADQAEACAJABIAAAHQgRgDgMAAgAs3BtIgdADIAAgHQAJgBAEgBQAFgDABgFIAAgIIAAhoQAAgJgCgDQgCgGgGAAIgJgBIAAgGQAWgCASgGIAACJQAAAIACADQADAGAOABIAAAHQgTgDgLAAgAgZBuIAAgHQALgCAEgCQAFgDABgHIAAgJIAAifQAAgJgBgEQgEgHgQgBIAAgJIBxAAIAFAyIgGAAQgFgWgGgJQgGgIgOgBIgmAAIAABbIAlAAQAHAAADgDQAFgFABgTIAGAAIAAA/IgGAAQgBgOgDgGQgEgGgJgBIgkAAIAABQQAAAJABACQADAIANAAIATAAQAPABAHgIQAJgKAEgZIAHAAIgHA0gAnvBuIAAgSQAdgqARgeQAQgbAHgQQAHgRAAgOQAAgOgHgKQgIgLgNAAQgJABgIAFQgIAFgEAJQgFAKgCAQIgJAAQADgdAHgNQAHgLALgFQAKgGAMAAQATABAMAMQAHAGAEAKQAEAKAAALQAAAWgQAbQgPAbgwBFIBRAAIgDAWgArIBuIAAgHQALgCAEgCQAFgDABgHIAAgJIAAifQAAgJgBgEQgEgHgQgBIAAgJIByAAIAFAyIgGAAQgFgWgGgJQgGgIgOgBIgmAAIAABbIAlAAQAHAAADgDQAFgFABgTIAGAAIAAA/IgGAAQgBgOgDgGQgEgGgJgBIgkAAIAABQQAAAJABACQADAIANAAIATAAQAPABAHgIQAJgKAEgZIAHAAIgHA0gAQwgqIgSAhIgLgKIATgfIgegLIAEgQIAeANIgBgnIANAAIgBAnIAegNIAEAQIgeALIATAfIgLAKgAumhIIAWgqIAVAAIgkAqgALEhOQgFgFAAgIQAAgHAEgFQAFgGAGAAQAGAAAEAGQAEAFAAAHQAAAIgEAFQgEAGgGAAQgGgBgEgFgAtBhOQgFgFAAgIQAAgHAEgFQAFgGAGAAQAGAAAEAGQAEAFAAAHQAAAIgEAFQgEAGgGAAQgGgBgEgFg");
	this.shape.setTransform(112.875,20.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1.8,9.4,222.2,22.9);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AtWBsQgLgXAAgfQAAgfALgXQANgaAYAAQANAAAJAKQAEAFAFALIAAgtIgnAAIAAgJIAnAAIAAgEQAAgJgBgEQgCgFgHgBIgEAAIgEAAIAAgGQAVgCASgHIAAAmIARAAIAAAJIgRAAIAACOIABAOQABAGAFACIAFABIAIAAIAAAFIgUAFIgPAEIgCgNIgCgNQgKAbgWAAQgYAAgOgbgAtLA2QAAAdAFAUQAHAWARAAQAKAAAIgKQAKgPAAgrQAAhKgdAAQgcABAABGgAIjBvQgNgXAAgjQAAgkAOgVQAPgYAYAAQAWAAAOAYQANAXAAAhQAAAjgNAYQgPAXgXAAQgYAAgOgXgAI3gIQgLARAAAsQAABJAdAAQAMAAAHgNQAKgRAAgqQAAhKgdAAQgKABgIALgAEgCGIAAjAQAAgJgCgEQgCgFgHgBIgIAAIAAgGQAVgCATgHIAABaQAFgKAEgFQAJgJAOgBQAWAAANAYQAOAWAAAiQAAAjgOAYQgOAWgWAAQgYAAgKgdIgMAdgAFEgMQgGAGgDAJQgHAUAAAgQAAAeAGASQADALAHAGQAGAFAIAAQALAAAIgMQALgRAAgrQAAhHgeAAQgHABgHAFgAvaBpQgFAMgGAFQgKAMgPgBQgVAAgLgSQgHgMAAgYIAAhMQAAgIgBgEQgCgFgHAAIgIgBIAAgGQAUgCAUgGIAABsQAAAVAEAHQAGAMANAAQAPAAAIgOQAEgJAAgVIAAhIQAAgIgBgEQgCgFgHAAIgIgBIAAgGQAUgCAUgGIAACFQAAAIABADQACAEAHABIAJAAIAAAFQgVAEgPAFIgCgdgAzBBwQgJgNgCgOIgBgKIgBgMIAAh6QAAgKgBgEQgDgFgIgCIgJgBIAAgIIASACIAOABIAPgBIASgCIAAAIIgMACQgIADgBAIIAAAJIAAB9QAAAUADAJQAJAZAdAAQAcAAALgWQAGgNAAgXIAAh5QAAgKgBgEQgDgFgIgCIgKgBIAAgIIAQABIALABIAGAAQAFgIAAgHIgBgBIgCAAQgKgDACgNQACgMAKABQANAAgBAQQAAASgUAbIAACBQAAAWgDALQgMApgsAAQgeAAgQgWgAO5BxQgPgYAAgkQAAglAPgVQAOgWAXAAQASAAAMAPQARARABAtIhPAAIAAAGQAAAcAIAUQAIATATAAQATAAAJgUQAEgKACgNIAKAAQgCATgIAOQgMAVgZAAQgZAAgNgVgAPAAmIA5AAQgCg5gaAAQgZAAgEA5gAGlB6QgLgMAAgSQAAgeAegQQARgJAWgDIAAgUQAAgPgEgIQgFgJgMAAQgLAAgHAHQgEAFAAAGIAAADIAAAFQAAAPgLAAQgJgBAAgKQAAgOAMgMQANgNATAAQAMAAALAHQAMAJAEAPQABAIAAAOIAABEQAAAPACAHQACAIAHgBIAGgBIAAAJQgJADgFgBQgMAAgFgKQgDgGgBgMQgFAMgFAFQgJAMgQAAQgQAAgKgMgAHCA1QgSAMAAAYQAAAPAGAIQAGAIAKAAQARgBAFgTQADgKAAgTIAAgdQgSAEgLAHgAhuB6QgLgMAAgSQAAgeAegQQARgJAWgDIAAgUQAAgPgEgIQgGgJgMAAQgKAAgHAHQgFAFAAAGIAAADIAAAFQAAAPgKAAQgJgBAAgKQAAgOAMgMQANgNASAAQANAAAKAHQANAJADAPQACAIAAAOIAABEQAAAPACAHQACAIAGgBIAHgBIAAAJQgJADgGgBQgLAAgFgKQgDgGgBgMQgFAMgFAFQgKAMgPAAQgQAAgKgMgAhSA1QgSAMAAAYQAAAPAGAIQAGAIAKAAQARgBAGgTQADgKAAgTIAAgdQgSAEgMAHgArQB6QgLgMAAgSQAAgeAegQQARgJAWgDIAAgUQAAgPgEgIQgFgJgMAAQgLAAgHAHQgEAFAAAGIAAADIAAAFQAAAPgLAAQgJgBAAgKQAAgOAMgMQANgNATAAQAMAAALAHQAMAJAEAPQABAIAAAOIAABEQAAAPACAHQACAIAHgBIAGgBIAAAJQgJADgFgBQgMAAgFgKQgDgGgBgMQgFAMgFAFQgJAMgQAAQgQAAgKgMgAqzA1QgSAMAAAYQAAAPAGAIQAGAIAKAAQARgBAFgTQADgKAAgTIAAgdQgSAEgLAHgATHCCQgLAAgRACIAAgHQAIAAAEgCQAEgDABgFIAAgHIAAhVQAAgRgDgGQgFgMgNAAQgaAAAAAmIAABSIABALQADAGANAAIAAAHQgRgCgLAAQgLAAgRACIAAgHQAIAAAEgCQAEgDABgFIAAgHIAAhUQAAgSgDgHQgFgLgMAAQgPABgIANQgEAJAAATIAABOQAAAHABAEQADAGANAAIAAAHQgRgCgLAAQgMAAgRACIAAgHQAJAAAEgCQAFgDAAgFIABgIIAAhlIgBgLQAAgGgEgBQgCgCgMAAIAAgGQAXgEAMgGQACANABAPQAFgJAFgFQAKgLAPAAQAXAAAJAaQAFgKAEgEQALgMAQAAQAXAAAJAUQAEAKAAAVIAABTQAAAJACADQADAGAOAAIAAAHQgRgCgMAAgAN8CCQgLAAgTACIAAgHQAJAAAEgCQAFgDABgFIAAgIIAAhoQAAgIgCgEQgCgFgGAAIgJgBIAAgGQAWgCASgGIAACIQAAAJACADQADAGAOAAIAAAHIgdgCgAM0CCQgMAAgRACIAAgHQAIAAAEgCQAEgDABgFIABgHIAAhRQAAgUgEgHQgGgMgOAAQgOAAgIAMQgFAJAAAUIAABPQAAAHABAEQADAGANAAIAAAHQgRgCgLAAQgMAAgRACIAAgHQAJAAAEgCQAFgDAAgFIABgIIAAilQAAgJgCgEQgCgFgHgBIgIAAIAAgGQAVgCATgHIAABXQAMgWAVAAQAWAAAKAVQAHAKAAAZIAABOQAAAJABADQADAGAPAAIAAAHQgSgCgLAAgACmCCQgMAAgRACIAAgHQAIAAAEgCQAEgDABgFIABgHIAAhVQAAgRgDgGQgGgMgNAAQgaAAAAAmIAABSIABALQAEAGAMAAIAAAHQgRgCgKAAQgLAAgRACIAAgHQAHAAAFgCQAEgDABgFIAAgHIAAhUQAAgSgDgHQgGgLgMAAQgPABgHANQgFAJAAATIAABOQAAAHACAEQADAGANAAIAAAHQgRgCgMAAQgLAAgRACIAAgHQAJAAAEgCQAEgDABgFIAAgIIAAhlIAAgLQgBgGgDgBQgDgCgKAAIAAgGQAVgEANgGQACANAAAPQAFgJAFgFQAKgLAPAAQAXAAAKAaQAEgKAFgEQAKgMARAAQAWAAAJAUQAFAKAAAVIAABTQAAAJABADQADAGAPAAIAAAHQgSgCgLAAgAimCCQgLAAgRACIAAgHQAIAAAEgCQAEgDABgFIAAgHIAAhRQAAgUgEgHQgGgMgNAAQgOAAgIAMQgGAJAAAUIAABPQAAAHACAEQADAGANAAIAAAHQgRgCgMAAQgLAAgSACIAAgHQAKAAAEgCQAEgDABgFIAAgIIAAhlIAAgLQgBgIgHAAIgKgBIAAgGQAWgEANgFQABAIABAUQAOgaAWAAQAVAAALAVQAGAKAAAZIAABOQAAAJACADQADAGAOAAIAAAHQgRgCgMAAgAmYCCQgRAAgQACIAAgIQALgBAFgCQAFgDABgHIAAgJIAAiWIgeAAIAAgIQARgCAMgKQALgKAFgPIAHAAIAADDQAAAKABADQADAGAIACIAJABIAAAIQgQgCgQAAgApECCQgLAAgTACIAAgHQAJAAAEgCQAFgDABgFIAAgIIAAhoQAAgIgCgEQgCgFgGAAIgJgBIAAgGQAWgCASgGIAACIQAAAJACADQADAGAOAAIAAAHIgdgCgAP1gsIgYgYIgZAYIgHAAIAagnIANAAIAaAngAHIgtIACgLQACgFAGgHQAFgHAAgHQAAgMgJAAQgNAAgBARIgFAAQAAgRAKgGQAFgCAHAAQAHAAAFADQAGAGAAAKQABAJgGAHIgFAEIgHAIQgDAEgBAGgAhbg5QgIgLgCgQIAFAAQAEAMAHAGQAHAGAIABQAJgBAGgGQAIgHADgLIAGAAQgDAQgHAMQgJALgNgBQgMABgJgMgANxg5QgFgFAAgIQAAgIAEgFQAFgFAGAAQAGAAAEAFQAEAFAAAIQAAAIgEAFQgEAFgGAAQgGAAgEgFgApPg5QgFgFAAgIQAAgIAEgFQAFgFAGAAQAGAAAEAFQAEAFAAAIQAAAIgEAFQgEAFgGAAQgGAAgEgFgAqqhCQgHgFgFgBQgIAAgFAPIgEgBQACgOAFgGQAGgHAHABQAIAAAHAGQAKAJAGAAQAHgBAEgOIAFABQgCAOgGAGQgFAHgGABQgIAAgLgLgAP5hMIABgLQADgFAFgHQAGgIAAgGQAAgNgKAAQgMAAgCARIgEAAQAAgQAKgGQAEgDAHAAQAIAAAEAEQAHAGAAALQAAAIgFAGIgGAFIgHAIQgDAEgBAGg");
	this.shape.setTransform(127.675,18.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2.5,5.3,250.4,26.999999999999996);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A35VAIAA4fMA4pgIOMgAEAgtg");
	mask.setTransform(209.55,134.425);

	// Layer_1
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(10,7,0.57,0.57);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(56.6,59.5,352.4,209.39999999999998);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJIA0QgFgFAAgHQAAgGAEgEIAGgEQgFgCAAgEQAAgEADgDIAFgDQgJgEAAgLQAAgKAFgFQAFgEAHAAIAHABIANgBIAAAHIgJAAQAEAEAAAJQAAAHgEAEQgDADgIACIgHADQAAAAgBABQAAAAgBAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAABABQAAAAABAAIAHABIAJACQALADAAAMQAAAJgGAFQgGAEgIAAQgKAAgGgFgAJNAgQgEADAAAFQAAAEAEADQAEADAHAAQAHAAAEgEQADgCAAgEQAAgKgPAAQgGAAgEACgAJQgOQgDADAAAGQAAAFADACQADAEAEAAQAEAAADgEQADgCAAgFQAAgFgDgEQgCgEgFAAQgEAAgDAEgAFuA4IAAg/IAAgLIgBgGIAGAAIABAJQAFgKAIAAQAHAAAEAFQAHAJAAAPQAAAPgGAJQgFAGgGAAQgJAAgFgKIAAAggAF4gNQgEAHAAAKQAAALAEAGQAEAFAFAAQAFAAACgEQAEgHAAgLQAAgLgEgHQgDgEgFAAQgFAAgDAFgAH1A0IgCgEQAAgBAAAAQAAgBABgBQAAAAAAAAQAAgBABAAIADgCQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABQABAAAAAAQAAABAAABQAAAAAAABQAAAAAAABQAAABAAAAQAAAAgBABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgDgBgAk5A0IgBgEIABgEQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIADACIABAEIgBAEIgDABQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAgAHtAeQgFgEgBgHIAAgJIAAgiIAHAAIAAAiQAAAJABADQADAEAFAAQAGAAADgGQACgEAAgIIAAggIAHAAIAAAnIAAAKIABAHIgHAAIgBgHIgDAFQgDAEgGAAQgFAAgEgEgAG6AbQgGgIAAgPQAAgOAGgJQAFgGAHAAQAFAAAEADIAEAGIAAgfIAGAAIAAA+QAAAOABADIgGAAIgBgGIAAgBIAAgBIAAABIgEAFQgDAEgGAAQgHAAgFgHgAG/gNQgEAHAAAKQAAALAEAHQADAEAFAAQAFAAADgEQAEgHAAgLQAAgKgEgHQgDgFgFAAQgFAAgDAFgAFCAeQgEgFAAgIQAAgMAKgFIARgEIAAgCQAAgGgBgDQgDgDgFAAQgJAAgBAJIgHAAQABgHADgEQAFgFAIAAQAHAAAFAEQADADABAHIAAAIIAAAUQAAALABAEIgGAAIgBgHQgEAJgKAAQgGAAgEgEgAFLAGQgGAEAAAHQAAAEACADQADADADAAQAHAAADgHQACgEAAgJIAAgGQgKADgEACgADNAeQgFgFAAgIQAAgMALgFIARgEIAAgCQAAgGgCgDQgCgDgFAAQgJAAgCAJIgGAAQAAgHAEgEQAEgFAJAAQAHAAAEAEQAEADAAAHIAAAIIAAAUQAAALACAEIgHAAIgBgHQgEAJgJAAQgGAAgEgEgADVAGQgGAEAAAHQAAAEADADQACADAEAAQAHAAADgHQACgEAAgJIAAgGQgKADgFACgACeAbQgGgJAAgOQAAgOAGgIQAFgHAJAAQAHAAAGAHQAGAIAAAOQAAAOgGAJQgGAHgIAAQgIAAgFgHgACigMQgEAGAAAKQAAAKAEAHQAEAGAFAAQAGAAADgGQAEgHAAgKQAAgKgEgGQgDgGgGAAQgFAAgEAGgAgFAeQgEgEgBgHIAAgJIAAgiIAGAAIAAAiQAAAJACADQACAEAFAAQAGAAADgGQACgEAAgIIAAggIAGAAIAAAnIAAAKIABAHIgGAAIgBgHIgEAFQgDAEgFAAQgFAAgEgEgAg2AbQgGgIAAgPQAAgPAHgIQAFgGAIAAQAJAAAFAKQAEAHAAALIAAACIgfAAQAAAJADAGQADAHAHAAQAFAAADgFIADgEIAGABQgEAPgNAAQgIAAgGgHgAgygLQgCAEgBAHIAYAAQAAgHgCgEQgDgHgHAAQgGAAgDAHgAh8AbQgGgIAAgPQAAgOAGgJQAFgGAHAAQAFAAAEADIAEAGIAAgRIgOAAIAAgFIAOAAIAAgJIAGAAIAAAJIAHAAIAAAFIgHAAIAAAwQAAAOABADIgGAAIgBgGIAAgBIAAgBIAAABIgEAFQgDAEgGAAQgHAAgFgHgAh3gNQgEAHAAAKQAAALAEAHQADAEAFAAQAFAAADgEQAEgHAAgLQAAgKgEgHQgDgFgFAAQgFAAgDAFgAlDAbQgGgIAAgPQAAgPAGgIQAFgGAIAAQAKAAAFAKQADAHAAALIAAACIgfAAQABAJACAGQAEAHAHAAQAFAAADgFIACgEIAGABQgEAPgNAAQgIAAgFgHgAlAgLQgCAEAAAHIAXAAQAAgHgCgEQgDgHgGAAQgGAAgEAHgAnMAeQgFgEgBgHIAAgJIAAgiIAHAAIAAAiQAAAJABADQADAEAFAAQAGAAADgGQACgEAAgIIAAggIAHAAIAAAnIAAAKIABAHIgHAAIgBgHIgDAFQgDAEgGAAQgFAAgEgEgAn9AbQgGgIAAgPQAAgPAHgIQAFgGAIAAQAJAAAFAKQAEAHAAALIAAACIgfAAQAAAJADAGQADAHAHAAQAFAAADgFIADgEIAGABQgEAPgNAAQgIAAgGgHgAn5gLQgCAEgBAHIAYAAQAAgHgCgEQgDgHgHAAQgGAAgDAHgAJ3AfQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAgBAAAAQAAgDACgCQABgBAAAAQAAAAABgBQAAAAABAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQABACAAADQAAAAAAABQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBgBgAjNAcQgGgGAAgKQAAgKAGgGIAHgIIgEgIQgDgFAAgFQAAgHAEgFQAEgEAGAAQAFAAAEAEQAEAEAAAHQAAAHgEAHIgHAHIAOAWQACgFAAgLIAGAAIAAADQAAALgEAIIAIAOIgIAAIgEgHQgDAEgDABQgEADgGAAQgJAAgFgFgAjIAAQgEAFAAAHQAAAGAEAEQADAEAGAAQAHAAAFgHIgPgYIgGAFgAjEglQgDACAAAEQAAAEADAEIAEAHQADgDACgDQADgEAAgFQAAgEgCgCQgCgCgDAAQgDAAgCACgAIzAgIAAggQAAgJgCgDQgCgGgGAAQgGAAgDAHQgDAEAAAHIAAAgIgGAAIAAgkIgBgOIAAgGIAGAAIABAJQAFgKAJAAQAGAAAEAEQADAEABAHIAAAKIAAAggAEUAgIAAggQAAgJgBgDQgCgGgGAAQgHAAgDAHQgCAEAAAHIAAAgIgHAAIAAgkIAAgOIgBgGIAHAAIAAAJQAFgKAJAAQAGAAAEAEQAEAEABAHIAAAKIAAAggACGAgIAAggIgBgMQgDgGgFAAQgHAAgDAHQgCAEAAAIIAAAfIgHAAIAAhPIAHAAIAAAeQAFgIAIAAQAFAAAEADQAEADABAGIABANIAAAggABXAgIgUgfIATgZIAIAAIgTAZIAVAfgAA8AgIAAhPIAHAAIAABPgAhOAgIAAg4IAHAAIAAA4gAj8AgIAAggQAAgJgBgDQgCgGgGAAQgHAAgDAHQgCAEAAAHIAAAgIgHAAIAAgkIAAgOIgBgGIAHAAIAAAJQAFgKAJAAQAGAAAEAEQAEAEABAHIAAAKIAAAggAlcAgIAAg4IAHAAIAAA4gAlwAgIgTgfIATgZIAIAAIgTAZIAUAfgAmKAgIAAhPIAGAAIAABPgAoWAgIAAg4IAHAAIAAA4gApQAgIAAglIgGAAIAAgHIAGAAIAAgjIAKAAIANABQALACAHALQAGALAAAPQAAAQgHAKQgHALgLACIgNAAgApJAYIAFAAIAKAAQAEgBADgDQAEgCACgFQAEgIAAgMQAAgOgFgJQgFgHgHgBIgMgBIgDAAIAAAbIAPAAIAAAHIgPAAgApwgVIgHAMIgEgEIAHgMIgLgEIABgGIALAFIAAgPIAFAAIAAAPIALgFIACAGIgMAEIAHAMIgDAEgAgigeIgHgJIgGAJIgFAAIAIgOIAHAAIAIAOgAkwgeIgGgJIgHAJIgFAAIAJgOIAGAAIAIAOgAnpgeIgHgJIgGAJIgFAAIAIgOIAHAAIAIAOgADZggIAAgDIACgCIABgCIABgBIABgBIABgCIAAgCIgBgBIgDgBQAAAAgBAAQAAAAgBAAQAAAAAAABQgBAAAAAAIgBAEIgDAAIAAgDIABgDQADgDADAAQAEAAABACIACADIABADIgBACIgBACIgBABIgCACIgBACIgBACgAFLghIAIgNIAHAAIgKANgAhOglQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABIgBAEQAAABgBAAQAAABAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAgAlcglQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABIgBAEQgBABAAAAQAAABgBAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAgAoWglQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABIgBAEQgBABAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAgAgdgrIgKgNIAHAAIAIANgAnkgrIgKgNIAHAAIAIANg");
	this.shape.setTransform(72.975,4.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(9,-1.6,128,11.299999999999999);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.514,1],-14.5,-4.6,14.7,4.7).s().p("AjwD8IC+pUIEjBeIi+JTg");
	this.shape.setTransform(24.125,34.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.3,69);


(lib.Symbol1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ABPAfIAAgQIACAAQAAAFABACIADADQACACADABQADAAACgDQACgCAAgDQAAgEgDgCIgEgDQgFgCAAgBQgGgDAAgGQAAgFADgDQADgDAFAAQAEAAADADIABgEIACAAIAAANIgCAAQgBgKgGAAQgDAAgCAEQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIABAEIAFADIAEACIAGAFQACACAAAEQAAAGgEADQgDADgEABQgFgBgEgDIgCAFgAAxAfIAAgQIACAAIACAHQAAAAAAABQAAAAABABQAAAAAAABQABAAAAAAQACACADABQADAAADgDQABgCAAgDQAAgEgCgCIgFgDIgFgDQgFgDAAgGQAAgFADgDQADgDAEAAQAEAAADADIACgEIABAAIAAANIgCAAQgBgKgGAAQgDAAgCAEQAAAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAABAAAAQAAAAABAAQAAABAAAAQAAABAEACIAFACIAFAFQACACAAAEQAAAGgDADQgDADgFABQgFgBgDgDIgDAFgAgkAaQgEgEgCgJQgCgGAAgHQAAgMAFgJQADgEAEgDQADgCAEAAQAHAAAEAGIADgGIABAAIAAASIgBAAQgEgOgJAAQgHAAgDAHQgDAHAAAMQAAALACAHQAEAIAHAAQAEAAAEgDQADgFABgIIACAAQAAAGgBAFQgDAEgDADQgEACgEABQgFgBgGgEgAAkAbIgBgFIgDAFQgCACgFABQgEgBgDgCQgDgDAAgFQAAgIAJgFQAEgBAGgBIAAgFQAAgEgBgBQgCgEgDAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAABIAAAAIAAABQAAABAAABQAAABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAgBQAAgDADgEQAEgDAFAAQADAAADABQADADABAFIABAFIAAASIAAAFQAAABABAAQAAAAAAABQAAAAABAAQAAAAABAAIABAAIAAACIgEABQgBAAAAgBQgBAAgBAAQAAAAAAgBQgBAAAAgBgAAaAJQgFADAAAGQAAAEACACQAAABABAAQAAAAABABQAAAAABAAQABAAAAAAQAEAAACgEIABgJIAAgHQgEABgEACgAAEAdIgHAAIAAgBQAAAAABAAQAAAAABAAQAAAAAAgBQABAAAAAAIAAgCIAAgCIAAgrIAAgEQAAAAAAAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgCAAIAAgCIAJgDIAAA1IABACQABACADABIAAABIgHAAgAhlAdIAAgCIAEgBIABgDIAAgBIAAgqIAAgEQAAgCgFAAIAAgCIAeAAIABANIgBAAQgBgGgCgCQgCgCgDAAIgKAAIAAAXIAKAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAgBQACgBAAgFIACAAIAAAQIgCAAIgBgFQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgJAAIAAAWIAAACQABACAEAAIAEAAQAEAAACgCQADgCABgHIACAAIgCAOgAhCAHIAAgDIASAAIAAADg");
	this.shape.setTransform(149.375,177.75);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C3CED4").s().p("AkvBDQgIAAAAgJIAAhzQAAgJAIAAIJfAAQAIAAAAAJIAABzQAAAJgIAAg");
	this.shape_1.setTransform(149.475,177.625);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer_2
	this.instance = new lib.bg1();
	this.instance.parent = this;
	this.instance.setTransform(0,-1,0.3762,0.3762);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-1,301,477.8);


(lib.Symbol27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.instance = new lib.Symbol29("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(63.45,64.25,1,1,0,0,0,45.6,10.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5).to({_off:false},0).to({y:46.65,alpha:1},10,cjs.Ease.get(1)).to({y:48.25},8,cjs.Ease.get(1)).wait(50).to({startPosition:0},0).to({_off:true},1).wait(1391));

	// Layer_1
	this.instance_1 = new lib.Symbol28("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(63.7,29.2,1,1,0,0,0,63.7,13.2);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:11.6,alpha:1},10,cjs.Ease.get(1)).to({y:13.2},8,cjs.Ease.get(1)).wait(55).to({startPosition:0},0).to({_off:true},1).wait(1391));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-59.4,-27.8,265.59999999999997,153.9);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ArSC/IAAl9IWlAAIAAF9g");
	mask.setTransform(47.7,15.525);

	// Layer_3
	this.instance = new lib.Symbol2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-51.6,14.65,1,1,0,0,0,24.1,34.5);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:146.9,y:19.05},23,cjs.Ease.get(1)).wait(67));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24.5,-3.5,144.5,38.1);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(43.35,7.65,0.4,0.4,0,0,0,43.4,7.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:7.6,scaleX:1.1,scaleY:1.1,x:43.4,y:7.6,alpha:1},11,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(1944));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-39.6,-12.6,188.6,50.9);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol7("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(168.15,55.2,1,1,0,0,0,114.2,20.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:125.75,alpha:1},11,cjs.Ease.get(1)).to({x:128.15},10,cjs.Ease.get(1)).wait(1339));

	// Layer_1
	this.instance_1 = new lib.Symbol6("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(87.5,20.4,1,1,0,0,0,127.5,20.4);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:129.9,alpha:1},11,cjs.Ease.get(1)).to({x:127.5},10,cjs.Ease.get(1)).wait(1339));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37.5,5.3,315.5,61.8);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol3("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(73,4.75,1,1,0,0,0,73.2,5.2);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},9,cjs.Ease.get(1)).wait(2516));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(8.8,-2.1,128,11.4);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.i=1;
	}
	this.frame_207 = function() {
		this.stop();
		var d = this;
		setTimeout(function () {
			if (d.i <= 2) {
			d.play();
		
			}
			d.i++;
		
		
		}, 2000);
	}
	this.frame_222 = function() {
		this.gotoAndPlay(2);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(207).call(this.frame_207).wait(15).call(this.frame_222).wait(1));

	// Layer_12
	this.instance = new lib.Symbol18();
	this.instance.parent = this;
	this.instance.setTransform(145.4,386.1,1,1,0,0,0,42.4,10.1);
	this.instance.alpha = 0.8008;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(146).to({_off:false},0).wait(77));

	// cta
	this.instance_1 = new lib.Symbol11("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(142.05,387.7,0.85,0.85,0,0,0,43.6,7.9);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(118).to({_off:false},0).wait(105));

	// Layer_4
	this.instance_2 = new lib.Symbol1("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(153.2,586.2,1,1,0,0,0,73.2,5.2);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(99).to({_off:false},0).wait(124));

	// Layer_6
	this.instance_3 = new lib.Symbol5("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(150.5,300.1,1.03,1.03,0,0,0,127.7,20.5);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(90).to({_off:false},0).wait(133));

	// logo
	this.instance_4 = new lib.Symbol4("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(176.5,545.3,1,1,0,0,0,241.5,187.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(223));

	// bg2
	this.instance_5 = new lib.Symbol15("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(155.1,315.85,1.2,1.2,0,0,0,159.1,299.9);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(70).to({_off:false},0).to({regX:159.2,regY:300,scaleX:1,scaleY:1,x:155.2,y:300,alpha:1},20,cjs.Ease.get(1)).wait(133));

	// t1
	this.instance_6 = new lib.Symbol27("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(146.4,320.9,0.82,0.82,0,0,0,63.9,13.3);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(9).to({_off:false},0).to({_off:true},74).wait(140));

	// bg1
	this.instance_7 = new lib.Symbol1copy("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(149.25,347.9,1.2,1.2,0,0,0,150,299.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({regY:300,scaleX:1,scaleY:1,x:150,y:300},17,cjs.Ease.get(1)).wait(206));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-32.2,-44,376.2,670.9);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.parent = this;
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(95.1,286.9,259.1,387.6);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg1.jpg?1715590280200", id:"bg1"},
		{src:"images/bg2.jpg?1715590280200", id:"bg2"},
		{src:"images/logo.jpg?1715590280200", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;