(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,200,200);


(lib.Symbol28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEF8F0").s().p("A6PV4MAAAgrvMA0fAAAMAAAArvg");
	this.shape.setTransform(168,140);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,280);


(lib.Symbol27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AilCzQgRgFgMgHQgLgIgFgJQgGgLAAgJQAAgPAIgJQAJgKAPgFQgIgEgFgHQgFgIAAgLQAAgJAGgKQAHgKAOgHQgPgIgJgOQgJgNAAgTQAAgPAGgMQAGgNALgIQALgJAPgEQAPgEASAAQAaAAAUAJIA8AAIAAAVQAAAFgDACQgDADgGABIgQADQADAKAAALQAAAQgGALQgGAMgLAIQgLAJgPAFQgPAFgRAAQgLAAgKgCQgIAFAAAGQAAAGAGACQAGADAJABQAJACAMAAIAXAAQANABAMADQALADAKAFQAJAGAGAJQAFAJAAAPQAAAOgHANQgGANgNAJQgNALgTAGQgSAGgYAAQgYAAgRgEgAikBtQgEAGAAAHQAAAFABAEQADAFAFACQAFADAKACQAIACANAAQAOAAAJgCQAKgCAFgDQAGgDACgFQADgFAAgFQAAgFgDgEIgKgFQgFgCgIgBIgRgBIgSgBIgSgCQgHAFgEAFgAiXgyQgIAIAAAPQAAANAIAJQAIAHARAAQARAAAIgHQAIgJAAgNQAAgPgIgIQgIgIgRAAQgRAAgIAIgAAFCyIAAkNIAhAAQALAAADAJIAFASIANgNQAHgGAIgEIAQgGQAKgCAKAAQAQAAAPAHQANAHAKAOQAKAMAGAUQAFATAAAYQAAAXgGAUQgGAUgMAOQgLAOgRAIQgQAIgTAAQgRAAgMgFQgLgFgKgJIAABSgABOgvQgJAFgKALIAABZQAIAJAKAEQAJADAKAAQAKAAAIgDQAHgEAHgIQAGgIADgNQADgMAAgSQAAgQgDgLQgCgMgGgIQgEgHgHgEQgHgDgJAAQgOAAgKAGgAMWBwQgGgCgFgEQgEgEgCgHQgDgFAAgHQAAgGADgGQACgGAEgFQAFgEAGgDQAFgBAHAAQAHAAAGABIALAHQAEAFACAGQADAGAAAGQAAAHgDAFQgCAHgEAEQgFAEgGACQgGADgHAAQgHAAgFgDgAH2BrQgUgHgNgNQgOgOgHgUQgHgTAAgYQAAgYAHgTQAHgUAOgNQANgOAUgHQATgHAXAAQAWAAAUAHQASAHAOAOQANANAHAUQAHATAAAYQAAAYgHATQgHAUgNAOQgOANgSAHQgUAIgWAAQgXAAgTgIgAH8glQgLAQAAAfQAAAgALAQQALAQAZAAQAXAAALgQQALgQAAggQAAgfgLgQQgLgQgXAAQgZAAgLAQgApYBrQgTgHgOgNQgNgOgIgUQgHgTAAgYQAAgYAHgTQAIgUANgNQAOgOATgHQATgHAXAAQAWAAAUAHQATAHANAOQAOANAGAUQAIATAAAYQAAAYgIATQgGAUgOAOQgNANgTAHQgUAIgWAAQgXAAgTgIgApRglQgMAQAAAfQAAAgAMAQQALAQAYAAQAXAAAMgQQALgQAAggQAAgfgLgQQgMgQgXAAQgYAAgLAQgAtDBtQgNgGgJgKQgIgKgFgOQgEgPAAgRIAAiAIA2AAIAACAQAAARAIAKQAIAKAPAAQAMAAAKgGQAKgFAJgJIAAiRIA2AAIAADLIghAAQgKAAgEgJIgDgPQgGAHgGAEQgHAFgIADQgHAEgJACQgJACgJAAQgRAAgNgGgAysBvQgLgEgIgIQgGgHgEgLQgEgKAAgOIAAhtIgTAAQgFAAgDgDQgCgDAAgFIAAgWIAggGIALg1QACgIAKAAIAdAAIAAA+IA0AAIAAAmIg0AAIAABpQAAAJAEAFQAEAFAHAAIAHgBIAEgCIAEgCIAEgBIAEABIADAEIARAaQgMAJgOAFQgPAEgPAAQgOAAgKgEgAS1BwIAAiBQAAgRgIgJQgIgKgPAAQgMAAgJAFQgLAFgKAJIAACSIg2AAIAAjLIAiAAQALAAACAJIAEAPQAGgHAHgEIAOgJQAHgEAJgCQAIgBAKAAQASAAAMAGQANAFAJAKQAJALAEAOQAEAOAAARIAACBgAOgBwIhQjLIAtAAQAGAAAFADQADACACAEIAiBkIAGAVIAFAUQABgLADgJIAHgVIAjhkQABgEAEgCQAEgDAGAAIArAAIhQDLgAKnBwIAAjLIA2AAIAADLgAFkBwIAAiBQAAgRgIgJQgIgKgQAAQgLAAgKAFQgLAFgIAJIAACSIg3AAIAAkmIA3AAIAABvQAGgGAGgDQAGgFAHgDQAHgDAIgCQAIgBAJAAQARAAANAGQAMAFAKAKQAJALAEAOQAEAOAAARIAACBgAkqBwIAAiBQAAgRgIgJQgIgKgQAAQgLAAgJAFQgLAFgJAJIAACSIg2AAIAAjLIAhAAQALAAACAJIAFAPQAFgHAHgEIAOgJQAIgEAIgCQAIgBALAAQARAAANAGQAMAFAJAKQAJALAEAOQAFAOAAARIAACBgAvIBwIAAiBQAAgRgIgJQgIgKgQAAQgLAAgKAFQgKAFgKAJIAACSIg2AAIAAkmIA2AAIAABvIANgJQAGgFAHgDQAGgDAJgCQAIgBAJAAQARAAANAGQANAFAIAKQAKALAEAOQAEAOAAARIAACBgAK1h2IgLgIQgEgEgDgHQgDgFAAgHQAAgIADgFIAHgLQAFgEAGgCQAGgDAHAAQAHAAAGADQAGACAFAEQAFAFACAGQADAFAAAIQAAAHgDAFQgCAHgFAEQgFAEgGAEQgGACgHAAQgHAAgGgCg");
	this.shape.setTransform(123.325,235.225);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFCC66","#FF915C"],[0,0.502],-126.2,0,126.1,0).s().p("Ay6GUQgzAAAAhEIAAqeQAAhFAzAAMAl2AAAQAyAAAABFIAAKeQAABEgyAAg");
	this.shape_1.setTransform(122.2338,234.8048,1.1449,0.8779);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.2,199.4,288.9,70.9);


(lib.Symbol25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#007E9E").s().p("ADrCQQgLgMAAgVIAAh7QAAgIAOAAIAFAAQAPAAAAAIIAAB1QAAALAFAGQAFAFAKAAQAKAAAIgFQAIgGAFgJIAAh3QAAgIAOAAIAGAAQAPAAAAAIIAAByQAAAUABALIACAMQAAADgFACIgKADIgJABQgGAAgCgFIgEgSQgIALgLAIQgMAGgNAAQgVAAgLgMgAIsBEQAAgvASgVQARgWAggBQAfAAAOAXQAPAXAAAqQAAAPgNABIhOAAQABAYAIALQAKAMARAAQAMAAAIgDIAPgHIAHgCQADAAACADIADAHIAAAIQAAAFgHAFQgIAFgMADQgMAEgNAAQhGAAAAhYgAJZAQQgJAMAAAaIA5AAQAAgygaABQgOgBgIAMgABCBEQAAgvASgVQASgWAggBQAeAAAPAXQAOAXAAAqQAAAPgNABIhNAAQAAAYAJALQAJAMASAAQALAAAIgDQAJgDAGgEIAHgCQADAAACADQACADABAEIABAIQAAAFgIAFQgIAFgMADQgLAEgOAAQhGAAAAhYgABvAQQgIAMAAAaIA5AAQAAgygbABQgOgBgIAMgAHVCaQgGABgEgCQgEgCAAgFIgpibIgBgGQAAgFAOAAIAIAAIAJABQAEABAAADIAcCHIABAAIAciHQAAgDAEgBIAKgBIAGAAQAOAAAAAFIAAADIgBADIgoCbQgCAFgEACQgDACgFgBgAAOCaQgIAAgDgCQgDgCAAgEIAAieQAAgFADgBQADgCAIAAIAFAAQAIAAADACQAEABAAAFIAACeQAAAEgEACQgDACgIAAgAg7CaQgJAAgDgCQgEgCAAgEIAAh0QAAgMgFgGQgFgGgMAAQgHAAgGADQgGAEgEAFIgGAIIAAB4QAAAEgDACQgDACgJAAIgFAAQgIAAgDgCQgDgCAAgEIAAjrQAAgIAOAAIAFAAQAPAAAAAIIAABZQAHgJALgHQALgGAOgBQASAAANAMQANAKAAAYIAAB7QAAAEgEACQgEACgHAAgAkHCaQgJAAgDgCQgEgCAAgEIAAh0QAAgMgFgGQgFgGgKAAQgJAAgIAGQgHAGgDAIIAAACIAAB2QAAAEgEACQgDACgIAAIgFAAQgJAAgDgCQgDgCAAgEIAAh0QAAgMgFgGQgFgGgKAAQgHAAgGADQgFAEgEAFIgGAIIAAB4QAAAEgDACQgDACgJAAIgEAAQgJAAgDgCQgDgCAAgEIAAhyQAAgWgCgJIgCgNQAAgDAFgCQAFgCAFAAIAKgBQAFAAACAFIAEARQAIgKALgHQALgIANAAQANABALAFQALAHAEANQAHgKALgIQALgHAPgBQARAAAMAMQAMAKAAAYIAAB7QAAAEgDACQgEACgIAAgAn4CaQgIAAgDgCQgEgCAAgEIAAieQAAgFAEgBQADgCAIAAIAFAAQAJAAADACQADABAAAFIAACeQAAAEgDACQgDACgJAAgApnCaQgPABAAgJIAAjCIgtAAQgHAAAAgNIAAgHQAAgLAHAAIB+AAQAIAAAAALIAAAHQAAANgIAAIgsAAIAADCQAAAJgPgBgAKBgnQgEgCgDgFIgLgRIgKARQgDAFgEACQgDABgHABQgJgBAAgEIABgEIACgHIALgXQACgFAGgCQAFgDAJAAQAKAAAFADQAGACACAFIAKAXIADAHIABAEQAAAEgJABQgHgBgDgBgACXgnQgEgCgDgFIgLgRIgKARQgDAFgDACQgEABgHABQgJgBAAgEIABgEIACgHIALgXQADgFAFgCQAGgDAIAAQAKAAAFADQAGACACAFIALAXIACAHIABAEQAAAEgJABQgHgBgDgBgAn2gmQgEgCgEgGIgPgUIgGgIQgDgEAAgCQAAgDAEgBQADgCAIAAQAMAAAEADQAFACACAFIAKAXIADAHIABAEQAAAEgJABIgLgBgAADgsQgDgDAAgDIAAgWQAAgEADgDQAEgCAKABQAJgBAEACQAEADAAAEIAAAWQAAADgEADQgEACgJAAQgKAAgEgCgAB9hhQgEgDAAgCQAAgCAFgEIAIgIQAEgFAAgGQAAgGgDgCQgDgCgEAAQgFAAgCABIgFABQgCAAgDgEQgEgFAAgCQAAgCAIgEQAIgEAJABQAKAAAJAFQAJAGAAANQAAAIgEAHQgDAHgGAEQgFAGgFACQgEADgCABQgDAAgDgEgAJuhiQgDgCgFgGIgPgUIgGgIQgCgDAAgCQAAgDADgCIAMAAQALgBAFADQAFACABAFIALAYIADAFIAAAFQAAAEgJAAIgLgBg");
	this.shape.setTransform(96.225,13.55);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(28,-2.1,136.5,31.3);


(lib.Symbol23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF915C").s().p("AA2CTIgCgBIgEgCQgPgEgKgNQgKgNAAgQIAAjXQAAgGgDgDQgFgFgFAAQgMAAAAAOIAADXQAAAQgJANQgKANgQAEIgGACIgEgPQAFgBABgBQAKgDAHgIQAHgJAAgLIAAjXQAAgMAIgIQAIgJALAAIABAAQALAAAIAJQAIAIAAAMIAADXQAAALAHAJQAGAIALADIABAAIAFACQgBAQgCAAIgBAAg");
	this.shape.setTransform(24.725,-7.3472);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkNE0IgEAAQgHgCABgIQACgIAHACIABAAQA0AKAggXQAdgUAQg1QAJgdAJhAIACgNIADgNIgSANQgSALgYAGIAAAAIgdAaQgZAiALAtQABAHgHABIgCABQgFAAgCgGQgMgzAcgnQgLAGgJAJQgNALgGAKQgCAEgEAAIgEgCIgBAAQgHgDAFgHIACgDQAHgKAMgLQAbgYAngLIAEgCIAGgCQAwgPAPghIABgCQAEgQAEgHIABgCQgNAFgLAAQgJAAgHgCQgDABgDgCQgLgDgOABQgbADgKAXQgDAFgFAAIgCgBQgHgDACgHQAMgbAcgGIAEgBQgPgKgEgIQgCgCABgEQABgCADgCQAHgFADAHQADAHAMAIQAMAIAMAEIAFABQAIACAJAAQAVAAAfgYQAHgGAIgFQANgIAPgEIAGgCQAKgDAHgIQAHgJAAgLIAAjYQAAgMAHgIQAIgJALAAIACAAQALAAAIAJQAIAIAAAMIAADYQAAALAHAJQAGAIALADIABAAIAFACQAYAGASARQAhAYAVAAQAIAAAJgCIAIgCQAWgHANgTQAEgGAHAEQAHADgGAHQgHAKgKAJIADAAQAcAHALAaQADAGgGAEIgEABQgFAAgBgFQgLgXgagDQgJgBgGABIgMADIgBAAIgBAAIgSACIgBAAQgLAAgNgFIABACIAGAPQACACABACIACAFIABACQAMAcAYATIABABQAgAYAhgIQAHgBACAHQACAIgIACIgSACQgiAAgegaIgKgJIgHgHIACAHIACANQAKA9AJAfQAQAyAaAYIALAKQgFgDgFAFQgEAGAGAFIgOgLQgcgagRg1IgLgwQgIAqgYAXQgBACgEAAQgDAAgCgCQgFgFAFgGQAegdgBhEIgCgVIgEgjQgFgVgFgLQgKgQgMgMIgEgCIgLgIQgMgIgOgEIgCgBIgEgBQgPgEgKgNQgKgNAAgQIAAjYQAAgGgDgDQgFgFgFAAQgNAAAAAOIAADYQAAAQgJANQgJANgQAEIgGACQgMADgKAGIgCABIgOAKIgCABQgNAMgJARIgIAXIAAABIgBAFIgDAmIgBAVQABBFAaAcQAFAGgFAFQgCACgEAAIgFgCQgWgYgGgvQgHAkgGAUQgRA3ghAXQgaATgmAAQgPAAgOgDg");
	this.shape_1.setTransform(22.0325,9.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#007E9E").s().p("AAZBbIACgiIgGAAQgVAAgTgDIgCAhQgCAIgGAAIgBAAQgIAAAAgIIADgkQgZgHgYgMQgGgEADgHQABgDADgBQADgBADACQAVALAWAGIADgsQgZgIgTgPQgGgFAEgGQAEgFAFADIACABQAQAMAUAGIAEhBQACgHAHAAQAIABgBAHIgFBFQAWAFAZAAIAFhGQAAgIAIAAQAHACAAAGIgEBFIAYgDIAHgCQAHgCACAJQACAHgIABIgaAFIgFAAIgEABIgDAqIAcgFQAIgCABAHQACAIgHACQgQAEgRACIgDAjQAAAHgIAAQgHgBAAgHgAgSAnQAWAFAYgBIADgsIgDAAQgYAAgTgEg");
	this.shape_2.setTransform(53.9507,42.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF915C").s().p("AFYFcIgOgDQhXgUhLgnQhKgngZgoQgYgmgEiAIADieIAAgHQAChNAHgnIABgCQAOAEAMAIIALAIIAEADQAMAMAKAQQAFAKAFAWIAEAjIACAUQABBEgeAdQgFAGAFAEQACADADAAQAEAAABgDQAYgWAIgqIALAwQARA0AcAbIAOALQAUAPAZAHIgEAuQgVgGgWgLQgCgCgEABQgCABgCACQgCAIAGADQAYAMAYAHIgCAkQAAAJAIAAIAAAAQAGAAACgIIADghQATADAWAAIAGAAIgDAhQAAAHAIACQAIAAAAgIIACgjQARgCARgEQAGgCgBgHQgCgHgIACIgcAFIADgrIAFgBIAEAAIAbgFQAHgCgBgHQgCgIgIABIgHACIgYAEIAFhFQAAgHgHgCQgJAAAAAIIgEBGQgaAAgWgFIAEhEQACgHgJgCQgGAAgCAIIgEBBQgUgHgQgMIgCgBIgLgJQgagYgQgyQgJgfgKg8IgCgNIgCgHIAHAHIAKAIQAeAaAiAAIASgCQAIgBgCgIQgCgIgHACQghAIgggYIgBgBQgYgTgMgcIgBgCIgCgFQgBgDgCgCIgGgPIgBgCQANAFALAAIABAAIASgBIABAAIABAAIAMgEQAGgBAJABQAaAEALAWQABAFAFAAIAEgBQAGgDgDgHQgLgagcgHIgDAAQAKgIAHgLQAGgHgHgDQgHgFgEAGQgNAVgWAHIgIABQgJACgIAAQgVAAghgZQgSgQgYgHQAShHAugPQA+gTBSBYQArAvAjA/QALATAJAWQAUArAPAwQA1ChgSBzQgQBphDAAIgHAAgAmqEUQgFgQgCgRQgLhKAShfQAJgzASg4QAwiWBWhcQBRhYA/ATQAuAPASBHQgPAEgNAIQgIAFgHAGQgfAZgVAAQgJAAgIgCIgFgBQgMgEgMgIQgMgJgDgHQgDgHgHAGQgDABgBADQgBADACADQAEAIAPALIgEAAQgcAGgMAbQgCAIAHACIACABQAFAAADgFQAKgWAbgEQAOgBALAEQADACADgBQAHABAJAAQALAAANgFIgBACQgEAIgEAPIgBADQgPAggwAQIgGABIgEACQgnALgbAYQgMALgHALIgCACQgFAHAHAEIABAAIAEABQAEAAACgEQAGgJANgMQAJgIALgHQgcAnAMAzQACAGAFAAIACgBQAHgCgBgGQgLgtAZghIAdgaIAAAAQAYgHASgKIASgNIgDANIgCANQgJBAgJAdQgQAzgdAVQggAXg0gKIgBAAQgHgCgCAIQgBAHAHACIAEABQAOADAPAAQAmAAAagTQAhgXARg2QAGgVAHgkQAGAvAWAXIAFADQAEAAACgDQAFgEgFgGQgagbgBhGIABgUIADgnIABgEIAAgCIAIgWQAJgRANgMIACgCIAOgKIACgBQAKgGAMgDIAAACQAIAmACBOIAAAHQADBzgBArQgCB/gYAnQgZAohLAnQg9AghEATQgQAFgSADQgLADgKAAQg3AAgUhIgAESCUIACgsQAVAEAYAAIACAAIgCAsIgIABQgUAAgTgFg");
	this.shape_3.setTransform(24.7212,31.6136);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-32,-22,113.3,117.4);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF915C").s().p("AgmCUQgYgWAAgnIAAi/QAAgFAFgCQAEgEAKAAIAGAAQAKAAAFAEQAEACAAAFIAAC/QAAAWANALQALAMAXAAQAWAAAMgMQANgLAAgWIAAi/QAAgLATAAIAIAAQAKAAAEgDQADgFAAgFQAAgIgFgHQgFgHAAgDQAAgDAEgEIAIgFIAHgCQAFAAAEAFQAEAGACAGQACAHAAAHQAAAQgJALQgGAHgMACIAAC7QAAAngXAWQgXAUgsAAQgsAAgXgUgAnLCGQgagkAAhJQAAhHAagjQAagkA2AAQALAAALACIARAGQAIADAAAHQAAAIgCAJQgCAHgGABIgNgCQgJgDgOAAQghAAgPAZQgPAYAAA3QAAA3APAaQAPAZAhAAQARAAAKgEQAJgDAEAAQAGgBACAJQADAIAAAJIgBAFQgCADgFACQgIAEgLADQgMACgOAAQg2AAgZgigAGICnQgTgBAAgJIAAgeQAAgKATAAIAIAAQATAAAAAKIAAAeQAAAJgTABgAE7CnQgHAAgEgDQgFgBgBgEIgPg9IhPAAIgPA9QgBAEgEABQgFADgGAAIgLAAQgPgBAAgHIAAgHIBFkBQADgKAQAAIASAAQAQAAACAKIBFEBIAAAEIABADQAAAHgPABgADwg0IgCANIgZBmIA9AAIgZhmIgCgNIgCgMIgCAAIgDAMgAiPCnQgKAAgEgEQgFgCAAgEIAAh0IhWAAIAAB0QAAAEgFACQgEAEgKAAIgHAAQgKAAgEgEQgEgCAAgEIAAkFQAAgFAEgCQAEgEAKAAIAHAAQAKAAAEAEQAFACAAAFIAABsIBWAAIAAhsQAAgFAFgCQAEgEAKAAIAHAAQAJAAAFAEQAEACAAAFIAAEFQAAAEgEACQgFAEgJAAgAGJBSQgOAAAAgKQAAgOAIgQQAHgRAPgRIAXgbQAKgMAAgPQAAgRgKgJQgLgIgTAAQgLAAgJAEIgPAFQgGADgDABQgDAAgDgFQgDgFgBgFIgCgJQAAgIAJgFQAKgFAOgEQAPgDANgBQAkABAWASQAVAUAAAcQAAAPgGAMQgFAMgJAKIgRAUQgNANgJANQgJANgDAPQAAAGgEABQgDACgIAAg");
	this.shape.setTransform(74.175,25.35);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(25.6,8.6,97.19999999999999,33.6);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#007E9E").s().p("ANaCwQgbgjAAhJQAAhIAbgjQAZgjAyAAQAyAAAaAjQAaAjAABIQAABJgaAjQgaAjgyAAQgyAAgZgjgAN6gLQgOAYAAA3QAAA3AOAaQANAZAeAAQAeAAANgZQAOgaABg3QgBg3gOgYQgNgageAAQgeAAgNAagAC3CwQgZgjgBhKQAAhHAbgjQAbgjA4AAQANAAAMACIATAFQAIADAAAIQAAAIgCAIQgDAIgGAAIgPgCQgIgCgRAAQgjAAgQAZQgQAXAAA3QAAA6APAYQAPAZAhAAIAPgBIAMgDIAAhQIghAAQgKAAAAgPIAAgIQAAgOAKAAIA+AAQANAAABANIAAByQgBAFgCADQgCADgFAEQgMAHgQAFQgTAEgRAAQg0AAgZgjgAkUCwQgagjAAhJQAAhIAagjQAagjAyAAQAdAAAVAMIADAAQALAAADgEQAEgEgBgFQAAgJgEgGQgFgHAAgDQAAgEAEgDIAHgFIAIgCQAEAAAEAFQAFAFACAHQACAHAAAGQAAARgKALQgGAHgMACIAHAIQAaAjAABIQAABJgaAjQgaAjgyAAQgyAAgagjgAjzgLQgOAYgBA3QABA3AOAaQANAZAeAAQAeAAANgZQAOgaABg3QgBg3gOgYQgNgageAAQgeAAgNAagAnxC+QgYgVABgoIAAi+QgBgFAFgDQAEgDAKAAIAHAAQAJAAAFADQAFADAAAFIAAC/QAAAVAMAMQAMALAXAAQAWAAANgLQAMgMAAgVIAAi/QAAgLATAAIAIAAQAKAAAEgEQADgEAAgFQAAgJgFgGQgEgHgBgDQABgEADgDIAIgFIAHgCQAFAAAEAFQAEAFADAHQABAHAAAGQABARgKALQgGAGgMADIAAC6QABAogYAVQgXAVgsAAQgsAAgYgVgAREDRQgKAAgEgDQgEgCAAgFIAAkEQAAgFAEgDQAEgDAKAAIAHAAQAKAAAEADQAEADABAFIAAEEQgBAFgEACQgEADgKAAgAL/DRQgKAAgFgDQgEgCAAgFIAAh0IhXAAIAAB0QABAFgFACQgEADgLAAIgGAAQgKAAgEgDQgEgCAAgFIAAkEQAAgFAEgDQAEgDAKAAIAGAAQALAAAEADQAFADgBAFIAABrIBXAAIAAhrQAAgFAEgDQAFgDAKAAIAHAAQAJAAAEADQAFADAAAFIAAEEQAAAFgFACQgEADgJAAgAG9DRQgKAAgEgDQgEgCAAgFIAAkBQAAgNANAAIA9AAQBPAAAABSQAABShPAAIgfAAIAABqQAAAFgEACQgEADgKAAgAHWA5IAfAAQAUAAAHgLQAJgLAAgYQAAgXgJgLQgHgLgUAAIgfAAgABYDRQgJAAgEgCQgEgBgDgGIhMiiIgFgMIgEgOIgCABIABANIABAOIAACfQAAAFgFACQgDADgLAAIgFAAQgKAAgEgDQgEgCAAgFIAAkEQAAgLASAAIAJAAQAKAAAEADQAEABADAGIBNCgIAFAMIAEAOIACgBIgBgMIgBgPIAAidQAAgFAFgDQADgDAKAAIAGAAQAKAAAEADQAEADABAFIAAEEQAAAKgTAAgApVDRQgJAAgFgDQgEgCgBgFIAAh0IhWAAIAAB0QAAAFgFACQgEADgKAAIgGAAQgKAAgFgDQgDgCAAgFIAAkEQAAgFADgDQAFgDAKAAIAGAAQAKAAAEADQAFADAAAFIAABrIBWAAIAAhrQABgFAEgDQAFgDAJAAIAHAAQAJAAAFADQAEADAAAFIAAEEQAAAFgEACQgFADgJAAgAtdDRQgSAAAAgKIAAjpIg2AAQgJAAAAgOIAAgIQAAgPAJAAICXAAQAJAAAAAPIAAAIQAAAOgJAAIg2AAIAADpQAAAKgRAAgAv/DRQgGAAgEgCQgEgBACgGIAMhFIgdAAIgNBEQAAAFgEADQgDACgLAAIgDAAQgGAAgEgCQgEgBACgGIAMhFIgVAAQgJAAAAgOIAAgGQAAgOAJAAIAbAAIAKg3IgXAAQgJAAAAgOIAAgGQAAgPAJAAIAdAAIAMg+QAAgFAEgDQADgCAMAAIACAAQAHAAAEACQAEACgBAFIgNA/IAcAAIANg+QAAgFADgDQAEgCALAAIADAAQAHAAADACQAEACgBAFIgMA/IARAAQAKAAAAAPIAAAGQAAAOgKAAIgYAAIgJA3IAVAAQAJAAAAAOIAAAGQAAAOgJAAIgbAAIgNBEQgBAFgDADQgEACgKAAgAwWBhIAdAAIAKg3IgcAAgAO/hYQgEAAgEgEIgRgQIgTAQQgDAEgDAAIgKABQgMAAAAgFIACgFIAFgHIAQgVQADgEAFgCQAFgCALAAQAKAAAFACQAFACAEAEIAPAVIAEAHIADAFQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQgDABgGAAIgJgBgAOaiSQgDgEAAgCQgBgDAGgDIALgIQAEgFAAgHQAAgFgDgCQgEgDgGAAQgGAAgEACIgFACQgCAAgFgGQgDgFAAgEQgBgDALgEQAKgEAKAAQANAAALAHQALAGAAAPQAAAIgEAIQgFAHgHAFQgGAGgGADQgFADgDAAQgDAAgFgEg");
	this.shape.setTransform(71.75,11.625);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40,-9.4,223.5,42.1);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF915C").s().p("AkkDHIAAgWQAAgKATAAQATAAAAAKIAAAWQAAAJgTAAQgTAAAAgJgAH7CIQgHAAgEgCQgFgBgBgFIgPg8IhPAAIgPA8QgBAFgEABQgFACgGAAIgLAAQgPAAAAgIIAAgGIBFkBQADgKAQAAIASAAQAQAAACAKIBFEBIAAAEIABACQAAAIgPAAgAGwhSIgCANIgZBmIA9AAIgZhmIgCgNIgCgNIgCAAIgDANgAABCIQgIAAgEgCQgEgBgDgGIhNihIgFgMIgEgOIgCABIABANIABAOIAACeQAAAFgFACQgEADgKAAIgFAAQgKAAgEgDQgEgCAAgFIAAkEQAAgLASAAIAJAAQAJAAAFADQAEABADAGIBOCgIAEAMIAFAOIACgBIgBgMIgBgPIAAidQAAgFAEgDQAEgDAJAAIAGAAQAKAAAEADQAEADAAAFIAAEEQAAAKgSAAgAjLCIQgGAAgFgCQgFgBAAgFIgPg8IhPAAIgQA8QAAAFgFABQgFACgGAAIgLAAQgPAAAAgIIABgGIBFkBQACgKARAAIARAAQAQAAADAKIBEEBIABAEIAAACQAAAIgPAAgAkVhSIgDANIgZBmIA+AAIgZhmIgDgNIgCgNIgCAAIgCANgACcCHQgNAAAAgNIAAhwIgSAAQgJAAAAgNIAAgIQAAgOAJAAIASAAIAAhqQAAgNANAAIBBAAQAyAAAaAiQAZAiAABIQAABHgZAiQgaAigyAAgAC7BjIAiAAQAdAAAOgZQAOgZAAg1QAAg2gOgYQgOgZgdAAIgiAAIAABSIAlAAQAJAAAAAOIAAAIQAAANgJAAIglAAgAoHCHQgNAAAAgNIAAj9QAAgNAMAAIA5AAQAoAAATAUQATAUAAAkQAAAUgJAQQgKAPgQAGIAAACQAVAGAMASQAMASAAAYQAABOhVAAgAnpBjIAdAAQAqAAAAgtQAAgVgMgMQgLgLgWAAIgaAAgAnpgZIAaAAQARAAAKgLQAJgLAAgTQAAgpgkAAIgaAAgAF4imQgGgDAAgDIABgEIABgEQAGgOAJgGQAKgGAKAAQALAAALADIAUAHQAKAEAGAAQAIAAADgEQAEgEACgEQADgDACAAQAEAAAFADQAGADAAACIgBAFIgDAIQgFAJgIAGQgHAGgNAAQgMAAgLgEIgVgGQgJgEgHAAQgHAAgDAEIgGAHQgCAEgDAAIgIgCg");
	this.shape.setTransform(93.875,21.375);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(40.6,0.6,106.6,41.6);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.logo();
	this.instance.setTransform(-224,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FCAF17").s().p("AgNBCIgBAAIgFgBQgIgCABgGIACgGIAAAAIAAAAIABAAQAGgLAWgNIAbgSQACgEgHgDIgugTIgBgBIAAABQABAGAIALQAIAKADADQABAAAAABQABAAABAAQAAAAABAAQAAAAAAAAQACgBAAgFIAAgBIgBgNIANAGIgCAJIgBACQgBAKgHAAQgGAAgFgIQgPgOgGgOQgEgLAMACQAUADAhALQATAHAAAIQAAAGgIAHIguAfIgDAEIACgBIAcgBIABAAQABgBAAAAQAAAAAAAAQAAgBAAAAQAAAAgBAAIgNgJIAEgCIAQAJQAGAGgKAEQgGADgQADQgOADgHAAIgCAAgAgvAGQgHgDAAgEQABgEAQgVQAhgpAJACQAGABADAJQAEAKAAAcIgOgFIgCgQQAAgBgBgBQAAgBAAAAQAAgBgBAAQAAgBAAAAIgIAHIgKAKQgGAAgCADQgCACABAEIgGAGQgLAKAAABQAAACAGADIAnAWIgDADg");
	this.shape.setTransform(79.0256,6.4254);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#860052").s().p("AC7AaQgFgEAAgFQAAgEACgDQAFgHAQgBIAHAAIAAgBQAAgMgKAAQgIAAgBAGIgHgDIAAgBQAEgIAMAAQAJAAAEAEQAFAEAAAHIAAAXIABAIIgIAAIgBgHIgFAFQgEACgFABQgHgBgEgDgADIAJQgKACAAAGQAAAGAJAAQAJABADgIIABgKgACSAWQgEgFAAgLQAAgIAFgIQAFgGAKAAQAMAAAGAJIgHACQgDgFgHgBQgNAAAAARQAAASANAAQAIAAADgGIAGADQgFAJgMAAQgLAAgGgIgABiAFQAAgKAHgGQAGgFAIAAQAOAAAFAPIAAAIIggAAQAAASAOgBQAFAAAEgEIAHABQgEAJgNAAQgVAAAAgZgABqACIAYAAQAAgNgMAAQgKAAgCANgAANAFQAAgKAHgGQAFgFAJAAQAOAAAEAPIABAIIggAAQAAASAOgBQAFAAAEgEIAHABQgFAJgMAAQgVAAAAgZgAAVACIAYAAQgBgNgLAAQgKAAgCANgAhHAaQgFgEAAgFQAAgEACgDQAEgGARgCIAHAAIAAgBQAAgMgKAAQgIAAgBAGIgHgDIAAgBQAEgIAMAAQAIAAAEAEQAGAEAAAHIAAAXIABAIIgIAAIAAgHQgJAIgGAAQgHgBgEgDgAg6AJQgKACAAAGQAAAGAJAAQAIABAEgIIABgKgAA5AdIAAgrIAIAAIAAAGQAEgIAKAAQALAAADALIABAiIgHAAIgBggQgCgGgHAAQgFAAgEAEQgDADAAAFIAAAagAggAdIAAgIIAhgrIghAAIAAgHIAqAAIAAAHIggAsIAgAAIAAAHgAhjAdIAAgrIAIAAIAAAIQAEgKALABIAAAHQgKAAgEAGQgBACAAAIIAAAVgAh4AbIgBgIIAAgcIgHAAIAAgFIAHAAIAAgLIAHgEIAAAPIAJAAIAAAFIgJAAIAAAYQAAAJAEgBIAFgBIAAAGIgIABQgGAAgBgCgAinAUIAHgBQAEAFAIgBQALABAAgIQAAgFgOgDQgPgDAAgJQAAgNARAAQAMAAAEAJIgHADQgCgGgIgBQgJAAAAAHQAAAFAKACQATADAAAKQAAAGgEAEQgGAEgJAAQgOAAgEgJgAixAdIgGgSIgXAAIgGASIgIAAIAWg6IAIAAIAVA6gAjLAEIAAAAIARAAIgIgXg");
	this.shape_1.setTransform(52.075,10);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-224,-0.2,308.5,20.2);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#007E9E").s().p("AkmCNQgPgLAAgWQAAgNAHgLQAHgLAMgGIAAgBQgMgIAAgQQAAgKAFgIQAEgHAHgGQgNgHgGgLQgFgMAAgRQAAgaAOgQQAPgPAbAAQAIAAAKACIAvAAQAHAAAAAMIAAAEQAAALgHAAIgJgBIgIAAIAAABQAHAMAAARQAAAYgNAOQgOAPgYABQgKABgGAEQgGAEAAAJQAAAIAGAEQAFADAJACIATADQASADANAKQANAJAAAWQAAAYgRANQgSANggAAQgeAAgPgKgAkTBYQgEAGAAAJQAAAXAhgBQAiABAAgWQAAgJgGgFQgEgFgIgBQgIgCgJgBIgRgDQgGADgFAHgAkKg+QgHAHAAATQAAASAHAHQAIAFAKAAQALAAAIgFQAHgHAAgSQAAgTgHgHQgIgGgLAAQgKAAgIAGgAAZCWQgNgBAAgFIABgFIASg4IguijIgBgFQAAgHAOABIAGAAQAGgBADACQAEABABAEIAcB7IACAAIAZh7QABgEAEgBQAEgCAFABIAHAAQANgBAAAHIAAACIgBADIg8DgQgBAEgEABIgJABgAE1CFIAAgRQAAgIAQAAQAQAAAAAIIAAARQAAAJgQAAQgQAAAAgJgAETBGQgMgOAAgYQAAgWALgMQALgOAUgFQAUgHAYAAIAAgMQAAgKgGgIQgFgHgPAAQgMAAgJADIgRAGIgIACQgCAAgDgDIgCgIIgBgIQAAgEAJgFQAIgEANgEQANgDANAAQAdAAAPAOQAPAOAAAYIAABHQAAAVACAJIABAMQAAAEgFACIgKADIgJAAQgFABgCgFIgEgQQgHAKgKAHQgKAFgPAAQgWAAgNgNgAE1AEQgLAIAAATQAAAMAFAHQAFAGALAAQAJAAAIgEQAIgFAFgJIAAgoQgcAAgMAGgADJBQQgJgEgFgJQgGgKAAgQIAAhoIgMAAQgHABAAgMIAAgFQAAgMAHAAIAMAAIAEgiQABgHAMgBIAEAAQAHAAADADQADACAAADIAAAiIAUAAQAHAAAAAMIAAAFQAAAMgHgBIgUAAIAABkQAAALADAEQACADAGAAIAIgBIAFAAQAAAAABAAQAAAAABABQAAAAABABQAAABAAABQACADABAEIAAAHQAAADgEADQgEADgGABIgMABQgJAAgJgDgAiWBGQgMgOAAgYQAAgWALgMQALgOAUgFQATgHAZAAIAAgMQAAgKgGgIQgFgHgPAAQgMAAgKADIgQAGIgJACQgCAAgCgDIgCgIIgBgIQAAgEAIgFQAJgEAMgEQANgDANAAQAeAAAPAOQAOAOAAAYIAABHQAAAVACAJIACAMQAAAEgFACIgKADIgJAAQgFABgCgFQgCgEgCgMQgHAKgLAHQgKAFgOAAQgWAAgNgNgAh0AEQgMAIAAATQAAAMAGAHQAEAGALAAQAKAAAIgEQAHgFAGgJIAAgoQgdAAgLAGgAG3BRQgIABgDgCQgEgDAAgDIAAidQAAgEAEgCQADgDAIABIAFAAQAIgBADADQAEACAAAEIAACdQAAADgEADQgDACgIgBgAljBRQgIABgDgCQgEgDAAgDIAAhyQAAgMgFgGQgFgGgMAAQgHAAgGADQgGAEgEAEIgFAIIAAB3QAAADgEADQgDACgIgBIgFAAQgIABgDgCQgEgDAAgDIAAhwQAAgVgCgKIgBgNQAAgEAFgCIAKgCIAJgBQAFAAACAGIAEARQAJgLALgGQALgIAOAAQASAAAMALQANAKAAAZIAAB5QAAADgEADQgDACgIgBgAGshzQgEgCAAgDIAAgWQAAgEAEgCQAEgDAKAAQAJAAAEADQAEACAAAEIAAAWQAAADgEACQgEADgJAAQgKAAgEgDg");
	this.shape.setTransform(174.675,24);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF915C").s().p("AmqCyQgPgLAAgWQAAgOAGgKQAIgLAMgGIAAgBQgMgIAAgQQAAgKAFgIQADgHAIgGQgNgGgGgNQgFgMgBgQQAAgaAPgPQAOgQAcAAQAIAAAJADIAwAAQAHAAAAALIAAAEQAAALgHAAIgJgBIgIAAIAAABQAHAMAAAQQAAAYgOAPQgNAPgYABQgKABgHAEQgFAEgBAJQABAIAFAEQAGADAJACIATADQARADANAKQAOAKAAAVQAAAYgRANQgSANggAAQgeAAgPgKgAmXB9QgEAGAAAJQAAAXAhAAQAhAAAAgWQABgKgGgEQgEgEgJgCQgHgCgJgBIgRgDQgHADgEAHgAmOgZQgIAHABATQgBASAIAFQAHAHALAAQAKAAAJgHQAHgFAAgSQAAgTgHgHQgJgGgKAAQgLAAgHAGgABLBtQgLgMAAgVIAAh5QAAgJAPAAIAEAAQAQAAAAAJIAABzQgBALAFAGQAFAFAKAAQAKAAAIgFQAIgGAEgJIAAh1QAAgJAPAAIAHAAQAIAAADgDQAEgDgBgFQABgHgFgFQgEgFAAgDQAAgCADgDIAGgFIAHgCQAEAAADAEQAEAEABAHQADAGAAAFQgBAPgIAJQgGAFgJACIAABrQAAAVABAJIACANQAAADgEACIgLADIgJAAQgFAAgCgEIgFgSQgHALgMAHQgLAHgNAAQgVAAgLgMgAJZBiQgQgXAAgqQgBgrASgXQAQgXAfAAQAgAAAQAXQARAXAAArQAAAqgRAXQgQAXggAAQgfAAgRgXgAJygNQgGAOAAAfQAAAgAGAOQAIAPAPAAQAPAAAHgPQAIgOgBggQABgfgIgOQgHgPgPAAQgPAAgIAPgAr6BnQgTgRAAghIAAidQAAgFADgBQAEgDAIAAIAFAAQAJAAADADQAEABAAAFIAACeQAAARAKAKQALAJASAAQATAAAKgJQALgKAAgRIAAieQAAgJAOAAIAGAAQAIAAAEADQADABAAAFIAACdQAAAhgTARQgUASgkAAQglAAgTgSgAL6B3QgIAAgDgCQgEgCABgEIAAidQgBgEAEgCQADgCAIAAIAFAAQAJAAACACQAEACAAAEIAACdQAAAEgEACQgCACgJAAgAIUB3QgJAAgDgCQgDgCgBgEIAAhyQAAgMgEgGQgGgGgLAAQgHAAgHAEQgGADgEAFQgDAEgCAEIAAB2QAAAEgEACQgCACgJAAIgFAAQgIAAgDgCQgEgCABgEIAAjoQAAgIAOAAIAFAAQAPAAAAAIIAABYQAGgJAMgHQALgHANAAQASAAANALQAMALAAAYIAAB5QAAAEgDACQgDACgJAAgAEhB3QgJAAgEgCQgDgCAAgEIAAjUQAAgLALAAIAzAAQBBAAAABEQAABEhBAAIgaAAIAABXQAAAEgDACQgEACgJAAgAE1gGIAaAAQAPAAAHgJQAHgJAAgUQAAgUgHgJQgHgJgPAAIgaAAgAAEB3QgHAAgDgCQgEgCAAgEIAAhyQAAgMgFgGQgFgGgMAAQgHAAgFAEQgHADgDAFQgEAEgCAEIAAB2QAAAEgDACQgEACgIAAIgFAAQgIAAgDgCQgDgCgBgEIAAjoQAAgIAPAAIAFAAQAPAAAAAIIAABYQAHgJALgHQALgHANAAQASAAALALQANALAAAYIAAB5QAAAEgEACQgDACgIAAgAi/B3QgPAAAAgIIAAjBIgsAAQgIAAABgLIAAgHQgBgMAIAAIB8AAQAIAAgBAMIAAAHQABALgIAAIgsAAIAADBQAAAIgPAAgAnoB3QgIAAgEgCQgDgCAAgEIAAhyQAAgMgFgGQgFgGgMAAQgHAAgGAEQgGADgEAFQgEAEgCAEIAAB2QAAAEgDACQgDACgJAAIgEAAQgIAAgDgCQgEgCAAgEIAAhxQAAgUgCgKIgBgNQAAgDAEgCIALgCIAJgBQAFAAACAFIAFARQAHgLAMgGQALgIAOAAQARAAANALQANALAAAYIAAB5QAAAEgEACQgDACgIAAgAKbhIQgFgCgCgFIgLgRIgKARQgDAFgEACQgDABgHAAQgJAAAAgEIACgEIABgGIALgYQACgFAGgCQAGgCAIAAQAKAAAFACQAFACACAFIALAYIADAGIABAEQAAAEgJAAQgIAAgCgBgALvhOQgDgCAAgDIAAgWQAAgEADgCQAFgCAJAAQAJAAAEACQAEACAAAEIAAAWQAAADgEACQgEADgJAAQgJAAgFgDgAKBiBQgDgDAAgDQAAgCADgDIAJgIQADgFAAgHQAAgFgCgCQgDgCgEAAIgIABIgEABQgCAAgDgEQgDgFgBgCQAAgDAJgDQAHgDAJAAQAKAAAJAFQAIAGABANQAAAIgFAGQgDAHgFAFIgKAIQgEADgCAAQgDAAgDgDg");
	this.shape_1.setTransform(42.95,20.325);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-35.2,1.5,255.8,37.7);


(lib.Symbol26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol27("synched",0);
	this.instance.setTransform(126,237.3,1,1,0,0,0,126,237.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(19).to({scaleX:1.1,scaleY:1.1,y:237.25},0).wait(20));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37,195.5,317.8,78);


(lib.Symbol24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol2("synched",0);
	this.instance.setTransform(93.95,41.2,1,1,0,0,0,89.9,21.7);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({_off:false},0).to({y:62.8,alpha:1},10,cjs.Ease.get(1)).to({y:61.2},8,cjs.Ease.get(1)).wait(96).to({startPosition:0},0).to({_off:true},1).wait(848));

	// Layer_1
	this.instance_1 = new lib.Symbol25("synched",0);
	this.instance_1.setTransform(92.6,-7.9,1,1,0,0,0,92.3,16.1);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:17.9,alpha:1},10,cjs.Ease.get(1)).to({y:16.1},8,cjs.Ease.get(1)).wait(100).to({startPosition:0},0).to({_off:true},1).wait(848));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-31.2,-26.1,255.89999999999998,156.7);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol23("synched",0);
	this.instance.setTransform(25.6,25.8,1,1,0,0,0,25.6,25.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},15,cjs.Ease.get(1)).wait(203).to({startPosition:0},0).to({_off:true},1).wait(3760));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19.1,-22,87.69999999999999,88.5);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.instance = new lib.Symbol21("synched",0);
	this.instance.setTransform(127.35,100.3,1,1,0,0,0,77.3,11.4);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(26).to({_off:false},0).to({x:98.15},14,cjs.Ease.get(1)).to({x:99.35},6,cjs.Ease.get(1)).wait(172).to({startPosition:0},0).to({_off:true},1).wait(1777));

	// Layer_2
	this.instance_1 = new lib.Symbol20("synched",0);
	this.instance_1.setTransform(71.6,66.05,1,1,0,0,0,77.9,16.1);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(26).to({_off:false},0).to({x:100.8},14,cjs.Ease.get(1)).to({x:99.6},6,cjs.Ease.get(1)).wait(172).to({startPosition:0},0).to({_off:true},1).wait(1777));

	// Layer_1
	this.instance_2 = new lib.Symbol19("synched",0);
	this.instance_2.setTransform(100.05,27.1,0.3,0.3,0,0,0,100.2,19.2);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regX:100,regY:18.9,scaleX:1.15,scaleY:1.15,x:100.1,y:19.15,alpha:1},15,cjs.Ease.get(1)).to({scaleX:1.1499,scaleY:1.1499,y:19.05},11,cjs.Ease.get(1)).to({regY:19.1,scaleX:1,scaleY:1,x:100,y:19.1},14,cjs.Ease.get(1)).wait(178).to({startPosition:0},0).to({_off:true},1).wait(1777));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-46.3,-2.1,252.7,133.2);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_218 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(218).call(this.frame_218).wait(1));

	// logo
	this.instance = new lib.Symbol13("synched",0);
	this.instance.setTransform(253.5,27.5,1,1,0,0,0,15.5,15.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},14,cjs.Ease.get(1)).wait(205));

	// cta
	this.instance_1 = new lib.Symbol26();
	this.instance_1.setTransform(174.8,-12.8,1,1,0,0,0,126.8,31.2);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(124).to({_off:false},0).to({alpha:1},19,cjs.Ease.get(1)).wait(76));

	// Layer_10
	this.instance_2 = new lib.Symbol24("synched",0);
	this.instance_2.setTransform(161.3,69.1,1,1,0,0,0,92.3,16.1);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(100).to({_off:false},0).wait(119));

	// bg copy
	this.instance_3 = new lib.Symbol28("synched",0);
	this.instance_3.setTransform(150,125,1,1,0,0,0,150,125);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(85).to({_off:false},0).to({alpha:1},16,cjs.Ease.get(1)).wait(118));

	// phoi
	this.instance_4 = new lib.Symbol22("synched",0);
	this.instance_4.setTransform(169.15,229.55,0.73,0.73,0,0,0,25.7,26.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(219));

	// Layer_5
	this.instance_5 = new lib.Symbol17("synched",0);
	this.instance_5.setTransform(175,60.1,1,1,0,0,0,100,19.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(219));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEF8F0").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(167.9993,139.9979,1.12,0.4667);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(219));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,280);


// stage content:
(lib._336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(168,140,168,140);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 336,
	height: 280,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/logo.png?1700215981904", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;