(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,400,800);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,200,200);


(lib.x1 = function() {
	this.initialize(img.x1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,700,510);


(lib.x2 = function() {
	this.initialize(img.x2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,637,492);


(lib.Symbol27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.x2();
	this.instance.parent = this;
	this.instance.setTransform(107,-2,0.88,0.88);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(107,-2,560.6,433);


(lib.Symbol26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.x1();
	this.instance.parent = this;
	this.instance.setTransform(59,158,0.82,0.82);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(59,158,574,418.20000000000005);


(lib.Symbol24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#C73A2B","#711D18"],[0,1],-0.1,-45.2,-0.1,44.8).s().p("AgTHCIAAuDIAnAAIAAODg");
	this.shape.setTransform(100.5375,45.4715,1.25,0.8817);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1 copy (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AihDvQgphWgBigQAAg9AKg1QAKg2ASgoQARgpAYgWQASgQAVgHQAUgJAXAAQAZAAAWAKQAWALATAVQAUAWAPArQAQAqAIA2QAIA3ABA6QAAAxgGAvQgGAvgLAnQgMAogPAbQgTAhgbASQgbARgiAAQhPAAgnhUgAhsjSQgXBIAACDQAACYAWBMQAXBLAsAAQAqAAAUhJQAWhJAAiKQAAhYgHg8QgHg8gPgiQgMgagOgOQgOgNgQABQgqAAgXBIgAoSEcQghgogFhNIAdAAQAFA2AVAbQAXAbAmABQAwgCAdguQAcgvABhQQgBhMgagpQgagrgugBQgdAAgWARQgVASgRAjIgbgCIArk1IDcAAIgIBBIjBAAIgYC3QAXgbAYgNQAXgNAfAAQAtABAhAaQAhAZASAuQATAuAAA+QAAA5gTAxQgSAygfAeQgTASgYAKQgYAJgbAAQg8AAgigngAGNEVQgbgpgBhEQABgsANgjQANghAWgTQAXgTAegBQAsABAaAqQAbAoABBEQgBBEgbApQgdAqgsABQgsgBgbgqgAGxBJQgNAiAABAQAAA+AMAhQANAfAZAAQAXAAANggQAMggAAhBQAAg/gLghQgNgggYAAQgYAAgNAhgADGE7IEop3IAjAAIkpJ3gAC4g9QgagpAAhGQAAgsANggQANgjAWgSQAXgUAegBQAsABAaApQAbApABBDQgBAtgMAjQgNAigXAUQgWATgdAAQgugBgbgpgADdkKQgNAgAAA6QAABEAMAhQAMAiAZAAQAYAAANghQAMggAAg/QAAhBgMggQgMghgYAAQgYABgNAgg");
	mask.setTransform(25.925,43.45);

	// Layer_2 copy
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#C73A2B","#711D18"],[0,1],-56.9,-56.9,56.9,56.7).s().p("AwGhoIOcueIRyRwIueOdg");
	this.shape_1.setTransform(27.7,43.5);

	var maskedShapeInstanceList = [this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer_1 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AwSD9IgWgBIgWABIgcADIAAgMQATAAAHgHQAGgFgBgSIAAkkQAAgPgCgHQgDgIgGgCQgGgCgOAAIAAgKIAhgEQAOgCAOgFIAEAUIACAdQAKgZAOgLQAOgMATAAQAZABATARQATATALAfQALAgAAAoQAAApgLAfQgKAggTARQgTASgZAAQgSAAgMgJQgNgIgLgVIAABpQgBASAHAGQAGAGATAAIAAAMIgegDgAwHhUQgNAeAAA7QAAA+ANAgQAMAgAZABQAXAAAMggQAMgfAAg8QAAg9gMggQgMgfgYgBQgXAAgNAggAPoDoQgIgHgBgMQABgMAIgIQAIgIAMAAQALAAAIAJQAIAHAAANQAAALgIAIQgIAHgLABQgMgBgIgIgALMCVIAAlOQABgVgGgHQgGgGgTABIAAgLQAUgCARgDQARgEAQgFIAACZQALgWANgKQANgJARgBQAZABATARQATASAKAgQAKAfABApQgBApgKAfQgLAggUARQgTASgZAAQgVAAgOgMQgOgLgJgZIgVAygAMBhSQgNAhAABBQAAAgADAWQAEAVAGAOQAHANAJAHQAJAGAKABQAXgBAMggQAMgfAAg9QAAh6gugBQgYABgMAhgAGvCDQgUgRgLggQgLgegBgrQABgqALggQALggAUgSQAVgSAbAAQAOAAAMAGQALAFAJANIALgcIAJAAIAABdIgMAAQgFgkgMgTQgNgTgTAAQgZABgOAhQgNAiAAA+QAAA6ANAdQANAeAZAAQAUABAMgUQANgTAEglIASAAQgFAvgSAXQgTAYgeABQgbgBgUgRgADZCDQgUgSgLggQgLgggBgpQABgpALggQAMggAUgSQAUgSAbAAQAdAAAUAWQAVAUAKApQAJgMAEgMQAFgMABgLIgCAAIgCAAIgCAAQgJAAgGgHQgGgGAAgMQAAgNAHgIQAGgHALAAQAMAAAHAJQAGAJAAAQQAAARgFARQgGARgLAQIgCADIgCADIgLAQIADASIAAAQQAAAqgLAfQgMAggUASQgUASgaABQgagBgUgRgADlhWQgMAhAAA+QAAA+ALAfQAMAfAXABQAXAAAMghQAMgfAAg9QAAg/gLghQgMgfgXAAQgXAAgMAggABPB9IAAgRIAAgJQgLAZgPALQgPALgVAAQgSAAgPgIQgOgHgJgPQgFgLgDgPQgDgPAAgUIAAiFQAAgUgFgIQgGgGgQABIgDAAIAAgJIAjgGQARgEASgFIAAC/QgBAjAKAPQAIAPAVAAQAYAAALgSQALgSAAgkIAAh/QAAgUgFgIQgGgGgQABIgEAAIAAgKQATgCARgDQARgEASgFIAADiQAAAPACAHQACAGAGACQAHACAOAAIAAAKQgUADgOADQgPAEgOAFIgDgXgAOzB/QgRgUAAghQAAgVAJgSQAIgQARgMQARgMAUgIQAUgIAZgEIAAgoQAAgbgIgMQgIgMgSAAQgQAAgJAIQgKAJAAAOIAAAHIABAGIAAAEQAAAMgGAFQgFAHgJAAQgIAAgFgFQgEgFAAgJQABgUAKgPQAKgPARgJQARgJAUgBQAUABAQAIQAPAJAJARQAFAJADAOQACAMAAAWIAAB3QAAAcAEALQAEAMAJgBIAFAAIAHgCIgBAPIgOADIgNABQgQAAgJgLQgIgLgCgZQgJAZgPAMQgOAMgVgBQgdgBgRgTgAPdARQgSAUAAAiQAAAYAJAOQAJAOARAAQAUAAAKgVQAKgVAAgrIAAgvQgnAIgSASgAlPCOQgLgHgGgKQgGgLgCgNQgCgNAAgYIACirIgcAAIAAgQQAWAAANgVQAOgVAHgqIAMAAIAABRIAzAAIAAATIgzAAIAACpQgBAjAGAOQAGAOAPAAQAGAAAGgCQAHgDAKgGIAAARQgNAIgKAFQgKADgLAAQgPAAgLgFgAiuCNIgWAAQgMgBgLABIgcADIAAgLQATgCAGgGQAGgFAAgTIAAixQAAgWgFgIQgEgHgQACIgCAAIgEAAIAAgLIAcgEIASgEIAPgFIADAbIACAbQAGgZAOgNQAOgOASAAQARAAALAMQALAMAAAUQAAAOgGAHQgGAIgKAAQgIABgGgGQgFgFAAgJIAAgDIACgGIAAgFIABgEQAAgFgEgEQgDgDgFAAQgRAAgKAZQgKAXAAAsIAAB2QAAATAGAFQAGAGATACIAAALIgcgDgAorCNIgWAAIgWAAIgdADIAAgLQATgCAGgGQAHgFgBgTIAAizQABgVgGgGQgGgHgTABIAAgKQATgCARgDIAigKIAADtQgBATAGAFQAHAGATACIAAALIgdgDgAqnCNQgLgBgLABQgLgBgLABIgcADIAAgLQARgCAGgGQAGgGAAgRIAAiNQAAgjgJgQQgKgQgUAAQgMAAgKAHQgKAFgFALQgFAJgCAKQgCAKAAARIAACLQAAARAFAGQAGAHARABIAAALIgbgDQgLgBgLABQgMgBgKABIgcADIAAgLQATgCAHgGQAGgFgBgTIAAkeQABgVgGgHQgGgGgTABIAAgLQASgCARgDQARgEASgFIAACWQALgTAPgKQAOgKATAAQARAAAOAJQAPAIAIAQQAGAKADAQQADAPAAAVIAACKQgBATAGAFQAGAGAUACIAAALIgcgDgACAgtQAMgOAIgOQAHgPAAgOIgCAAIgBAAIgDAAQgJAAgGgHQgGgHAAgLQAAgNAHgHQAGgIAMAAQALAAAHAJQAHAJAAARQAAAQgGAQQgGARgLARIgCACIgBADIgBACIgCACgAD4irIAshUIAzAAIhLBUgApPirIAshUIAyAAIhLBUg");
	mask_1.setTransform(235.425,46.85);

	// Layer_2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#C73A2B","#711D18","#C73A2B"],[0.094,0.38,0.808],-33.6,-54.8,81.5,42.8).s().p("A7UgsIVrxlMAg/AS+I1sRmg");
	this.shape_2.setTransform(237.85,58);

	var maskedShapeInstanceList = [this.shape_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	// Layer_4
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#F9DFB6","#FFFED7"],[0,1],-209.2,0,209,0).s().p("EggrAIBIAAwAMBBWAAAIAAQAg");
	this.shape_3.setTransform(157.7,44.2);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(1));

	// Layer_1 (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("AiAGIQgGgFAAgHQAAgJAGgFQAFgFAJAAQAHAAAFAFQAFAGABAIQgBAHgFAFQgFAGgHAAQgJAAgFgGgACSFTIgLgUIgHgOIgGgLIgIgPIhYimIAAC6QgBAKACAEQABAGAFABQAGADAKABIAAAJIgSgBIgMgBIgMABIgRABIAAgJQAKgBAFgCQAGgCABgGQACgEAAgKIAAjJQgDgGgHgCQgEgDgLgBIAAgIIANAAIAMABIAMgBIALAAIBmC9IAAibIgBgPQgDgGgFgBQgFgDgLgBIAAgIIATABIANAAIALAAIARgBIAAAIQgKACgGACQgFACgBAFQgCAFAAAKIAADjgADsFAQgTgPgKgeQgKgeAAgpQAAgnAKgeQAKgdATgQQASgQAaAAQANAAAMAFQALAFAKALIALgVIAHAAIAABLIgJAAQgHghgMgPQgNgPgUAAQgcAAgOAeQgOAgAAA7QAAA6AOAeQAOAeAbAAQAJAAAJgDQAKgCAKgIIAAhBQAAgLgEgDQgFgEgOgBIAAgJIAUACIAQAAIAPAAIAUgCIAAAJIgNACQgFACgCAEIAAAMIAAA+QgVAPgPAFQgPAGgQAAQgaAAgTgQgAgpFLIgRgBIgSABIgTACIAAgJQAJgBAFgDQAFgCgBgFIgBgHIgBgGIgKgqIhFAAIgKAkIgDALIgCAIQAAAFAFACQAFADAKABIAAAJIgPgBIgOgBIgMABIgRABIAAgJQAKAAAFgDQAEgCAEgGQADgEADgMIBGjjIA/DoQADAIADAEQACAFAGACQAFADAIAAIAAAJIgTgCgAhcD3IgdhxIghBxIA+AAgAkUFLIgRgBIgQABIgVACIAAgJQAKgBAGgDQAFgBABgGQACgEAAgKIAAjRIgQAAQgKAAgHAEQgFAEgFAKQgFAKgEATIgIAAIAIg6ICFAAIAHA6IgHAAQgFgTgEgKQgEgKgHgEQgGgEgJAAIgRAAIAADRQgBAKACAEQABAGAGABQAEADALABIAAAJIgWgCgAiNArQgKgNgCgZIAKAAQAEAOAHAIQAIAGALAAQALAAAHgGQAIgIAEgOIALAAQgCAZgLANQgKAOgSAAQgSAAgKgOgAjxhIQgOgGgKgMQgJgKgHgRQgGgQgEgWQgEgUAAgWQAAgoAKgeQAJgdATgQQATgRAYAAQAZAAATARQASAQAKAdQAKAeAAAoQAAAYgEAVQgEAUgJATQAJATAJAJQAJAJAIAAIAAAKIgJAAQgIAAgGgBQgGgCgGgFQgGgFgIgKQgLAMgMAFQgNAHgOgBQgPAAgNgGgAj7kfQgOAfgBA5QABA7AOAfQANAgAZABQAZgBANgfQANgeAAg5QAAg8gNggQgNgfgZAAQgZAAgNAfgAg2hKQgQgJgJgQQgFgJgDgLQgBgLAAgRIAAiQQgBgJgBgGQgCgEgFgCQgFgDgKgBIAAgJIAWACIAPAAIARAAIAWgCIAAAJQgKABgGADQgFACgCAEQgCAGABAJIAACTQAAAPABAKQACAJAEAGQAFALAKAEQAKAHAPgBQALAAAJgEQAJgEAHgHQAHgHADgMQAEgNAAgQIAAiRQAAgJgCgGQgBgEgGgCQgGgDgKgBIAAgJIASABIANABIANgBIARgBIAAAJQgMABgFADQgEACgDAEQgBAGAAAJIAACQQAAAQgCAMQgDAMgFAKQgJAPgPAIQgOAIgTAAQgUAAgPgIgAD8hIIgRgBIgSABIgUADIAAgJQAKgBAEgDQAFgDAAgEIgBgGIgCgIIgKgpIhEAAIgLAkIgDAMIgBAHQAAAEAFADQAEADALABIAAAJIgPgCIgOAAIgNAAIgQACIAAgJQAKgBAEgCQAFgCADgGQAEgFACgLIBHjjIA/DnIAFANQACAFAGACQAFACAKABIAAAJIgUgDgADIicIgchwIgiBwIA+AAgAC4lZIg9g0IAkAAIAnA0g");
	mask_2.setTransform(-103.3,44);

	// Layer_2
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#EFCD95","#FEFDCE"],[0,0.722],-47.8,0,47.8,0).s().p("AndI4IAAxvIO7AAIAARvg");
	this.shape_4.setTransform(-102.778,43.675,0.8557,1);

	var maskedShapeInstanceList = [this.shape_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(1));

	// Layer_5 (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("AovIBIAAwAIReAAIAAQAg");
	mask_3.setTransform(-102,44.2);

	// Layer_6
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#C73A2B","#711D18"],[0,1],-76.5,-74.3,54.1,66.6).s().p("A06jSIWlvcITQQKI1bVTg");
	this.shape_5.setTransform(-104.9132,50.2998,0.8632,0.8799);

	var maskedShapeInstanceList = [this.shape_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-157.9,-7,524.8,102.5);


(lib.Symbol14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AAIBeQgNgLgIgXQgIgXAAgeQAAgdAIgXQAIgWANgNQAOgMATgBQALAAAJAEQAJAFAHAIIAIgQIAEAAIAAA5IgGAAQgFgZgJgLQgKgMgPAAQgVAAgLAXQgLAXAAAtQAAApALAXQALAWAUAAQASAAAKgOQAKgPABgbIAJAAQgBAhgOASQgNASgXABQgTgBgNgNgAi2BeQgOgLgIgXQgIgXAAgeQAAgdAIgXQAIgWAOgNQAOgMATgBQALAAAJAEQAJAFAHAIIAIgQIAEAAIAAA5IgGAAQgFgZgJgLQgKgMgPAAQgVAAgLAXQgLAXAAAtQAAApALAXQALAWAUAAQASAAAKgOQAKgPABgbIAJAAQgBAhgOASQgNASgXABQgTgBgNgNgAuWBeQgOgLgIgXQgHgXAAgeQAAgdAIgXQAHgWAOgNQAPgMATgBQALAAAIAEQAJAFAHAIIAIgQIAFAAIAAA5IgHAAQgEgZgKgLQgKgMgPAAQgVAAgKAXQgLAXAAAtQAAApALAXQALAWAUAAQARAAAKgOQAKgPACgbIAJAAQgCAhgNASQgNASgYABQgSgBgOgNgAM0BiQgKgJgFgQQgGgQAAgVQAAgVAGgPQAFgQAJgJQAKgJAMAAQAJgBAGAGQAGAFAFAKIAAgkIgZAAIAAgJIAZAAIAAgDQABgLgDgEQgDgDgKAAIAAgFIATgDIARgEIAAAhIARAAIAAAJIgRAAIAAB8IABANQABAEADABQAEACAIAAIAAAFIgTADQgIACgFADIgCgMIgCgLQgEAMgHAFQgHAGgJAAQgNAAgJgJgAM6gKQgFAOAAAgQAAAeAGAQQAGARALAAQALAAAGgPQAHgPAAgbQAAgigGgRQgGgRgNAAQgLAAgGAQgAIgBiQgKgJgFgQQgGgQAAgVQAAgVAGgPQAFgQAJgJQAKgJAMAAQAJgBAGAGQAGAFAFAKIAAgkIgZAAIAAgJIAZAAIAAgDQABgLgDgEQgDgDgKAAIAAgFIATgDIARgEIAAAhIARAAIAAAJIgRAAIAAB8IABANQABAEADABQAEACAIAAIAAAFIgTADQgIACgFADIgCgMIgCgLQgEAMgHAFQgHAGgJAAQgNAAgJgJgAImgKQgFAOAAAgQAAAeAGAQQAGARALAAQALAAAGgPQAHgPAAgbQAAgigGgRQgGgRgNAAQgLAAgGAQgAF3BrIAAgxIAGAAQADAUAHAKQAHAJAMABQAKAAAHgIQAGgGAAgMQAAgIgEgHQgFgGgMgGIgSgLQgGgEgDgEQgEgEgCgGQgCgHAAgHQAAgQAKgLQAJgKAQAAQAHAAAFACQAGACAFAFIADgLIAFAAIAAArIgGAAQgBgQgGgIQgGgJgKAAQgJAAgGAHQgFAGgBAKQAAAIAFAFQAEAGAMAGIAPAJIAJAHQAGAFADAHQADAHAAAIQAAAUgKAKQgLAMgRAAQgIAAgGgDQgHgDgGgGIgFANgAEXBrIAAgxIAGAAQADAUAHAKQAHAJAMABQAKAAAHgIQAGgGAAgMQAAgIgEgHQgFgGgMgGIgSgLQgGgEgDgEQgEgEgCgGQgCgHAAgHQAAgQAKgLQAJgKAQAAQAHAAAFACQAGACAFAFIADgLIAFAAIAAArIgGAAQgBgQgGgIQgGgJgKAAQgJAAgGAHQgFAGgBAKQAAAIAFAFQAEAGAMAGIAPAJIAJAHQAGAFADAHQADAHAAAIQAAAUgKAKQgLAMgRAAQgIAAgGgDQgHgDgGgGIgFANgAl8BkQgLgHgHgMQgGgLAAgQQAAgLADgIQADgKAIgIQAHgKAMgJIgLgVIgFgMQgBgFAAgGQAAgSAKgKQAJgLAPgBQAOABAIAJQAIAKAAAQQAAAIgCAHQgDAIgFAJQgFAIgKAKIAmBAQAFgHACgJQACgIAAgHQAAgGgCgCQgDgCgHgBIAAgIIAJACIAIAAIAIAAIAJgCIAAAIQgIABgDADQgCACgBAIQgBAMgDAJQgCAIgFAJIAGALIAGAJQACADADABIAJABIAAAGIgIgCIgHAAIgGAAIgIACIgJgQQgKAKgJAEQgJAEgKAAQgOgBgLgGgAl7AhQgFAKAAANQAAASAJALQAIALAPABQAHAAAHgFQAHgDAJgIIgohFQgMALgFAKgAlvhHQgFAHgBALQAAAHAEAJQADAJAIANQALgMAEgJQAFgIAAgKQAAgLgFgGQgFgGgHgBQgHABgFAGgAomBrIAAgxIAGAAQACAUAHAKQAIAJALABQALAAAGgIQAGgGABgMQAAgIgFgHQgFgGgMgGIgRgLQgGgEgEgEQgEgEgCgGQgCgHAAgHQABgQAJgLQAKgKAQAAQAHAAAFACQAFACAFAFIAEgLIAFAAIAAArIgGAAQgCgQgFgIQgGgJgKAAQgKAAgFAHQgGAGAAAKQAAAIAEAFQAEAGANAGIAOAJIAJAHQAGAFAEAHQADAHAAAIQAAAUgLAKQgKAMgRAAQgIAAgHgDQgHgDgGgGIgFANgAqGBrIAAgxIAGAAQACAUAHAKQAIAJALABQALAAAGgIQAGgGABgMQAAgIgFgHQgFgGgMgGIgRgLQgGgEgEgEQgEgEgCgGQgCgHAAgHQABgQAJgLQAKgKAQAAQAHAAAFACQAFACAFAFIAEgLIAFAAIAAArIgGAAQgCgQgFgIQgGgJgKAAQgKAAgFAHQgGAGAAAKQAAAIAEAFQAEAGANAGIAOAJIAJAHQAGAFAEAHQADAHAAAIQAAAUgLAKQgKAMgRAAQgIAAgHgDQgHgDgGgGIgFANgAOgBXQgNgTAAghQAAgWAGgOQAFgRALgIQAKgKANABQAUAAALASQALAQABAgIhDAAIABAWIACAPIADAMQAEAIAFAEQAGAFAIAAQAMAAAHgKQAIgKACgSIAJAAQgCAXgLAMQgLANgRAAQgWgBgMgTgAPXAWQgBgYgGgNQgFgNgLAAQgKAAgGANQgGANgCAYIAvAAIAAAAgAKIBgQgJgKAAgRQAAgLAEgJQAFgIAIgGQAJgHAKgEQAKgEANgCIAAgTQAAgOgEgGQgEgGgJAAQgIAAgFAEQgFAEAAAIIAAADIAAADIAAACQAAAFgCADQgDADgFABQgEgBgCgCQgCgDAAgDQAAgKAFgIQAFgIAJgFQAIgEALAAQAKAAAIAEQAIAFAEAJQADAEABAHIABAQIAAA9QAAAPACAFQACAGAFAAIADAAIADgBIAAAHIgIACIgGABQgIAAgFgGQgEgGgBgMQgFAMgHAGQgHAGgLAAQgOAAgJgKgAKdAoQgJAKAAARQAAAMAFAIQAEAGAJAAQAKAAAFgKQAFgLAAgVIAAgZQgUAFgJAJgAC0BgQgJgKAAgRQAAgLAEgJQAFgIAIgGQAJgHAKgEQAKgEANgCIAAgTQAAgOgEgGQgEgGgJAAQgIAAgFAEQgFAEAAAIIAAADIAAADIAAACQAAAFgCADQgDADgFABQgEgBgCgCQgCgDAAgDQAAgKAFgIQAFgIAJgFQAIgEALAAQAKAAAIAEQAIAFAEAJQADAEABAHIABAQIAAA9QAAAPACAFQACAGAFAAIADAAIADgBIAAAHIgIACIgGABQgIAAgFgGQgEgGgBgMQgFAMgHAGQgHAGgLAAQgOAAgJgKgADJAoQgJAKAAARQAAAMAFAIQAEAGAJAAQAKAAAFgKQAFgLAAgVIAAgZQgUAFgJAJgArqBgQgIgKAAgRQAAgLAEgJQAEgIAJgGQAJgHAKgEQAKgEANgCIAAgTQAAgOgFgGQgEgGgJAAQgIAAgEAEQgFAEAAAIIAAADIAAADIAAACQAAAFgDADQgDADgEABQgEgBgDgCQgCgDAAgDQAAgKAGgIQAFgIAIgFQAJgEAKAAQAKAAAIAEQAIAFAFAJQADAEABAHIABAQIAAA9QAAAPACAFQACAGAFAAIACAAIADgBIAAAHIgHACIgGABQgJAAgEgGQgEgGgBgMQgFAMgIAGQgHAGgLAAQgOAAgJgKgArVAoQgJAKAAARQAAAMAFAIQAFAGAIAAQALAAAFgKQAFgLAAgVIAAgZQgUAFgKAJgARdBnIgLgBIgLABIgOACIAAgGQAIgBAEgDQADgDgBgJIAAhJQABgQgFgIQgFgIgKAAQgHAAgFADQgFADgDAGIgDAJIgBAMIAABIQAAAJADADQADADAIABIAAAGIgOgCIgLgBIgLABIgOACIAAgGQAKgBADgDQADgDAAgJIAAhZIgBgMQgBgEgDgBIgKgBIAAgFIARgEIANgEIACAKIABAOQAGgLAIgFQAIgGAKAAQAJAAAHAEQAHAFAFAIQADAFABAHQACAHAAAKIAABIQgBAJADADQAEADAJABIAAAGIgOgCgACRBnIgLgBIgLABIgPACIAAgGQAKgBADgDQADgDAAgJIAAiRQAAgLgDgEQgDgDgKAAIAAgFIATgDIARgEIAACvQAAAJADADQADADAKABIAAAGIgPgCgAsNBnIgLgBIgLABIgOACIAAgGQAJgBADgDQAEgDgBgJIAAiRQABgLgDgEQgDgDgKAAIAAgFIASgDIASgEIAACvQgBAJADADQADADAKABIAAAGIgPgCgAxqBnIAAgGIALgDQAEgBACgEIABgMIAAiLIgBgMQgCgEgEgCQgDgBgIAAIAAgIIBlAAIAEAsIgHAAQgCgOgEgIQgDgIgFgDQgEgDgIABIggAAIAABQIAfAAQAHAAADgFQADgFAAgOIAHAAIAAA3IgHAAQAAgNgDgGQgDgFgIABIgeAAIAABGQgBAJADAEQAEADAJAAIAQAAQAIABAGgEQAFgCAEgJQAEgIADgPIAGAAIgFAugAhYAgIAAgNIA7AAIAAANgAv3AgIAAgNIA8AAIAAANgAPZg3IgZgZIgZAZIgLAAIAegrIAMAAIAWAeIAUgmIAaAAIgmAqIgGAAIAGAJgAKzg+IgKgJIgHgFIgFgBQgEAAgDADQgEADgCAIIgHgCQAEgQAFgGQAFgHAIAAIAHACIAIAFIAGAGIAFADIAFABQAFABADgEQADgDACgJIAGACQgCAOgFAIQgGAHgJABQgEAAgEgCg");
	mask.setTransform(86.675,47.2);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#EEBA64","#FEFDCE"],[0,0.667],-118.6,0.2,118.5,0.2).s().p("AyhGXIAAstMAlDAAAIAAMtg");
	this.shape.setTransform(86.075,37.075);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26.4,36.5,226.20000000000002,38.7);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(0,15,0.13,0.13);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1208));

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AkjD1IAAnpIJHAAIAAHpg");
	this.shape.setTransform(13.1398,28.547,1.0522,1.049);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1208));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-17.6,2.9,61.5,51.300000000000004);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AgbBQIgGAAIgFAAIgHABIAAgDQAEAAACgCQACgBgBgFIAAhKIAAgGQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBAAAAAAIgFgBIAAgDIAIgBIAHgBIABAFIAAAHQAEgGADgDQADgDAFAAQAGAAAFAEQAEAFADAIQACAHAAALQAAALgCAHQgDAJgEAEQgFAFgFAAQgGAAgCgCQgEgDgDgFIAAAbQABAFABABQACACAEAAIAAADIgHgBgAgYgGQgEAHAAAPQAAAQAEAJQADAIAGAAQAGAAADgIQACgIABgPQgBgRgCgHQgDgIgGAAQgGAAgDAIgAFbBQIgBAAIAAgHIACAAQAEAAAEgDQADgDACgHIAEgLIgRg4IgDgFQgCgCgEAAIAAgDIAHAAIAFAAIAGAAIAHAAIAAADIgGABIgBACIAAACIABACIAMAnIAMgmIABgDIAAgCQAAAAgBgBQAAAAAAAAQAAAAAAgBQgBAAAAAAIgFgBIAAgDIAFAAIAEAAIAFAAIAFAAIAAADQgEAAgCACQgCACgBADIgVBHQgDAIgEAEQgEAEgGAAgADrBLQgGgFAAgKQAAgFACgEQADgEAGgCIgFgEIgBgFQAAgEADgDQADgDAHgCQgHgCgDgFQgFgGAAgIQABgJAFgGQAGgGAJAAIAGABIAGADIAPAAIAAAFIgMgBIADAHIABAFQAAAJgEAGQgFAGgJACIgIADIgEADIgBACQAAABABABQAAAAAAABQAAAAABAAQAAABAAAAIAIACIAGAAIAGABIAEABQAFACADAFQADAEgBAGQABAKgIAGQgGAGgMAAQgKAAgHgFgADuA0QgFADAAAGQABAHAFAEQAFAEAIAAQAJAAAEgEQAFgEAAgGQAAgHgFgDQgFgDgJAAQgIAAgFADgAD1gJQgDAEAAAHQAAAJADAFQACAFAFAAQAFAAACgFQADgFABgJQAAgHgDgFQgCgFgGAAQgEAAgDAGgAFBAyQgCgDAAgGQgDAGgEADQgDADgGAAQgGAAgFgFQgEgFgBgJQAAgGADgEQACgEAEgDQAEgDAGgDQAFgCAGgBIAAgJQAAgHgCgDQgCgDgEAAQgEAAgDACQgCACAAAEIAAACIAAABIAAABIgBAEQgBAAAAAAQgBABAAAAQgBAAAAAAQAAAAgBAAIgDgBIgBgDQAAgEACgEIAHgHQAFgCAFAAQAEAAAFACQADACACAFIADAGIAAAHIAAAfIABAKQAAABABAAQAAABAAAAQABABAAAAQABAAAAAAIABAAIACAAIAAADIgEABIgCABQgFAAgCgDgAEvAUQgFAFAAAIQAAAHADADQACAEAEAAQAFAAACgGQADgFAAgLIAAgMQgKACgEAFgAByAyQgDgDAAgGQgCAGgEADQgEADgFAAQgHAAgEgFQgFgFAAgJQAAgGADgEQACgEAEgDIAJgGIAMgDIAAgJQAAgHgDgDQgCgDgEAAQgDAAgDACQgCACAAAEIAAACIAAABIAAABQAAABgBABQAAAAAAAAQAAAAAAABQgBAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAgBAAIgCgBIgBgDQAAgEACgEQADgEAEgDQAEgCAFAAQAFAAAEACQAEACACAFIADAGIAAAHIAAAfIABAKQAAABAAAAQABABAAAAQABABAAAAQABAAAAAAIABAAIACAAIAAADIgEABIgDABQgEAAgCgDgABfAUQgFAFAAAIQAAAHADADQACAEAEAAQAGAAACgGQADgFAAgLIAAgMQgKACgFAFgAi8AyQgBgDgBgGQgDAGgDADQgEADgFAAQgHAAgFgFQgEgFAAgJQAAgGACgEQACgEAFgDIAJgGIALgDIAAgJQAAgHgBgDQgDgDgEAAQgEAAgDACQgCACAAAEIAAACIAAABIAAABIgBAEQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgDgBIgBgDQAAgEACgEQADgEAEgDQAEgCAGAAQAFAAADACQAEACADAFIACAGIAAAHIAAAfIABAKQABABAAAAQAAABABAAQAAABABAAQAAAAABAAIABAAIACAAIAAADIgEABIgEABQgDAAgDgDgAjOAUQgEAFAAAIQgBAHADADQACAEAEAAQAGAAACgGQACgFAAgLIAAgMQgKACgEAFgADWAzIgFAAIgGAAIgHABIAAgDQAFAAABgCQABgBAAgFIAAglQAAgHgCgEQgCgEgFAAQgDAAgDABQgCACgBACIgCAFIgBAGIAAAkQAAAFACABQABACAEAAIAAADIgGgBIgHAAIgFAAIgGABIAAgDQAEAAABgCQACgBAAgFIAAgsIgBgGQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAgBAAIgEAAIAAgDIAIgCIAHgCIAAAFIABAIQADgGAEgEQAEgCAFAAQAEAAAEACQAEACACAFIACAGIAAAIIAAAkQABAFABABQACACAEAAIAAADIgHgBgABBAzIgGAAIgFAAIgHABIAAgDQAEAAABgCQACgBAAgFIAAglQAAgHgDgEQgCgEgFAAQgDAAgCABIgFAEIgBAFIAAAGIAAAkQAAAFABABQABACAFAAIAAADIgHgBIgGAAIgFAAIgHABIAAgDQAEAAACgCQABgBABgFIAAhJIgBgHQgCgCgFAAIAAgCIAJgCIAJgCIAAAnQACgFAEgDQADgCAGAAQADAAAFACQADACACAFIACAGIABAIIAAAkQAAAFACABQABACAEAAIAAADIgGgBgAhZAzIgFAAIgGAAIgHABIAAgDQAEAAACgCQACgBgBgFIAAgmQAAgHgCgEQgBgDgGAAQgFAAgDAEQgDAEAAAHIAAAlQABAFABABQABACAFAAIAAADIgHgBIgGAAIgFAAIgHABIAAgDQAEAAACgCQABgBABgFIAAgmIgBgGIgBgEIgDgDIgEgBQgDAAgDABQgCACgBACIgCAFIAAAHIAAAjQAAAFABABQABACAEAAIAAADIgGgBIgGAAIgGAAIgGABIAAgDQAFAAABgCQACgBAAgFIAAgsIgBgGIgBgCIgCgBIgEAAIAAgDIAJgCIAGgCIABAGIABAGQADgGADgDQAEgCAFAAQAFAAADACQAEAEACAGQADgHAEgDQADgCAGAAQAIAAAEAGQADAFAAAKIAAAmQAAAFACABQACACAEAAIAAADIgHgBgAjtAzIgFAAIgFAAIgIABIAAgDQAEAAACgCQACgBAAgFIAAglQAAgHgCgEQgDgEgFAAQgDAAgDABIgDAEIgDAFIAAAGIAAAkQAAAFACABQABACAEAAIAAADIgHgBIgFAAIgGAAIgHABIAAgDQAGAAABgCQACgBgBgFIAAhJQABgFgCgCQgCgCgEAAIAAgCIAIgCIAJgCIAAAnQADgFAEgDQADgCAFAAQAEAAAEACQAEACACAFIACAGIABAIIAAAkQgBAFACABQABACAGAAIAAADIgIgBgAksAzIgHAAIgHAAIgIABIAAgEIACAAIAEgBIACgCIgBgCIgBgDIgUgnIgFAHIAAAfIABAGIADACIAFABIAAAEIgHgBIgGAAIgHAAIgIABIAAgEIAGgBIACgCIABgGIAAhHIgBgGQAAgBAAAAQAAAAAAgBQgBAAAAAAQgBgBAAAAIgGgBIAAgEIAIABIAHAAIAGAAIAHgBIAAAEIgFABQgBAAAAABQgBAAAAAAQAAABgBAAQAAAAAAABIgBAGIAAAgIAagjIABgCIABgCQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAgBAAIgFgBIAAgEIAGABIAGAAIAFAAIAGgBIAAAEIgFABIgFACIgDAFIgTAbIAYAuIAEAGIAEACIAFABIAAAEIgIgBgABkgcIALgWIAMAAIgSAWgAjJgcIAKgWIANAAIgTAWg");
	mask.setTransform(39.5,8.0854);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#EEBA64","#FEFDCE"],[0,0.667],-41.4,0,41.3,0).s().p("AmdCVIAAkpIM7AAIAAEpg");
	this.shape.setTransform(40.625,8.675);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FAE2B9").ss(0.8,1,1).p("AndhsIO7AAIAADZIu7AAg");
	this.shape_1.setTransform(40.0038,8.5375,0.9595,1.0313);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(59,4,0,0.529)").s().p("AndBsIAAjXIO7AAIAADXg");
	this.shape_2.setTransform(40.0038,8.5375,0.9595,1.0313);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.8,-3.6,93.7,24.400000000000002);


(lib.Symbol10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AEtBtQgLgIgFgQQgGgRAAgVQAAgWAGgQQAGgOAKgKQAKgJAOAAQAPAAAKALQALALAFATQAEgFADgHQACgFAAgGIgBAAIgBAAIAAAAQgFAAgDgDQgDgEAAgFQAAgHADgDQADgEAGgBQAGAAADAFQAEAFAAAIQAAAJgDAHQgDAIgGAJIgBABIAAACIgGAHIABAKIAAAIQAAAWgFAQQgGARgKAIQgLAKgNAAQgNAAgKgKgAEzAAQgGAQAAAfQAAAhAFAQQAGAQAMAAQAMgBAGgQQAGgQAAggQAAgggGgPQgGgRgMAAQgLAAgGARgAC5B3IAAgwIAGAAQADATAHAJQAHAKAMAAQAKABAHgIQAGgGAAgMQAAgJgEgFQgFgHgMgHIgSgKQgGgEgDgEQgEgEgCgHQgCgGAAgHQAAgQAKgKQAJgLAQAAQAHAAAFACQAGACAFAFIADgMIAFAAIAAAsIgGAAQgBgRgGgIQgGgIgKAAQgJAAgGAGQgFAHgBAJQAAAJAFAFQAEAFAMAIIAPAIIAJAHQAGAFADAHQADAHAAAJQAAASgKAMQgLALgRAAQgIAAgGgCQgHgDgGgHIgFANgAAxBuQgKgJgGgQQgGgPAAgWQAAgWAGgRQAGgOAKgKQAKgJAOAAQAIAAAFADQAGADAFAGIAFgOIAFAAIAAAuIgGAAQgDgSgGgJQgGgJgKAAQgNAAgHAQQgHARAAAhQAAAdAHAPQAHAPAMAAQALAAAGgKQAGgKACgSIAJAAQgCAXgJANQgKAMgPAAQgOAAgKgJgAoOBtQgKgIgGgQQgFgRAAgVQAAgWAFgQQAGgOALgKQAKgJAOAAQAOAAALALQAKALAFATQAFgFACgHQADgFAAgGIgBAAIgBAAIgBAAQgFAAgDgDQgDgEAAgFQAAgHAEgEQADgEAGAAQAGAAADAFQADAEAAAGIAPgCIASgGIAAB5QgBAJADADQAEADAJAAIAAAGIgPgBIgKAAIgMAAIgOABIAAgGQAJAAADgDQAEgDgBgJIAAhcQABgKgDgDQgDgCgHgBQAAAIgCAGQgDAIgGAJIgBABIgBACIgFAHIABAKIAAAIQAAAWgGAQQgGARgKAIQgKAKgNAAQgOAAgKgKgAoIAAQgGAQAAAfQAAAhAGAQQAGAQAMAAQALgBAGgQQAGgQAAggQAAgggFgPQgGgRgMAAQgMAAgGARgAL7BrIAAgKIAAgDQgFANgIAFQgIAGgLAAQgJAAgIgEQgHgEgEgIQgDgFgCgIQgBgHAAgLIAAhDQAAgKgDgEIgEgCIgCALQgDAIgGAIIAAACIgBABIgBAAIgBACIgLAAQAHgHAEgIQADgGAAgIIgBAAIAAABIgCAAQgEgBgDgDQgDgDAAgGQAAgGADgEQADgFAGAAQAGABADAEQADAFABAHIAJgBIARgFIAABgQAAASAFAIQAFAIAKAAQAMAAAGgJQAGgJAAgTIAAhAQAAgKgDgEQgDgEgIABIgCAAIAAgFIASgCIASgFIAAByIABALQABAEADABIALABIAAAFIgSADQgHABgHADIgCgLgAKBBrIgBgJIAAgEQgFANgHAFQgIAGgLAAQgKAAgHgEQgHgEgFgIQgDgFgBgIQgCgHAAgLIAAhDQABgKgDgEQgDgEgIABIgCAAIAAgFIASgCIASgFIAABgQAAASAEAIQAFAIALAAQAMAAAFgJQAGgJAAgTIAAhAQAAgKgDgEQgDgEgIABIgCAAIAAgFIATgCIARgFIAAByIABALQABAEADABIALABIAAAFIgRADQgIABgHADIgBgLgAhFBsQgJgKAAgRQAAgLAEgIQAFgJAIgHQAJgGAKgEQAKgEANgBIAAgWQAAgMgEgGQgEgHgJAAQgIABgFAEQgFAFAAAGIAAADIAAADIAAACQAAAGgCADQgDADgFAAQgEAAgCgCQgCgDAAgFQAAgJAFgHQAFgIAJgEQAIgFALAAQAKAAAIAFQAIAEAEAIQADAFABAGIAAASIAAA8QAAAOACAHQACAFAFAAIADAAIADgBIAAAIIgIABIgGAAQgHABgFgGQgEgGgBgMQgFAMgHAHQgHAFgLAAQgOAAgJgKgAgwA0QgJAKAAARQAAANAFAGQAEAIAJAAQAKAAAFgLQAFgLAAgWIAAgYQgUAFgJAJgAIaBzIgLAAIgLAAIgOABIAAgGQAIAAADgDQADgEAAgHIAAhJQAAgSgEgHQgFgIgKAAQgHAAgFADQgFAEgDADIgDAKIgBAOIAABIQAAAHADAEQADADAIAAIAAAGIgOgBIgLAAIgLAAIgOABIAAgGQAKAAADgDQADgDAAgJIAAiSQAAgKgDgDQgDgDgJAAIAAgGIASgCIARgFIAABNQAGgLAHgEQAHgFAKAAQAJAAAHAFQAHAEAFAHQADAGABAHQACAHAAALIAABHQgBAJADADQADADAKAAIAAAGIgOgBgAhoBzIgLAAIgMAAIgOABIAAgGQAJAAADgDQADgEAAgHIAAhJQAAgSgFgHQgFgIgKAAQgGAAgFADQgFAEgDADIgDAKIgBAOIAABIQgBAHADAEQADADAJAAIAAAGIgOgBIgLAAIgLAAIgOABIAAgGQAJAAAEgDQADgDgBgJIAAiSQABgKgDgDQgDgDgKAAIAAgGIASgCIASgFIAABNQAFgLAIgEQAHgFAJAAQAJAAAHAFQAIAEAEAHQADAGABAHQACAHAAALIAABHQAAAJADADQADADAKAAIAAAGIgOgBgAjcB0IgHgBIgHABIgJAAIgihJIgOATIAAAhQAAAJADADQADADAKAAIAAAGIgPgBIgLAAIgLAAIgPABIAAgGQAKAAADgDQADgDAAgJIAAiSQAAgKgDgDQgDgDgJAAIAAgGIASgCIARgFIAACCIAlgyIADgEIABgFQAAgDgDgBQgDgCgHgBIAAgFIALABIAKAAIALAAIANgBIAAAFIgKACIgHAEIgHAIIgWAdIAhBEIAGAKQACADAEABQADABAGAAIAAAGIgKAAgAo+BzIgLAAIgLAAIgOABIAAgGQAIAAADgDQADgEAAgHIAAhJQAAgSgEgHQgFgIgKAAQgHAAgFADQgFAEgDADIgDAKIgBAOIAABIQAAAHADAEQADADAIAAIAAAGIgOgBIgLAAIgLAAIgOABIAAgGQAKAAADgDQADgDAAgJIAAiSQAAgKgDgDQgDgDgJAAIAAgGIASgCIARgFIAABNQAGgLAHgEQAHgFAKAAQAJAAAHAFQAHAEAFAHQADAGABAHQACAHAAALIAABHQgBAJADADQADADAKAAIAAAGIgOgBgArXBzIgMgBIgNABIgQABIAAgHIAMgCQAEgCABgEQABgEAAgHIAAieIgMAAQgIAAgFADQgFADgDAHQgDAIgEAOIgGAAIAGgsIBmAAIAGAsIgGAAQgDgOgEgIQgDgHgFgDQgFgDgHAAIgNAAIAACeIABALQABAEAEACIAMACIAAAHIgRgBgAE/gqIAAgRIAKgCIAFgBIACgBQAEgDAAgGQAAgFgEgDQgDgCgGAAIgFAAIgIADIgDgJIALgEIALgBQAKAAAHAGQAGAGAAAKQAAAJgFAFQgFAFgJgBIgEAAIgEAAIAAALgAJvgtQgEgDgGgGIgGgFIgFgCQgFAAgDAEQgDADgDAIIgGgCQADgQAFgHQAFgGAIAAQAEAAAEACQADABAEAEIAGAGIAFADIAFABQAFABADgEQADgEACgIIAHACQgCAOgGAIQgGAHgJABQgDAAgFgCgAnygsIgngqIAaAAIAXAqgAg3g3QgIgLgBgTIAIAAQADALAGAHQAGAFAIAAQAJAAAGgFQAFgHADgLIAJAAQgCATgIALQgIALgOAAQgNAAgJgLgAmsgzQgEgEAAgGQAAgGAEgEQAEgEAGAAQAGAAAEAEQAEAEAAAGQAAAGgEAEQgEAEgGAAQgGAAgEgEgAgmhLIAWgrIAZAAIglArg");
	mask.setTransform(85.975,17.7);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#EEBA64","#FEFDCE"],[0,0.667],-124.8,0.2,124.8,0.2).s().p("AzfFTIAAqlMAm/AAAIAAKlg");
	this.shape.setTransform(86.2533,37.0907,0.9624,1.1981);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,168,29.6);


(lib.Symbol4copy4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AgaBYQgOgMgIgXQgHgWAAgfQgBgdAJgXQAHgWAOgNQAOgMATgBQALAAAIAFQAJAEAHAJIAIgRIAEAAIAAA5IgGAAQgEgZgKgLQgKgMgPAAQgUAAgKAXQgMAYAAAsQAAApAMAXQAKAWATABQASgBAKgOQAKgPABgaIAJAAQgBAggNASQgNASgYABQgRgBgOgMg");
	mask.setTransform(-2.2,-408.975);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#EEBA64","#FEFDCE"],[0,0.667],-124.4,0.2,124.4,0.2).s().p("AzbFTIAAqlMAm3AAAIAAKlg");
	this.shape.setTransform(61.725,-424.35);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60,-455,244.6,56.10000000000002);


(lib.Symbol4copy3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Ag1BhIAAgHIAMgDQAEgBABgEIABgMIAAiLIgBgMQgBgEgEgBQgEgCgIAAIAAgIIBkAAIAEAsIgGAAQgDgOgDgHQgDgIgFgDQgFgDgHAAIggAAIAABQIAfAAQAHABACgGQADgFABgOIAHAAIAAA4IgHAAQAAgOgEgFQgDgGgIABIgdAAIAABGQAAAKADADQADAEAIAAIAQAAQAJAAAFgDQAGgDADgJQAEgIADgPIAHAAIgGAvg");
	mask.setTransform(-1.875,-408.975);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#EEBA64","#FEFDCE"],[0,0.667],-124.4,0.2,124.4,0.2).s().p("AzbFTIAAqlMAm3AAAIAAKlg");
	this.shape.setTransform(61.725,-424.35);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60,-455,244.6,55.69999999999999);


(lib.Symbol4copy2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AnGBeQgOgMgJgWQgHgXAAgeQAAgdAIgXQAHgWAPgNQAOgNATAAQALAAAIAFQAKAEAGAIIAIgQIAFAAIAAA5IgGAAQgFgZgKgLQgJgNgPAAQgWAAgKAYQgLAXAAAtQAAApALAXQALAWAUAAQARAAALgOQAJgPACgbIAJAAQgBAhgOASQgNASgYABQgSgBgNgNgAFlBiQgKgJgGgQQgFgQAAgVQAAgVAFgPQAGgQAJgJQAKgJAMAAQAIgBAHAFQAGAFAFALIAAgkIgaAAIAAgJIAaAAIAAgDQABgLgDgEQgDgCgKAAIAAgGIASgDIARgEIAAAhIARAAIAAAJIgRAAIAAB8IABANQACAEADABQAEACAHAAIAAAFIgTADQgHACgFADIgDgMIgBgLQgFAMgGAFQgHAGgKAAQgMAAgJgJgAFrgKQgFAOAAAgQgBAfAHAPQAFARAMAAQALAAAGgPQAGgPAAgbQABgigHgRQgFgRgNAAQgLAAgGAQgABQBiQgJgJgGgQQgFgQAAgVQAAgVAFgPQAGgQAJgJQAJgJANAAQAJgBAGAFQAGAFAFALIAAgkIgZAAIAAgJIAZAAIAAgDQAAgLgDgEQgCgCgKAAIAAgGIATgDIARgEIAAAhIARAAIAAAJIgRAAIAAB8IABANQABAEADABQADACAJAAIAAAFIgUADQgHACgFADIgCgMIgCgLQgEAMgIAFQgGAGgJAAQgNAAgKgJgABXgKQgFAOgBAgQAAAfAHAPQAFARAMAAQALAAAGgPQAHgPgBgbQAAgigFgRQgHgRgMAAQgLAAgGAQgAhXBrIAAgxIAGAAQADAUAGAKQAIAJALABQALAAAGgIQAHgGAAgMQAAgIgFgHQgFgGgMgGIgRgLQgGgEgEgEQgEgEgBgGQgCgHAAgHQAAgQAKgLQAJgKAQAAQAHAAAFACQAGACAFAFIADgLIAFAAIAAArIgGAAQgCgQgFgIQgGgJgKAAQgJAAgGAGQgGAHAAAKQAAAHAFAGQADAGANAGIAOAJIAJAHQAHAFADAHQADAHAAAIQAAAUgKAKQgLAMgRAAQgIAAgGgDQgIgDgGgGIgEANgAi3BrIAAgxIAGAAQADAUAGAKQAIAJAMABQAKAAAGgIQAHgGAAgMQAAgIgEgHQgGgGgLgGIgSgLQgGgEgDgEQgFgEgCgGQgBgHAAgHQAAgQAJgLQAKgKAQAAQAHAAAFACQAFACAFAFIAEgLIAFAAIAAArIgGAAQgBgQgGgIQgGgJgKAAQgKAAgFAGQgGAHAAAKQAAAHAEAGQAFAGAMAGIAPAJIAJAHQAFAFAEAHQADAHAAAIQAAAUgKAKQgLAMgRAAQgIAAgHgDQgGgDgGgGIgGANgAHRBXQgNgTAAghQAAgWAFgOQAGgRALgIQAKgKANABQAUgBALATQAKARABAfIhCAAIABAWIABAPIAEAMQADAIAGAEQAGAFAIAAQAMAAAHgKQAHgKACgSIAJAAQgBAXgLAMQgLANgRAAQgXgBgLgTgAIIAWQgCgYgFgNQgGgNgLAAQgJAAgGANQgHANgBAYIAvAAIAAAAgAC5BgQgJgKAAgRQAAgLAEgJQAEgIAJgGQAJgHAKgEQAKgEANgBIAAgUQAAgOgEgGQgFgHgJABQgHAAgFAEQgFAFAAAGIAAAEIAAADIAAACQAAAFgDADQgDADgEABQgEgBgCgCQgDgDAAgDQAAgKAGgIQAFgIAIgFQAJgEALAAQAJAAAJAEQAHAFAFAJQADAEABAHIABAQIAAA9QAAAPACAFQACAGAFAAIADAAIACgBIAAAHIgHACIgGABQgJAAgEgGQgEgGgBgMQgFANgIAFQgGAGgMAAQgOAAgIgKgADNAoQgJAKAAARQAAANAGAGQAEAHAJAAQAKAAAFgKQAFgKAAgXIAAgYQgUAFgKAJgAkaBgQgJgKAAgRQAAgLAEgJQAEgIAJgGQAJgHAKgEQAKgEANgBIAAgUQAAgOgEgGQgFgHgJABQgHAAgFAEQgFAFAAAGIAAAEIAAADIAAACQAAAFgDADQgDADgEABQgEgBgCgCQgDgDAAgDQAAgKAGgIQAFgIAIgFQAJgEALAAQAJAAAJAEQAHAFAFAJQADAEABAHIABAQIAAA9QAAAPACAFQACAGAFAAIADAAIACgBIAAAHIgHACIgGABQgJAAgEgGQgEgGgBgMQgFANgIAFQgGAGgMAAQgOAAgIgKgAkGAoQgJAKAAARQAAANAGAGQAEAHAJAAQAKAAAFgKQAFgKAAgXIAAgYQgUAFgKAJgAKOBnIgLgBIgMABIgNABIAAgFQAIgBADgDQADgDAAgJIAAhJQAAgQgEgIQgFgIgLAAQgGAAgFADQgFADgDAGIgDAJIgBAMIAABIQAAAJADADQACADAJABIAAAFIgOgBIgLgBIgLABIgOABIAAgFQAKgBACgDQAEgDgBgJIAAhZIgBgMQAAgEgDgBIgKgBIAAgFIARgEIANgEIACAKIABAOQAGgLAIgGQAHgFALAAQAJAAAHAEQAHAFAEAIQADAFACAHQACAHAAAKIAABIQgBAJADADQAEADAJABIAAAFIgOgBgAk9BnIgLgBIgMABIgOABIAAgFQAKgBACgDQAEgDgBgJIAAiRQABgLgDgEQgDgCgKAAIAAgGIATgDIARgEIAACvQAAAJACADQAEADAJABIAAAFIgOgBgAqbBnIAAgGIALgDQAFgBABgEIABgMIAAiLIgBgMQgBgEgFgBQgDgCgIAAIAAgIIBlAAIAEAsIgGAAQgDgOgEgIQgCgHgGgEQgEgDgIABIggAAIAABQIAgAAQAGAAADgFQADgFAAgOIAHAAIAAA3IgHAAQABgNgEgGQgDgFgIABIgeAAIAABFQgBAKAEAEQADAEAJgBIAQAAQAIABAGgEQAFgCAEgJQAEgIADgPIAHAAIgGAugAonAgIAAgNIA7AAIAAANgAIKg3IgZgZIgZAZIgMAAIAfgrIALAAIAWAeIAVgmIAaAAIgnAqIgFAAIAGAJgADjg+IgKgJIgGgFIgFgBQgFAAgDADQgDAEgCAHIgHgCQAEgQAFgGQAEgHAJAAIAHACIAIAFIAGAGIAEADIAGABQAEABAEgEQADgDABgJIAHACQgCAOgGAIQgFAHgJABQgEAAgFgCg");
	mask.setTransform(59.55,-409.65);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#EEBA64","#FEFDCE"],[0,0.667],-124.8,0.2,124.8,0.2).s().p("AzfFTIAAqlMAm/AAAIAAKlg");
	this.shape.setTransform(61.7272,-424.35,0.9968,1);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60,-455,244.6,56.10000000000002);


(lib.Symbol4copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AoABeQgOgMgIgWQgIgXAAgeQAAgdAIgXQAIgWAOgNQAOgNATAAQALAAAJAFQAJAEAHAIIAIgQIAEAAIAAA5IgGAAQgFgZgJgLQgKgNgPAAQgVAAgLAYQgLAXAAAtQAAApALAXQALAWAUAAQASAAAKgOQAKgPABgbIAJAAQgBAhgOASQgNASgXABQgTgBgNgNgAErBiQgKgJgFgQQgGgQAAgVQAAgVAGgPQAFgQAJgJQAKgJAMAAQAJgBAGAFQAGAFAFALIAAgkIgZAAIAAgJIAZAAIAAgDQABgLgDgEQgDgCgKAAIAAgGIATgDIARgEIAAAhIARAAIAAAJIgRAAIAAB8IABANQABAEADABQAEACAIAAIAAAFIgTADQgIACgFADIgCgMIgCgLQgEAMgHAFQgHAGgJAAQgNAAgJgJgAExgKQgFAOAAAgQAAAfAGAPQAGARALAAQALAAAGgPQAHgPAAgbQAAgigGgRQgGgRgNAAQgLAAgGAQgAAXBiQgKgJgFgQQgGgQAAgVQAAgVAGgPQAFgQAJgJQAKgJAMAAQAJgBAGAFQAGAFAFALIAAgkIgZAAIAAgJIAZAAIAAgDQABgLgDgEQgDgCgKAAIAAgGIATgDIARgEIAAAhIARAAIAAAJIgRAAIAAB8IABANQABAEADABQAEACAIAAIAAAFIgTADQgIACgFADIgCgMIgCgLQgEAMgHAFQgHAGgJAAQgNAAgJgJgAAdgKQgFAOAAAgQAAAfAGAPQAGARALAAQALAAAGgPQAHgPAAgbQAAgigGgRQgGgRgNAAQgLAAgGAQgAiRBrIAAgxIAGAAQADAUAHAKQAHAJAMABQAKAAAHgIQAGgGAAgMQAAgIgEgHQgFgGgMgGIgSgLQgGgEgDgEQgEgEgCgGQgCgHAAgHQAAgQAKgLQAJgKAQAAQAHAAAFACQAGACAFAFIADgLIAFAAIAAArIgGAAQgBgQgGgIQgGgJgKAAQgJAAgGAGQgFAHgBAKQAAAHAFAGQAEAGAMAGIAPAJIAJAHQAGAFADAHQADAHAAAIQAAAUgKAKQgLAMgRAAQgIAAgGgDQgHgDgGgGIgFANgAjxBrIAAgxIAGAAQADAUAHAKQAHAJAMABQAKAAAHgIQAGgGAAgMQAAgIgEgHQgFgGgMgGIgSgLQgGgEgDgEQgEgEgCgGQgCgHAAgHQAAgQAKgLQAJgKAQAAQAHAAAFACQAGACAFAFIADgLIAFAAIAAArIgGAAQgBgQgGgIQgGgJgKAAQgJAAgGAGQgFAHgBAKQAAAHAFAGQAEAGAMAGIAPAJIAJAHQAGAFADAHQADAHAAAIQAAAUgKAKQgLAMgRAAQgIAAgGgDQgHgDgGgGIgFANgAGXBXQgNgTAAghQAAgWAGgOQAFgRALgIQAKgKANABQAUgBALATQALARABAfIhDAAIABAWIACAPIADAMQAEAIAFAEQAGAFAIAAQAMAAAHgKQAIgKACgSIAJAAQgCAXgLAMQgLANgRAAQgWgBgMgTgAHOAWQgBgYgGgNQgFgNgLAAQgKAAgGANQgGANgCAYIAvAAIAAAAgAB/BgQgJgKAAgRQAAgLAEgJQAFgIAIgGQAJgHAKgEQAKgEANgBIAAgUQAAgOgEgGQgEgHgJABQgIAAgFAEQgFAFAAAGIAAAEIAAADIAAACQAAAFgCADQgDADgFABQgEgBgCgCQgCgDAAgDQAAgKAFgIQAFgIAJgFQAIgEALAAQAKAAAIAEQAIAFAEAJQADAEABAHIABAQIAAA9QAAAPACAFQACAGAFAAIADAAIADgBIAAAHIgIACIgGABQgIAAgFgGQgEgGgBgMQgFANgHAFQgHAGgLAAQgOAAgJgKgACUAoQgJAKAAARQAAANAFAGQAEAHAJAAQAKAAAFgKQAFgKAAgXIAAgYQgUAFgJAJgAlUBgQgJgKAAgRQAAgLAEgJQAFgIAIgGQAJgHAKgEQAKgEANgBIAAgUQAAgOgEgGQgEgHgJABQgIAAgFAEQgFAFAAAGIAAAEIAAADIAAACQAAAFgCADQgDADgFABQgEgBgCgCQgCgDAAgDQAAgKAFgIQAFgIAJgFQAIgEALAAQAKAAAIAEQAIAFAEAJQADAEABAHIABAQIAAA9QAAAPACAFQACAGAFAAIADAAIADgBIAAAHIgIACIgGABQgIAAgFgGQgEgGgBgMQgFANgHAFQgHAGgLAAQgOAAgJgKgAk/AoQgJAKAAARQAAANAFAGQAEAHAJAAQAKAAAFgKQAFgKAAgXIAAgYQgUAFgJAJgAJUBnIgLgBIgLABIgOABIAAgFQAIgBAEgDQADgDgBgJIAAhJQABgQgFgIQgFgIgKAAQgHAAgFADQgFADgDAGIgDAJIgBAMIAABIQAAAJADADQADADAIABIAAAFIgOgBIgLgBIgLABIgOABIAAgFQAKgBADgDQADgDAAgJIAAhZIgBgMQgBgEgDgBIgKgBIAAgFIARgEIANgEIACAKIABAOQAGgLAIgGQAIgFAKAAQAJAAAHAEQAHAFAFAIQADAFABAHQACAHAAAKIAABIQgBAJADADQAEADAJABIAAAFIgOgBgAl3BnIgLgBIgLABIgPABIAAgFQAKgBADgDQADgDAAgJIAAiRQAAgLgDgEQgDgCgKAAIAAgGIATgDIARgEIAACvQAAAJADADQADADAKABIAAAFIgPgBgAphAgIAAgNIA7AAIAAANgAHQg3IgZgZIgZAZIgLAAIAegrIAMAAIAWAeIAUgmIAaAAIgmAqIgGAAIAGAJgACqg+IgKgJIgHgFIgFgBQgEAAgDADQgEAEgCAHIgHgCQAEgQAFgGQAFgHAIAAIAHACIAIAFIAGAGIAFADIAFABQAFABADgEQADgDACgJIAGACQgCAOgFAIQgGAHgJABQgEAAgEgCg");
	mask.setTransform(65.325,-409.65);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#EEBA64","#FEFDCE"],[0,0.667],-124.4,0.2,124.4,0.2).s().p("AzbFTIAAqlMAm3AAAIAAKlg");
	this.shape.setTransform(61.725,-424.35);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60,-455,244.6,56.10000000000002);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.514,1],-14.5,-4.6,14.7,4.7).s().p("AjwD8IC+pUIEjBeIi+JTg");
	this.shape.setTransform(24.125,34.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.3,69);


(lib.Symbol1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.bg();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Symbol25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.instance = new lib.Symbol27("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(901.5,352,1,1,0,0,0,360.5,192);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(69).to({startPosition:0},0).to({x:1574.8,y:427.95,alpha:0},16,cjs.Ease.get(1)).wait(110).to({regX:360.4,scaleX:1.3,scaleY:1.3,x:110.15,y:47.05},0).to({regX:360.6,regY:192.1,scaleX:1.6,scaleY:1.6,x:584.05,y:308.55,alpha:1},16,cjs.Ease.get(1)).wait(629));

	// Layer_1
	this.instance_1 = new lib.Symbol26("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(433.5,255.5,1,1,0,0,0,433.5,255.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(69).to({startPosition:0},0).to({regX:433.6,scaleX:1.5999,scaleY:1.5999,x:782,y:149.7},16,cjs.Ease.get(1)).wait(98).to({scaleX:1.6,scaleY:1.6},0).to({scaleX:1.5499,scaleY:1.5499,x:-26.65,y:369.7,alpha:0},16,cjs.Ease.get(1)).wait(641));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-607.2,-205.1,2489.1000000000004,1071.8);


(lib.Symbol23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol24("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(140,44.95,0.5,0.5,0,0,0,167.2,45);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.1,scaleY:1.1,x:175.3,y:45,alpha:1},9,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,x:167.2},10,cjs.Ease.get(1)).wait(2002));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-182.3,-12.2,577.3,112.7);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Al7BeIAAi7IL3AAIAAC7g");
	mask.setTransform(49.05,4.6);

	// Layer_3
	this.instance = new lib.Symbol2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-4.05,1.5,0.6,0.7756,0,0,0,24.1,34.5);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:24.2,regY:34.4,scaleY:0.7078,x:102.9,y:2.7},23,cjs.Ease.get(1)).wait(67));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-4.8,87.1,18.8);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(43.35,7.65,0.4,0.4,0,0,0,43.4,7.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:7.6,scaleX:1.1,scaleY:1.1,x:43.4,y:7.6,alpha:1},11,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(1944));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-11.8,-4.7,102.89999999999999,26.7);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol14("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(83.95,83.1,0.3,0.3,0,0,0,84,37.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({_off:false},0).to({scaleX:1.05,scaleY:1.05,x:84,y:35,alpha:1},11,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,y:37.6},8,cjs.Ease.get(1)).wait(45).to({startPosition:0},0).to({alpha:0},11,cjs.Ease.get(1)).wait(1226));

	// Layer_3
	this.instance_1 = new lib.Symbol10("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(84.45,63.85,0.3,0.3,0,0,0,84,37.9);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regY:37.6,scaleX:1.05,scaleY:1.05,x:84.5,y:37.2,alpha:1},11,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,y:37.85},8,cjs.Ease.get(1)).wait(49).to({startPosition:0},0).to({x:82.5,y:-18.15},11,cjs.Ease.get(1)).wait(1226));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-31.9,-49.9,237.5,139.1);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol23("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(82.1,-361.75,0.35,0.35,0,0,0,168.8,43.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(15).to({_off:false},0).wait(176).to({startPosition:176},0).to({_off:true},1).wait(506));

	// Layer_1 copy 4
	this.instance_1 = new lib.Symbol4copy4("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(51.9,22.3,1,1,0,0,0,51.9,11.8);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(111).to({_off:false},0).to({y:11.8,alpha:1},15,cjs.Ease.get(1)).wait(65).to({startPosition:0},0).to({_off:true},1).wait(503).to({_off:false},0).wait(3));

	// Layer_1 copy 3
	this.instance_2 = new lib.Symbol4copy3("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(51.9,11.8,1,1,0,0,0,51.9,11.8);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(102).to({_off:false},0).to({y:4.8,alpha:0},15,cjs.Ease.get(1)).wait(74).to({startPosition:0},0).to({_off:true},1).wait(503).to({_off:false},0).wait(3));

	// Layer_1 copy 2
	this.instance_3 = new lib.Symbol4copy("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(51.9,11.8,1,1,0,0,0,51.9,11.8);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(102).to({_off:false},0).wait(89).to({startPosition:0},0).to({_off:true},1).wait(506));

	// Layer_1 copy
	this.instance_4 = new lib.Symbol4copy2("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(-39.1,11.8,1,1,0,0,0,51.9,11.8);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:55.95,alpha:1},11,cjs.Ease.get(1)).to({x:51.9},7,cjs.Ease.get(1)).to({_off:true},84).wait(596));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-98.2,-425.6,259.4,83.80000000000001);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_275 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(275).call(this.frame_275).wait(1));

	// logo
	this.instance = new lib.Symbol13("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(152.5,563.5,1,1,0,0,0,15.5,15.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(276));

	// effect cta
	this.instance_1 = new lib.Symbol18();
	this.instance_1.parent = this;
	this.instance_1.setTransform(136,436.2,2,2,0,0,0,42.5,10.1);
	this.instance_1.alpha = 0.8008;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(244).to({_off:false},0).wait(32));

	// cta
	this.instance_2 = new lib.Symbol11("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(155.75,425.5,1.6499,1.6499,0,0,0,44.1,8.8);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(224).to({_off:false},0).wait(52));

	// t2
	this.instance_3 = new lib.Symbol3("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(142.9,576.8,1,1,0,0,0,51.9,11.8);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(84).to({_off:false},0).wait(192));

	// t1
	this.instance_4 = new lib.Symbol9("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(150,201.6,1,1,0,0,0,84,37.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(276));

	// Layer_10
	this.instance_5 = new lib.Symbol25("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(103.25,322.45,0.235,0.235,0,0,0,435.2,257.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(276));

	// Layer_8 copy
	this.instance_6 = new lib.Symbol1copy("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(150,300,1,1,0,0,0,150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(276));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-141.6,0,584.7,602.2);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.parent = this;
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,300,150,302.20000000000005);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 300,
	height: 600,
	fps: 31,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg.jpg?1707132158431", id:"bg"},
		{src:"images/logo.png?1707132158431", id:"logo"},
		{src:"images/x1.png?1707132158431", id:"x1"},
		{src:"images/x2.png?1707132158431", id:"x2"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;