(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bg1 = function() {
	this.initialize(img.bg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,1220);


(lib.bg2 = function() {
	this.initialize(img.bg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,465,940);


(lib.bg3 = function() {
	this.initialize(img.bg3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,651);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,200,200);


(lib.Tween4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.514,1],-7.6,-4.8,7.6,4.7).s().p("AjICZID5mQICYBgIj5GOg");
	this.shape.setTransform(-0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-20.1,-24.7,40.2,49.5);


(lib.Tween3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.514,1],-7.6,-4.8,7.6,4.7).s().p("AjICZID5mQICYBgIj5GOg");
	this.shape.setTransform(-0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-20.1,-24.7,40.2,49.5);


(lib.Symbol33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AOFB+IgYACIAAgGQAHAAAEgCQADgBABgFIABgGIAAiKQAAgLgEgDQgDgCgJAAIAAgFQAQgBANgEQACAIABAPQAKgWASAAQASAAAMASQAMATAAAcQAAAcgLATQgMATgSAAQgMAAgHgIQgEgEgFgJIAAA1QAAAGACADQACAFAMAAIAAAGIgZgCgAOXgnQgJANAAAiQAAA9AaAAQAYAAAAg6QAAg7gZAAQgJAAgHAJgAF/B+IgYACIAAgGQAHAAAEgCQADgBABgFIABgGIAAiKQAAgLgEgDQgDgCgJAAIAAgFQAQgBANgEQACAIABAPQAKgWASAAQASAAAMASQAMATAAAcQAAAcgLATQgMATgSAAQgMAAgHgIQgEgEgFgJIAAA1QAAAGACADQACAFAMAAIAAAGIgZgCgAGRgnQgJANAAAiQAAA9AaAAQAYAAAAg6QAAg7gZAAQgJAAgHAJgAtfB+IgZACIAAgGQAHAAAEgCQAEgBAAgFIABgGIAAg1QgFAJgEAEQgHAIgMAAQgSAAgMgTQgLgTAAgcQAAgcAMgTQAMgSASAAQATAAAJAWQABgOACgJQAMAEARABIAAAFIgDAAQgIAAgCAEQgDAEAAAIIAACKQAAAGACADQACAFAMAAIAAAGIgYgCgAuRgmQgJAOAAAiQAAA7AYAAQAaAAAAg8QAAg5gZAAQgKAAgGAKgAq2B+IAAgNQAIAAAFgCQAKgEAGgSIAHgUIghhpQgCgIgEgCQgEgCgGAAIAAgGIAWACIAXgCIAAAGIgGABQgGABAAAEIACAHIAXBNIAZhMIABgIQAAgEgFgBIgHgBIAAgGIAQACIATgCIAAAGQgFABgEACQgFACgCAIIgqCDQgGASgJAHQgHAFgLAAIgDAAgAyKB6QgDgDAAgGQAAgFADgDQADgEAFAAQAEAAADAEQADADAAAFQAAAGgDADQgDAEgEAAQgFAAgDgEgAAuBPIgSghIhGiBIAACFQAAAJABACQAEAGANABIAAAHIgWgCIgWACIAAgHQAKgBADgCQAFgCAAgFIABgIIAAiNQgEgFgEgCQgEgBgHAAIAAgHIATABIAQgBIBLCIIAAhvQAAgJgCgDQgDgFgOgBIAAgHIAXABIAVgBIAAAHQgIAAgEACQgFADgBAFIAAAIIAACggA0WA3QgKgTAAgZQAAgZAKgSQALgWAUAAQALAAAHAIQAEAEAEAJIAAgkIghAAIAAgIIAhAAIAAgEIgBgKQgCgEgGgBIgCAAIgEAAIAAgFQARgCAQgFIAAAfIAPAAIAAAIIgPAAIAABzIABALQABAFAEABIAEABIAGABIAAAEIgQAEIgNADIgCgKIgBgLQgJAWgSAAQgVAAgLgWgA0NALQAAAYAFAQQAFASAOAAQAJAAAGgIQAKgNAAgjQAAg8gaAAQgXAAAAA6gARoA5QgLgTAAgcQAAgcAMgTQANgTAUAAQATAAAMATQALAUAAAbQAAAcgMATQgMAUgUAAQgUAAgMgUgAR5gnQgJAOAAAjQAAA8AYAAQAKAAAHgLQAIgOAAgiQAAg8gZAAQgIAAgHAKgArrA0QgFAKgEAFQgJAJgNAAQgSAAgJgPQgGgKAAgUIAAg9IgBgLQgCgEgFAAIgHgBIAAgEQARgCAQgFIAABZQAAAQAEAHQAFAJALAAQANAAAGgMQAEgHAAgRIAAg6IgBgLQgCgEgFAAIgHgBIAAgEQARgCAQgFIAABsIABAKQACADAGAAIAIABIAAAEQgSADgNAFIgBgZgAw5A6QgMgSAAgdQAAgeANgTQAMgSATAAQANAAAKALIAGgNIADAAIAAAsIgFAAQgCgMgDgHQgDgHgFgFQgGgEgGAAQgOAAgHASQgGARAAAZQAAA5AaAAQAVAAAEgkIAJAAQgCAPgEAKQgKAUgUAAQgTAAgMgTgAyjA5QgLgTAAgcQAAgcAMgTQANgTAUAAQATAAAMATQALAUAAAbQAAAcgMATQgMAUgUAAQgUAAgMgUgAySgnQgJAOAAAjQAAA8AYAAQAKAAAHgLQAIgOAAgiQAAg8gZAAQgIAAgHAKgAULBIQgDgFAAgGQAAgHADgEQAEgFAGAAQAFAAADAFQAEAEAAAHQAAAGgEAFQgDAEgGAAQgFAAgEgEgAJgBDQgJgKAAgQQAAgYAZgNQAOgGATgDIAAgQQAAgNgDgGQgFgIgKAAQgJAAgGAGQgEAEAAAGIAAACIAAAEQAAAMgJAAQgHAAAAgJQAAgMAKgKQALgKAPAAQALAAAJAFQALAIACANQACAHAAALIAAA2QAAANACAGQABAGAGAAIAFgBIAAAHQgHACgFAAQgKAAgEgJQgDgFAAgJQgFAJgEAFQgIAJgNAAQgOAAgIgJgAJ4AKQgPAKAAAUQAAAMAFAGQAFAGAIAAQAPAAAFgQQACgHAAgQIAAgYQgPAEgKAFgADUBDQgJgKAAgQQAAgYAZgNQAOgGATgDIAAgQQAAgNgDgGQgFgIgKAAQgJAAgGAGQgEAEAAAGIAAACIAAAEQAAAMgJAAQgHAAAAgJQAAgMAKgKQALgKAPAAQALAAAJAFQALAIACANQACAHAAALIAAA2QAAANACAGQABAGAGAAIAFgBIAAAHQgHACgFAAQgKAAgEgJQgDgFAAgJQgFAJgEAFQgIAJgNAAQgOAAgIgJgADsAKQgPAKAAAUQAAAMAFAGQAFAGAIAAQAPAAAFgQQACgHAAgQIAAgYQgPAEgKAFgAioA0QgEAKgFAFQgIAJgNAAQgSAAgJgPQgGgKAAgUIAAg9IgBgKQgCgGgNAAIAAgEQASgCAQgGIAABaQAAAQADAHQAFAJAMAAQAMAAAHgMQAEgHAAgRIAAg6QAAgIgBgCQgDgGgMAAIAAgEQARgCARgGIAAAJQAGgJAAgIIgCAAQgJgCACgLQACgJAIAAQALAAAAANQAAAMgLAOIgDAFIgEAFIAABaIABAKQACADAGAAIAHABIAAAEQgRACgOAFIgBgYgAkoA9QgCgGAAgKIgBgNIAAhLIgNAAIAAgIQAFgBAEgCQANgHAEgeIAGAAIAAAmIAaAAIAAAKIgaAAIAABOQAAAQACAGQACAJAJAAQAFAAAJgGIAAAIQgLAIgKAAQgQAAgGgPgApCA7QgMgTAAgeQAAgdAMgTQAMgRAUAAQAPAAALALQAOAQAAAjIhCAAIAAAGQAAAWAGAQQAHAQAQAAQARAAAHgRQADgHACgLIAIAAQgBAQgHALQgKARgVAAQgVAAgMgRgAo7gCIAvAAQgBgugWAAQgVAAgDAugATcBJIgZACIAAgGQAIAAAEgCQADgCABgEIAAgGIAAhVIgBgLQgCgEgFAAIgHgBIAAgEQASgCAPgFIAABwIABAJQADAFAMAAIAAAGIgZgCgAQ3BJQgKAAgPACIAAgGQAHAAAEgCQADgCABgEIAAgGIAAhBQAAgQgDgHQgFgKgMAAQgLAAgHALQgFAHAAAQIAABAQAAAGACADQACAFALAAIAAAGQgOgCgKAAQgKAAgOACIAAgGQAHAAAEgCQADgCABgEIABgGIAAiIQAAgHgCgDQgCgEgFgBIgHAAIAAgFQARgCAQgFIAABHQALgSASAAQASAAAJARQAFAJAAAUIAABAIABAJQADAFAMAAIAAAGQgPgCgJAAgAMTBJQgKAAgOACIAAgGQAGAAAEgCQADgCABgEIAAgGIAAhBQAAgQgDgHQgFgKgLAAQgMAAgHALQgEAHAAAQIAABAIABAJQACAFALAAIAAAGQgOgCgKAAQgKAAgOACIAAgGQAHAAAEgCQAEgCAAgEIABgGIAAhTIgBgKQAAgFgGgBIgJgBIAAgEQASgEALgEQACAHABAQQALgVATAAQASAAAJAQQAFAKAAAUIAABAQAAAGACADQACAFAMAAIAAAGQgOgCgKAAgAIxBJQgKAAgPACIAAgGQAHAAAEgCQADgCABgEIAAgGIAAhBQAAgQgDgHQgFgKgMAAQgLAAgHALQgFAHAAAQIAABAQAAAGACADQACAFALAAIAAAGQgOgCgKAAQgKAAgOACIAAgGQAHAAAEgCQADgCABgEIABgGIAAiIQAAgHgCgDQgCgEgFgBIgHAAIAAgFQARgCAQgFIAABHQALgSASAAQASAAAJARQAFAJAAAUIAABAIABAJQADAFAMAAIAAAGQgPgCgJAAgAClBJQgKAAgPACIAAgGQAHAAAEgCQADgCABgEIAAgGIAAhBQAAgQgDgHQgFgKgMAAQgLAAgHALQgFAHAAAQIAABAQAAAGACADQACAFALAAIAAAGQgOgCgKAAQgKAAgOACIAAgGQAHAAAEgCQADgCABgEIABgGIAAiIQAAgHgCgDQgCgEgFgBIgHAAIAAgFQARgCAQgFIAABHQALgSASAAQASAAAJARQAFAJAAAUIAABAIABAJQADAFAMAAIAAAGQgPgCgJAAgAmUBJQgKAAgOACIAAgGQAGAAAEgCQADgCABgEIAAgGIAAhBQAAgQgDgHQgFgKgLAAQgMAAgHALQgEAHAAAQIAABAIABAJQACAFALAAIAAAGQgOgCgKAAQgKAAgOACIAAgGQAHAAAEgCQAEgCAAgEIABgGIAAhTIgBgKQAAgFgGgBIgJgBIAAgEQASgEALgEQACAHABAQQALgVATAAQASAAAJAQQAFAKAAAUIAABAQAAAGACADQACAFAMAAIAAAGQgOgCgKAAgASchFIgUgUIgVAUIgGAAIAWggIAKAAIAXAggAKVhFIgVgUIgVAUIgGAAIAXggIAKAAIAWAggAoOhFIgVgUIgVAUIgGAAIAWggIALAAIAWAggAxuhFIgVgUIgVAUIgGAAIAWggIALAAIAWAggAD8hKIgegiIASAAIASAigAi2hKIgfgiIASAAIATAigATThQQgEgEAAgGQAAgHAEgEQAEgEAFAAQAFAAADAEQAEAEAAAHQAAAGgEAEQgDAEgFAAQgFAAgEgEgAoAhbIgegiIASAAIASAigASchdIATgiIASAAIgfAig");
	this.shape.setTransform(124.825,5.625);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.4,-7.1,262.5,25.5);


(lib.Symbol32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ApOBuQgJgFgDgIQgFgHAAgJQAAgUAYgJQgFgCgCgDQgGgEAAgHQAAgPAbgGQgKgDgGgGQgNgLAAgTQAAgSALgLQAMgLAVAAQAPAAAMAHIAhAAIAAALIgYAAQAGAKAAAMQAAAVgQALQgIAFgTAFIgRAGQgJACAAAHQAAAEAFACIARACQAdACALAEQAKAFAGAKQADAHABAIQgBAJgDAIQgFAIgHAFQgPALgYAAQgWABgOgJgApLBDQgKAFAAALQABAMAKAIQAOAHASAAQARAAALgHQALgHAAgMQAAgYgsABQgRgBgLAHgAo8gwQgHAJAAAQQAAAOAGAIQAFALANgBQAMAAAHgJQAFgKAAgOQAAghgYAAQgMAAgFAJgAIUA3QgRgNgIgaQgGgRAAgXQAAgpASgaQAJgOAPgGQALgHAPAAQAYAAAPARIAJgQIAFAAIAAA1IgGAAQgKgsgigBQgZAAgMAZQgLAXABAkQgBAiAKAXQAMAZAZgBQARABALgMQAOgNACgbIAJAAQgBAUgHAPQgHANgNAJQgMAHgPAAQgVgBgQgNgAhHAuQgMgSAAgaQAAgZAMgSQALgWAXAAQANAAAJAIQADAEAGAJIAAgkIglAAIAAgIIAlABIAAgFQgBgHgBgDQgCgEgGgBIgEAAIgEAAIAAgEQAUgCARgGIAAAfIAQAAIAAAIIgQAAIAABzIAAAMQABAEAGABIAEABIAHABIAAAFIgSADIgOAEIgCgLIgCgLQgKAWgUABQgXAAgNgXgAg9ACQAAAYAFAQQAGATARAAQAKAAAHgJQAKgNAAgjQAAg7gdAAQgaAAAAA5gAvkA3QgRgNgIgaQgGgRAAgXQAAgpASgaQAJgOAPgGQALgHAPAAQAXAAAQARIAJgQIAFAAIAAA1IgGAAQgKgsgigBQgZAAgMAZQgLAXABAkQgBAiAKAXQAMAZAZgBQARABALgMQAOgNACgbIAJAAQgBAUgHAPQgHANgNAJQgNAHgOAAQgVgBgQgNgAOzBEIAAgtIAFAAQACAMAEAHQAEAIAGAEQAIAGAIAAQAMAAAIgIQAHgHAAgKQAAgKgIgGQgFgDgOgHIgTgJQgRgJAAgTQAAgQAKgKQALgKARAAQAOAAALAJIAFgLIAFAAIAAApIgHAAQgCgfgYAAQgKAAgIAHQgFAHAAAIQAAAIAEAFQAEADAMAHIARAIQAMAEAGAGQAIAIAAANQgBARgJAKQgMANgTAAQgRAAgNgMIgGAMgANHBEIAAgtIAFAAQADAMADAHQAEAIAHAEQAHAGAJAAQALAAAIgIQAIgHgBgKQAAgKgIgGQgFgDgOgHIgSgJQgRgJAAgTQAAgQAKgKQALgKAQAAQAOAAAMAJIAFgLIAEAAIAAApIgGAAQgDgfgYAAQgKAAgHAHQgGAHAAAIQAAAIAFAFQADADANAHIAQAIQANAEAGAGQAHAIAAANQAAARgKAKQgMANgSAAQgRAAgOgMIgGAMgAjGArQgFAKgGAFQgJAJgOAAQgVAAgKgPQgHgJABgUIAAg9QAAgJgCgCQgCgFgHAAIgHgBIAAgEQATgCATgFIAABZQAAAQADAHQAHAJAMAAQAOAAAIgLQAEgIAAgRIAAg5QAAgJgBgCQgCgFgHAAIgIgBIAAgEQAUgCASgFIAABtQAAAGACADQACADAHAAIAIABIAAAFQgVACgNAFIgCgZgAsbArQgFAKgFAFQgKAJgPAAQgUAAgKgPQgGgJgBgUIAAg9QABgJgCgCQgDgFgGAAIgIgBIAAgEQAUgCASgFIAABZQABAQAEAHQAGAJAMAAQAPAAAGgLQAFgIAAgRIAAg5QAAgJgBgCQgCgFgGAAIgIgBIAAgEQATgCASgFIAABtQABAGABADQACADAGAAIAJABIAAAFQgVACgOAFIgBgZgALYA6QgLgKAAgPQAAgYAegMQAPgIAWgCIAAgQQAAgOgEgGQgGgHgLAAQgKgBgGAGQgFAEAAAGIAAADIAAADQAAANgKAAQgIgBgBgIQAAgNALgKQANgKASAAQAMAAAKAGQAMAHADANQACAHAAAMIAAA1QAAANABAGQADAGAFAAIAHgBIAAAHQgIACgGAAQgLAAgFgIQgDgGgBgJQgEAJgFAFQgJAKgPAAQgPAAgKgKgAL0ABQgSAKAAAUQAAAMAGAHQAGAFAJAAQAQAAAGgPQADgIAAgQIAAgXQgSAEgKAEgAA4A6QgLgKAAgPQAAgYAdgMQAQgIAVgCIAAgQQAAgOgDgGQgGgHgLAAQgKgBgHAGQgFAEAAAGIAAADIAAADQAAANgKAAQgIgBAAgIQAAgNALgKQANgKASAAQAMAAAJAGQANAHACANQACAHAAAMIAAA1QABANABAGQACAGAGAAIAHgBIAAAHQgJACgGAAQgKAAgFgIQgDgGgBgJQgFAJgFAFQgIAKgPAAQgQAAgJgKgABTABQgRAKAAAUQgBAMAHAHQAFAFAJAAQARAAAGgPQACgIAAgQIAAgXQgRAEgLAEgAlOArQgGAKgFAGQgJAIgPAAQgUAAgLgPQgGgKAAgTIAAg9IgBgLQgDgFgOgBIAAgEQAUgCATgFIAABZQAAAQADAHQAGAJANAAQAOAAAIgLQAEgIAAgRIAAg5QAAgJgBgCQgDgFgOgBIAAgEQAUgCASgFIAAAJQAIgKAAgHIgCAAQgLgDADgLQACgJAJAAQAMAAAAANQAAANgMAOIgEAEIgFAGIAABaQAAAGACADQACADAGAAIAJABIAAAFQgUABgPAGIgBgZgAKjBAIgdACIAAgFQAJgBAEgBQAFgCAAgFIAAgGIAAiIQAAgHgBgDQgCgEgHgBIgHAAIAAgFQATgCATgFIAACjQAAAGACADQACAFAOABIAAAFIgcgCgAC9BAIgdACIAAgFQAJgBAEgBQAFgCAAgFIAAgGIAAhUQAAgJgBgCQgCgFgHAAIgHgBIAAgEQAUgCASgFIAABwIABAJQAEAFANABIAAAFIgcgCgAqHBAQgMAAgQACIAAgFQAIAAAEgCQAEgDAAgEIAAgGIAAhBQABgQgEgHQgFgJgNgBQgOAAgIALQgFAHAAAQIAABAQAAAHABACQADAFANABIAAAFQgQgCgLAAQgMAAgQACIAAgFQAJgBADgBQAEgCACgFIAAgGIAAhTIAAgJQgBgGgHgBIgKgBIAAgEQAVgDAMgFQADAHAAAQQANgVAVAAQAVAAAKARQAGAKAAATIAABAQAAAGACADQACAFAOABIAAAFQgRgCgKAAgAEmBBIAAgGQALgBAEgCQAFgDABgFIABgHIAAiDQAAgHgCgDQgDgHgRgBIAAgGIBuAAIAEApIgFAAQgEgSgGgIQgHgGgNgBIglAAIAABLIAlAAQAGAAADgDQAFgFABgPIAGAAIAAA1IgGAAQAAgMgEgFQgDgGgJAAIgkAAIAABBQABAHABACQADAHANgBIASAAQAOAAAGgFQAJgJAFgUIAFAAIgFArgAGogBIAAgLIBAAAIAAALgAsshTIgkgiIAWAAIAUAigACyhZQgEgEAAgGQAAgHAEgDQAEgFAGAAQAFAAAFAFQADADAAAHQAAAGgDAEQgFAFgFAAQgGAAgEgFgABchgQgHgEgEAAQgIgBgFAMIgEgBQACgLAEgFQAGgFAHAAQAIAAAGAFQAKAIAFgBQAIAAADgMIAFABQgCALgFAGQgFAFgGABQgHAAgLgJg");
	this.shape.setTransform(109,2.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(6.3,-9.4,205.5,23.700000000000003);


(lib.Symbol30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg3();
	this.instance.setTransform(-4,-15,0.96,0.96);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-15,307.2,625);


(lib.Symbol29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AoHCrQgFgFAAgHQAAgHAFgEQAEgFAHAAQAGAAAFAFQAFAEAAAHQAAAHgFAFQgFAFgGAAQgHAAgEgFgAGlBSQgPgaAAgiQAAghAOgYQARgeAfAAQATAAALALQAFAFAHAMIAAgwIgzAAIAAgKIAzAAIAAgFQAAgKgCgEQgCgGgKgBIgEAAIgHAAIAAgGQAcgDAYgHIAAAqIAXAAIAAAKIgXAAIAACbIABAOQACAHAHACIAHABIAJAAIAAAGIgaAFQgLACgIADIgDgOIgDgPQgOAegcAAQgfAAgSgdgAGzAWQAAAgAHAVQAJAZAWAAQANAAAKgLQAOgRAAgvQAAhQgnAAQgkAAAABNgAiVBWQgTgZAAgnQAAgkASgZQARgaAcAAQASAAALALQAGAFAGAMIAAg/QAAgKgCgEQgCgGgJgBIgLAAIAAgGQAcgDAYgHIAADPQAAAKABAEQACAHAGACQAFABALAAIAAAHQgcADgRAGQgEgPgBgOQgOAegcAAQgdAAgRgZgAiLAWQAAAhAIAUQADAMAJAHQAIAHAKAAQAOAAAKgMQAOgRAAgvQAAhQgnAAQglAAAABNgAuJBeQgWgSgMgiQgHgZAAgdQAAg2AZgkQAMgSATgKQARgHATAAQAhAAAVAVIANgVIAGAAIAABHIgIAAQgPg7gtAAQgjAAgQAgQgPAfAAAxQAAAtAOAdQAQAiAjAAQAWAAAQgPQATgSACglIANAAQgBAcgKATQgKATgSAKQgRAKgVAAQgbAAgXgRgAovBUQgRgZAAglQAAgnATgZQATgZAgAAQAeAAARAaQASAagBAkQAAAlgRAaQgTAageAAQggAAgTgagAoUgtQgPATAAAvQAABQAmAAQAPAAALgOQANgTgBguQABhQgmAAQgOAAgKANgANHBNQgHANgHAHQgNAMgVAAQgbAAgOgUQgJgNAAgbIAAhRQAAgLgCgEQgDgFgJgBIgLAAIAAgGQAbgDAagHIAAB3QgBAWAGAJQAIAMARAAQAUAAAKgPQAGgLAAgWIAAhNQABgLgDgEQgCgFgJgBIgLAAIAAgGQAbgDAZgHIAACRQAAAKACADQADAEAJABIALAAIAAAGQgbADgUAHQgCgKAAgXgAOSBnQgHgGAAgIQAAgJAHgGQAFgGAIAAQAJAAAFAGQAGAGAAAJQAAAIgGAGQgFAGgJAAQgIAAgFgGgAJLBhQgOgNAAgVQAAggAngRQAWgKAdgEIAAgUQAAgSgFgIQgIgKgPAAQgOAAgJAHQgGAFAAAJIAAADIAAAFQAAAQgOAAQgLAAAAgMQAAgRAPgMQARgOAYAAQARAAAOAHQARAKAEASQACAJAAAPIAABJQAAARACAHQADAIAJAAIAIgBIAAAJQgMADgIAAQgOAAgHgLQgDgHgCgNQgGANgHAGQgNAMgUAAQgVAAgNgMgAJxAWQgYAMAAAbQAAAQAIAJQAHAIANAAQAWAAAJgVQADgLAAgVIAAgfQgXAEgPAIgAANBhQgNgNgBgVQABggAmgRQAWgKAcgEIAAgUQAAgSgEgIQgIgKgQAAQgOAAgIAHQgHAFABAJIAAADIAAAFQgBAQgOAAQgLAAAAgMQAAgRAQgMQAQgOAZAAQARAAANAHQARAKAEASQACAJAAAPIAABJQAAARADAHQADAIAIAAIAJgBIAAAJQgMADgIAAQgPAAgGgLQgEgHgBgNQgHANgHAGQgMAMgUAAQgVAAgNgMgAAyAWQgXAMgBAbQABAQAHAJQAIAIANAAQAWAAAIgVQAEgLgBgVIAAgfQgXAEgPAIgAEYBpQgPAAgWACIAAgHQAKAAAGgDQAFgDABgFIABgIIAAhXQAAgVgGgJQgHgOgSAAQgSAAgLAPQgHAKAAAUIAABWQAAAJACADQAEAHAQAAIAAAHQgWgCgPAAQgPAAgWACIAAgHQAMAAAFgDQAGgCABgGIAAgIIAAhvIgBgNQAAgHgKgBIgNgBIAAgGQAdgFARgGQACAKABAVQATgcAcAAQAcAAAOAWQAIANAAAaIAABWQAAAJACADQAFAGASABIAAAHQgWgCgQAAgAklBpQgQAAgVACIAAgHQAJAAAGgDQAGgDAAgFIABgIIAAhXQAAgVgFgJQgIgOgRAAQgTAAgLAPQgGAKAAAUIAABWQAAAJACADQADAHARAAIAAAHQgWgCgQAAQgOAAgXACIAAgHQAMAAAGgDQAFgCACgGIAAgIIAAhvIgBgNQgBgHgJgBIgNgBIAAgGQAcgFARgGQADAKAAAVQATgcAdAAQAcAAANAWQAJANAAAaIAABWQAAAJACADQAEAGATABIAAAHQgXgCgPAAgApxBpQgPAAgXACIAAgHQAKAAAGgDQAFgDABgFIABgIIAAhXQAAgVgFgJQgIgOgRAAQgTAAgKAPQgIAKABAUIAABWQgBAJACADQAFAHAQAAIAAAHQgXgCgPAAQgOAAgXACIAAgHQAMAAAGgDQAFgCABgGIABgIIAAi1QAAgKgDgEQgCgGgJgBIgLAAIAAgGQAcgDAZgHIAABfQAQgYAbAAQAcAAAOAWQAIANAAAaIAABWQAAAJACADQAFAGASABIAAAHQgWgCgPAAgAKehUIghgbIggAbIgJAAIAigrIAQAAIAjArgABfhUIghgbIgfAbIgKAAIAjgrIAQAAIAiArgAK2hvIgwgtIAcAAIAdAtgAA/iaQgIgGgGAAQgLAAgGAQIgHgCQAEgOAFgHQAIgIAKABQAKAAAJAHQAOAKAIAAQAJgBAFgQIAGABQgCAPgHAIQgHAHgJABIgBAAQgKAAgOgMg");
	this.shape.setTransform(73.7,9.3985);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-21,-8.1,189.4,35.1);


(lib.Symbol28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AjKBsQgYgSgKgiQgIgaAAgdQAAg2AZgjQAMgTAUgJQAQgHAUAAQAggBAXAWIAMgVIAHAAIAABHIgIAAQgPg7gugBQgkAAgPAhQgPAeAAAxQAAAtANAeQARAiAjAAQAXAAAPgPQAUgSABglIANAAQgBAcgJASQgLAUgSAKQgRAKgVgBQgcAAgWgQgAFLB8IAAg8IAIAAQADAPAFAKQAFALALAGQAJAHAMgBQARABAKgKQAJgKABgNQAAgNgLgIIgbgNIgagNQgYgNAAgYQAAgWAPgNQAPgNAXAAQATAAARALIAGgPIAFAAIAAA4IgHAAQgEgqggAAQgQAAgJAKQgJAJABALQgBAKAIAGQAEAFASAIIAWAKQARAIAIAIQALAKAAATQAAAVgPAPQgPAPgaAAQgXAAgTgPIgIAQgADBB8IAAg8IAHAAQADAPAFAKQAFALAKAGQALAHAMgBQAPABALgKQAKgKAAgNQAAgNgMgIIgagNIgZgNQgYgNAAgYQgBgWAQgNQAPgNAWAAQATAAARALIAFgPIAGAAIAAA4IgHAAQgFgqggAAQgPAAgKAKQgHAJgBALQABAKAGAGQAGAFARAIIAWAKQARAIAIAIQALAKAAATQAAAVgOAPQgQAPgaAAQgXAAgTgPIgJAQgAHdB1QgFgGAAgIQAAgJAFgGQAHgGAIAAQAIAAAFAGQAHAGgBAJQABAIgHAGQgFAGgIAAQgJAAgGgGgAAxBvQgOgOgBgUQAAghAogQQAXgKAcgEIAAgUQAAgTgEgHQgIgKgQAAQgOAAgJAHQgGAFAAAIIAAADIAAAGQAAAPgOAAQgMAAAAgMQABgQAPgNQARgNAYAAQASgBANAIQARAJAEATQACAIAAAPIAABJQAAASADAHQADAHAIAAIAJAAIAAAJQgMADgHgBQgQABgGgMQgEgHgBgMQgIANgGAGQgMAMgVAAQgVAAgNgMgABXAkQgZAMAAAbQAAAQAJAJQAHAHANABQAXAAAIgWQAEgKgBgVIAAggQgXAFgPAIgAgOB3IgoACIAAgHQANAAAFgDQAGgCABgGIAAgJIAAi0QAAgKgBgFQgDgFgJgBIgLAAIAAgGQAbgDAZgHIAADZQAAAKABADQAFAGATABIAAAHIgmgCgAn/B4IAAgJQAPgBAGgCQAHgEABgHIABgKIAAitQAAgLgDgEQgEgIgXgBIAAgJICYAAIAGA2IgIAAQgFgYgIgJQgJgKgTAAIgyAAIAABiIAxAAQAKAAAEgDQAHgFABgVIAIAAIAABFIgIAAQgBgPgFgIQgEgGgNAAIgwAAIAABWQAAALABADQAEAIASAAIAZAAQAUAAAJgIQAMgLAGgcIAIAAIgIA6gAlWAfIAAgQIBZAAIAAAQg");
	this.shape.setTransform(62.35,-8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(11.2,-20.4,102.3,24.9);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.logo();
	this.instance.setTransform(9,-8,0.165,0.165);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:true},1).wait(1).to({_off:false},0).wait(262).to({_off:true},1).wait(931));

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AmHFVIAAqoIMPAAIAAKog");
	this.shape.setTransform(24.85,10.55);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(12).to({_off:true},1).wait(1).to({_off:false},0).wait(262).to({_off:true},1).wait(931));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.3,-23.5,78.39999999999999,68.1);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjPBcIAAhuIgBgVIgBgJIAOAAQABAFABAJQAKgRARAAQAOAAAKAJQAPAPAAAcQAAAbgOAPQgJAKgPAAQgRAAgLgQIAAA3gAi4gdQgJAMAAASQAAASAIAMQAIAJAKAAQALAAAGgHQAIgMAAgUQAAgUgJgLQgGgIgKAAQgLAAgGAJgAKbAtQgLgIABgSIANAAQADAWAUAAQAJAAAFgFQAHgEAAgJQAAgHgHgFIgVgIQgPgDgFgGQgGgHAAgKQAAgNAKgIQAJgHAOAAQAUAAAJANQAEAGABAMIgOAAQgBgJgEgEQgFgGgKABQgJgBgFAFQgFAEABAGQgBAHAFADQAEADAOAEQAOAFAGACQAMAHAAAPQAAAOgJAIQgKAJgQAAQgSAAgJgIgAJCAtQgLgIAAgSIAOAAQACAWAVAAQAIAAAGgFQAGgEAAgJQAAgHgGgFIgVgIQgPgDgFgGQgHgHAAgKQAAgNAKgIQAKgHAOAAQAUAAAIANQAFAGAAAMIgNAAQgBgJgFgEQgFgGgJABQgJgBgGAFQgEAEAAAGQAAAHAEADQAEADAOAEQAPAFAFACQAMAHAAAPQAAAOgIAIQgKAJgRAAQgRAAgJgIgAHgAuQgLgHABgOQgBgWAXgIQANgEAXgFIAAgDQAAgLgDgEQgEgHgMABQgTAAgDAQIgOAAQACgMAGgIQALgJARAAQAPAAAKAHQAHAGABAMIABAOIAAAlQAAARACAJIgNAAIgDgOQgIAQgUAAQgNAAgIgHgAHyAFQgOAHAAAMQAAAHAGAFQAFAFAIAAQAPAAAHgMQADgHAAgPIAAgJQgUADgKAEgAE/AjQgQgUgBghQABgmATgVQAPgOAWAAQALAAAKAEQAJAFAGAIQAHAJACAPIgOAAQgGgbgaAAQgRAAgLAOQgLARAAAcQAAAcANAQQAKANARAAQATAAAJgQQAEgIABgMIAPAAQgCASgHAMQgNAUgZAAQgaAAgPgSgAADAuQgJgHABgOQgBgWAWgIQANgEAXgFIAAgDQAAgLgDgEQgEgHgMABQgTAAgDAQIgNAAQACgMAFgIQALgJARAAQAPAAAKAHQAHAGABAMIAAAOIAAAlQAAARADAJIgNAAIgCgOQgJAQgUAAQgNAAgJgHgAAWAFQgNAHAAAMQgBAHAGAFQAFAFAIAAQAPAAAGgMQAEgHAAgPIAAgJQgVADgJAEgAn9AuQgKgHABgOQgBgWAXgIQANgEAXgFIAAgDQAAgLgDgEQgEgHgMABQgTAAgDAQIgOAAQACgMAGgIQALgJARAAQAPAAAJAHQAIAGABAMIAAAOIAAAlQAAARADAJIgNAAIgCgOQgJAQgUAAQgNAAgJgHgAnqAFQgNAHAAAMQgBAHAGAFQAFAFAIAAQAPAAAGgMQAEgHAAgPIAAgJQgVADgJAEgAGuAzIAAiMIAPAAIAACMgACWAzIAAiMIBMAAIAAAOIg9AAIAAAvIA4AAIAAAOIg4AAIAAAzIA+AAIAAAOgAgsAzIAAg4QAAgRgDgGQgFgJgMAAQgNAAgIALQgEAIAAAPIAAA2IgOAAIAAiMIAOAAIAAA1QALgPARAAQALAAAIAFQAIAGADAMQACAFgBARIAAA5gAkuAzIAAg8IAAgNQgCgPgRAAQgNAAgGAKQgEAHAAAMIAAA7IgOAAIAAg6QAAgRgDgEQgEgKgMABQgGgBgGADQgFADgDAFQgEAHAAANIAAA6IgOAAIAAhEIgBgVIgCgKIAPAAQACAGAAAHQAJgQATAAQATAAAHARQALgRATAAQATAAAGANQADAGABAJIABAOIAAA8gAotAzIAAg4QAAgRgDgGQgFgJgMAAQgNAAgIALQgEAIAAAPIAAA2IgOAAIAAiMIAOAAIAAA1QALgPARAAQALAAAIAFQAIAGADAMQACAFgBARIAAA5gAqNAzIg7hJIA4hDIASAAIg4BCIA9BKgArXAzIAAiMIAPAAIAABDIAABJgADsADIAAgKIA4AAIAAAKgArIgWgAAWhAIARgXIAPAAIgWAXgAnqhAIARgXIAPAAIgWAXg");
	this.shape.setTransform(37,7.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0066CC").s().p("As4C1IAAlpIZxAAIAAFpg");
	this.shape_1.setTransform(37.6606,6.7294,1.1034,1.0011);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-53.3,-11.4,182,36.3);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AE8CCQgMAAgSACIAAgGQAJAAAEgCQAFgCABgFIAAgHIAAiTQAAgMgFgEQgDgCgLAAIAAgFQAUgBAPgEQADAIABARQAMgYAWAAQAXAAAOATQAPAUAAAfQAAAegOAUQgOAUgXABQgOAAgJgJQgFgFgFgJIAAA4QAAAIABADQAEAEAOABIAAAGQgSgCgMAAgAFSgvQgLAOAAAlQAABBAfAAQAegBAAg9QAAhAgfABQgLAAgIAJgAmnBAQgSgOgIgcQgGgUAAgXQAAgsATgcQAKgPAPgIQANgGAQAAQAZAAARARIAKgQIAFAAIAAA5IgHAAQgLgxgkABQgbAAgNAZQgMAZAAAoQAAAkALAYQANAbAcAAQARAAANgNQAOgNACgeIAKAAQgBAWgIAPQgHAPgPAJQgNAIgQAAQgWAAgSgOgAKdAzQgFALgGAFQgLAJgPABQgWAAgLgRQgHgKAAgWIAAhBQAAgJgCgDQgCgEgHgBIgIAAIAAgFQAVgCAUgGIAABgQAAARAEAHQAGALAOgBQAQAAAHgMQAFgIAAgSIAAg+QAAgJgBgDQgDgEgGgBIgJAAIAAgFQAVgCAUgGIAAB1QAAAIACACQACAEAHAAIAJAAIAAAGQgWACgPAFQgCgIAAgSgApHAzQgGALgFAFQgLAKgPAAQgWAAgLgRQgHgKAAgWIAAhBQAAgJgCgDQgCgFgPAAIAAgFQAVgCAUgGIAABgQAAARAEAHQAGAKAOAAQAPAAAIgMQAFgIAAgSIAAg+QAAgJgBgDQgDgFgPAAIAAgFQAVgCAUgGIAAAJQAIgKAAgIIgDAAQgKgDACgLQACgKAKAAQANAAAAAOQAAANgNAPIgEAGIgFAFIAABhQAAAHACADQACADAHABIAJAAIAAAGQgVACgQAFQgCgIAAgSgALfBHQgEgEAAgHQAAgHAEgEQAFgGAGAAQAGAAAFAGQAFAEAAAHQAAAHgFAEQgFAFgGABQgGgBgFgFgArkA8QgDgGAAgLIgBgOIAAhRIgRAAIAAgIIAMgDQAQgJAFgfIAHAAIAAApIAfAAIAAAKIgfAAIAABUQAAASACAGQAEAJAKAAQAHAAALgGIAAAJQgOAJgNAAQgUAAgGgRgAIUBJQgMAAgRACIAAgGQAIAAAEgCQAFgDAAgDIABgHIAAhGQAAgSgEgGQgGgMgOAAQgPAAgIANQgGAHAAARIAABFQAAAGACADQADAGANAAIAAAGQgRgCgMAAQgMAAgSACIAAgGQAKgBAEgBQAEgCABgFIABgHIAAiRQAAgIgCgDQgCgFgHgBIgJAAIAAgFQAWgCATgFIAABMQANgUAWABQAWAAALASQAHAKAAAVIAABEQAAAIABACQAEAGAOAAIAAAGQgSgCgMAAgACwBJQgMAAgRACIAAgGQAIAAAEgCQAFgDAAgDIABgHIAAhGQAAgSgEgGQgGgMgOAAQgPAAgIANQgGAHAAARIAABFQAAAGACADQADAGANAAIAAAGQgRgCgMAAQgMAAgSACIAAgGQAKgBAEgBQAEgCABgFIABgHIAAiRQAAgIgCgDQgCgFgHgBIgJAAIAAgFQAWgCATgFIAABMQANgUAWABQAWAAALASQAHAKAAAVIAABEQAAAIABACQAEAGAOAAIAAAGQgSgCgMAAgAAdBJQgMAAgRACIAAgGQAIAAAEgCQAEgDABgDIAAgHIAAhGQAAgSgEgGQgGgMgNAAQgOAAgJANQgFAHAAARIAABFIABAJQAEAGANAAIAAAGQgSgCgMAAQgLAAgSACIAAgGQAJgBAEgBQAFgCABgFIAAgHIAAhZIAAgJQgBgHgHgBIgLgBIAAgEQAXgEANgFQACAIABARQAOgXAWABQAWAAALARQAGALAAAVIAABEQAAAIACACQADAGAPAAIAAAGQgSgCgMAAgAh5BJIgeACIAAgGQAJgBAFgBQAEgCABgFIAAgHIAAhaQAAgJgBgDQgCgEgHgBIgJAAIAAgFQAWgCATgGIAAB4QAAAIACACQADAGAPAAIAAAGIgfgCgAjDBJQgMAAgRACIAAgGQAIAAAEgCQAFgDAAgDIABgHIAAhGQAAgSgEgGQgGgMgOAAQgPAAgIANQgGAHAAARIAABFQAAAGACADQADAGANAAIAAAGQgRgCgMAAQgMAAgSACIAAgGQAKgBAEgBQAEgCABgFIABgHIAAiRQAAgIgCgDQgCgFgHgBIgJAAIAAgFQAWgCATgFIAABMQANgUAWABQAWAAALASQAHAKAAAVIAABEQAAAIABACQAEAGAOAAIAAAGQgSgCgMAAgAJ5hRQABgGABgDQADgFAFgFQAGgHAAgGQAAgLgKAAQgNAAgBAPIgFAAQAAgOALgFQAEgDAHAAQAIAAAFAEQAHAFAAAIQAAAIgGAGIgFAEIgHAGQgEAEgBAFgAiHhVIAWgkIAWAAIgmAkgApYhVIgmgkIAWAAIAXAkg");
	this.shape.setTransform(76.175,13.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,152.4,26.4);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ABmCLQgLAAgQACIAAgFQAJgBADgCQAEgCABgEIAAgHIAAiUQAAgMgEgDQgDgCgKgBIAAgFQASgBANgEQACAJABAQQALgYATAAQATAAANAUQAMAUAAAeQAAAegMAUQgMAVgTAAQgNAAgHgJQgEgEgFgKIAAA5QAAAHABADQADAFANABIAAAFQgQgCgKAAgAB5gmQgKAOAAAlQAABBAbAAQAZAAAAg+QAAg/gbAAQgJAAgGAJgASNCIQgEgEAAgGQAAgGAEgDQADgEAEAAQAFAAADAEQADADAAAGQAAAFgDAEQgDAEgFAAQgEAAgDgDgAgxCIQgDgEAAgGQAAgGADgDQADgEAFAAQAEAAADAEQADADAAAGQAAAFgDAEQgDAEgEAAQgFAAgDgDgArXCIQgDgEAAgGQAAgGADgDQADgEAFAAQAEAAADAEQADADAAAGQAAAFgDAEQgDAEgEAAQgFAAgDgDgAP+BXIAAiqIgBgLQgCgEgGgBIgIgBIAAgFQATgCARgFIAABPQAEgJAEgEQAIgJAMAAQAUAAAMAUQAMAUAAAeQAAAfgNAUQgMAUgUAAQgUAAgKgZIgKAagAQfgqQgGAFgDAJQgGARAAAcQAAAaAFAQQADAJAHAFQAFAFAGAAQALAAAHgLQAJgPAAglQAAg+gaAAQgHAAgFAFgALwBAQgLgUAAgdQAAgcALgUQANgXAXAAQAPAAAKALQAHgKAAgJIAAAAIgCAAQgJgDACgLQACgKAIAAQAMAAgBAOQAAANgLAPIgCADIgCACQAPAVAAAiQAAAdgLAUQgMAYgWAAQgWAAgNgXgAMDgmQgKAPAAAmQAABAAZAAQAbAAAAhAQAAhAgaAAQgKAAgGALgAryBAQgKgUAAgdQAAgcALgUQANgXAXAAQAPAAAKALQAHgKAAgJIgBAAIgBAAQgKgDACgLQACgKAJAAQALAAAAAOQAAANgLAPIgCADIgCACQAPAVAAAiQAAAdgLAUQgNAYgWAAQgWAAgNgXgArfgmQgKAPAAAmQAABAAaAAQAaAAAAhAQAAhAgaAAQgJAAgHALgANgBCQgNgTAAgfQAAghAOgUQANgTAUAAQAOAAAKAMIAGgPIAEAAIAAAwIgFAAQgCgNgEgIQgDgHgGgFQgGgEgGAAQgPAAgHATQgGASAAAbQAAA9AbAAQAWAAAEgmIAKAAQgCAQgFAKQgKAVgVAAQgUAAgNgUgAK0A8QgFALgEAFQgJAKgOAAQgTAAgKgRQgGgKAAgWIAAhBIgBgMQgCgFgNAAIAAgFQASgCARgGIAABgQAAARAEAIQAFAJANAAQANAAAGgMQAFgIAAgSIAAg+QAAgIgCgEQgCgFgNAAIAAgFQASgCARgGIAAAJQAIgJAAgJIgDAAQgJgCACgMQACgKAIAAQAMAAgBAOQAAANgKAPIgEAGIgFAFIAABhQAAAHACADQACADAGABIAIAAIAAAGQgTACgOAFIgBgagAhJBDQgMgUAAggQAAgfAMgUQANgUAUAAQARAAALANQAOARAAAlIhEAAIgBAHQAAAYAHARQAHARARAAQASAAAHgSQAEgIABgLIAIAAQgBAQgGAMQgLATgWAAQgWAAgNgTgAhCABIAzAAQgCgxgXAAQgXAAgDAxgAw7BBQgMgUAAgeQAAgfANgUQANgUAVAAQAVAAAMAVQALAUAAAdQAAAfgMAUQgMAVgVAAQgVAAgNgVgAwpgmQgKAPAAAmQAABAAaAAQAKAAAHgLQAJgQAAglQAAhAgaAAQgKAAgGALgAR1BMQgKgLAAgQQAAgaAbgOQAPgIAUgCIAAgRQAAgPgEgGQgFgJgLAAQgJAAgGAHQgEAEAAAGIAAADIAAAEQAAANgKAAQgHAAAAgKQAAgNAKgKQAMgLAQAAQAMAAAJAGQALAHADAPQABAHAAAMIAAA7QAAANACAHQACAGAGAAIAGgBIAAAHQgIACgGAAQgKAAgEgJQgDgFgBgLQgEALgFAFQgIAKgOAAQgOAAgJgKgASOAPQgQAKAAAWQAAAMAGAIQAFAGAJAAQAPAAAFgRQADgIAAgRIAAgaQgQAEgLAGgAHTBFQgCgGAAgKIAAgPIAAhQIgPAAIAAgJIAKgDQANgIAFggIAGAAIAAApIAbAAIAAALIgbAAIAABTQAAASACAGQADAJAJAAQAGAAAJgGIAAAJQgMAJgLAAQgRAAgGgRgAnJA8QgNgcAAgpQAAgvAOgbQAMgYAYAAQAOAAAMALQALALAGAcQAFAVAAAaQAAAngLAcQgMAdgaAAQgYAAgMgagAm2hXQgMAUAAA6QAAAnAIAZQADAKAGAGQAFAGAHAAQAdAAAAhXQAAgrgHgXQgHgXgPAAQgJAAgIAMgApGBCQgGgLgBgRIAIAAQABAMAEAGQAHAPAQAAQARAAAKgRQAIgOAAgWQAAgWgJgNQgIgOgPAAQgTAAgKAWIgHgBIANhfIBEAAIgCAUIg9AAIgIA4QANgQATAAQAVAAAMARQANASAAAbQAAAcgNATQgNAWgYAAQgYAAgKgUgAuPBFQgCgGgBgKIAAgPIAAhQIgPAAIAAgJIALgDQANgIAEggIAGAAIAAApIAcAAIAAALIgcAAIAABTQAAASACAGQADAJAJAAQAGAAAKgGIAAAJQgMAJgLAAQgRAAgGgRgAkXBHQgHgNAAgTQAAgVAIgMQAJgNAOAAQAOAAAIANQAIANAAATQAAAUgIANQgIAOgPAAQgOAAgJgOgAkNAMQgDAKAAARQAAAnAQAAQARAAAAgnQAAgngRAAQgJAAgEAMgAIlBSQgKAAgQACIAAgGQAIAAAEgCQAEgCABgFIAAgGIAAhZIAAgLQgBgHgGgBIgKAAIAAgFQATgDAMgEQACAOAAANQADgIAFgHQAIgLAMAAQAKAAAFAHQAFAHAAAJQAAAGgCAEQgDAEgFAAQgEAAgCgCQgDgDAAgEIABgHIAAgCQAAgDgCgCQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAQgLAAgGASQgDALAAARIAAA9QAAAHABADQADAFANAAIAAAGQgRgCgKAAgAFgBSIgaACIAAgGQAIAAAEgCQAEgCABgFIAAgGIAAhbQAAgIgBgEQgCgEgGgBIgIAAIAAgFQATgCARgGIAAB5QAAAHABADQADAFANAAIAAAGIgbgCgAEhBSQgLAAgPACIAAgGQAHAAAEgCQAEgCAAgEIABgHIAAhGQAAgRgEgHQgFgLgMAAQgNAAgHAMQgFAHAAARIAABFQAAAHACACQADAGALAAIAAAGQgPgCgLAAQgKAAgPACIAAgGQAIAAAEgCQADgCABgFIABgGIAAiSQAAgIgCgDQgCgEgGgBIgHgBIAAgFQASgCARgFIAABMQAMgTASAAQATAAAKASQAFAKAAAVIAABFQAAAHACADQADAFAMAAIAAAGQgPgCgKAAgAh+BSIgaACIAAgGQAIAAAEgCQADgCABgFIABgGIAAiSQAAgIgCgDQgCgEgGgBIgHgBIAAgFQASgCARgFIAACvQAAAHACADQADAFAMAAIAAAGIgagCgAs+BSQgKAAgQACIAAgGQAIAAAEgCQAEgCABgFIAAgGIAAhZIAAgLQgBgHgGgBIgKAAIAAgFQATgDAMgEQACAOAAANQADgIAFgHQAIgLAMAAQAKAAAFAHQAFAHAAAJQAAAGgCAEQgDAEgFAAQgEAAgCgCQgDgDAAgEIABgHIAAgCQAAgDgCgCQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAQgLAAgGASQgDALAAARIAAA9QAAAHABADQADAFANAAIAAAGQgRgCgKAAgAxvBSQgKAAgPACIAAgGQAHAAADgCQAEgCABgEIAAgHIAAhGQAAgRgDgHQgGgLgMAAQgMAAgHAMQgFAHAAARIAABFQAAAHABACQADAGALAAIAAAGQgPgCgKAAQgKAAgQACIAAgGQAIAAAEgCQAEgCABgFIAAgGIAAiSQAAgIgBgDQgCgEgGgBIgHgBIAAgFQASgCARgFIAABMQALgTATAAQATAAAJASQAGAKAAAVIAABFQAAAHABADQADAFANAAIAAAGQgQgCgKAAgAlTBTIBbjAIAKAAIhcDAgAlYggQgIgNAAgTQAAgUAIgNQAJgOAPAAQANAAAIAOQAIANAAATQAAAUgIANQgIAOgOAAQgPAAgIgOgAlPhbQgDAKAAARQAAAnARAAQAQAAAAgnQAAgogQAAQgKAAgEANgAgShGIgWgWIgWAWIgHAAIAYgiIALAAIAXAigAwEhGIgWgWIgWAWIgHAAIAYgiIALAAIAXAigAFUhMIATgkIATAAIggAkgAMIhNIATgkIATAAIggAkgAwZh7QgGgFgEAAQgHAAgFANIgEgCQADgLAEgGQAFgGAGAAQAHAAAHAGQAJAIAFAAQAGAAAEgNIAEABQgCAMgFAGQgEAGgGAAQgHAAgKgJg");
	this.shape.setTransform(122.675,14.0982);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,245.4,28.2);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AwCBrIAAg/IAHAAQAIA0AoAAQARAAALgMQAKgLAAgPQAAgSgNgKQgGgFgUgLQgfgPgHgIQgNgMAAgVQAAgXAPgOQAOgOAXAAQAVAAAPAPIAIgQIAFAAIAAA2IgGAAQgEgQgFgKQgLgSgVAAQgPAAgKALQgJAKAAAPQAAAQAPAKIAbAPQAWALAJAHQARAOAAAZQAAAYgQAQQgPAPgYAAQgYAAgTgRIgKATgANUBTQgMgUAAgdQAAgdANgTQAPgXAbAAQARAAAMALQAIgKAAgJIAAAAIgCAAQgLgDACgLQACgKAKAAQAOAAgBAOQAAANgNAPIgCADIgCACQARAVAAAiQAAAdgNAUQgOAYgaAAQgaAAgPgXgANqgTQgLAPAAAmQAABAAeAAQAeAAAAhAQAAhAgeAAQgLAAgIALgAL3BqIgLgfIgghbQgDgJgFgCQgEgBgIgBIAAgGIAdACIAcgCIAAAGIgIABQgHABAAAFIACAHIAdBXIAehXIACgIQAAgEgFgBIgJgBIAAgGIAVACIAVgCIAAAGQgJABgEACQgEACgDAJIggBZIgLAggAINBqIAAgxIAGAAQADANADAHQAFAJAIAFQAHAFAKAAQANAAAIgIQAHgHAAgLQAAgLgJgGQgEgDgQgIIgUgKQgTgKAAgVQAAgQAMgKQAMgLARAAQAPAAANAJIAFgMIAFAAIAAAsIgGAAQgEghgZAAQgMAAgIAIQgGAHAAAJQAAAHAGAGQAEAEANAGIASAIQANAHAGAGQAJAJAAAOQAAARgLAMQgNANgUAAQgSAAgPgMIgHANgAGZBqIAAgxIAGAAQACANAEAHQAEAJAIAFQAIAFAJAAQANAAAIgIQAIgHAAgLQAAgLgJgGQgFgDgPgIIgVgKQgSgKAAgVQAAgQALgKQAMgLASAAQAPAAANAJIAEgMIAFAAIAAAsIgGAAQgDghgaAAQgMAAgHAIQgHAHAAAJQAAAHAGAGQAEAEAOAGIARAIQAOAHAGAGQAIAJAAAOQAAARgLAMQgMANgVAAQgSAAgPgMIgGANgABKBcQgSgOgIgcQgHgUAAgYQAAgrAUgcQAKgPAPgHQANgHAQAAQAZAAASASIAJgRIAFAAIAAA5IgGAAQgLgwglAAQgbAAgNAaQgMAZAAAmQAAAlALAYQANAbAcAAQARAAANgMQAPgOACgeIAKAAQgBAWgIAQQgIAPgOAIQgOAIgQAAQgWAAgSgOgAtsBTQgNgUAAgdQAAgdANgTQAPgXAbAAQASAAALALQAJgKAAgJIgBAAIgCAAQgLgDADgLQACgKAKAAQANAAAAAOQAAANgNAPIgCADIgDACQASAVAAAiQAAAdgNAUQgPAYgaAAQgZAAgPgXgAtWgTQgMAPAAAmQAABAAeAAQAfAAAAhAQAAhAgfAAQgKAAgIALgAkxBPQgGALgFAFQgLAKgQAAQgWAAgLgRQgHgKAAgVIAAhCQAAgIgCgEQgCgEgHgBIgIAAIAAgFQAVgCAUgGIAABgQAAARAEAIQAHAKAOAAQAPAAAIgNQAFgIAAgSIAAg+QAAgIgCgEQgCgEgHgBIgJAAIAAgFQAWgCAUgGIAAB1QAAAIABACQADAEAHAAIAJAAIAAAGQgWACgQAFIgBgagAnFBPQgGALgFAFQgLAKgQAAQgWAAgLgRQgHgKAAgWIAAhBQAAgIgCgEQgCgFgPAAIAAgFQAVgCAUgGIAABgQAAARAEAIQAGAJAPAAQAPAAAIgMQAFgIAAgSIAAg+QAAgIgCgEQgCgFgQAAIAAgFQAWgCAUgGIAAAJQAIgJAAgJIgDAAQgKgCACgMQACgKAKAAQANAAAAAOQAAANgNAPIgEAGIgFAFIAABhQAAAHABADQADADAHABIAJAAIAAAGQgWACgQAFQgBgIAAgSgAEgBfQgLgLAAgQQAAgaAfgOQASgIAXgDIAAgRQAAgOgFgGQgFgJgNAAQgLAAgHAHQgFAEAAAGIAAADIAAAEQAAAMgLAAQgJAAAAgJQAAgNAMgKQAOgLATAAQANAAALAGQANAHAEAPQABAHAAALIAAA8QAAANACAHQACAGAHAAIAHgBIAAAHQgJACgGAAQgMAAgFgJQgDgFgBgLQgGALgFAFQgKAKgQAAQgRAAgKgKgAE+AiQgTAKAAAWQAAAMAGAIQAGAGALAAQARAAAHgRQADgIAAgRIAAgaQgTAEgMAGgAPkBlIgfACIAAgGQAKAAAEgCQAFgCABgFIAAgGIAAhbQAAgIgCgEQgCgEgHgBIgIAAIAAgFQAWgCATgGIAAB5QAAAHACADQADAFAPAAIAAAGIgfgCgADmBlIgfACIAAgGQAKAAAEgCQAFgCABgFIAAgGIAAiSQAAgIgCgDQgCgEgHgBIgIgBIAAgFQAVgCAUgFIAACvQAAAHACADQADAFAPAAIAAAGIgfgCgApPBlQgMAAgSACIAAgGQAJAAAEgCQAEgCABgEIABgHIAAhHQAAgQgFgHQgGgLgOAAQgOAAgJAMQgFAHAAAQIAABGQAAAHABACQAEAGANAAIAAAGQgSgCgMAAQgMAAgSACIAAgGQAKAAAEgCQAEgCABgFIABgGIAAiSQAAgIgCgDQgCgEgHgBIgJgBIAAgFQAWgCAUgFIAABMQANgTAWAAQAWAAALASQAHAKAAAUIAABGQAAAHABADQADAFAPAAIAAAGQgSgCgMAAgAi2BmIAAgHQALgBAFgCQAFgCABgGIABgIIAAiMQAAgJgCgDQgEgGgRgBIAAgHIB3AAIAFArIgGAAQgFgTgGgHQgHgIgPAAIgnAAIAABPIAnAAQAIAAACgCQAFgFABgRIAHAAIAAA4IgHAAQAAgNgEgFQgDgGgKAAIgmAAIAABGQAAAIABACQADAHAOAAIAUAAQAPAAAHgGQAKgJAFgWIAGAAIgGAugAgqAfIAAgNIBGAAIAAANgAtKg3QABgHABgCQADgFAFgGQAGgHAAgGQAAgKgKAAQgNAAgBAOIgFAAQAAgOAKgFQAFgDAHAAQAIAAAFAEQAHAFAAAJQAAAIgGAFIgFAFIgIAGQgDAEgBAFgAPZg/QgFgFAAgGQAAgHAFgFQAEgEAGAAQAGAAAFAEQAEAFAAAHQAAAGgEAFQgEAFgHAAQgGAAgEgFgANwg6IAXgkIAWAAIgmAkgAnnhJQgGgFgGAAQgIAAgFANIgFgCQADgMAEgFQAGgGAIAAQAIAAAIAGQAKAIAGAAQAIgBAEgNIAFACQgCALgGAHQgFAFgHABQgIAAgMgJg");
	this.shape.setTransform(102.675,10.675);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,205.4,21.4);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg2();
	this.instance.setTransform(0,0,0.6452,0.6452);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,606.5);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg1();
	this.instance.setTransform(0,-5,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-5,300,610);


(lib.Symbol31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.instance = new lib.Symbol33("synched",0);
	this.instance.setTransform(150.4,39.5,1,1,0,0,0,124.4,10.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:123.1,alpha:1},11,cjs.Ease.get(1)).to({x:124.4},11,cjs.Ease.get(1)).wait(37).to({startPosition:0},0).to({_off:true},1).wait(1595));

	// Layer_1
	this.instance_1 = new lib.Symbol32("synched",0);
	this.instance_1.setTransform(98.9,11.45,1,1,0,0,0,108.6,11.2);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:126.2,alpha:1},11,cjs.Ease.get(1)).to({x:124.9},11,cjs.Ease.get(1)).wait(37).to({startPosition:0},0).to({_off:true},1).wait(1595));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.7,-9.2,289.8,56.3);


(lib.Symbol27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.instance = new lib.Symbol28("synched",0);
	this.instance.setTransform(73,34.75,0.4,0.4,0,0,0,62.3,8.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:8.3,scaleX:1.05,scaleY:1.05,x:73.05,y:7.15,alpha:1},9,cjs.Ease.get(1)).to({regX:62.2,scaleX:1,scaleY:1,x:73,y:8.8},9,cjs.Ease.get(1)).wait(243).to({startPosition:0},0).to({_off:true},1).wait(1106));

	// Layer_1
	this.instance_1 = new lib.Symbol29("synched",0);
	this.instance_1.setTransform(73.5,50.55,0.4,0.4,0,0,0,73.5,8.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(5).to({_off:false},0).to({regX:73.4,regY:8.6,scaleX:1.05,scaleY:1.05,y:35.1,alpha:1},9,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,y:36.5},9,cjs.Ease.get(1)).wait(238).to({startPosition:0},0).to({_off:true},1).wait(1106));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-25.6,-23,198.9,80.9);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Au4C+IAAl7IdxAAIAAF7g");
	mask.setTransform(38.45,13.825);

	// Layer_2
	this.instance = new lib.Tween3("synched",0);
	this.instance.setTransform(-81.8,4.45,1.3691,1.8299,0,0,0,-0.3,0.1);

	this.instance_1 = new lib.Tween4("synched",0);
	this.instance_1.setTransform(167.25,11.85,1.5945,2.1152);

	var maskedShapeInstanceList = [this.instance,this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},23).wait(67));
	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true,regX:0,regY:0,scaleX:1.5945,scaleY:2.1152,x:167.25,y:11.85},23,cjs.Ease.get(1)).wait(67));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.8,-5.1,190.60000000000002,37.9);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.setTransform(43.35,7.65,0.4,0.4,0,0,0,43.4,7.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:7.6,scaleX:1.1,scaleY:1.1,x:43.4,y:7.6,alpha:1},11,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(15).to({startPosition:0},0).to({_off:true},1).wait(1928));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63,-13.3,200.3,39.900000000000006);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.instance = new lib.Symbol6("synched",0);
	this.instance.setTransform(105.45,110.85,1,1,0,0,0,76.2,13.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).to({y:89.35,alpha:1},11,cjs.Ease.get(1)).to({y:90.85},10,cjs.Ease.get(1)).wait(140).to({startPosition:0},0).to({_off:true},1).wait(1014));

	// Layer_2
	this.instance_1 = new lib.Symbol5("synched",0);
	this.instance_1.setTransform(105.1,75.3,1,1,0,0,0,122.7,14.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({_off:false},0).to({y:53.8,alpha:1},11,cjs.Ease.get(1)).to({y:55.3},10,cjs.Ease.get(1)).wait(145).to({startPosition:0},0).to({_off:true},1).wait(1014));

	// Layer_1
	this.instance_2 = new lib.Symbol4("synched",0);
	this.instance_2.setTransform(106.2,38.1,1,1,0,0,0,102.7,10.7);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:16.6,alpha:1},11,cjs.Ease.get(1)).to({y:18.1},10,cjs.Ease.get(1)).wait(149).to({startPosition:0},0).to({_off:true},1).wait(1014));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-17.6,5.9,245.4,118.19999999999999);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_275 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(275).call(this.frame_275).wait(1));

	// logo
	this.instance = new lib.Symbol13("synched",0);
	this.instance.setTransform(140.5,573.5,1,1,0,0,0,15.5,15.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1,startPosition:14},13,cjs.Ease.get(1)).wait(263));

	// Layer_12
	this.instance_1 = new lib.Symbol18();
	this.instance_1.setTransform(154.4,461.1,1,1,0,0,0,42.4,10.1);
	this.instance_1.alpha = 0.7695;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(274).to({_off:false},0).wait(2));

	// cta
	this.instance_2 = new lib.Symbol11("synched",0);
	this.instance_2.setTransform(156.55,466.1,1.05,1.05,0,0,0,43.4,7.7);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(239).to({_off:false},0).wait(37));

	// Layer_6
	this.instance_3 = new lib.Symbol31("synched",0);
	this.instance_3.setTransform(148.85,126.8,1,1,0,0,0,124.4,25.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(216).to({_off:false},0).wait(60));

	// Layer_5
	this.instance_4 = new lib.Symbol30("synched",0);
	this.instance_4.setTransform(150.55,298.95,1.2,1.2,0,0,0,152.5,300.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(199).to({_off:false},0).to({scaleX:1,scaleY:1,x:150.5,y:298.9,alpha:1},16,cjs.Ease.get(1)).wait(61));

	// Layer_10
	this.instance_5 = new lib.Symbol3("synched",0);
	this.instance_5.setTransform(149.8,91.2,1,1,0,0,0,105.8,18.2);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(105).to({_off:false},0).wait(171));

	// Layer_7
	this.instance_6 = new lib.Symbol2("synched",0);
	this.instance_6.setTransform(150,300.25,1.2,1.2,0,0,0,150,303.2);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(89).to({_off:false},0).to({scaleX:1,scaleY:1,y:300.2,alpha:1},16,cjs.Ease.get(1)).wait(171));

	// Layer_3
	this.instance_7 = new lib.Symbol27("synched",0);
	this.instance_7.setTransform(149,139.2,1,1,0,0,0,72,22.2);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(14).to({_off:false},0).wait(262));

	// Layer_8
	this.instance_8 = new lib.Symbol1("synched",0);
	this.instance_8.setTransform(150,299.85,1.2,1.2,0,0,0,150,299.9);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({regY:300,scaleX:1,scaleY:1,y:300,alpha:1},13,cjs.Ease.get(1)).wait(263));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37.2,-80.1,368.59999999999997,749.9);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(120.1,234.1,210.00000000000003,431.9);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg1.jpg?1700203754684", id:"bg1"},
		{src:"images/bg2.jpg?1700203754684", id:"bg2"},
		{src:"images/bg3.jpg?1700203754684", id:"bg3"},
		{src:"images/logo.png?1700203754684", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;