(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bg1 = function() {
	this.initialize(img.bg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,900,631);


(lib.bg2 = function() {
	this.initialize(img.bg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,900,633);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,200,200);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGwB0IgSABIAAgEIAIgBQADgCAAgDIABgEIAAgoIgGAJQgGAHgIAAQgOAAgIgPQgIgOAAgVQAAgUAIgNQAJgOANgBQAOAAAHARIACgRQAJADAMABIAAAEIgCAAQgGAAgCACQgBADAAAGIAABnIAAAGQACADAJABIAAAEIgSgBgAGMgGQgHAKAAAaQAAArASAAQATAAAAgsQAAgpgSAAQgHAAgFAGgAN7BuQgFgDgDgGQgCgGAAgGQAAgPAPgGQgDgCgCgCQgDgDAAgFQAAgLARgFQgGgDgEgEQgJgIAAgOQAAgNAIgIQAIgIANAAQAKAAAHAFIAVAAIAAAIIgPgBQAEAHAAAJQAAAQgLAIQgEAFgNAEIgLADQgGACAAAFQAAADADACIAMABQASACAHADQAHAEADAGQADAGAAAGQAAAHgDAFQgCAGgFAEQgKAIgPAAQgOAAgKgGgAN+BOQgHAFAAAHQAAAJAIAGQAIAFALAAQAMABAHgGQAHgFAAgJQAAgSgcAAQgLAAgHAFgAOHgHQgEAHAAALQAAAKADAHQAEAIAIAAQAIAAAEgIQADgHAAgLQAAgXgPAAQgHAAgEAGgALjBxQgCgDAAgEQAAgDACgDQACgCADgBQADABADACQACADAAADQAAAEgCADQgDACgDAAQgDAAgCgCgAu4BRIAAg6IAFAAQAGAxAfgBQAOAAAIgKQAHgKAAgPQAAgRgJgJQgFgEgPgJQgYgQgGgHQgKgMAAgSQAAgXAMgMQALgNARAAQAQAAAMAOIAGgPIAEAAIAAAyIgFAAQgCgPgFgJQgIgRgQAAQgMAAgHALQgIAJAAANQAAAQAMAJIAVAOQARALAHAHQANAMAAAWQAAAYgMAOQgMAOgSAAQgTAAgPgQIgIARgAgWBEQgOgNgGgaQgFgSAAgWQAAgpAPgbQAHgNANgHQAKgGALAAQATAAAOAQIAHgQIAEAAIAAA2IgFAAQgIgtgdAAQgUAAgKAYQgJAYAAAkQAAAiAJAWQAJAZAVAAQAOAAAKgLQALgNABgcIAIAAQgBAUgGAPQgGAOgLAIQgKAHgNAAQgQAAgOgNgAkKBEQgOgNgHgaQgFgTAAgWQAAgqAQgZQAPgaAbAAQATABAPAPIAIgQIAEAAIAAA2IgFAAQgDgQgFgIQgEgKgJgGQgIgGgJAAQgQAAgKAOQgPAUAAAzQAABVAoAAQAOAAAPgLIAAgtIgBgIQgDgFgNAAIAAgGIAZABIAYgBIAAAGQgJAAgDADQgDABAAADIAAAGIAAAsQgZAUgXgBQgSABgOgNgAmIA3QgEALgEAEQgIAKgNgBQgRAAgIgPQgGgJAAgUIAAg9QAAgIgBgDQgCgEgFgBIgHAAIAAgEQARgDAPgFIAABZQAAAQAEAIQAEAIALABQAMAAAGgMQAEgIAAgQIAAg6IgBgLQgCgEgFgBIgHAAIAAgEQARgDAPgFIAABtQAAAHACACQABAEAGAAIAHABIAAAEQgRADgMAEIgCgZgAtEA7QgKgSAAgbQAAgbAKgSQAMgVAVAAQANAAAKAKQAGgKAAgIIgBAAQAAAAAAAAQAAABgBAAQAAAAAAgBQAAAAAAAAQgIgCABgLQACgJAIAAQAKAAAAANQAAAMgKAOIgCADIgCADQAOASAAAhQAAAagKATQgLAWgVgBQgTABgMgWgAszgkQgJAPAAAjQAAA8AXgBQAYAAAAg6QAAg8gYAAQgIAAgGAJgAn7A3QgEALgEAFQgIAIgNAAQgRAAgIgPQgGgJAAgUIAAg9QAAgIgBgDQgCgFgMAAIAAgEQARgCAPgGIAABZQAAAQAEAIQAEAIALABQAMAAAGgMQAEgIAAgQIAAg6QAAgIgBgDQgCgFgMAAIAAgEQARgCAPgGIAAAJQAHgKAAgHIgCAAQgJgDACgKQACgJAIAAQAKAAAAAMQAAANgKAOIgEAFIgEAFIAABaQAAAHACACQABAEAGAAIAHABIAAAEQgRACgMAFIgCgZgACkBPIgGgUIgTg/QgCgGgDgBIgHgCIAAgEIARABIARgBIAAAEIgFABQgEAAAAADIABAGIARA7IASg7IABgGQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAgBAAIgFgBIAAgEIAMABIANgBIAAAEIgIACQgDABgBAHIgTA9IgHAVgALTBIQgHgIAAgLQAAgSASgKQALgEAOgDIAAgMQAAgJgDgEQgDgGgIAAQgGAAgFAEQgCADAAAFIAAABIAAACQAAAJgHAAQgFAAAAgGQAAgJAHgGQAIgJALAAQAIABAHAEQAHAFACAJQACAFAAAJIAAAoIABAOQABAFAEgBIAEgBIAAAGIgJACQgHgBgDgGQgCgEgBgHQgDAHgDAEQgGAHgJAAQgKAAgGgHgALkAeQgLAHAAAPQAAAJAEAEQADAFAHAAQAKAAAEgLQACgHAAgLIAAgRQgMACgHAEgAKkBEQgCgFAAgHIAAgKIAAg3IgKAAIAAgHQAEAAADgCQAJgFADgWIAEAAIAAAcIATAAIAAAIIgTAAIAAA5QAAANACADQACAHAGAAQAEAAAHgEIAAAFQgJAHgHAAQgMAAgEgLgAIrBIQgHgIAAgLQAAgSASgKQALgEAOgDIAAgMQAAgJgDgEQgDgGgIAAQgGAAgFAEQgCADAAAFIAAABIAAACQAAAJgHAAQgFAAAAgGQAAgJAHgGQAIgJALAAQAIABAHAEQAHAFACAJQACAFAAAJIAAAoIABAOQABAFAEgBIAEgBIAAAGIgJACQgHgBgDgGQgCgEgBgHQgDAHgDAEQgGAHgJAAQgKAAgGgHgAI8AeQgLAHAAAPQAAAJAEAEQADAFAHAAQAKAAAEgLQACgHAAgLIAAgRQgMACgHAEgAICA9QgDAHgDAEQgHAGgJABQgNgBgHgKQgEgIAAgPIAAgtIgBgIQgBgDgEAAIgFAAIAAgEQAMgBAMgEIAABCQAAAMADAFQAEAGAIABQAJAAAFgJQADgGAAgMIAAgrIgBgIQgCgDgEAAIgFAAIAAgEQANgBAMgEIAABRQAAAEABACQABACAEABIAGAAIAAAEQgOABgJAEIgBgSgADcA/QgIgNAAgUQAAgVAIgMQAJgQAQAAQAKAAAHAIQAFgHAAgGIAAgBIgBAAQgHgBABgIQACgHAGAAQAIAAgBAKQAAAJgHALIgCABIgBACQAKANAAAYQAAAUgHAOQgJAQgPAAQgPAAgJgQgADpgHQgHAKAAAbQAAAsASAAQASAAAAgsQAAgrgSAAQgHAAgEAGgApmBNQgJAAgOACIAAgGQAGAAAEgCQADgDABgEIAAgFIAAhCQAAgPgDgHQgFgKgLAAQgLAAgHALQgEAHAAAPIAABBIABAJQADAFAKAAIAAAGQgOgCgJAAQgJAAgOACIAAgGQAHAAAEgCQADgCABgFIAAgFIAAiIQAAgHgBgEQgCgDgFgBIgHAAIAAgGQARgBAPgGIAABHQAKgSARAAQARAAAJARQAFAKAAATIAABBIABAJQADAFALAAIAAAGQgOgCgJAAgANWBNIgSABIAAgFQAFAAADgBQACgBABgDIAAgFIAAgxQAAgMgCgDQgEgIgIAAQgJAAgFAIQgDAEAAAMIAAAwIABAHQACADAHAAIAAAFIgRgBIgSABIAAgFQAGAAACgBQADgBAAgDIABgFIAAg+IgBgGQAAgFgEAAIgHAAIAAgEQAOgCAIgEIABASQAJgQANgBQANAAAHANQAEAGAAAPIAAAwQAAAFABACQACADAJAAIAAAFIgSgBgAEyBNIgSABIAAgFQAFAAADgBQACgBABgDIAAgFIAAg/IgBgIQgBgDgEAAIgFAAIAAgEQANgBALgEIAABTIABAHQACADAJAAIAAAFIgSgBgAigBOIAAgHQAJgBAEgBQAEgDABgFIAAgIIAAiDQAAgIgBgDQgCgFgHAAIgIgCIAAgGIAbACIAbgCIAAAGQgJABgEACQgEACgBAGIAAAHIAACCQAAAIABACQACAGALABIAPAAQAKgBAFgDQAEgCAEgJQAEgHACgNIAFAAIgFAsgALfglQgFgGgCgKIADAAQADAIAEADQAFAEAFAAQAFAAAEgEQAFgEACgHIADAAQgBAKgFAGQgGAIgHAAQgIAAgFgIgAJIghIgWgYIANAAIANAYgADsghIAOgZIANAAIgXAZgAErglQgDgDAAgFQAAgEADgDQADgDADAAQAEAAACADQADADAAAEQAAAFgCADQgDADgEAAQgDAAgDgDgAsphFIABgJIAGgKQAFgFAAgGQAAgKgIAAQgKAAgBANIgEAAQAAgNAJgFQADgCAGAAQAGAAADADQAGAFAAAIQAAAHgFAGIgEAEIgFAFQgDAFgBAEgAoVhWQgFgEgEgBQgGAAgEAMIgEgBQACgLAEgFQAEgFAGAAQAHAAAFAFQAJAIAEgBQAGAAADgMIAEABQgBALgFAGQgEAFgFABQgGAAgKgJg");
	this.shape.setTransform(130.275,-255);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(35,-266.7,190.6,23.399999999999977);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg2();
	this.instance.parent = this;
	this.instance.setTransform(4,0,0.3333,0.3333);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4,0,300,211);


(lib.Symbol14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AT3BZQgFgDgCgFQgDgGAAgGQAAgOAOgGIgEgDQgEgEAAgEQAAgLAQgFQgFgCgEgEQgIgIAAgMQABgNAGgIQAHgIAMAAQAKAAAGAFIAUAAIAAAIIgPgBQAFAIAAAIQAAAOgKAJQgFADgLAEIgKAEQgFACgBAEQAAADADABIALACQARABAGAEQAGADADAGQADAFAAAGQAAAGgDAGQgCAGgEADQgJAIgPAAQgMAAgJgGgAT5A7QgGAEAAAIQAAAIAHAFQAHAFALAAQAKAAAHgFQAGgEABgJQAAgRgaAAQgKAAgHAFgAUCgVQgEAGgBALQAAAJAEAGQAEAIAHAAQAIAAADgIQADgGAAgJQAAgYgOAAQgHAAgDAHgARwBcQgCgDgBgDQABgEACgCQABgDADAAQADAAACADQACACAAAEQAAADgCADQgCACgDAAQgDAAgBgCgAldA8IgGgUIgSg7QgBgGgDgCIgGgBIAAgEIAQACIAOgCIAAAEIgDABQgFAAAAAEIABAEIAQA5IARg4IABgGQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAAAgBAAIgFgBIAAgEIAMABIALgBIAAAEIgHACQgDACgBAFIgRA6IgGAVgARfAuQgIgNAAgUQAAgUAIgNQAJgNANAAQANAAAIANQAHAOAAATQAAATgHAOQgIAOgOAAQgOAAgHgOgARqgWQgHAKAAAZQAAAqARAAQAHAAAEgIQAFgJAAgZQAAgpgQAAQgGAAgEAGgAO6AtQgHgNAAgTQAAgSAHgNQAIgPAPAAQAJAAAHAHQAFgHgBgFIAAgBIgBAAQgGgBACgIQAAgGAGAAQAHAAAAAJQAAAJgHAKIgBABIgCACQAKAOAAAWQAAASgHAOQgIAPgOAAQgOAAgIgPgAPGgWQgGAKgBAZQAAAqARAAQARAAAAgqQAAgpgRAAQgGAAgEAGgAF5AuQgHgNAAgUQAAgUAIgNQAJgNANAAQANAAAHANQAIAOAAATQAAATgIAOQgHAOgOAAQgOAAgIgOgAGFgWQgGAKgBAZQAAAqARAAQAGAAAFgIQAGgJAAgZQAAgpgRAAQgGAAgEAGgADxArIgGARIgFAAIAAhvIAAgHQgCgDgDAAIgFgBIAAgDQAMgBAKgEIAAA0QADgGADgDQAFgGAIAAQANAAAHAOQAIANAAATQgBAUgHANQgJAOgMAAQgNAAgGgRgAD7gYQgDADgCAGQgEAMAAARQABARADALQABAGAEADQAEADAEAAQAHAAAEgHQAGgKAAgYQAAgogRAAQgEAAgEADgApTAvQgHgNgBgVQABgUAHgNQAJgNANAAQAKAAAHAIQAKALAAAZIgsAAIAAAEQgBAQAFALQAFALAKAAQALAAAFgMQACgFABgHIAGAAQgBAKgFAIQgGANgOAAQgOAAgJgNgApOAEIAgAAQgBgggOAAQgPAAgCAggAs5AuQgHgNAAgUQgBgUAJgNQAIgNANAAQANAAAIANQAIAOgBATQABATgIAOQgIAOgOAAQgNAAgIgOgAstgWQgHAKAAAZQAAAqAQAAQAHAAAEgIQAGgJAAgZQAAgpgRAAQgFAAgEAGgAvCArIgGARIgFAAIAAhvIAAgHQgCgDgDAAIgFgBIAAgDQAMgBALgEIAAA0QADgGACgDQAFgGAIAAQANAAAHAOQAIANAAATQgBAUgHANQgJAOgMAAQgNAAgGgRgAu3gYQgEADgCAGQgEAMABARQAAARACALQACAGAFADQADADAEAAQAGAAAFgHQAGgKAAgYQAAgogQAAQgFAAgDADgAJZA1QgCgDAAgHQgDAHgDADQgGAGgIAAQgKAAgFgGQgGgHAAgLQAAgRARgJQAKgFAMgCIAAgLQAAgJgCgEQgEgGgHAAQgFAAgFAEQgCADAAAFIAAABIAAADQAAAIgGAAQgFAAAAgGQAAgJAHgGQAHgIALAAQAHAAAGAEQAHAFACAKIABANIAAAlIABANQABAEAEAAIADAAIAAAFIgIABQgHAAgCgGgAJEANQgKAHAAAOQAAAIADAFQADAEAGAAQAKAAAEgLQABgGAAgLIAAgQQgKACgHAEgAFYA1QgCgDgBgHQgDAHgCADQgGAGgJAAQgJAAgFgGQgHgHABgLQAAgRARgJQAJgFAMgCIAAgLQABgJgDgEQgDgGgHAAQgGAAgEAEQgDADAAAFIAAABIAAADQAAAIgFAAQgGAAAAgGQAAgJAIgGQAHgIAKAAQAIAAAFAEQAIAFABAKIACANIAAAlIABANQAAAEAEAAIAEAAIAAAFIgIABQgHAAgCgGgAFCANQgJAHgBAOQABAIADAFQADAEAGAAQAJAAAEgLQACgGgBgLIAAgQQgKACgHAEgAApA1QgCgDAAgHQgDAHgDADQgGAGgIAAQgJAAgGgGQgFgHAAgLQAAgRAQgJQAJgFANgCIAAgLQAAgJgDgEQgCgGgIAAQgGAAgEAEQgCADAAAFIAAABIAAADQAAAIgGAAQgFAAAAgGQAAgJAHgGQAHgIAKAAQAIAAAGAEQAHAFACAKIABANIAAAlIABANQABAEAEAAIAEAAIAAAFIgJABQgHAAgCgGgAAUANQgKAHAAAOQAAAIAEAFQADAEAFAAQAKAAADgLQACgGAAgLIAAgQQgKACgHAEgAkHA1QgCgDAAgHQgDAHgDADQgFAGgJAAQgJAAgGgGQgFgHgBgLQAAgRARgJQAKgFANgCIAAgLQgBgJgCgEQgDgGgHAAQgGAAgEAEQgCADgBAFIAAABIAAADQABAIgHAAQgEAAAAgGQgBgJAIgGQAGgIALAAQAIAAAGAEQAHAFABAKIABANIAAAlIABANQABAEAEAAIAEAAIAAAFIgJABQgGAAgDgGgAkbANQgLAHABAOQgBAIAEAFQADAEAGAAQAJAAAEgLQABgGABgLIAAgQQgLACgGAEgAtbA1QgCgDAAgHIgGAKQgGAGgJAAQgIAAgGgGQgGgHAAgLQAAgRARgJQAJgFANgCIAAgLQAAgJgDgEQgCgGgIAAQgFAAgFAEQgCADAAAFIAAABIAAADQAAAIgGAAQgFAAAAgGQAAgJAHgGQAHgIAKAAQAIAAAGAEQAHAFACAKIABANIAAAlIABANQABAEADAAIAFAAIAAAFIgJABQgGAAgDgGgAtwANQgKAHAAAOQAAAIAEAFQACAEAHAAQAJAAADgLQACgGAAgLIAAgQQgKACgHAEgAyKA1QgBgDgBgHQgDAHgDADQgFAGgJAAQgJAAgGgGQgFgHAAgLQAAgRAQgJQAKgFANgCIAAgLQgBgJgCgEQgDgGgHAAQgGAAgEAEQgCADgBAFIAAABIAAADQABAIgHAAQgEAAAAgGQgBgJAIgGQAGgIALAAQAIAAAFAEQAIAFABAKIABANIAAAlIABANQABAEAEAAIAEAAIAAAFIgJABQgGAAgDgGgAyfANQgKAHABAOQAAAIADAFQADAEAGAAQAJAAAEgLQABgGABgLIAAgQQgLACgHAEgATVA5IgQABIAAgDIAHgCQACgBAAgDIABgEIAAguQAAgLgCgFQgEgHgHAAQgJAAgEAIQgDAFAAALIAAAtIABAGQABADAIABIAAADIgRgBIgPABIAAgDIAHgCQACgBABgDIAAgFIAAg6IAAgGQAAgEgFgBIgFAAIAAgEQAMgCAIgDIABAQQAIgPAMAAQAMAAAGAMQAEAHAAAOIAAAsIABAHQABADAJABIAAADIgRgBgAQtA5IgRABIAAgDIAIgCQACgBABgDIAAgFIAAg6IAAgHQgBgEgEgBIgGAAIAAgDQANgCAHgDIACASIAEgKQAGgHAHAAQAHAAADAFQADAEAAAGQAAAEgCADQgBACgDAAQgBAAAAAAQgBAAgBAAQAAAAgBgBQAAAAAAAAQgCgCAAgDIAAgEIABgCQAAAAgBgBQAAAAAAgBQAAAAAAAAQgBgBAAAAIgDgBQgHAAgEALQgCAHAAALIAAAoIABAHQACADAIABIAAADIgRgBgAOZA5IgQABIAAgDIAHgCQACgBAAgDIAAgEIAAgwQABgKgCgEQgDgHgHAAQgPAAgBAWIAAAvIABAGQACADAHABIAAADIgQgBIgPABIAAgDIAGgCQADgBABgDIAAgEIAAgwQAAgKgCgFQgEgGgHAAQgIAAgEAIQgDAGABAKIAAAtIABAGQABADAIABIAAADIgRgBIgQABIAAgDIAHgCQADgBAAgDIAAgFIAAg6IAAgGQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAQgCgBgGAAIAAgEQAMgCAIgDIACAQIAFgIQAGgHAJAAQANAAAFAPIAFgIQAFgHAKAAQANAAAFAMQACAGAAAMIAAAvIACAHQABADAJABIAAADIgRgBgAL8A5IgPABIAAgDIAGgCQACgBABgDIAAgEIAAguQAAgLgCgFQgEgHgHAAQgIAAgEAIQgDAFAAALIAAAtIAAAGQACADAHABIAAADIgQgBIgRABIAAgDIAIgCQADgBAAgDIAAgFIAAhfIgBgHQgBgDgDAAIgFgBIAAgDQALgBAMgEIAAAyQAGgNANAAQAMAAAGAMQADAHAAAOIAAAsIABAHQACADAIABIAAADIgRgBgAKsA5IgQABIAAgDIAHgCQACgBABgDIAAgEIAAguQAAgLgCgFQgEgHgIAAQgHAAgFAIQgDAFAAALIAAAtIABAGQACADAHABIAAADIgQgBIgRABIAAgDIAIgCQADgBAAgDIAAgFIAAg6IAAgGQAAgEgEgBIgHAAIAAgEQANgCAHgDIACAQQAIgPAMAAQAMAAAGAMQAEAHAAAOIAAAsIAAAHQADADAHABIAAADIgQgBgAIVA5IgQABIAAgDIAGgCQACgBABgDIAAgEIAAguQAAgLgCgFQgDgHgIAAQgIAAgFAIQgCAFAAALIAAAtIAAAGQACADAHABIAAADIgQgBIgRABIAAgDIAIgCQADgBAAgDIAAgFIAAhfIgBgHQgBgDgDAAIgFgBIAAgDQAMgBALgEIAAAyQAGgNANAAQALAAAHAMQADAHAAAOIAAAsIABAHQACADAIABIAAADIgQgBgAChA5IgQABIAAgDIAGgCQADgBABgDIAAgEIAAgwQAAgKgCgEQgDgHgIAAQgOAAAAAWIAAAvIABAGQABADAIABIAAADIgRgBIgPABIAAgDIAGgCQADgBAAgDIAAgEIAAgwQAAgKgCgFQgCgGgHAAQgJAAgEAIQgDAGAAAKIAAAtIABAGQACADAHABIAAADIgQgBIgQABIAAgDIAIgCQACgBAAgDIAAgFIAAg6IAAgGQAAgBAAgBQAAAAAAgBQgBAAAAgBQgBAAAAAAQgBgBgHAAIAAgEQAMgCAIgDIABAQIAGgIQAGgHAIAAQANAAAFAPIAGgIQAGgHAJAAQANAAAFAMQACAGAAAMIAAAvIABAHQACADAIABIAAADIgQgBgAgbA5IgPABIAAgDIAGgCQADgBAAgDIABgEIAAguQgBgLgCgFQgDgHgIAAQgIAAgEAIQgDAFAAALIAAAtIABAGQABADAIABIAAADIgRgBIgQABIAAgDIAIgCQACgBAAgDIAAgFIAAg6IAAgGQAAgEgEgBIgGAAIAAgEQAMgCAIgDIABAQQAIgPANAAQAMAAAGAMQADAHAAAOIAAAsIABAHQACADAIABIAAADIgRgBgAm5A5IgQABIAAgDIAGgCQADgBABgDIAAgEIAAgwQAAgKgCgEQgDgHgIAAQgOAAAAAWIAAAvIABAGQABADAIABIAAADIgRgBIgPABIAAgDIAHgCQACgBAAgDIAAgEIAAgwQAAgKgCgFQgCgGgHAAQgJAAgEAIQgDAGAAAKIAAAtIABAGQACADAHABIAAADIgQgBIgQABIAAgDIAIgCQACgBAAgDIAAgFIAAg6IAAgGQAAgBAAgBQAAAAAAgBQgBAAAAgBQgBAAAAAAQgBgBgHAAIAAgEQAMgCAIgDIABAQIAGgIQAGgHAIAAQANAAAFAPIAGgIQAGgHAJAAQANAAAFAMQACAGAAAMIAAAvIABAHQACADAIABIAAADIgQgBgAp2A5IgQABIAAgDIAHgCQADgBABgDIAAgFIAAg7IgBgHQgCgDgDgBIgFAAIAAgDQAMgCAKgDIAABOIABAHQADADAHABIAAADIgRgBgAqeA5IgQABIAAgDIAHgCQACgBAAgDIAAgEIAAguQAAgLgBgFQgEgHgHAAQgJAAgEAIQgDAFAAALIAAAtIAAAGQADADAGABIAAADIgQgBIgQABIAAgDIAHgCQADgBABgDIAAgFIAAhfIgBgHQgBgDgEAAIgEgBIAAgDQALgBALgEIAAAyQAHgNAMAAQAMAAAGAMQAEAHAAAOIAAAsIABAHQABADAJABIAAADIgRgBgAwRA5IgQABIAAgDIAGgCQACgBABgDIAAgEIAAgwQAAgKgBgEQgDgHgIAAQgPAAAAAWIAAAvIABAGQACADAHABIAAADIgQgBIgPABIAAgDIAGgCQACgBABgDIAAgEIAAgwQAAgKgCgFQgDgGgHAAQgJAAgDAIQgDAGAAAKIAAAtIABAGQACADAHABIAAADIgQgBIgRABIAAgDIAIgCQADgBAAgDIAAgFIAAg6IAAgGQAAgBAAgBQgBAAAAgBQAAAAgBgBQAAAAgBAAQgBgBgHAAIAAgEQANgCAHgDIACAQIAFgIQAHgHAIAAQANAAAFAPIAFgIQAGgHAJAAQAOAAAEAMQADAGAAAMIAAAvIABAHQABADAJABIAAADIgQgBgAzOA5IgQABIAAgDIAHgCQABgBABgDIAAgEIAAguQAAgLgCgFQgDgHgIAAQgIAAgFAIQgCAFAAALIAAAtIABAGQABADAIABIAAADIgRgBIgQABIAAgDIAHgCQADgBAAgDIAAgFIAAg6IAAgGQAAgEgEgBIgGAAIAAgEQAMgCAIgDIACAQQAHgPANAAQALAAAHAMQADAHAAAOIAAAsIABAHQACADAIABIAAADIgQgBgA1YA5IgTABIAAgEQAHgBACgBQAEgCAAgEIAAgFIAAhWIgRAAIAAgFQAJgBAIgFQAGgGACgJIAEAAIAABwIABAIQACADAFABIAEABIAAAEIgSgBgAjDA6IAAgLIAagpQAKgPADgKQAEgJABgIQAAgJgFgFQgFgGgHAAQgFAAgEADQgFADgCAFQgDAFgBAKIgFAAQABgRAFgHQADgHAHgDQAFgDAHAAQALAAAHAHQAEAEACAGQACAGABAGQAAANgKAPQgJAPgaAnIAtAAIgBAOgAVagdIgKATIgGgGIAKgSIgRgGIACgKIARAIIAAgXIAHAAIAAAXIARgIIACAKIgRAGIALASIgGAGgASCgqIgPgPIgNAPIgFAAIAQgXIAHAAIAOAXgAowgqIgOgPIgOAPIgEAAIAPgXIAHAAIAPAXgAFGgrIACgGIADgHQAEgEAAgEQAAgIgGAAQgGAAgCAKIgCAAQAAgJAGgEQACgBAEAAQAEAAADACQADADAAAGQABAFgEAEIgCADIgEAEIgDAGgAtsgrIABgGIAEgHQADgEAAgEQAAgIgFAAQgHAAgBAKIgDAAQABgJAFgEQADgBAEAAQAEAAACACQAEADAAAGQAAAFgDAEIgDADIgDAEIgDAGgAAPgyQgFgGgBgJIADAAQADAGADAEQAEADAFAAQAEAAAEgDQAFgEABgGIAEAAQgBAJgFAGQgFAGgHAAQgHAAgFgGgAykgyQgEgGgBgJIACAAQADAGAEAEQADADAGAAQAEAAAEgDQAFgEABgGIAEAAQgCAJgFAGQgFAGgGAAQgIAAgFgGgAPNgtIABgGIAEgHQADgEAAgEQAAgHgFAAQgIAAAAAJIgDAAQAAgJAGgEQADgBADAAQAEAAAEACQADAEAAAGQABAEgEAEIgDADIgEAEIgCAGgAJPguIgUgYIALAAIANAYgAkRguIgUgYIAMAAIANAYgAp7gyQgDgDAAgEQAAgFADgDQACgDADAAQADAAADADQACADAAAFQAAAEgCADQgDADgDAAQgDAAgCgDgAoug9IABgGIAEgHQADgFAAgEQABgHgGAAQgHAAAAAKIgDAAQAAgJAFgEQADgBAEAAQAEAAADACQADADAAAGQAAAFgCAEIgEADIgEAEQgCACAAAEg");
	this.shape.setTransform(128.7,6.825);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10.5,-2.7,278.4,19.099999999999998);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(-105,19,0.11,0.11);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1208));

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A3yDbIAAm1MAvlAAAIAAG1g");
	this.shape.setTransform(8.775,30.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1208));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-143.5,8.3,304.6,43.8);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AikBFQgCgCAAgDQAAgDACgCQACgCADAAQADAAADACQABACAAADQAAADgCACQgCACgDAAQgDAAgCgCgADnApQgIgHAAgKQAAgQASgHQAJgDATgCIAAgEQAAgIgDgDQgEgEgJAAQgOAAgCAMIgLAAQABgJAFgGQAIgHAOAAQAMAAAHAGQAFAEABAJIAAALIAAAbQAAANACAHIgKAAIgCgLQgGAMgQAAQgKAAgGgEgAD1AJQgLAFAAAJQAAAGAFAEQADADAHAAQALAAAGgJQADgFAAgMIAAgHQgRADgHADgAA6ApQgHgFgBgKIgBgMIAAgtIALAAIAAAtQAAAMADAEQADAGAKAAQAKAAAFgJQADgFAAgLIAAgqIALAAIAAAGIABgBIADgEQABAAAAgBQAAAAAAgBQABAAAAgBQAAgBAAAAIgBAAIgDgCQgCgDABgDQAAgEADgBQADgBADAAQADABABADQACADgBAFQgDAJgMAJIAAAnIAAAIIAAAEQAAAGACAFIgLAAIgBgFIgBgGQgCAFgEADQgFAEgJAAQgJAAgHgEgAAIAmIgCgGIAAg2IgLAAIAAgJIALAAIAAgVIALAAIAAAVIASAAIAAAJIgSAAIAAAlIAAAOQABAGAHAAQAGAAAGgCIAAAKQgIACgGAAQgLAAgEgHgAiyApQgIgHAAgKQAAgQARgHQAKgDASgCIAAgEQAAgIgCgDQgEgEgJAAQgOAAgDAMIgLAAQABgJAGgGQAHgHAOAAQAMAAAHAGQAGAEABAJIAAALIAAAbQAAANACAHIgKAAQgCgFAAgGQgGAMgQAAQgKAAgGgEgAikAJQgLAFAAAJQAAAGAFAEQADADAHAAQALAAAFgJQADgFAAgMIAAgHQgQADgHADgACzAsIgbhLIALAAIAVA+IAVg+IAMAAIgaBLgAFZAsIAAgrQAAgMgBgFQgEgHgJAAQgLAAgGAJQgEAGAAAJIAAArIgLAAIAAgxIAAgSIgBgIIAKAAQACAFgBAGQAIgNAQAAQAKAAAGAGQAGAFABAJIAAANIAAAsgAhAAsIAAgrQAAgMgCgFQgDgHgKAAQgLAAgFAJQgEAGAAAJIAAArIgLAAIAAgxIAAgSIgCgIIALAAQACAFgBAGQAIgNAPAAQALAAAGAGQAGAFABAJIAAANIAAAsgAjVAsIAAgrQAAgMgCgEQgEgIgJAAQgLAAgFAJQgEAGAAAKIAAAqIgLAAIAAhqIALAAIAAAoQAJgLANAAQAIAAAGAEQAHAEACAJQABAEAAAMIAAAsgAkmAsIgyhXIAABXIgLAAIAAhpIANAAIAyBXIAAhXIALAAIAABpgAEJgnIgLgNIgKANIgJAAIAOgSIAKAAIAPASgAiRgnIgLgNIgLANIgIAAIAOgSIAKAAIAPASgAEMg1IANgRIAMAAIgRARg");
	this.shape.setTransform(55.425,3.875);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#08ABF1").s().p("AxJDxIAAnhMAiTAAAIAAHhg");
	this.shape_1.setTransform(52.3014,2.8852,0.6073,0.611);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.4,-11.8,133.4,29.400000000000002);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKyAwQgHgFAAgGQAAgHAGgDIAFgDQgFgCAAgEQAAgDAEgDIAGgDQgLgEAAgJQAAgKAGgFQAGgDAHAAIAJABIAQAAIAAAFIgMAAQAFAEAAAIQAAAHgFADQgDADgJACIgIADQgBAAAAAAQgBABAAAAQgBABAAAAQAAABAAAAQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAIAJACIAKABQANACAAALQAAAJgHAEQgHAEgKAAQgLAAgGgEgAK4AeQgFACAAAEQAAAEAFADQAEACAIAAQAIABAEgEQAEgCAAgEQAAgIgRgBQgHAAgEADgAK7gNQgDADAAAGQAAAEADACQACADAGAAQAEAAAEgDQADgCAAgEQAAgGgDgCQgDgEgFAAQgFAAgDADgAG1AzIAAg5IAAgLIgBgEIAHAAIABAHQAGgJAIAAQAIAAAGAEQAHAJABAOQAAAOgIAHQgFAGgIAAQgJAAgGgIIAAAcgAHBgMQgFAHAAAJQAAAJAEAGQAEAFAGAAQAGAAADgEQAFgGAAgKQgBgLgFgFQgDgFgFAAQgGAAgDAFgAJRAvQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAABQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAgAEFAvQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAgAJIAbQgFgDgBgHIgBgIIAAgeIAIAAIAAAeQAAAIABADQAEAEAFAAQAIAAADgGQACgDABgIIAAgcIAHAAIAAAjIAAAJIACAHIgIAAIgBgHIgFAFQgDADgGAAQgHAAgEgEgAINAZQgHgIAAgNQAAgNAHgIQAFgGAIAAQAHAAADADIAFAGIAAgdIAIAAIAAA5IABAQIgHAAIgBgGIAAgCIgFAFQgEAEgGAAQgIAAgGgGgAISgMQgEAGAAAKQAAAKAEAGQADAEAGAAQAHAAACgEQAGgGAAgKQgBgKgEgGQgDgFgHAAQgFAAgEAFgAGCAbQgGgEABgHQAAgMAMgEQAHgBAMgCIAAgCQAAgGgBgCQgDgEgGAAQgKAAgCAJIgHAAQAAgHAEgEQAGgEAJAAQAIAAAFADQAEADABAHIAAAIIAAASQAAAJABAFIgHAAIgBgHQgFAIgLAAQgGAAgFgEgAGMAGQgIADAAAGQABAEADADQACACAFABQAHgBAEgGQADgDgBgJIAAgFIgQAFgAD5AZQgHgIAAgNQABgNAHgJQAGgFAJAAQAKAAAHAJQAEAHAAAKIAAACIgkAAQAAAIADAFQAFAGAIAAQAFAAAEgDIACgFIAIABQgFAOgOAAQgKAAgHgGgAD9gKQgCAEgBAFIAcAAQAAgFgCgEQgEgHgHAAQgHAAgFAHgABaAbQgEgDgBgHIgBgIIAAgeIAHAAIAAAeQAAAIACADQADAEAGAAQAHAAAEgGQACgDAAgIIAAgcIAIAAIAAAjIAAAJIABAHIgIAAIgBgHIgEAFQgDADgGAAQgHAAgFgEgAAiAZQgHgIAAgNQAAgNAIgJQAFgFAKAAQAKAAAGAJQAEAHAAAKIAAACIgjAAQAAAIADAFQAEAGAIAAQAGAAAEgDIACgFIAHABQgFAOgOAAQgJAAgHgGgAAmgKQgCAEgBAFIAbAAQAAgFgCgEQgDgHgIAAQgHAAgEAHgAguAZQgIgIAAgNQAAgNAIgIQAEgGAJAAQAGAAAEADIAEAGIAAgQIgPAAIAAgFIAPAAIAAgIIAIAAIAAAIIAIAAIAAAFIgIAAIAAAsIABAQIgHAAIgBgGIAAgCIgEAFQgFAEgFAAQgJAAgFgGgAgpgMQgEAGgBAKQABAKAEAGQADAEAGAAQAGAAADgEQAFgGAAgKQAAgKgEgGQgEgFgGAAQgGAAgDAFgAkXAbQgFgEAAgHQAAgMAMgEQAHgBANgCIAAgCQAAgGgCgCQgDgEgGAAQgKAAgBAJIgIAAQAAgHAEgEQAGgEAJAAQAJAAAEADQAFADAAAHIAAAIIAAASQABAJABAFIgIAAIgBgHQgEAIgLAAQgHAAgFgEgAkNAGQgHADAAAGQAAAEADADQADACAEABQAIgBAEgGQACgDAAgJIAAgFIgRAFgAlNAZQgHgJAAgMQAAgNAHgIQAHgGAJAAQAJAAAGAGQAIAIgBANQABAMgIAJQgGAGgJAAQgJAAgHgGgAlHgLQgFAFAAAKQAAAJAFAGQADAFAHAAQAGAAAEgFQAFgGAAgJQAAgKgFgFQgEgFgGgBQgHABgDAFgAoLAbQgEgDgCgHIAAgIIAAgeIAHAAIAAAeQABAIABADQADAEAGAAQAHAAAEgGQACgDAAgIIAAgcIAIAAIAAAjIAAAJIABAHIgIAAIAAgHIgFAFQgDADgHAAQgGAAgFgEgApDAZQgHgIAAgNQAAgNAIgJQAGgFAJAAQAKAAAGAJQAEAHABAKIAAACIgkAAQAAAIADAFQAEAGAIAAQAGAAAEgDIACgFIAHABQgEAOgPAAQgKAAgGgGgAo/gKQgCAEgBAFIAbAAQAAgFgCgEQgDgHgIAAQgHAAgEAHgAiMAZQgHgFAAgKQAAgIAHgFIAHgIIgFgHQgDgFAAgFQAAgGAEgEQAFgEAHAAQAGAAAEADQAFAEAAAHQAAAGgFAGIgHAHIAPATQADgEAAgJIAGAAIAAACQABAKgFAIIAJANIgIAAIgGgHIgGAFQgGACgGAAQgKAAgFgFgAiHAAQgFAFABAFQAAAGADADQAEAFAHAAQAIAAAGgHIgRgVIgHAEgAiCgiQgEACAAADQAAAFAEAEIADAGIAHgGQADgEAAgFQAAgDgCgCQgCgBgEgBQgDABgCABgAKYAeIAAgeQABgIgCgDQgCgFgHAAQgHAAgEAGQgDAEAAAGIAAAeIgHAAIAAgiIgBgNIgBgEIAHAAIABAHQAGgJAKAAQAIAAAEADQAEAEABAGIAAAKIAAAegAFLAeIAAgeQABgIgCgDQgCgFgHAAQgHAAgEAGQgDAEAAAGIAAAeIgHAAIAAgiIgBgNIgBgEIAHAAIABAHQAGgJAKAAQAIAAAEADQAEAEABAGIAAAKIAAAegADdAeIAAgzIAIAAIAAAzgADFAeIgWgdIAWgWIAJAAIgVAWIAXAdgACnAeIAAhJIAIAAIAABJgAAFAeIAAgzIAIAAIAAAzgAjEAeIAAgeQAAgIgCgDQgBgFgIAAQgHAAgEAGQgCAEAAAGIAAAeIgIAAIAAgiIAAgNIgBgEIAHAAIABAHQAGgJAKAAQAHAAAFADQADAEABAGIAAAKIAAAegAlpAeIAAgeQABgIgCgDQgDgFgGAAQgIAAgDAGQgDAEAAAHIAAAdIgHAAIAAhJIAHAAIAAAbQAGgHAJAAQAGAAAEADQAFACACAHIAAALIAAAegAmgAeIgWgdIAWgWIAJAAIgVAWIAXAdgAm+AeIAAhJIAHAAIAABJgApgAeIAAgzIAIAAIAAAzgAqkAeIAAgjIgHAAIAAgGIAHAAIAAggIALAAIAPABQAOACAGAKQAIAKAAAOQgBAOgHAJQgIALgMABIgQABgAqcAXIAGAAIALgBQAEgBAFgDQAEgCACgEQAFgHAAgLQAAgNgHgJQgEgGgJgBIgOgBIgDAAIAAAZIASAAIAAAGIgSAAgArJgUIgJALIgDgCIAHgLIgNgFIACgEIANADIAAgNIAFAAIAAANIANgDIACAEIgOAFIAIALIgDACgAEQgcIgHgIIgIAIIgGAAIAKgMIAHAAIAKAMgAA5gcIgIgIIgHAIIgHAAIAKgMIAHAAIAKAMgAotgcIgHgIIgHAIIgGAAIAJgMIAIAAIAJAMgAkIgdIAAgDIABgDIACgBIABgBIABgBIABgBIAAgCIgBgBIgEgBIgCABQgBAAAAABQAAAAgBAAQAAABAAAAQAAABAAABIgEAAIABgDIABgDQACgCAFgBQAEABACABIACACIABAEIgBACIgBABIgCABIgCACIgCACIAAACgAGMgeIAJgMIAIAAIgLAMgADdgiQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQABAAAAAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAABQABAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQgBABgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBAAAAgAAFgiQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQABABAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAQgBABAAAAQgBAAgBAAQAAABgBAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAgApggiQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQABABAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAQgBABAAAAQgBAAgBAAQAAABgBAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAgAA+gnIgLgMIAIAAIAJAMgAongnIgLgMIAIAAIAJAMg");
	this.shape.setTransform(73.15,5.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,146.3,10.4);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.514,1],-14.5,-4.6,14.7,4.7).s().p("AjwD8IC+pUIEjBeIi+JTg");
	this.shape.setTransform(24.125,34.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.3,69);


(lib.Symbol1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.bg1();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.3333,0.3334);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,210.4);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol14("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(130.55,-212.75,1,1,0,0,0,129.7,10);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-225.75,alpha:1},10,cjs.Ease.get(1)).wait(2730));

	// Layer_1
	this.instance_1 = new lib.Symbol20("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(104.7,-5.4,1,1,0,0,0,104.7,11.1);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:11.1,alpha:1},10,cjs.Ease.get(1)).wait(2730));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-9.6,-283.2,278.40000000000003,76.79999999999998);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Ao2B9IAAj5IRtAAIAAD5g");
	mask.setTransform(44.55,13.475);

	// Layer_3
	this.instance = new lib.Symbol2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-40.1,14.65,1,1,0,0,0,24.1,34.5);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:126.8,y:19.05},23,cjs.Ease.get(1)).wait(67));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.1,0,113.39999999999999,26);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(43.35,7.65,0.4,0.4,0,0,0,43.4,7.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:7.6,scaleX:1.1,scaleY:1.1,x:43.4,y:7.6,alpha:1},11,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(1944));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-20.2,-13.7,146.7,32.4);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol3("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(73,4.75,1,1,0,0,0,73.2,5.2);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},9,cjs.Ease.get(1)).wait(2516));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.2,-0.4,146.29999999999998,10.4);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_215 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(215).call(this.frame_215).wait(110));

	// Layer_12
	this.instance = new lib.Symbol18();
	this.instance.parent = this;
	this.instance.setTransform(234.4,226.1,1,1,0,0,0,42.4,10.1);
	this.instance.alpha = 0.8008;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(141).to({_off:false},0).wait(184));

	// cta
	this.instance_1 = new lib.Symbol11("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(229.05,233.7,0.85,0.85,0,0,0,43.6,7.9);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(44).to({_off:false},0).wait(281));

	// logo
	this.instance_2 = new lib.Symbol13("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(157.5,215.5,1,1,0,0,0,15.5,15.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(325));

	// Layer_4
	this.instance_3 = new lib.Symbol1("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(236.9,199.05,0.75,0.75,0,0,0,73.2,5.4);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(64).to({_off:false},0).wait(261));

	// t1
	this.instance_4 = new lib.Symbol19("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(125.7,299.1,1,1,0,0,0,104.7,11.1);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(9).to({_off:false},0).to({_off:true},207).wait(109));

	// bg2
	this.instance_5 = new lib.Symbol15("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(155.3,339.9,1.2,1.2,0,0,0,159.2,299.9);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(112).to({_off:false},0).to({regY:300,scaleX:1,scaleY:1,x:155.2,y:300,alpha:1},20,cjs.Ease.get(1)).to({_off:true},84).wait(109));

	// bg1
	this.instance_6 = new lib.Symbol1copy("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(146.05,329.9,1.2,1.2,0,0,0,150,299.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({regY:300,scaleX:1,scaleY:1,x:150,y:300},17,cjs.Ease.get(1)).to({_off:true},120).wait(188));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37.1,-99.4,372,759.4);


// stage content:
(lib._300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.parent = this;
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(116.1,95.1,210.00000000000003,157);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg1.jpg?1714645586314", id:"bg1"},
		{src:"images/bg2.jpg?1714645586314", id:"bg2"},
		{src:"images/logo.png?1714645586314", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;