(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bg1 = function() {
	this.initialize(img.bg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,900,1224);


(lib.bg2 = function() {
	this.initialize(img.bg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,900,1214);


(lib.bg3 = function() {
	this.initialize(img.bg3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,900,1230);


(lib.logomec = function() {
	this.initialize(img.logomec);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,886,102);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,200,200);


(lib.Symbol25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMyBwIgXABIAAgEQAHAAADgCQAEgCAAgDIABgGIAAh6QAAgKgEgDQgCgBgJgBIAAgEQAPgCALgDQACAIABANQAJgUAQAAQAQAAALARQAKAQAAAZQAAAZgKAQQgKARgQAAQgLABgGgIIgIgLIAAAvQAAAFACADQACAEALABIAAAEIgWgBgANCgiQgJALAAAeQAAA2AXAAQAWAAAAgzQAAg0gXAAQgIgBgFAJgAFnBwIgXABIAAgEQAHAAADgCQAEgCAAgDIABgGIAAh6QAAgKgEgDQgCgBgJgBIAAgEQAPgCALgDQACAIABANQAJgUAQAAQAQAAALARQAKAQAAAZQAAAZgKAQQgKARgQAAQgLABgGgIIgIgLIAAAvQAAAFACADQACAEALABIAAAEIgWgBgAF3giQgJALAAAeQAAA2AXAAQAWAAAAgzQAAg0gXAAQgIgBgFAJgAroBwIgWABIAAgEQAHAAADgCQADgCABgDIAAgGIAAgvIgHALQgHAIgKgBQgRAAgKgRQgKgQAAgZQAAgZALgQQAKgRAQAAQARAAAIAUQABgNACgIQALADAPACIAAAEIgDAAQgHAAgCADQgCAEAAAIIAAB6IABAIQACAEALABIAAAEIgWgBgAsUghQgIALAAAgQAAAzAVAAQAXAAAAg2QAAgxgWAAQgIgBgGAKgApWBwIAAgMQAHAAAEgBQAKgEAFgQIAGgSIgdhdQgCgHgEgCIgJgBIAAgGIAUABIAVgBIAAAGIgGAAQgFABAAADIACAHIAUBEIAWhEIACgGQAAgEgFgBIgHAAIAAgGIAPABIARgBIAAAGIgIABQgFADgCAHIglB0QgFAQgIAHQgHAEgJAAIgDAAgAvxBtQgCgEAAgEQAAgFACgDQADgDAEAAQADAAADADQADADAAAFQAAAEgDAEQgDADgDAAQgEAAgDgDgAA7BGIgQgdIg+hzIAAB3QAAAIABACQADAEANABIAAAGIgUgBIgTABIAAgGQAIAAADgCQAEgCABgFIAAgGIAAh/QgDgDgEgBIgKgCIAAgGIARAAIAOAAIBCB5IAAhkIgBgKQgCgEgNgBIAAgGIAUABIATgBIAAAGIgLACQgEADgBAEIAAAGIAACPgAxtAxQgJgRAAgWQAAgWAJgRQAJgTASAAQAKAAAHAHIAHALIAAgfIgdAAIAAgHIAdAAIAAgDIgBgKQgCgDgFgBIgDAAIgDAAIAAgEQAQgDAOgEIAAAcIAMAAIAAAHIgMAAIAABmIAAAKQABAEAEACIAEAAIAFABIAAADIgPAEIgLADIgCgKIgBgKQgIAUgQAAQgSAAgKgTgAxlAKQAAAVAEAOQAFAQAMAAQAIABAGgIQAIgLAAggQAAg1gXABQgUAAAAAzgAP6AyQgKgQAAgZQAAgZALgRQALgRASAAQARABAKARQAKAQAAAZQAAAYgKARQgLASgSAAQgRAAgLgSgAQJgjQgIANAAAfQAAA1AVAAQAJAAAGgKQAHgMAAgeQAAg1gVAAQgIgBgGAJgAiCAuQgEAKgEADQgIAJgLgBQgQAAgIgNQgFgJAAgRIAAg2IgBgKQgCgEgLgBIAAgDQAPgDAPgEIAABPQAAAPADAFQAEAJAKAAQAMAAAFgKQAEgIAAgOIAAgzIgBgKQgCgEgLgBIAAgDQAPgDAPgEIAAAIQAGgIAAgHIgCAAQgIgCACgKQABgIAHAAQAKgBAAAMQAAALgJANIgEAEIgDAFIAABQIABAIQABACAGABIAGABIAAADQgPADgMAEIgBgWgAnuA0QgLgQAAgbQAAgZALgRQAKgQASAAQANAAAKAKQAMAOABAfIg7AAIAAAFQAAAVAGAOQAGAOAOAAQAOAAAHgPQADgHABgJIAIAAQgBANgGAKQgKAQgSAAQgTAAgKgQgAnpgCIArAAQgCgpgSAAQgUAAgDApgAqFAuQgEAJgEAEQgIAJgLgBQgQAAgIgNQgFgJAAgRIAAg2IgBgKQgCgDgFgBIgGgBIAAgDQAPgCAPgFIAABPQAAAPADAFQAEAJAKAAQAMAAAFgKQAEgIAAgOIAAgzIgBgKQgCgDgFgBIgGgBIAAgDQAPgCAPgFIAABhIABAIQABACAGABIAGABIAAADQgQADgLAEIgBgWgAupAzQgLgPAAgaQAAgbAMgRQALgQAQAAQAMAAAJAKIAFgLIADAAIAAAnIgEAAQgCgLgDgHQgDgGgEgEQgFgDgGAAQgMAAgGAPQgFAQAAAWQAAAyAXAAQASAAADgfIAIAAQgBANgEAIQgIASgSAAQgRAAgLgRgAwHAyQgKgQAAgZQAAgZALgRQALgRASAAQARABAKARQAKAQAAAZQAAAYgKARQgLASgSAAQgRAAgLgSgAv4gjQgIANAAAfQAAA1AVAAQAJAAAGgKQAHgMAAgeQAAg1gVAAQgIgBgGAJgAItA7QgIgIAAgOQAAgWAWgLQANgGARgCIAAgPQAAgLgDgFQgFgIgJABQgHAAgGAEQgDAEAAAFIAAADIAAADQAAALgIAAQgHAAAAgJQAAgKAJgJQAKgJAOAAQAJAAAIAFQAKAHACALIABAQIAAAxQAAALACAFQABAFAFAAIAFgBIAAAHIgLABQgIAAgEgHQgCgFgBgIQgEAIgEAEQgHAJgMgBQgMABgHgJgAJCAKQgNAHAAATQAAAKAFAFQAEAGAHAAQANAAAEgOQADgHAAgOIAAgVQgOADgJAGgADOA7QgIgIAAgOQAAgWAXgLQANgGAQgCIAAgPQAAgLgDgFQgEgIgJABQgIAAgFAEQgEAEAAAFIAAADIAAADQAAALgIAAQgGAAAAgJQAAgKAJgJQAJgJAOAAQAKAAAIAFQAJAHADALIABAQIAAAxQAAALABAFQACAFAFAAIAFgBIAAAHIgLABQgJAAgEgHQgCgFgBgIQgEAIgDAEQgHAJgMgBQgMABgIgJgADkAKQgOAHAAATQAAAKAFAFQAEAGAIAAQAMAAAFgOQACgHAAgOIAAgVQgNADgJAGgAj0A2QgCgFgBgJIAAgMIAAhCIgMAAIAAgIQAFAAAEgCQALgHADgaIAFAAIAAAiIAXAAIAAAJIgXAAIAABFQAAAPACAEQADAIAHAAQAFAAAIgFIAAAHQgKAIgJgBQgPAAgEgNgARhBBIgWABIAAgFQAGAAAEgCQADgBABgEIAAgGIAAhKIgBgKQgCgDgFgBIgGgBIAAgDQAQgDAOgEIAABjIABAJQACAEALAAIAAAFIgWgBgAPOBBIgVABIAAgFQAGAAADgCQADgCABgDIAAgFIAAg6QAAgPgDgFQgEgJgKAAQgLAAgGAJQgEAHAAAOIAAA5QAAAGABACQACAEAKAAIAAAFIgWgBIgVABIAAgFQAHAAADgCQADgBABgEIAAgGIAAh3IgBgKQgCgDgFgBIgGAAIAAgFQAQgBAOgFIAAA/QAJgQAQAAQAQAAAIAPQAFAJAAARIAAA4QAAAGABADQACAEALAAIAAAFIgWgBgALMBBIgVABIAAgFQAFAAAEgCQADgCAAgDIABgFIAAg6QAAgPgDgFQgFgJgKAAQgKAAgHAJQgDAHAAAOIAAA5IABAIQACAEAJAAIAAAFIgVgBIgVABIAAgFQAGAAADgCQAEgBAAgEIABgGIAAhJIgBgIQAAgGgFgBIgIAAIAAgEQAQgCAKgFQABAHABAOQAKgTARAAQAQAAAIAPQAEAIAAASIAAA4QAAAGACADQACAEALAAIAAAFIgWgBgAIDBBIgVABIAAgFQAGAAADgCQADgCABgDIAAgFIAAg6QAAgPgDgFQgEgJgKAAQgLAAgGAJQgEAHAAAOIAAA5QAAAGABACQACAEAKAAIAAAFIgWgBIgVABIAAgFQAHAAADgCQADgBABgEIAAgGIAAh3IgBgKQgCgDgFgBIgGAAIAAgFQAQgBAOgFIAAA/QAJgQAQAAQAQAAAIAPQAFAJAAARIAAA4QAAAGABADQACAEALAAIAAAFIgWgBgAClBBIgWABIAAgFQAGAAAEgCQADgCAAgDIABgFIAAg6QAAgPgDgFQgFgJgKAAQgKAAgHAJQgEAHAAAOIAAA5QAAAGACACQACAEAJAAIAAAFIgVgBIgWABIAAgFQAHAAADgCQAEgBAAgEIABgGIAAh3IgBgKQgCgDgFgBIgGAAIAAgFQAPgBAOgFIAAA/QAKgQAQAAQAQAAAIAPQAEAJAAARIAAA4QAAAGACADQACAEALAAIAAAFIgWgBgAlUBBIgVABIAAgFQAFAAAEgCQADgCAAgDIABgFIAAg6QAAgPgDgFQgFgJgKAAQgKAAgHAJQgDAHAAAOIAAA5IABAIQACAEAJAAIAAAFIgVgBIgVABIAAgFQAGAAADgCQAEgBAAgEIABgGIAAhJIgBgIQAAgGgFgBIgIAAIAAgEQAQgCAKgFQABAHABAOQAKgTARAAQAQAAAIAPQAEAIAAASIAAA4QAAAGACADQACAEALAAIAAAFIgWgBgAQog9IgSgSIgTASIgFAAIAUgcIAJAAIAUAcgAJcg9IgSgSIgTASIgFAAIAUgcIAJAAIAUAcgAnAg9IgTgSIgSASIgGAAIAUgcIAJAAIAUAcgAvYg9IgTgSIgSASIgGAAIAUgcIAJAAIAUAcgADyhCIgbgeIAQAAIAQAegAiPhCIgbgeIAQAAIAQAegARZhHQgEgEAAgFQAAgGADgDQAEgFAEAAQAFAAADAFQADADAAAGQAAAFgDAEQgDADgFAAQgEAAgDgDgAmzhSIgcgeIAQAAIARAegAQohTIAQgeIAQAAIgbAeg");
	this.shape.setTransform(114.275,11.35);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,228.6,22.7);


(lib.Symbol24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AC4BnQgGgFgDgGQgEgHAAgIQAAgSATgIIgGgEQgFgEAAgGQAAgNAWgGQgIgDgFgFQgKgKAAgQQAAgQAJgKQAKgKAQAAQALAAAJAHIAbAAIAAAJIgTAAQAEAJAAALQAAASgNAKQgFAEgPAFIgOAFQgHADAAAFQAAAEAEABIAOACQAWACAJAEQAHAEAFAJQADAGAAAHQAAAIgDAHQgDAHgGAFQgLAKgUAAQgQAAgMgHgAC7BAQgIAFAAAKQAAALAJAGQAKAHAOAAQAOAAAJgHQAIgFAAgLQAAgVgiAAQgNAAgJAFgADGglQgFAIAAAOQAAAMAEAHQAFAJAKAAQAJAAAFgJQAEgHABgNQAAgegTAAQgJAAgFAJgAxqBCIAAg0IAEAAQAGArAeAAQAMAAAHgJQAIgJAAgNQAAgPgJgIQgFgDgOgJQgWgOgGgGQgJgKAAgRQAAgUALgLQAKgLARAAQAOAAAMAMIAFgNIAEAAIAAAsIgFAAQgCgNgEgIQgHgPgQAAQgLAAgHAJQgHAIAAAMQAAAOAMAIIATANQAQAKAGAGQANALAAATQAAAVgMANQgLAMgRAAQgSAAgNgOIgHAPgAOIAuQgJgRABgWQgBgWAJgQQAJgUATAAQAJAAAHAHIAHAMIAAggIgdAAIAAgHIAdAAIAAgDIgBgKQgCgDgFgBIgDAAIgDAAIAAgEQAQgCAOgFIAAAcIAMAAIAAAHIgMAAIAABmIAAAKQACAEADACIAEAAIAGABIAAAEIgQADIgLADIgBgJIgCgKQgIAUgQAAQgSAAgKgUgAOQAHQAAAVAEAOQAFARANAAQAHAAAGgIQAIgLAAggQAAg0gWAAQgVAAAAAzgAkNA2QgNgLgGgXQgFgRABgTQAAgkANgYQAIgMALgGQAKgFAKAAQATAAANAOIAHgOIADAAIAAAvIgEAAQgJgngaAAQgUAAgIAVQgJAVAAAgQAAAeAHAUQAJAWAVAAQAMAAAJgKQALgMABgYIAHAAQAAASgFANQgGANgKAGQgKAHgMAAQgQAAgNgMgAMlArQgFAJgDAFQgIAIgLAAQgRAAgHgOQgFgIgBgSIAAg2IgBgKQgBgDgFgBIgGAAIAAgEQAPgCAOgFIAABPQAAAPADAGQAFAIAKAAQALAAAGgKQAEgHgBgPIAAgzIgBgKQgBgDgFgBIgGAAIAAgEQAPgCAOgFIAABhIABAIQACADAGAAIAGABIAAAEQgQACgLAEIgBgWgAK6ArQgEAKgEAEQgHAIgMAAQgQAAgIgOQgFgJAAgRIAAg2IgBgKQgCgEgLAAIAAgEQAQgCAOgFIAABPQAAAPADAGQAEAIAKAAQAMAAAFgKQAEgHAAgPIAAgzIgBgKQgCgEgLAAIAAgEQAQgCAOgFIAAAIQAGgIAAgHIgCAAQgIgCACgKQABgIAHAAQAKAAAAAMQAAAKgJANIgDAFIgEAEIAABQIABAIQABADAGAAIAHABIAAAEQgQACgMAEIgBgWgAH8AxQgLgQAAgaQAAgbAMgRQALgPARAAQAMAAAIAKIAFgMIADAAIAAAnIgEAAQgCgLgCgGQgDgHgFgDQgFgEgGAAQgMAAgGAQQgFAPAAAWQAAAyAXAAQASAAADgfIAIAAQgBANgEAJQgIARgSAAQgRAAgLgQgAFKAxQgKgQAAgaQAAgbALgRQALgPAQAAQAMAAAJAKIAFgMIADAAIAAAnIgEAAQgCgLgDgGQgDgHgEgDQgFgEgGAAQgMAAgGAQQgFAPAAAWQAAAyAXAAQASAAAEgfIAHAAQAAANgFAJQgIARgSAAQgRAAgLgQgAAYArQgFAJgDAFQgIAIgKAAQgQAAgJgOQgEgIAAgSIAAg2IgCgKQgBgDgFgBIgHAAIAAgEQAQgCAOgFIAABPQAAAPAEAGQAEAIAJAAQALAAAGgKQAEgHAAgPIAAgzIgCgKQgBgDgFgBIgHAAIAAgEQAQgCAOgFIAABhIABAIQACADAFAAIAHABIAAAEQgQACgLAEIgBgWgAh0AxQgLgQAAgaQAAgbAMgRQALgPAQAAQAMAAAJAKIAFgMIAEAAIAAAnIgFAAQgCgLgCgGQgDgHgFgDQgFgEgFAAQgNAAgFAQQgGAPAAAWQAAAyAXAAQASAAAEgfIAIAAQgBANgFAJQgIARgSAAQgRAAgLgQgAnvA2QgNgMgGgWQgFgRAAgUQAAglAOgWQAPgXAZAAQARAAAPAOIAIgOIADAAIAAAvIgEAAQgEgNgEgIQgEgJgIgFQgIgFgIAAQgPAAgKAMQgOASAAAtQAABMAmAAQANAAAOgKIAAgoIgCgHQgBgDgMgBIAAgGIAVABIAXgBIAAAGQgIABgDABQgCABgBADIAAAFIAAAnQgXARgVAAQgQAAgOgLgApjArQgEAJgEAFQgHAIgMAAQgQAAgIgOQgFgIAAgSIAAg2IgBgKQgCgDgFgBIgGAAIAAgEQAPgCAPgFIAABPQAAAPADAGQAEAIALAAQALAAAGgKQADgHAAgPIAAgzIgBgKQgCgDgFgBIgGAAIAAgEQAPgCAPgFIAABhIABAIQACADAFAAIAGABIAAAEQgQACgLAEIgBgWgArOArQgDAKgFAEQgHAIgMAAQgQAAgHgOQgGgJAAgRIAAg2IgBgKQgCgEgKAAIAAgEQAPgCAPgFIAABPQAAAPACAGQAFAIAKAAQAMAAAFgKQADgHAAgPIAAgzIAAgKQgDgEgKAAIAAgEQAPgCAPgFIAAAIQAFgIABgHIgDAAQgHgCACgKQABgIAHAAQAKAAAAAMQgBAKgIANIgEAFIgDAEIAABQIAAAIQACADAGAAIAGABIAAAEQgQACgMAEIgBgWgAv+AuQgJgQAAgYQAAgXAKgRQAKgSAUAAQAMAAAIAJQAHgJAAgHIgBAAIgBAAQgIgCABgKQACgIAHAAQAKAAgBAMQABALgKAMIgBACIgCADQANARAAAcQAAAXgKARQgKATgTAAQgSAAgLgTgAvugmQgJANAAAfQABA1AVAAQAWAAAAg0QAAg1gWAAQgHAAgGAIgAPtA5QgJgJABgOQgBgWAXgLQANgFARgDIAAgOQAAgMgEgFQgEgHgJAAQgIAAgFAFQgDADgBAGIAAACIAAADQABALgJAAQgGAAAAgIQAAgLAJgIQAKgKANAAQAKAAAIAFQAKAHACALIABARIAAAwQAAALACAFQABAFAFAAIAFgBIAAAHIgLABQgIAAgFgHQgBgFgBgIQgEAJgEAEQgHAIgMAAQgMAAgHgIgAQCAHQgNAIAAASQAAAKAEAGQAFAFAHAAQANAAAEgOQADgHAAgOIAAgUQgOACgJAGgAGdA5QgIgJAAgOQAAgWAXgLQANgFAQgDIAAgOQAAgMgDgFQgEgHgKAAQgHAAgFAFQgEADAAAGIAAACIAAADQAAALgIAAQgHAAABgIQAAgLAJgIQAJgKAOAAQAJAAAIAFQAKAHADALIABARIAAAwQAAALABAFQABAFAGAAIAEgBIAAAHIgKABQgJAAgEgHQgCgFgBgIQgEAJgEAEQgGAIgNAAQgMAAgHgIgAGyAHQgNAIAAASQAAAKAFAGQAEAFAIAAQAMAAAFgOQACgHAAgOIAAgUQgOACgJAGgARVA+IgWABIAAgEQAGgBAEgBQADgCABgEIAAgFIAAhLIgBgKQgBgDgGgBIgGAAIAAgEQAQgCAOgFIAABkIABAIQADAEAKABIAAAEIgWgBgACLA+IgVABIAAgEQAGAAADgCQADgCABgEIAAgFIAAg6QAAgOgDgGQgEgJgKAAQgLAAgGAKQgEAGAAAOIAAA5IABAIQACAEAKABIAAAEIgVgBIgWABIAAgEQAGgBADgBQAEgCABgEIAAgFIAAhKIAAgIQgBgFgFgBIgIgBIAAgEQAQgCAKgFQACAHAAAOQALgTAQAAQAQAAAIAPQAFAJgBARIAAA5QAAAGACACQACAEALABIAAAEIgWgBgAsxA+IgVABIAAgEQAGAAADgCQADgCABgEIAAgFIAAg6QAAgOgDgGQgEgJgKAAQgKAAgHAKQgEAGAAAOIAAA5QAAAGABACQACAEAKABIAAAEIgWgBIgVABIAAgEQAHgBADgBQAEgCAAgEIAAgFIAAh4IgBgKQgCgDgEgBIgGAAIAAgFQAPgBAOgFIAAA/QAJgQAQAAQAQAAAJAPQAEAJAAARIAAA5QAAAGABACQACAEAMABIAAAEIgXgBgAmMA/IAAgGQAIgBADgBQAEgDABgEIAAgHIAAh0IgBgKQgCgEgGgBIgHgBIAAgGIAZACIAYgCIAAAGIgMACQgDACgBAFIAAAHIAABzIABAJQACAGAKAAIAOAAQAJAAAEgDQAFgDADgHQAEgHACgLIAEAAIgEAngAvlhDQAAgGABgCQACgEAEgFQAEgFAAgFQAAgJgHAAQgJAAgBAMIgEAAQAAgMAIgEQADgCAFAAQAGAAADADQAGAEAAAIQAAAGgFAEIgDAEIgGAFIgDAIgAGwhFIARgeIAQAAIgbAegAAKhFIgageIAQAAIAQAegARNhKQgDgEgBgFQAAgGADgDQAEgEAEAAQAFAAADAEQADADAAAGQAAAFgDAEQgDAEgFAAQgEAAgDgEgAQJhQQgFgEgDAAQgHAAgDAKIgEgBQACgJADgFQAEgFAGAAQAGAAAFAFQAIAHAFAAQAFgBADgLIADABQgBAKgEAFQgEAFgFABQgFAAgJgIgArlhSQgFgEgEAAQgGAAgDAKIgFgBQACgKAEgEQAFgFAFAAQAFAAAGAFQAIAHAEgBQAFAAADgLIAEABQgBAKgFAFQgDAFgGAAIAAAAQgGAAgHgHg");
	this.shape.setTransform(113.1,11.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,226.2,22.1);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg3();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.3389,0.3389);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,305,416.8);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AO4BgQgRgQgIgfQgGgWABgaQgBgwATgfQAIgQAPgJQANgHAOAAQAYAAARAUIAJgTIAEAAIAAA/IgFAAQgLg1giAAQgaAAgMAcQgMAcAAArQAAApALAaQAMAeAaAAQAQAAANgOQAOgQABggIAKAAQgCAYgGARQgIARgOAJQgMAJgQAAQgUAAgRgPgAiFBvIAAg2IAGAAQACAOAEAIQAEAKAHAGQAHAFAKAAQALAAAIgJQAHgIAAgMQAAgLgIgHQgFgEgOgIIgTgMQgSgLAAgVQAAgUALgLQALgMARAAQANAAANAKIAEgNIAFAAIAAAxIgGAAQgEglgXAAQgLAAgIAJQgFAHgBAKQAAAKAGAFQAEAEANAHIAQAJQAMAHAHAHQAHAKABAQQAAATgMANQgLAOgTAAQgRAAgOgOIgGAPgAl0BZQgOgXAAgiQAAggANgXQANgWAVAAQANAAAJAJQADAFAGALIAAg4QAAgKgBgDQgCgFgHgBIgIAAIAAgGQAUgCASgGIAAC3IABANQACAGAEACIAMABIAAAGQgVADgMAFQgDgNgBgNQgLAbgVAAQgVAAgNgWgAlsAgQAAAdAFASQAEALAFAGQAHAGAIAAQAKAAAHgLQAKgPAAgpQAAhHgdAAQgbAAAABEgAKRBfQgRgQgIgdQgFgXAAgbQAAgxASgeQATgeAgAAQAXAAASASIAKgTIAFAAIAABAIgGAAQgEgSgGgLQgFgLgKgHQgKgHgMAAQgTAAgMAQQgSAYgBA8QAABlAyAAQAQAAATgMIAAg2QgBgHgBgCQgDgGgPgBIAAgIQARACAMAAQALAAASgCIAAAIQgLABgEACQgCACgBAFIAAAGIAAA0QgeAXgcAAQgVAAgSgPgApaBYQgNgVAAgjQgBgkAPgWQAOgVAWAAQAQAAAKANIAHgQIAFAAIAAA0IgGAAQgCgOgEgIQgDgJgHgFQgGgFgHAAQgRAAgHAVQgHATAAAfQAABEAeAAQAXAAAGgqIAKAAQgCARgGAMQgKAXgXAAQgXAAgOgWgADIBZQgOgWAAgkQAAgiAOgWQANgVAXAAQARAAANANQARATAAAqIhNAAIAAAGQAAAbAIATQAIATASAAQATAAAJgUQAEgJABgMIAKAAQgBASgIANQgNAVgXAAQgZAAgNgVgADPAQIA3AAQgBg2gZAAQgZAAgEA2gAjvBZQgPgWAAgkQAAgiAPgWQANgVAXAAQARAAANANQAQATABAqIhNAAIAAAGQAAAbAHATQAIATATAAQASAAAJgUQAEgJACgMIAKAAQgCASgHANQgNAVgYAAQgZAAgMgVgAjpAQIA4AAQgCg2gYAAQgZAAgFA2gAnpBZQgPgWAAgkQAAgiAPgWQANgVAXAAQARAAAMANQARATABAqIhNAAIAAAGQAAAbAHATQAIATATAAQATAAAIgUQAEgJACgMIAKAAQgCASgIANQgMAVgYAAQgYAAgNgVgAniAQIA3AAQgCg2gYAAQgaAAgDA2gAsyBZQgOgWAAgkQAAgiAOgWQAOgVAWAAQASAAANANQAQATABAqIhNAAIAAAGQAAAbAIATQAHATATAAQATAAAJgUQADgJABgMIALAAQgCASgHANQgNAVgYAAQgZAAgNgVgAsrAQIA4AAQgCg2gZAAQgZAAgEA2gAGRBqQgMAAgQACIAAgHQAIAAADgCQAEgDACgEIAAgHIAAhPQAAgSgEgIQgGgMgNAAQgOAAgHANQgGAJAAARIAABOQAAAHABADQAEAGAMAAIAAAHQgRgCgLAAQgLAAgRACIAAgHQAJAAAEgCQAEgCABgGIABgHIAAhiIgBgLQgBgHgGgBIgKgBIAAgFQAUgEAOgGIACAcQAOgZAVAAQAVAAAKATQAGAMABAWIAABNQgBAIACADQADAGAOAAIAAAHQgRgCgLAAgAqvBqQgMAAgRACIAAgHQAIAAAFgCQAEgCABgGIAAgHIAAhiIAAgMQgBgHgHgCIgKAAIAAgGQAUgCANgFIADAeQADgKAFgHQAJgMANAAQALAAAGAIQAGAHgBALQAAAGgCAEQgDAFgFAAQgFAAgDgDQgDgDAAgEIABgHIAAgDQAAgDgCgDQgCgCgDAAQgMAAgHAUQgDAMAAATIAABDQgBAIACADQADAGAOAAIAAAHQgRgCgLAAgAtzBpQgMAAgTADIAAgIQAJgBAFgCQAGgDAAgGIABgIIgCimIgrCOIgHAWIgGAXIgEAAIg3i8IgGCmIAAADQAAAHACADQADAGARACIAAAIIgZgCIgbACIAAgIQALgBAFgCQAEgDABgGIABgJIAGicIAAgBQgBgJgBgEQgEgGgQgCIAAgHIAWABQAMAAAMgCIAvChIAxihIAZACIAUgBIAAAHQgKABgFACQgGAEAAAMIAAADIACCcQAAAJACAEQADAHARABIAAAIQgVgDgMAAgAMRBrIAAgIQALgBAEgCQAFgDABgGIABgJIAAibQgBgKgBgEQgCgFgJgCIgJgBIAAgHQAUACAMAAQANAAAUgCIAAAHQgMABgEACQgEADgCAHIAAAJIAACaQAAAJABACQADAIANAAIASAAQANAAAFgEQAFgDAFgKQAEgJADgPIAHAAIgHA0gAG7BrIBGiOIgdAAQgJAAgEADQgHAEgFANIgEANIgGAAIAGgpIBVAAIhFCNIAeAAQALAAAGgEQAJgIAGgZIAFAAIgHAugAAkBrIAAgIQAMgBADgCQAGgDABgGIAAgJIAAiaQAAgKgBgEQgEgHgRgBIAAgIIBFAAQAMAAAIADQAJADAGAGQAPAPABAaQAAAigdANQALADAGAEQAIAGAGALQAFAMAAAQQAAAVgLARQgKAQgTAFQgIACgNAAgABPBQQAAALADACQAEAEAKAAIAJAAQAQAAAJgLQAKgNABgaQAAgYgKgMQgIgLgTAAIgZAAgABPgJIASAAQANAAAGgDQAQgKABgfQAAgVgIgLQgGgLgRAAIgXAAgAglAcIAAgOIBBAAIAAAOg");
	this.shape.setTransform(104.65,11.075);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,209.3,22.2);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg2();
	this.instance.parent = this;
	this.instance.setTransform(3,20,0.3411,0.3411);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(3,20,307,414.1);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.logomec();
	this.instance.parent = this;
	this.instance.setTransform(-225,19,0.105,0.105);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1208));

	// Layer_1
	this.instance_1 = new lib.logo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-15,-11,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1208));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-225,-11,250,40.7);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEFEFE").s().p("AG/BJIAAgKQALAAAFgFQAEgDADgIIACgHIgbhQIANAAIAVBCIAXhCIAMAAIgaBKQgGARgEAFQgIARgUAAIgDAAgAEoBDQgJgGAAgKQAAgJAHgGQAEgDAGgCQgJgDAAgGQAAgGAHgEIAIgDQgQgGAAgQQAAgOAJgHQAJgHALAAQAHAAAGADIAYgCIAAAKIgQgBQAHAHAAAMQAAAMgJAEQgEAFgNADIgNADQgFACAAADQAAADAEACIANABQAMAAAEACQATAEAAARQAAANgKAHQgLAEgPAAQgSAAgJgGgAExAnQgHAFAAAGQAAAGAHAFQAHAEALAAQAOAAAGgFQAFgEAAgGQAAgOgaAAQgKAAgHADgAE3gaQgGAFAAAIQAAAGAGAFQAEAFAHgBQAIABAFgEQAEgFAAgHQAAgIgDgEQgGgFgIgBQgGAAgFAFgAhTBJIAAhZIgBgQIgBgIIANAAIABANQAHgPAPgBQALAAAJAJQALAMAAAWQAAAWgLAMQgIAIgLAAQgPAAgIgNIAAAsgAhAgZQgHALAAAOQAAAPAGAKQAFAGALAAQAIAAAEgFQAIgKAAgQQAAgQgJgJQgEgGgIAAQgKAAgEAGgAF8AkQgIgGAAgMQAAgRASgFQAKgDAUgEIAAgEQAAgIgDgDQgEgFgKAAQgPAAgCANIgMAAQABgLAGgFQAJgJAOAAQAMAAAIAHQAGAFABAJIABAMIAAAcQAAAPABAGIgLAAIgCgKQgHANgQAAQgLAAgGgGgAGKAEQgLAFAAAIQAAAHAFAEQAEADAHAAQAMABAFgKQAEgFAAgNIAAgIQgSAEgIAEgABbAkQgIgGAAgMQAAgRASgFQAKgDATgEIAAgEQAAgIgCgDQgDgFgLAAQgOAAgDANIgMAAQABgLAGgFQAIgJAPAAQANAAAGAHQAIAFAAAJIABAMIAAAcQAAAPABAGIgLAAIgCgKQgGANgRAAQgLAAgGgGgABpAEQgLAFAAAIQAAAHAGAEQADADAHAAQAMABAGgKQACgFAAgNIAAgIQgRAEgIAEgAlMAkQgIgGAAgMQAAgRATgFQAKgDAUgEIAAgEQAAgIgCgDQgFgFgJAAQgQAAgCANIgMAAQABgLAHgFQAHgJAPAAQANAAAHAHQAHAFAAAJIABAMIAAAcQAAAPACAGIgMAAIgBgKQgIANgQAAQgLAAgHgGgAk8AEQgMAFAAAIQAAAHAFAEQAEADAHAAQAMABAGgKQADgFAAgNIAAgIQgSAEgHAEgAEDAnIAAgsQAAgOgDgEQgDgIgLAAQgMABgFAIQgEAHAAALIAAArIgMAAIAAgzQAAgQgBgEIAAgIIALAAQACAGAAAHQAHgPAQgBQALAAAHAHQAGAFABAKIABAPIAAAtgAAyAnIAAgsQAAgOgCgEQgEgIgKAAQgLABgGAIQgEAHAAALIAAArIgMAAIAAhvIAMAAIAAAqQAJgNAOAAQAJABAHAEQAGAGADAIQABAEAAAOIAAAtgAihAnIAAgvIgBgKQgBgNgOAAQgLABgFAHQgDAGAAAKIAAAuIgMAAIAAguQAAgNgCgEQgDgHgLAAQgFAAgEACIgHAGQgDAHAAAJIAAAuIgLAAIAAg2IAAgQIgDgJIALAAQADAFAAAHQAHgOAQgBQAQABAFAPQAJgPAQgBQAPAAAGAMQACAEAAAIIABALIAAAvgAlzAnIAAgsQAAgOgCgEQgFgIgKAAQgLABgGAIQgEAHAAALIAAArIgLAAIAAhvIALAAIAAAqQAJgNAOAAQAKABAFAEQAIAGACAIIABASIAAAtgAnDAnIgxg5IAug1IAPAAIgtA1IAyA5gAoBAnIAAhuIANAAIAAA1IAAA5gAn0gSgABpg0IAPgTIAMAAIgSATgAk8g0IANgTIANAAIgSATg");
	this.shape.setTransform(41.575,8.05);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0066CC").s().p("AmpBoIAAjPINTAAIAADPg");
	this.shape_1.setTransform(41.5258,7.6894,1.4577,1.4038);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-20.6,-6.9,124.30000000000001,29.200000000000003);


(lib.Symbol10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADsBpQgDgDAAgEQAAgFADgEQACgCAEAAQAEAAACACQADAEAAAFQAAAEgDADQgCADgEAAQgEAAgCgDgAhZBpQgDgDAAgEQAAgFADgEQACgCAEAAQAEAAACACQADAEAAAFQAAAEgDADQgCADgEAAQgEAAgCgDgAB1AwQgLgQAAgaQAAgYAKgRQAKgQAQgBQALAAAGAHIAHAMIAAgqQAAgHgBgCQgCgEgFgBIgGAAIAAgEQAQgCAOgEIAACIIABAKQABAFADABIAJABIAAAFQgQACgKADIgDgTQgIAUgQAAQgQAAgKgRgAB7AGQAAAWAEAOQACAHAFAFQAFAEAGABQAIgBAFgHQAIgMAAgfQAAg1gWAAQgVAAAAAzgAKCAtQgJgQAAgXQAAgYAKgRQALgSATAAQANAAAIAJQAGgIAAgIIAAAAIgCAAQgIgCACgKQACgIAHAAQAKAAgBAMQAAALgJAMIgCACIgBADQAMARAAAcQAAAYgJAQQgKAUgTgBQgTABgLgUgAKSgmQgIAMAAAgQAAA1AVAAQAXAAAAg1QAAg1gWAAQgIAAgGAJgAHGAwQgLgQAAgaQAAgbAMgQQALgQARAAQALAAAJAKIAFgMIAEAAIAAAnIgFAAQgCgLgCgGQgDgHgFgDQgFgEgGAAQgMAAgGAQQgFAPAAAWQAAAyAXAAQASABAEggIAIAAQgCANgEAJQgIARgSAAQgRAAgLgQgAE2AvQgKgQAAgZQAAgaALgQQALgRASAAQARAAAKARQAKARAAAYQAAAZgKARQgLARgRAAQgSAAgLgRgAFFgmQgIAMAAAgQAAA1AWAAQAIAAAGgKQAIgNAAgeQAAg1gWAAQgIAAgGAJgAgSAwQgLgQAAgaQAAgbAMgQQALgQAQAAQALAAAJAKIAFgMIAEAAIAAAnIgFAAQgCgLgCgGQgDgHgFgDQgFgEgGAAQgLAAgGAQQgFAPAAAWQAAAyAWAAQASABAEggIAIAAQgCANgEAJQgIARgSAAQgQAAgLgQgAhwAvQgKgQAAgZQAAgaALgQQALgRASAAQARAAAKARQAKARAAAYQAAAZgKARQgLARgRAAQgSAAgLgRgAhhgmQgIAMAAAgQAAA1AWAAQAIAAAGgKQAIgNAAgeQAAg1gWAAQgIAAgGAJgAijArQgEAIgEAFQgIAIgLAAQgQAAgIgNQgGgJAAgSIAAg2IgBgJQgBgEgFgBIgHAAIAAgEQAQgCAOgEIAABPQAAAOAEAGQAEAIAKAAQALAAAGgKQAEgHAAgPIAAgzQAAgHgCgCQgBgEgFgBIgGAAIAAgEQAPgCAPgEIAABgIABAJQABACAGABIAGAAIAAAEQgQACgLAEIgBgVgAkwAwQgLgQAAgaQAAgbAMgQQALgQARAAQALAAAJAKIAFgMIAEAAIAAAnIgFAAQgCgLgCgGQgDgHgFgDQgFgEgGAAQgMAAgGAQQgFAPAAAWQAAAyAXAAQASABAEggIAIAAQgCANgEAJQgIARgSAAQgRAAgLgQgAscAwQgKgQAAgaQAAgbAMgQQAKgQARAAQAMAAAIAKIAGgMIADAAIAAAnIgEAAQgCgLgDgGQgDgHgFgDQgFgEgFAAQgNAAgFAQQgGAPAAAWQAAAyAXAAQATABADggIAIAAQgBANgEAJQgJARgRAAQgSAAgLgQgAMUA8QgDgEAAgFQAAgGADgEQADgEAFAAQAFAAADAEQADAEAAAGQAAAFgDAEQgDAEgFAAQgFAAgDgEgADXA4QgIgJAAgNQAAgXAXgLQANgFAQgDIAAgOQAAgMgDgFQgEgHgJAAQgIAAgFAFQgEADAAAGIAAACIABADQAAAMgIgBQgHAAAAgIQAAgLAJgIQAKgKANAAQAKAAAIAGQAKAGACAMQABAGAAAKIAAAwQAAALACAGQABAEAFAAIAFgBIAAAHIgLABQgJABgDgIQgDgEAAgJQgEAJgEAEQgHAIgMAAQgMAAgIgIgADtAGQgOAIAAASQAAAKAFAGQAEAFAIABQANgBAEgOQACgGAAgPIAAgTQgNACgJAFgAnCA4QgIgJAAgNQAAgXAXgLQANgFAQgDIAAgOQAAgMgDgFQgEgHgJAAQgIAAgFAFQgEADAAAGIAAACIABADQAAAMgIgBQgHAAAAgIQAAgLAJgIQAKgKANAAQAKAAAIAGQAKAGACAMQABAGAAAKIAAAwQAAALACAGQABAEAFAAIAFgBIAAAHIgLABQgJABgDgIQgDgEAAgJQgEAJgEAEQgHAIgMAAQgMAAgIgIgAmsAGQgOAIAAASQAAAKAFAGQAEAFAIABQANgBAEgOQACgGAAgPIAAgTQgNACgJAFgALqA+IgWAAIAAgEQAHAAADgCQADgBABgEIAAgGIAAhLIgBgJQgBgEgFgBIgHAAIAAgEQAQgCAOgEIAABjIABAIQADAFALAAIAAAEIgXAAgAJXA+IgVAAIAAgEQAGAAADgCQADgCABgDIAAgGIAAg5QAAgPgDgGQgFgIgKgBQgKAAgGAKQgEAGAAAPIAAA4IABAIQACAFAKAAIAAAEIgWAAIgVAAIAAgEQAGAAADgCQAEgBAAgEIABgGIAAh4IgBgJQgCgEgFgBIgGAAIAAgEQAPgCAPgEIAAA/QAJgQAQgBQAQABAIAPQAFAIAAASIAAA4IABAIQACAFALAAIAAAEIgWAAgAnsA+IgWAAIAAgEQAHAAADgCQAEgBAAgEIABgGIAAh4QAAgHgCgCQgBgEgFgBIgHAAIAAgEQAQgCAOgEIAACQQAAAGACACQACAFALAAIAAAEIgXAAgApUA+IgWAAIAAgEQAHAAADgCQADgBABgEIAAgGIAAhLIgBgJQgCgEgFgBIgGAAIAAgEQAQgCAOgEIAABjIABAIQACAFALAAIAAAEIgWAAgAqKA+IgWAAIAAgEQAGAAADgCQAEgCAAgDIAAgGIAAg5QAAgPgDgGQgEgIgKgBQgLAAgGAKQgEAGAAAPIAAA4IABAIQADAFAJAAIAAAEIgVAAIgWAAIAAgEQAHAAADgCQADgBABgEIAAgGIAAh4IgBgJQgCgEgFgBIgGAAIAAgEQAQgCAOgEIAAA/QAKgQAPgBQAQABAIAPQAFAIAAASIAAA4IABAIQADAFAKAAIAAAEIgVAAgAhBhAIgTgSIgSASIgGAAIAUgdIAKAAIATAdgApahCIABgHIAGgJQAEgGAAgEQAAgJgHAAQgJAAgBALIgEAAQAAgLAIgFQADgBAFgBQAGAAADADQAGAFAAAHQAAAHgFAEIgDADIgGAGQgCADgBAEgAmdhGIgcgdIAQAAIARAdgALihKQgDgEAAgGQAAgGADgDQADgEAFAAQAEAAADAEQAEADAAAGQAAAGgEAEQgDADgEAAQgFAAgDgDg");
	this.shape.setTransform(80.375,55.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.3,44.6,161.4,21.699999999999996);


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg1();
	this.instance.parent = this;
	this.instance.setTransform(-2,-2,0.3378,0.3378);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2,-2,304,413.4);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AicBpQgDgDAAgEQAAgFADgEQACgCAEAAQAEAAACACQADAEAAAFQAAAEgDADQgCADgEAAQgEAAgCgDgAARAtQgJgQAAgXQAAgVAJgRQAJgUASAAQALAAAGAHQADAEAFAIIAAggIgeAAIAAgHIAeAAIAAgDQgBgHgBgCQgBgEgFgBIgDAAIgEAAIAAgEQAQgCAOgFIAAAcIANAAIAAAHIgNAAIAABmIABAKQABAFADABIAFAAIAEABIAAAEIgOADIgMADIgBgJIgBgKQgIAUgRAAQgSAAgKgUgAAZAGQAAAWAEAOQAFAQANAAQAHAAAHgHQAHgMABgfQgBg1gWAAQgVAAAAAzgAJsAvQgKgQAAgZQAAgaALgQQALgRASAAQARAAAKARQAKARAAAYQAAAZgKARQgLARgSAAQgSAAgKgRgAJ7gmQgIAMAAAgQAAA1AVAAQAJAAAGgKQAIgNAAgeQAAg1gXAAQgHAAgGAJgAG5AwQgKgQAAgaQAAgbAMgQQALgQAQAAQAMAAAJAKIAFgMIAEAAIAAAnIgFAAQgCgLgCgGQgEgHgEgDQgFgEgGAAQgMAAgGAQQgFAPAAAWQAAAyAXAAQASABAEggIAIAAQgCANgEAJQgJARgRAAQgRAAgMgQgAizAvQgKgQAAgZQABgaAKgQQALgRATAAQARAAAKARQAJARABAYQgBAZgJARQgMARgRAAQgSAAgLgRgAijgmQgJAMAAAgQAAA1AWAAQAJAAAFgKQAIgNAAgeQAAg1gWAAQgIAAgFAJgAINA4QgIgJAAgNQAAgXAWgLQAOgFAQgDIAAgOQAAgMgDgFQgEgHgJAAQgIAAgGAFQgDADAAAGIAAACIABADQgBAMgHgBQgIAAAAgIQAAgLAJgIQALgKANAAQAKAAAIAGQAJAGACAMQACAGAAAKIAAAwQAAALABAGQACAEAFAAIAFgBIAAAHIgMABQgIABgDgIQgDgEAAgJQgFAJgDAEQgIAIgLAAQgMAAgIgIgAIjAGQgOAIAAASQAAAKAFAGQAEAFAHAAQANAAAFgOQACgGAAgPIAAgTQgNACgJAFgAFcA+IgWAAIAAgEQAGAAADgCQADgCABgDIAAgGIAAg5QAAgPgDgGQgEgIgKgBQgLAAgGAKQgEAGAAAPIAAA4IABAIQACAFAKAAIAAAEIgVAAIgWAAIAAgEQAGAAADgCQAEgBABgEIAAgGIAAh4IgBgJQgCgEgFgBIgGAAIAAgEQAPgCAPgEIAAA/QAKgQAPgBQAQABAIAPQAFAIAAASIAAA4IABAIQACAFALAAIAAAEIgVAAgADwA+IgWAAIAAgEQAHAAADgCQADgCABgDIAAgGIAAg5QAAgPgDgGQgFgIgKgBQgKAAgHAKQgDAGAAAPIAAA4IABAIQACAFAJAAIAAAEIgVAAIgWAAIAAgEQAHAAADgCQAEgBABgEIAAgGIAAhJIgBgJQAAgFgGgBIgIgBIAAgDQARgDAJgEIADAUQAKgSAQgBQARAAAHAPQAFAJABASIAAA4IABAIQACAFALAAIAAAEIgWAAgACDA+IgXAAIAAgEQAIAAACgCQAEgBABgEIAAgGIAAhLIgBgJQgCgEgFgBIgHAAIAAgEQARgCAOgEIAABjIABAIQACAFALAAIAAAEIgWAAgAhLA+IgXAAIAAgEQAIAAACgCQAEgBABgEIAAgGIAAhLIgBgJQgCgEgFgBIgHAAIAAgEQAQgCAPgEIAABjIABAIQACAFALAAIAAAEIgWAAgAjeA+IgWAAIAAgEQAGAAAEgCQACgBABgEIAAgGIAAg9QAAgMgCgFQgEgJgJAAQgVAAAAAdIAAA6IACAIQACAFAKAAIAAAEIgVAAIgVAAIAAgEQAGAAADgCQADgBABgEIAAgGIAAg8QAAgNgDgGQgEgHgJgBQgLAAgGALQgDAGAAAPIAAA3IABAIQADAFAJAAIAAAEIgVAAIgWAAIAAgEQAGAAADgCQAEgBABgEIAAgGIAAhJIAAgJQgBgEgCgBIgLgCIAAgDQARgEAJgDQACAJAAALQAEgHADgEQAJgIALAAQARAAAHATQADgHAEgDQAIgJAMAAQASAAAGAPQAEAIgBAPIAAA8IABAIQACAFAMAAIAAAEIgWAAgAmvA+IgWAAIAAgEQAHAAADgCQADgBABgEIAAgGIAAhLIgBgJQgBgEgGgBIgGAAIAAgEQAQgCAOgEIAABjIABAIQADAFALAAIAAAEIgXAAgAnlA+IgVAAIAAgEQAGAAADgCQADgCAAgDIAAgGIAAg5QAAgPgCgGQgFgIgKgBQgKAAgHAKQgEAGAAAPIAAA4IABAIQADAFAJAAIAAAEIgVAAIgVAAIAAgEQAGAAADgCQADgBABgEIAAgGIAAh4IgBgJQgBgEgGgBIgFAAIAAgEQAPgCAOgEIAAA/QAKgQAQgBQAQABAHAPQAGAIgBASIAAA4IABAIQADAFALAAIAAAEIgWAAgApTA9IgZABIAAgFIAIgBQAGgBAAgEQAAgCgEgHIgkg/IgIALIAAAzQAAAIACACQACAFAMABIAAAFIgXgBIgZABIAAgFIALgDQAEgBABgGIABgGIAAh1QAAgIgCgCQgBgEgHgBIgHgBIAAgGIAZACIAYgCIAAAGQgJABgDACQgDABgCAGIAAAGIAAA3IAtg8QAEgEAAgCQAAgDgGgBIgHgBIAAgGIAVABIAUgBIAAAGQgIAAgDACQgHADgGAIIgiAtIAsBMQAGAJAGADQAEACAHABIAAAFIgbgBgAB9hCIABgHIAGgJQAEgGAAgEQAAgJgHAAQgKAAgBAMIgDAAQAAgMAIgFQADgCAFAAQAGAAADADQAGAFgBAHQABAHgFAEIgEADIgFAGQgDADAAAEgAhThKQgEgEAAgGQAAgFAEgEQADgEAEAAQAEAAADAEQAEAEAAAFQAAAGgEAEQgDADgEAAQgEAAgDgDgAm3hKQgDgEAAgGQAAgFADgEQADgEAEAAQAFAAADAEQAEAEgBAFQABAGgEAEQgDADgFAAQgEAAgDgDg");
	this.shape.setTransform(73.05,14.45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.4,3.6,137.4,21.7);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.514,1],-14.5,-4.6,14.7,4.7).s().p("AjwD8IC+pUIEjBeIi+JTg");
	this.shape.setTransform(24.125,34.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.3,69);


(lib.Symbol16copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AgbAAIA3AA");
	this.shape.setTransform(150.6,21.75);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiGBjQALgMAMgTQAKgSAFgOQgJAGgIAAQgPAAgJgOQgMgRAAgYQAAgZAMgRQAMgRATAAQAVgBAMAUQALARAAAZQAAA0g8A6gAh4gyQgEAMAAAUQAAAXAEAMQAEANAKAAQALAAAEgNQAEgNAAgTQAAgXgEgNQgEgNgLAAQgLAAgDAOgAjxBjQALgMAMgTQAKgSAFgOQgJAGgIAAQgPAAgKgOQgLgRAAgYQAAgZAMgRQAMgRAUAAQAUgBAMAUQALARAAAZQAAA0g8A6gAjjgyQgEAMAAAUQAAAXAEAMQAEANAKAAQALAAAEgNQAEgNAAgTQAAgXgEgNQgEgNgLAAQgLAAgDAOgAptBJQgEAKgEAEQgIAHgMAAQgQAAgJgOQgFgKAAgRIAAgzQAAgMgCgCQgDgDgJAAIAAgGQATgCATgHIAABVQABAOADAFQADAHAIAAQAJAAAFgKQACgGAAgLIAAg0QAAgLgCgDQgCgDgKAAIAAgGQAUgCATgHIAAALQAHgHACgJQgGAAgCgGQgDgFADgGQACgHAHgBIADABQAIACAAALQAAASgVATIAABNQAAAHACACQABACAGABIAFAAIAAAIQgTACgOAGIgDgXgAJZBIQgMgYABglQgBgmAMgYQAHgKAJgGQAIgGALABQAJAAAIAFQAIAFAFAJQAHAMADAQQAEASAAARQAAAmgNAYQgKAXgWAAQgWgBgMgWgAJnALQAAAkAEAVQAEATAMAAQALAAAFgUQAEgWAAgiQAAgngFgSQgFgSgKAAQgUAAAABLgAHvBIQgMgYAAglQAAgmAMgYQAHgKAJgGQAIgGAKABQAKAAAIAFQAIAFAGAJQAGAMAEAQQADASAAARQAAAmgMAYQgLAXgWAAQgXgBgLgWgAH9ALQAAAkAEAVQAFATALAAQALAAAFgUQAEgWAAgiQAAgngFgSQgFgSgKAAQgVAAABBLgAGFBIQgMgYAAglQAAgmAMgYQAGgKAJgGQAJgGAKABQAJAAAIAFQAJAFAFAJQAHAMADAQQAEASgBARQAAAmgMAYQgKAXgXAAQgWgBgLgWgAGSALQAAAkAFAVQAEATALAAQAMAAAEgUQAFgWgBgiQAAgngEgSQgFgSgLAAQgUAAAABLgAFMBZQgEgGAAgIQAAgJAEgFQAFgGAGAAQAGAAAGAGQAEAGAAAIQAAAIgEAGQgGAGgGAAQgGAAgFgGgADnBIQgMgYAAglQAAgmAMgYQAGgKAKgGQAIgGAKABQAJAAAJAFQAHAFAGAJQAHAMADAQQAEASAAARQAAAmgNAYQgLAXgVAAQgXgBgLgWgAD0ALQAAAkAFAVQAEATAMAAQAKAAAFgUQAEgWABgiQAAgngGgSQgFgSgJAAQgVAAAABLgAB8BIQgMgYABglQgBgmAMgYQAHgKAJgGQAIgGALABQAJAAAIAFQAIAFAFAJQAHAMADAQQAEASAAARQAAAmgNAYQgKAXgWAAQgWgBgMgWgACKALQAAAkAEAVQAEATAMAAQALAAAFgUQAEgWAAgiQAAgngFgSQgFgSgKAAQgUAAAABLgAASBIQgMgYAAglQAAgmAMgYQAGgKAJgGQAJgGAKABQAJAAAIAFQAJAFAFAJQAGAMAEAQQADASABARQgBAmgMAYQgKAXgWAAQgXgBgLgWgAAfALQAAAkAFAVQAEATAMAAQALAAAEgUQAFgWgBgiQAAgngEgSQgGgSgJAAQgVAAAABLgAglBZQgFgGAAgIQAAgJAFgFQAEgGAGAAQAHAAAEAGQAFAGAAAIQAAAIgFAGQgEAGgHAAQgGAAgEgGgAmZBZQgEgGgBgIQABgJAEgFQAFgGAGAAQAGAAAFAGQAFAGAAAIQAAAIgFAGQgFAGgGAAQgGAAgFgGgArkBWQgGgKAAgQIAAgEIABhIIgMAAIAAgJQAMAAAHgKQAIgLADgQIAHAAIAAAlIAUAAIAAAJIgUAAIgBBKIABAOQABAFADADQACACADAAQAHAAAHgIIAAALIgIAFQgHAEgIAAQgNAAgHgIgAlpBcIAAgYIAUgaQAhgsABgZQgBgKgFgHQgGgHgIAAQgMAAgGALQgEAFgCAMIgJAAIACgQQAEgTAMgHQAJgIAOABQAPgBAKAKQAMAMAAATQAAAQgJAQQgKARgTAZIgTAWIA9AAIgDAcgAoGBcIAAgYIATgaQAigsgBgZQABgKgGgHQgFgHgKAAQgLAAgHALQgDAFgCAMIgJAAIACgQQAEgTAMgHQAKgIAMABQAQgBAKAKQAMAMAAATQAAAQgJAQQgKARgUAZIgSAWIA9AAIgEAcgAK7AEQgHgLAAgRQAAgPAHgMQAHgMAMAAQAFAAAEACIAFAGIAAgQIgTAAIAAgGIATAAQAAgIgCgBQgBgCgGAAIAAgEQANgCAMgEIAAAVIAIAAIAAAGIgIAAIAABDQAAAFACADQABACAGAAIAAADIgKACIgLAEIgCgKIgEAGQgEAFgHAAQgMAAgIgMgALEgYQABAQABAIQADAMAHgBQAIAAABgKQADgIAAgRQAAgOgCgHQgCgNgIAAQgMgBAAAjgAp5gsIgagdIARAAIAOAdg");
	this.shape_1.setTransform(78.1,18.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2.4,8.3,152,19.8);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnrBgIAAg+IAGAAQACARAFALQAFAKAJAGQAGAEAHAAQAMABAHgLQAGgIAAgLQAAgPgKgKQgEgFgOgKQgUgOgGgIQgJgMAAgSQAAgXANgMQALgLARAAQANAAAJAHIAHAIIAGgRIAEAAIAAA1IgGAAQgCgPgFgKQgIgQgPAAQgKgBgGAJQgGAIAAALQAAAKAHAIIAMAKIAZATQAKAHAEAJQAGALAAAPQAAAWgMAQQgLAOgSAAQgPAAgNgKIgHgHIgIAUgAGlBXQgLgHgHgNQgNgYAAglQAAgjAKgZQAHgQAMgIQAMgJAOAAQAQABALAJQADAEAEAFIAHgTIAEAAIAAA8IgGAAQgDgRgFgKQgEgKgIgGQgHgFgIAAQgTAAgHAXQgHAXAAAeQAAAhAHATQAIAWATAAQAKAAAHgFQAIgGAFgJQAFgLABgQIAGAAQAAAWgHAPQgHAPgMAIQgKAGgMAAQgMAAgLgHgAA0BHQgEAJgEAEQgIAIgMAAQgQAAgIgPQgFgKAAgRIAAg0QAAgNgCgDQgCgDgJAAIAAgGQASgDATgGIAABYQAAAOACAFQAEAIAIAAQAJAAAFgLQACgFAAgMIAAg1QAAgNgCgDQgCgDgKAAIAAgGQAUgDASgGIAABlQAAAHACADQACACAFABIAGAAIAAAHQgUADgNAGQgCgLgBgMgAg9BHQgEAJgEAEQgIAIgMAAQgQAAgIgPQgGgKAAgRIAAg0QAAgNgCgDQgCgDgJAAIAAgGQATgDATgGIAABYQAAAOACAFQAEAIAIAAQAJAAAFgLQACgFAAgMIAAg1QAAgNgCgDQgCgDgKAAIAAgGQAUgDASgGIAAAKQAHgHACgJQgGAAgCgGQgDgFADgHQACgHAHgBIACABQAJACAAALQAAAUgVASIAABRQAAAHACACQACADAFABIAGAAIAAAHQgUADgNAGQgCgLgBgMgAl5BKQgLgTAAgaQAAgbALgRQAMgVAUAAQANAAAKAKQAGgGABgJQgFABgDgGQgCgGACgFQADgIAGAAIADAAQAIACAAALQAAARgOAPQANATAAAdQAAAagLASQgMAWgTgBQgTAAgMgTgAlrAdQAAAYADAQQADARALAAQALAAAEgTQACgPAAgWQAAgYgCgLQgDgXgMAAQgRAAAAA5gACkBFQgPgZAAgpQAAgpAQgYQAQgXAaAAQAQAAALAJIAJAIIAHgTIAEAAIAAA8IgGAAQgDgQgEgKQgFgLgIgGQgIgHgJAAQgjAAAABOQAAAjAGAWQAHAaAVAAQAJABAMgHIAAgtIgBgJQgCgFgLgBIAAgKIAaACIAZgCIAAAKQgHABgDACQgCACAAAEIAAAHIAAAlQgXAWgaAAQgbAAgQgYgAiiBZIgYACIAAgHQAHAAABgEQABgCAAgJIAAhCQAAgKgCgFQgEgIgIAAQgJgBgEAJQgDAGAAALIAABAQAAAJACACQABAEAHAAIAAAHIgYgCIgYACIAAgIQAJAAACgCQADgDAAgKIAAh5IgBgKIgBgGQgCgCgKAAIAAgHQATgCATgHIAABEQAJgPARgBQAQAAAIAQQAFAKAAARIAAA8QAAAKACADQADACAJAAIAAAIIgYgCgAEVBaIAAgKQAJAAADgBQADgCABgGIABgJIAAh1QAAgJgCgEQgBgEgHgBIgHAAIAAgKIAeACIAdgCIAAAKQgJAAgDABQgDADgBAFIgBAJIAAB5QAAAJACACQADADAHAAIAKAAQAKAAAGgGQAGgFAFgPIADgMIAGAAIgGAwgAlcg0IABgJIAGgJQADgEAAgFQAAgJgGAAQgIABgBAMIgEAAQAAgNAHgEQAEgCAFgBQAFAAADADQAFAFAAAHQAAAGgEAFIgHAHQgDAEgBAGgAhShAQgFgEgDAAQgGAAgDAMIgEgCQABgKAEgGQAEgGAGAAQAFAAAGAGQAHAHAEgBQAFAAADgMIAEACQgCALgEAGQgEAFgEABQgGAAgIgJg");
	this.shape.setTransform(54.625,13.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(5.4,3.6,98.5,19.099999999999998);


(lib.Symbol23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol25("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(63.05,38.4,1,1,0,0,0,114.2,11.3);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5).to({_off:false},0).to({x:114.8,alpha:1},11,cjs.Ease.get(1)).to({x:113.05},9,cjs.Ease.get(1)).wait(1384));

	// Layer_1
	this.instance_1 = new lib.Symbol24("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(62.3,10.6,1,1,0,0,0,113.1,11);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:114.05,alpha:1},11,cjs.Ease.get(1)).to({x:112.3},9,cjs.Ease.get(1)).wait(1389));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51.1,-0.4,280.3,50.199999999999996);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A3bPnIAA/NMAu3AAAIAAfNg");
	this.shape.setTransform(152,503.15);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},226).wait(3665));

	// Layer_1
	this.instance = new lib.Symbol22("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(152.5,208.4,1.3,1.3,0,0,0,152.5,208.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1,scaleY:1,alpha:1},17,cjs.Ease.get(1)).wait(3874));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-45.7,-62.5,396.4,665.5);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol20("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(104.7,11.1,1,1,0,0,0,104.7,11.1);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},12,cjs.Ease.get(1)).wait(2728));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,209.3,22.2);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AprCSIAAkjITXAAIAAEjg");
	mask.setTransform(40.45,11.6);

	// Layer_3
	this.instance = new lib.Symbol2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-47.6,9.65,1,1,0,0,0,24.1,34.5);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:127.9},23,cjs.Ease.get(1)).wait(67));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-21.5,-3,124,29.2);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(43.35,7.65,0.4,0.4,0,0,0,43.4,7.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:7.6,scaleX:1.1,scaleY:1.1,x:43.4,y:7.6,alpha:1},11,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(1944));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27,-8.3,136.7,32.1);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol10("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(27.3,11.8,1,1,0,0,0,62.3,11.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:63.8,alpha:1},11,cjs.Ease.get(1)).to({x:62.3},9,cjs.Ease.get(1)).wait(1170));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-35.3,44.6,197.89999999999998,21.699999999999996);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol16copy("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(72.3,32.2,1,1,0,0,0,100.9,8);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5).to({_off:false},0).to({x:104.5,alpha:1},11,cjs.Ease.get(1)).to({x:103.8},9,cjs.Ease.get(1)).to({_off:true},886).wait(1));

	// Layer_1
	this.instance_1 = new lib.Symbol6("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(61.5,11.8,1,1,0,0,0,96.5,11.8);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:97.25,alpha:1},11,cjs.Ease.get(1)).to({x:96.5},9,cjs.Ease.get(1)).wait(892));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.6,3.6,187.6,48.699999999999996);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol4("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(16.9,11.8,1,1,0,0,0,51.9,11.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:52.9,alpha:1},11,cjs.Ease.get(1)).to({x:51.9},9,cjs.Ease.get(1)).wait(56).to({startPosition:0},0).to({_off:true},1).wait(29).to({_off:false},0).wait(9).to({startPosition:0},0).to({_off:true},1).wait(6).to({_off:false},0).wait(146).to({startPosition:0},0).to({_off:true},1).wait(426));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30.6,2.7,214.7,22.6);


(lib.Symbol1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A3bPnIAA/MMAu3AAAIAAfMg");
	this.shape.setTransform(150,500.15);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},226).wait(4074));

	// Layer_2
	this.instance = new lib.Symbol8("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(151.2,67.8,1,1,0,0,0,151.2,68.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4300));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2,-3,304,603);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A3bPnIAA/MMAu3AAAIAAfMg");
	this.shape.setTransform(150,500.15);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},226).wait(4074));

	// Layer_1
	this.instance = new lib.Symbol17("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(154.05,203.75,1.3,1.3,0,0,0,160,226.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1,scaleY:1,x:154,y:203.7,alpha:1},17,cjs.Ease.get(1)).wait(4283));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50,-64.9,399.1,664.9);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_282 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(282).call(this.frame_282).wait(1));

	// logo
	this.instance = new lib.Symbol13("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(261.5,566.5,1,1,0,0,0,15.5,15.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(283));

	// Layer_12
	this.instance_1 = new lib.Symbol18();
	this.instance_1.parent = this;
	this.instance_1.setTransform(84.4,507.1,1,1,0,0,0,42.4,10.1);
	this.instance_1.alpha = 0.8008;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(175).to({_off:false},0).wait(108));

	// cta
	this.instance_2 = new lib.Symbol11("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(84.5,508.8,1,1,0,0,0,43.5,7.8);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(130).to({_off:false},0).wait(153));

	// Layer_6
	this.instance_3 = new lib.Symbol23("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(136.1,437,1,1,0,0,0,113.1,11);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(235).to({_off:false},0).wait(48));

	// Layer_13
	this.instance_4 = new lib.Symbol21("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(150.5,205.4,1,1,0,0,0,152.5,208.4);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(222).to({_off:false},0).wait(61));

	// Layer_7
	this.instance_5 = new lib.Symbol5("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(111.5,432.8,1,1,0,0,0,96.5,11.8);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(111).to({_off:false},0).wait(103).to({startPosition:102},0).to({x:124.5,alpha:0,startPosition:111},10,cjs.Ease.get(1)).to({_off:true},22).wait(37));

	// Layer_8
	this.instance_6 = new lib.Symbol1("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(150,300,1,1,0,0,0,150,300);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(98).to({_off:false},0).to({_off:true},148).wait(37));

	// Layer_10
	this.instance_7 = new lib.Symbol9("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(83.3,459.8,1,1,0,0,0,62.3,11.8);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(16).to({_off:false},0).wait(73).to({startPosition:111},0).to({x:113.3,alpha:0,startPosition:127},10,cjs.Ease.get(1)).to({_off:true},147).wait(37));

	// Layer_5
	this.instance_8 = new lib.Symbol3("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(67.9,471.8,1,1,0,0,0,51.9,11.8);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(12).to({_off:false},0).wait(77).to({startPosition:106},0).to({x:99.15,alpha:0,startPosition:122},10,cjs.Ease.get(1)).to({_off:true},147).wait(37));

	// Layer_4
	this.instance_9 = new lib.Symbol19("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(125.25,434.9,1,1,0,0,0,104.7,11.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(89).to({startPosition:118},0).to({alpha:0,startPosition:134},10,cjs.Ease.get(1)).to({_off:true},147).wait(37));

	// Layer_8 copy
	this.instance_10 = new lib.Symbol1copy("synched",0);
	this.instance_10.parent = this;
	this.instance_10.setTransform(150,300,1,1,0,0,0,150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({_off:true},246).wait(37));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50,-65.5,399.1,665.5);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.parent = this;
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(148,297.1,154,302.9);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg1.jpg?1700798555788", id:"bg1"},
		{src:"images/bg2.jpg?1700798555788", id:"bg2"},
		{src:"images/bg3.jpg?1700798555788", id:"bg3"},
		{src:"images/logomec.png?1700798555788", id:"logomec"},
		{src:"images/logo.png?1700798555788", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;