(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bg1 = function() {
	this.initialize(img.bg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,960,1511);


(lib.bg2 = function() {
	this.initialize(img.bg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,960,1785);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,200,200);


(lib.Symbol31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AhdAAIC7AA");
	this.shape.setTransform(4.575,1.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.8,0.8,20.8,1.9999999999999998);


(lib.Symbol30copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AQbCEQgIgFgEgIQgEgJAAgLQAAgWAXgLQgGgDgBgCQgGgFAAgIQAAgRAZgIQgIgEgHgGQgLgNAAgVQAAgVAKgMQALgNAUAAQANAAALAIIAfAAIAAAMIgXgBQAGAMAAAOQAAAYgPANQgHAGgSAGQgKADgGADQgIAEAAAHQAAAFAFACQADABANABQAaADALAFQAJAFAFALQADAIAAAKQAAAKgDAJQgEAJgGAGQgOAOgXAAQgUAAgNgLgAQeBTQgJAGAAANQAAAOAKAIQAMAJARAAQAQAAALgIQAJgIAAgOQAAgbgoAAQgQAAgKAHgAQrgxQgGALAAASQAAAQAFAJQAGAMAMAAQALAAAGgMQAEgJAAgRQAAgngVAAQgLAAgGALgANHCJQgEgEAAgGQAAgGAEgEQADgFAEAAQAEAAAEAFQADAEAAAGQAAAFgDAFQgEAEgEAAQgEAAgDgEgAMsA+QgMgWAAggQAAghANgWQANgVAVAAQAVAAALAWQAMAWAAAfQAAAhgMAWQgMAWgWAAQgUAAgNgWgAM+gyQgKARAAApQAABEAZAAQALAAAHgMQAJgQAAgoQAAhEgaAAQgJAAgHAKgAIrA8QgLgVAAgfQAAgfALgVQANgYAXAAQAPAAAKALQAHgKAAgKIgBAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgJgDACgMQACgLAIAAQALAAAAAQQAAAOgLAQIgCADIgCADQAPAVAAAlQAAAfgLAWQgMAYgXAAQgVAAgNgYgAI+gyQgKARAAApQAABEAZAAQAbAAAAhEQAAhEgbAAQgIAAgHAKgAlYA+QgLgWAAggQAAghANgWQAMgVAWAAQAUAAAMAWQALAWAAAfQAAAhgLAWQgNAWgVAAQgVAAgNgWgAlGgyQgKARAAApQAABEAaAAQAKAAAHgMQAJgQAAgoQAAhEgaAAQgJAAgHAKgAo9BUIAAi1QAAgJgCgDQgCgFgFAAIgIgBIAAgFQATgCAQgHIAABWQAFgKAEgFQAIgJAMAAQATAAAMAVQANAWAAAgQAAAhgNAVQgNAWgTAAQgUAAgKgbIgKAbgAodg1QgFAFgDAKQgGATAAAdQAAAcAFARQADAJAGAGQAGAFAGAAQAKAAAHgMQAKgPAAgpQAAhCgbAAQgGAAgGAGgAg0BJQgJgLAAgSQAAgcAagPQAPgHATgDIAAgTQAAgQgDgGQgFgJgLAAQgJAAgGAHQgEAEAAAHIAAADIAAAEQAAAOgJAAQgIAAAAgLQAAgOAKgKQAMgMAQAAQALAAAJAGQALAIADAQQABAHAAAOIAAA+QAAAPACAGQABAHAGAAIAGgBIAAAIQgIACgFAAQgKAAgFgJQgCgGgBgLQgEALgEAFQgIALgOAAQgOAAgJgLgAgbAIQgQALAAAXQAAAOAGAHQAFAHAIAAQAPAAAGgSQACgJAAgSIAAgaQgPACgLAHgAnHBJQgJgLAAgSQAAgcAagPQAPgHAUgDIAAgTQAAgQgEgGQgFgJgKAAQgKAAgGAHQgEAEAAAHIAAADIAAAEQAAAOgJAAQgIAAAAgLQAAgOAKgKQAMgMAQAAQAMAAAJAGQALAIADAQQACAHAAAOIAAA+IABAVQACAHAGAAIAGgBIAAAIQgIACgGAAQgKAAgEgJQgDgGAAgLQgFALgFAFQgIALgOAAQgOAAgJgLgAmuAIQgPALAAAXQAAAOAFAHQAFAHAJAAQAPAAAFgSQADgJAAgSIAAgaQgQACgLAHgAueBJQgJgLAAgSQAAgcAagPQAPgHATgDIAAgTQAAgQgDgGQgFgJgLAAQgJAAgGAHQgEAEAAAHIAAADIAAAEQAAAOgJAAQgIAAAAgLQAAgOAKgKQAMgMAQAAQALAAAKAGQALAIADAQQABAHAAAOIAAA+QAAAPACAGQABAHAGAAIAGgBIAAAIQgIACgFAAQgKAAgFgJQgCgGgBgLQgFALgEAFQgIALgOAAQgOAAgJgLgAuFAIQgQALAAAXQAAAOAGAHQAFAHAIAAQAPAAAGgSQACgJAAgSIAAgaQgPACgLAHgAPlBQQgKAAgPACIAAgGQAHAAAEgDQAEgCAAgFIABgGIAAhMQAAgSgEgIQgFgLgMAAQgMAAgIAMQgFAIAAASIAABLQAAAGACADQADAGAKABIAAAGQgOgCgLAAIgZACIAAgGQAIgBAEgCQAEgCAAgFIABgHIAAhfIgBgLQAAgHgGgBIgKAAIAAgGQATgEAMgFQACAIAAATQANgYATAAQATAAAKASQAFAMAAAWIAABKQAAAIABADQADAFANABIAAAGQgQgCgKAAgALfBQQgKAAgQACIAAgGQAIgBAEgCQAEgCABgFIAAgHIAAhfIAAgMQgBgHgGgBIgJgBIAAgFQASgDAMgEIACAdQADgKAEgGQAJgMAMAAQAJAAAGAIQAFAHAAAKQAAAGgDAEQgCAFgFAAQgEAAgDgDQgCgDAAgEIAAgHIABgDQAAgDgCgCQgCgCgDAAQgLAAgGATQgDALAAAUIAABAIABALQACAFAOABIAAAGQgRgCgKAAgAH4BQQgKAAgPACIAAgGQAHAAADgDQAEgCABgFIAAgGIAAhPQAAgRgDgGQgEgLgMAAQgXAAAAAkIAABNQAAAGABADQADAGALABIAAAGQgPgCgKAAIgYACIAAgGQAHAAADgDQAEgCABgFIAAgGIAAhPQAAgRgDgHQgFgKgKAAQgOAAgGANQgEAJAAASIAABJQAAAGABADQADAGALABIAAAGQgPgCgKAAQgKAAgPACIAAgGQAIgBADgCQAEgCABgFIABgHIAAhfIgBgLQAAgGgDgBQgDgBgKAAIAAgGQATgEAMgFQACAMAAAOIAJgNQAJgKANAAQAUAAAJAYIAIgOQAJgKAPAAQAUAAAHASQAFAKAAAVIAABNQAAAHABAEQADAFANABIAAAGQgQgCgKAAgAEEBQQgLAAgPACIAAgGQAIAAADgDQAEgCAAgFIABgGIAAhMQAAgSgEgIQgFgLgMAAQgMAAgHAMQgFAIAAASIAABLQAAAGABADQADAGALABIAAAGQgPgCgKAAQgKAAgQACIAAgGQAJgBADgCQAEgCABgFIAAgHIAAicQAAgJgBgDQgCgFgGAAIgHgBIAAgFQASgCARgHIAABSQALgUASAAQATAAAKATQAGALAAAWIAABKIABALQADAFAMABIAAAGQgPgCgKAAgACFBQQgKAAgPACIAAgGQAHAAAEgDQAEgCAAgFIABgGIAAhMQAAgSgEgIQgFgLgMAAQgMAAgIAMQgEAIAAASIAABLQAAAGABADQADAGALABIAAAGQgPgCgLAAQgJAAgQACIAAgGQAIgBAEgCQAEgCABgFIAAgHIAAhfIAAgLQgBgHgGgBIgJAAIAAgGQATgEALgFQACAIABATQAMgYATAAQATAAAKASQAFAMAAAWIAABKQAAAIACADQADAFAMABIAAAGQgPgCgLAAgAhlBQQgLAAgPACIAAgGQAHAAAEgDQAEgCAAgFIABgGIAAhMQAAgSgEgIQgFgLgMAAQgMAAgIAMQgFAIAAASIAABLQAAAGACADQADAGALABIAAAGQgPgCgKAAQgKAAgQACIAAgGQAIgBAEgCQAEgCABgFIAAgHIAAicQAAgJgBgDQgCgFgGAAIgHgBIAAgFQASgCAQgHIAABSQAMgUASAAQATAAAKATQAFALAAAWIAABKIABALQADAFANABIAAAGQgPgCgKAAgAqpBQQgKAAgPACIAAgGQAHAAAEgDQADgCABgFIAAgGIAAhPQAAgRgCgGQgFgLgMAAQgXAAAAAkIAABNQAAAGABADQADAGALABIAAAGQgPgCgJAAQgKAAgPACIAAgGQAHAAAEgDQADgCABgFIAAgGIAAhPQAAgRgDgHQgEgKgLAAQgOAAgGANQgEAJAAASIAABJQAAAGACADQACAGAMABIAAAGQgPgCgLAAQgKAAgPACIAAgGQAIgBADgCQAEgCABgFIABgHIAAhfIgBgLQAAgGgDgBQgDgBgKAAIAAgGQAUgEALgFQACAMAAAOIAJgNQAJgKANAAQAVAAAIAYIAIgOQAJgKAPAAQAUAAAIASQAEAKAAAVIAABNQAAAHABAEQADAFANABIAAAGQgQgCgKAAgAvQBQQgKAAgPACIAAgGQAHAAAEgDQAEgCAAgFIABgGIAAhMQAAgSgEgIQgFgLgMAAQgMAAgIAMQgEAIAAASIAABLIABAJQADAGALABIAAAGQgPgCgLAAQgJAAgQACIAAgGQAIgBAEgCQAEgCABgFIAAgHIAAhfIAAgLQgBgHgGgBIgJAAIAAgGQATgEALgFQACAIABATQAMgYATAAQATAAAKASQAFAMAAAWIAABKIABALQADAFANABIAAAGQgQgCgKAAgAzWBRIAAgSQAagoAPgaQAOgaAHgQQAFgQAAgMQAAgOgGgJQgHgKgMAAQgIAAgHAFQgHAFgEAIQgEAJgCAQIgHAAQACgcAHgMQAFgKAKgFQAJgFAKAAQARAAALALQAGAGAEAKQAEAKAAAJQAAAVgOAaQgOAagrA/IBIAAIgCAWgAS0g+IgPAfIgKgJIARgeIgbgKIAEgQIAaAOIgBgmIAMAAIgBAmIAagOIAEAQIgaAKIARAeIgKAJgANjhTIgWgXIgVAXIgHAAIAYglIAKAAIAYAlgAmohUIACgLIAHgLQAFgHAAgGQAAgMgJAAQgLAAgBAQIgEAAQAAgPAJgGQAEgDAGAAQAGAAAEAEQAGAFAAAKQABAIgFAGIgFAFIgGAHQgDAEgBAGgAuNhgQgHgKgCgPIAEAAQAEALAGAGQAGAGAIAAQAHAAAGgGQAHgHADgKIAFAAQgCAPgHAKQgIALgLAAQgLAAgIgLgAJIhYIACgKQACgFAFgGQAFgHAAgGQAAgMgJAAQgLAAgBAQIgEAAQAAgPAJgGQAEgDAGAAQAHAAADAEQAHAGAAAJQAAAJgFAFIgFAFIgGAHQgDAEgBAFgAgKhZIgggnIATAAIATAng");
	this.shape.setTransform(90.475,52.975);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-33.4,38.7,247.8,28.599999999999994);


(lib.Symbol30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACBBoQgMgVAAggQAAgjANgUQAMgWAWAAQAUAAAMAWQAMAWAAAgQAAAggMAWQgNAXgVAAQgVAAgMgXgACTgHQgLAPAAAqQAABFAaAAQAKAAAIgNQAIgQAAgnQAAhFgZAAQgKAAgGALgAhkB/IAAi1QAAgJgCgEQgCgEgFgBIgHAAIAAgGQASgCAQgGIAABVIAJgOQAIgKAMAAQAUAAALAWQAMAVAAAgQAAAigMAVQgNAVgTAAQgVAAgJgbIgKAcgAhEgLQgFAGgDAIQgFATgBAeQABAcAFARQACAKAGAGQAGAFAGAAQALAAAGgMQAKgQAAgoQAAhCgbAAQgGAAgGAFgAHpBqQgOgVAAgjQAAgiAOgVQALgUAVAAQAQAAALANQAPARAAAqIhFAAIAAAGQAAAaAHATQAGASASAAQARAAAIgTQADgJABgMIAJAAQgBARgHANQgLAUgVAAQgXAAgLgUgAHvAkIAxAAQgBg1gWAAQgXAAgDA1gAASBzQgKgLAAgSQAAgcAagOQAQgJATgDIAAgTQAAgOgDgGQgGgKgKAAQgJAAgHAHQgEAEAAAHIAAACIAAAFQABAOgKAAQgIAAAAgLQAAgNAKgLQAMgMAQAAQAMAAAJAGQALAJADAOQABAIAAANIAABAQAAAOACAHQACAGAGAAIAGgBIAAAIQgIACgFAAQgKAAgFgJQgCgGgBgLQgFALgEAGQgJAKgOAAQgOAAgIgLgAAqAzQgPAKAAAYQAAANAFAHQAGAIAIAAQAPAAAFgTQADgIAAgTIAAgbQgPAEgMAHgAnFBzQgKgLAAgSQABgcAagOQAPgJAUgDIAAgTQgBgOgDgGQgFgKgKAAQgKAAgGAHQgEAEAAAHIAAACIAAAFQAAAOgJAAQgIAAAAgLQAAgNALgLQALgMAQAAQALAAAKAGQALAJADAOQABAIAAANIAABAIABAVQADAGAGAAIAGgBIAAAIQgJACgFAAQgKAAgEgJQgDgGgBgLQgEALgFAGQgIAKgOAAQgOAAgJgLgAmsAzQgQAKAAAYQABANAFAHQAFAIAIAAQAPAAAGgTQACgIABgTIAAgbQgQAEgLAHgALZB6QgLAAgPACIAAgGQAHAAAEgCQADgDABgEIAAgHIAAhQQAAgQgCgGQgFgLgMAAQgWAAAAAkIAABNIABAKQADAGAKAAIAAAGQgPgCgJAAQgJAAgQACIAAgGQAIAAACgCQAEgDABgEIABgHIAAhPQAAgRgEgGQgEgLgLAAQgNAAgHANQgEAIAAASIAABKQABAHABADQACAGAMAAIAAAGQgPgCgKAAQgLAAgPACIAAgGQAIAAADgCQAFgCABgGIAAgGIAAhgIAAgLQgBgFgDgBQgDgCgKAAIAAgFQAUgEALgGQACANABAOIAIgOQAJgKANAAQAVAAAIAYIAIgNQAJgLAPAAQAUAAAHASQAFAJAAAVIAABPQAAAHACADQACAGANAAIAAAGQgQgCgJAAgAGzB6IgbACIAAgGQAJAAADgCQAEgCABgGIABgGIAAhjQgBgIgBgDQgCgFgGAAIgHgBIAAgFQATgDAQgFIAACBQgBAHACADQADAGANAAIAAAGIgagCgAFzB6QgKAAgQACIAAgGQAHAAAEgCQAEgDABgEIAAgHIAAhMQAAgSgEgIQgFgLgMAAQgMAAgIAMQgEAIAAASIAABLQAAAHABADQADAGALAAIAAAGQgPgCgKAAQgKAAgQACIAAgGQAJAAADgCQAEgCABgGIAAgGIAAicIgBgNQgCgEgGgBIgHAAIAAgGQASgCARgGIAABSQALgVASAAQATAAAKATQAFALABAWIAABLIABAKQACAGANAAIAAAGQgPgCgKAAgAjQB6QgKAAgPACIAAgGQAHAAAEgCQADgDABgEIAAgHIAAhQQAAgQgCgGQgFgLgMAAQgWAAAAAkIAABNIABAKQADAGAKAAIAAAGQgOgCgKAAQgKAAgOACIAAgGQAGAAAEgCQADgDABgEIABgHIAAhPQgBgRgDgGQgEgLgLAAQgOAAgGANQgDAIAAASIAABKQgBAHACADQACAGAMAAIAAAGQgPgCgKAAQgKAAgQACIAAgGQAIAAADgCQAFgCABgGIAAgGIAAhgIAAgLQgBgFgDgBQgDgCgKAAIAAgFQAUgEALgGQACANABAOIAIgOQAKgKAMAAQAVAAAIAYIAIgNQAKgLAOAAQAUAAAIASQAEAJAAAVIAABPQAAAHACADQACAGANAAIAAAGQgPgCgLAAgAn2B6QgLAAgOACIAAgGQAGAAAEgCQAEgDABgEIAAgHIAAhMQAAgSgEgIQgFgLgMAAQgMAAgIAMQgEAIAAASIAABLQAAAHABADQADAGAKAAIAAAGQgOgCgLAAQgJAAgPACIAAgGQAHAAAEgCQAEgCABgGIABgGIAAhgIgBgLQgBgGgGgBIgJgBIAAgFQATgEALgFQACAIABASQAMgYAUAAQASAAAKATQAFALAAAWIAABLQAAAHACADQACAGANAAIAAAGQgQgCgJAAgArNB6QgPAAgOACIAAgHQAJgBAEgCQAFgDABgGIAAgJIAAiNIgaAAIAAgIQAOgBALgJQAKgKAEgPIAHAAIAAC4QgBAJACAEQACAFAHACIAIABIAAAHQgOgCgOAAgAIegpIgWgXIgWAXIgHAAIAZgkIAKAAIAYAkgAAwgqIACgKIAHgLQAFgIAAgGQAAgLgIAAQgMAAgBAQIgEAAQAAgQAJgFQAEgDAGAAQAGAAAEAEQAGAFABAKQAAAIgFAGIgFAFIgGAGQgDAFAAAFgAm0g2QgHgJgCgPIAFAAQADAKAHAHQAFAFAIAAQAHAAAHgFQAGgHADgKIAFAAQgCAPgHAKQgIAKgLAAQgLAAgIgLgAGpg2QgEgEAAgIQAAgHAEgFQAEgFAFAAQAFAAAEAFQADAGAAAGQAAAIgDAEQgDAFgGAAQgFAAgEgFgAIghIQABgHABgDQACgFAFgGQAFgHAAgGQAAgMgIAAQgMAAgBAQIgDAAQAAgPAIgGQAFgDAFAAQAHAAAEAEQAGAFAAAKQAAAIgFAHIgEAEIgHAHQgCAEgBAFg");
	this.shape.setTransform(91.9,18.675);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(16.5,6,150.8,25.4);


(lib.Symbol29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah4BsIgUABIAAgEQAGgBADgBQADgCAAgEIABgGIAAgxQgEAJgDADQgGAIgKAAQgPAAgJgSQgKgRAAgaQAAgaAKgRQAKgRAPAAQAPAAAIAUIADgUQAJADAOABIAAAFIgCAAQgHAAgCADQgCAEAAAIIAAB+IABAJQACAEAKABIAAAEIgUgBgAihgrQgHANAAAfQAAA2AUAAQAVAAAAg3QAAg0gVAAQgIAAgFAJgAGJBlQgGgEgDgHQgDgHAAgJQAAgRARgJIgGgEQgDgEAAgHQAAgNATgHQgHgCgFgGQgIgKgBgQQABgSAHgJQAJgLAPAAQALAAAIAHIAZAAIAAAKIgSgBQAFAJgBAMQAAAUgMAJQgEAFgOAFIgOAEQgFADAAAGQgBAEAEABQACACALABQAVACAHAEQAIAEAEAJQADAGAAAIQAAAIgDAHQgDAIgFAEQgLALgSAAQgQAAgKgIgAGLA9QgGAFAAALQAAALAHAGQAJAHAOAAQAMAAAJgHQAHgGAAgLQAAgWgeAAQgOAAgIAGgAGVgsQgEAIAAAPQAAANAEAIQAFAIAJAAQAJAAAEgIQAEgIAAgOQAAgfgRAAQgJAAgFAJgADeBpQgDgEABgFQgBgEADgEQACgDAFAAQADAAACADQADAEAAAEQAAAFgDAEQgCADgDAAQgFAAgCgDgAmkA/IgHgaIgWhOQgBgIgEgBQgCgCgGAAIAAgFIAUABIASgBIAAAFIgFAAQgEABgBAEIABAGIATBLIAVhKIACgHQgBgEgDgBIgFAAIAAgFIANABIAOgBIAAAFQgGAAgCACQgEACgCAIIgVBMIgHAbgAgcAoQgEAJgEAEQgHAJgLAAQgOAAgHgOQgFgJgBgTIAAg3IgBgLQgBgDgEAAIgGgBIAAgEQAOgCAOgFIAABSQAAAPACAGQAFAJAJAAQAKAAAFgLQAEgHAAgPIAAg1IgBgLQgCgDgFAAIgGgBIAAgEQAPgCAOgFIAABkIABAJQABADAFAAIAGABIAAAEQgPACgKAEIgBgWgAllArQgJgRAAgZQAAgYAJgRQAKgUASAAQAMAAAHAKQAGgJgBgHIAAgBQAAABAAAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQgHgCACgKQABgIAHAAQAIAAAAAMQAAAMgIANIgCACIgCACQAMASAAAdQAAAYgIARQgKAUgRAAQgSAAgJgTgAlXgtQgIAOAAAgQAAA3AVAAQAUAAAAg3QAAg2gUAAQgIAAgFAIgADMA1QgIgJAAgOQAAgWAVgLQAMgGAPgDIAAgPQAAgNgDgFQgEgHgHAAQgIAAgFAFQgDAEAAAFIAAADIAAADQAAALgIAAQgFAAAAgIQAAgMAIgIQAIgKAOAAQAIAAAIAFQAIAHACAMIABARIAAAyQABAMABAFQACAFAEAAIAFgBIAAAHIgLABQgIAAgDgHQgCgFAAgJIgIANQgGAJgLAAQgMAAgGgJgADfABQgMAJAAASQAAALAEAGQAEAGAHAAQAMAAAEgOQACgHAAgQIAAgUQgMADgJAEgACXAwIgCgOIAAgNIAAhEIgLAAIAAgIQAFAAADgCQAKgIAEgbIAFAAIAAAkIAVAAIAAAJIgVAAIAABHQAAAPACAFQABAIAIAAQAEAAAHgFIAAAHQgJAIgJAAQgMAAgGgOgAAQA1QgHgJAAgOQAAgWAVgLQAMgGAPgDIAAgPQAAgNgDgFQgEgHgIAAQgIAAgEAFQgEAEAAAFIAAADIAAADQABALgIAAQgGAAAAgIQAAgMAIgIQAJgKANAAQAJAAAHAFQAJAHACAMIABARIAAAyQAAAMABAFQACAFAEAAIAGgBIAAAHIgMABQgHAAgEgHQgCgFAAgJIgHANQgGAJgMAAQgLAAgHgJgAAkABQgNAJABASQAAALAEAGQADAGAIAAQAMAAAEgOQACgHAAgQIAAgUQgMADgJAEgAFfA7IgUABIAAgFQAFAAAEgBQACgCACgEIAAgGIAAg8QAAgOgDgGQgFgKgJAAQgJAAgGAKQgEAHAAAPIAAA6IABAJQACAEAJAAIAAAFIgUgBIgTABIAAgFIAJgBQACgCABgEIAAgGIAAhMIAAgIQAAgGgGgBIgGAAIAAgFQAPgCAJgFIABAWQAKgUAPAAQAPAAAIAQQAEAJAAASIAAA6IABAJQACAEAKAAIAAAFIgUgBgAkGA7IgTABIAAgFIAIgBQADgCABgEIAAgGIAAhNIgBgLQgBgDgFAAIgFgBIAAgEQAOgCANgFIAABnIABAJQACAEALAAIAAAFIgWgBgADZhSQgFgHgCgMIADAAQADAIAFAFQAFAFAGAAQAGAAAEgFQAGgFACgIIAEAAQgCAMgFAIQgGAIgJAAQgJAAgGgJgAAyhMIgagfIAPAAIAPAfgAlThNIAPgfIAPAAIgaAfgAkNhSQgDgEAAgFQAAgGADgEQADgEAEAAQAEAAADAEQADAEAAAGQAAAFgDAEQgDAEgEAAQgEAAgDgEg");
	this.shape.setTransform(49.85,12.875);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(3.6,2,92.60000000000001,21.8);


(lib.Symbol28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ArbCVIAAhYIAIAAQAIBIAvAAQAUAAAMgQQAMgPAAgWQAAgYgPgOQgGgHgXgPQgkgWgJgKQgOgSAAgcQAAghARgUQAQgSAbAAQAYAAARAUIAJgVIAGAAIAABJIgHAAQgEgVgHgOQgMgagYAAQgSAAgLAQQgKAPAAATQAAAXARAOIAfAVQAaAPAKAKQATATAAAjQAAAigSAWQgRAVgcAAQgcAAgWgYIgLAbgAJoCAQgVgTgKgnQgHgcAAgiQAAg7AWgpQAMgUASgKQAPgJARABQAeAAAUAXIALgXIAGAAIAABQIgHAAQgOhDgqgBQgfABgOAjQgPAkAAA1QAAAzANAiQAPAlAgABQAUgBAPgQQARgVACgpIAMAAQgBAfgJAWQgJAVgRAMQgQAKgSAAQgaAAgUgTgAEFCAQgVgVgKglQgHgcAAgkQAAg8AXgmQAXgmAoAAQAcAAAWAXIANgXIAFAAIAABQIgHAAQgFgYgHgNQgHgPgMgIQgMgJgPAAQgXAAgPAVQgWAeAABKQAACBA8AAQAUAAAXgPIAAhFQAAgHgCgEQgDgHgUgBIAAgKQAWACAOAAQAOAAAWgCIAAAKQgOABgEACQgDAEgBAEIgBAJIAABBQgkAegiAAQgbAAgVgTgAoyByQgOgaAAgoQAAgqAPgbQASgeAfAAQAUAAANAOQAKgNAAgNIgBgBQAAABgBAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQgNgDADgQQADgOALAAQAPAAAAAVQAAASgPAUIgDAEIgCAEQAUAcAAAxQAAAngPAcQgRAhgeAAQgdgBgSgggAoYgbQgNAVAAA1QAABZAiAAQAkAAAAhYQAAhZgkAAQgMAAgJAOgABSBuQgGAOgHAIQgMAOgSAAQgagBgMgWQgIgPAAgeIAAhbQAAgMgCgFQgCgFgIgBIgKgBIAAgHQAYgCAXgJIAACGQAAAYAFALQAHAOAQAAQASgBAJgRQAFgMAAgYIAAhXQAAgMgBgFQgDgFgHgBIgLgBIAAgHQAZgCAXgJIAACjQAAALACADQADAFAIABIALABIAAAGQgaAEgSAHIgCgkgAhUBuQgGAPgGAHQgNAOgSAAQgZgBgNgWQgIgPAAgeIAAhbQAAgMgCgEQgDgIgRAAIAAgHQAYgCAXgJIAACGQAAAYAGALQAGANARAAQARAAAJgRQAGgLAAgZIAAhXQAAgMgCgEQgCgIgSAAIAAgHQAYgCAYgJIAAAOQAJgOAAgMIgDAAQgMgDACgQQADgOALgBQAQAAgBAUQAAASgOAWIgGAHIgFAHIAACHQAAALACADQACAFAJABIAKAAIAAAHQgZAEgSAHQgDgMAAgYgAjvCNQgOAAgUACIAAgIQAKAAAFgDQAEgEABgFIABgJIAAhjQAAgXgFgKQgHgOgQAAQgRAAgKAPQgHAMAAAVIAABiQAAAJACAEQAEAIAPAAIAAAIQgUgCgOAAQgNAAgVACIAAgIQALAAAFgDQAFgCABgHIAAgJIAAjLQAAgLgBgFQgDgGgIgBIgKAAIAAgIQAZgCAWgIIAABrQAQgcAZAAQAZAAANAZQAIAOAAAcIAABiQAAAJACAFQAEAGAQABIAAAIQgUgCgOAAgAGfCOIAAgKQANgBAFgDQAHgDAAgIIABgMIAAjEQAAgLgCgFQgDgGgKgDIgLgBIAAgKQAYADAPAAQAQAAAYgDIAAAKQgOABgFADQgGADAAAJIgBAKIAADEQAAALABADQAEAJAQABIAXAAQAOgBAHgFQAHgDAFgNQAGgMADgSIAHAAIgHBBgAoKhNIACgNQADgHAHgIQAHgJAAgIQAAgPgMgBQgPABgCAUIgGAAQAAgUANgHQAFgDAIAAQAKAAAFAEQAJAIAAAMQAAALgIAIIgGAGIgIAIQgEAGgBAHgAh6hmQgIgHgGAAQgKAAgFARIgGgBQADgQAGgIQAHgIAIgBQAJABAKAIQAMALAHAAQAIgBAGgSIAFACQgDAQgGAJQgGAHgIABIgCABQgJAAgMgNg");
	this.shape.setTransform(68.375,15.65);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.8,0.8,146.4,29.7);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg2();
	this.instance.parent = this;
	this.instance.setTransform(-1,-79,0.34,0.34);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-79,326.4,606.9);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(-109,14,0.13,0.13);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1208));

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Ak1EBIAAoBIJrAAIAAIBg");
	this.shape.setTransform(-96.05,27.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1208));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-127,2.2,62,51.4);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkNBxQgEgDAAgFQAAgFAEgEQADgDAFAAQAFAAAEADQADAEAAAFQAAAFgEADQgDAEgFAAQgFAAgDgEgAF6BCQgNgKAAgRQAAgaAdgLQAQgFAegFIAAgFQAAgNgEgFQgGgIgPAAQgXAAgEAUIgSAAQABgPAKgJQAMgLAXAAQATAAAMAIQAJAIABAPIABARIAAAtQAAAWADAKIgRAAQgCgHgBgJQgKATgaAAQgQAAgLgIgAGRAPQgRAIAAAPQAAAJAHAGQAGAGALAAQATAAAIgOQAFgJAAgTIAAgNQgbAFgMAGgABgBDQgMgIgDgQIgBgUIAAhKIASAAIAABKQAAATAFAGQAGAKAPAAQAQAAAJgOQAFgIAAgSIAAhFIASAAIAAAJIABgBIAGgHQACgDABgEIgBAAQgDgBgCgCQgFgEACgGQABgGAFgCQAEgCAFABQAFACACAFQADAFgCAHQgEAPgUAPIAABAIAAANIAAAHQAAAKADAHIgSAAIgCgHIAAgJQgFAIgFAEQgJAHgOAAQgQAAgKgHgAklBCQgNgKAAgRQAAgaAdgLQAPgFAfgFIAAgFQAAgNgEgFQgHgIgOAAQgYAAgEAUIgSAAQACgPAJgJQAMgLAXAAQAUAAALAIQAJAIACAPIAAARIAAAtQAAAWAEAKIgRAAQgDgHAAgJQgLATgZAAQgRAAgKgIgAkOAPQgRAIAAAPQAAAJAHAGQAGAGAKAAQATAAAJgOQAFgJAAgTIAAgNQgbAFgMAGgAAMA/QgCgEgBgGIAAhZIgRAAIAAgPIARAAIAAgkIATAAIAAAkIAdAAIAAAPIgdAAIAAA9IAAAWQACALALAAQAKAAAJgEIAAAQQgMAEgKAAQgTAAgHgLgAElBJIgsh8IATAAIAiBmIAjhmIATAAIgsB8gAI2BHIAAhFQAAgVgDgHQgGgMgPAAQgSAAgJAOQgGAKAAAQIAABFIgSAAIAAhQQAAgZgBgFIgCgMIARAAQADAHgBALQANgVAZAAQARAAAKAIQAKAJACAPIAAAWIAABHgAhpBHIAAhFQAAgVgDgHQgGgMgQAAQgSAAgJAOQgGAKAAAQIAABFIgSAAIAAhQQAAgZgBgFIgCgMIASAAQACAHAAALQAMgVAaAAQAQAAALAIQAKAJABAPIABAWIAABHgAleBHIAAhFQAAgVgDgHQgGgMgQAAQgRAAgJAPQgGAJAAARIAABEIgSAAIAAitIASAAIAABBQAOgRAWAAQANAAAKAGQAMAHADAOQABAHAAAUIAABHgAniBHIhTiPIAACPIgSAAIAAisIAVAAIBTCPIAAiPIASAAIAACsgAGzhBIgSgUIgSAUIgOAAIAYgeIAQAAIAYAegAjvhBIgRgUIgSAUIgOAAIAXgeIARAAIAYAegAG4hXIAVgdIATAAIgcAdg");
	this.shape.setTransform(48.825,7.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#08ABF1").s().p("AxJDxIAAnhMAiTAAAIAAHhg");
	this.shape_1.setTransform(44.3,7.75);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65.5,-16.3,219.6,48.2);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKyAwQgHgFAAgGQAAgHAGgDIAFgDQgFgCAAgEQAAgDAEgDIAGgDQgLgEAAgJQAAgKAGgFQAGgDAHAAIAJABIAQAAIAAAFIgMAAQAFAEAAAIQAAAHgFADQgDADgJACIgIADQgBAAAAAAQgBABAAAAQgBABAAAAQAAABAAAAQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAIAJACIAKABQANACAAALQAAAJgHAEQgHAEgKAAQgLAAgGgEgAK4AeQgFACAAAEQAAAEAFADQAEACAIAAQAIABAEgEQAEgCAAgEQAAgIgRgBQgHAAgEADgAK7gNQgDADAAAGQAAAEADACQACADAGAAQAEAAAEgDQADgCAAgEQAAgGgDgCQgDgEgFAAQgFAAgDADgAG1AzIAAg5IAAgLIgBgEIAHAAIABAHQAGgJAIAAQAIAAAGAEQAHAJABAOQAAAOgIAHQgFAGgIAAQgJAAgGgIIAAAcgAHBgMQgFAHAAAJQAAAJAEAGQAEAFAGAAQAGAAADgEQAFgGAAgKQgBgLgFgFQgDgFgFAAQgGAAgDAFgAJRAvQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAABQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAgAEFAvQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAgAJIAbQgFgDgBgHIgBgIIAAgeIAIAAIAAAeQAAAIABADQAEAEAFAAQAIAAADgGQACgDABgIIAAgcIAHAAIAAAjIAAAJIACAHIgIAAIgBgHIgFAFQgDADgGAAQgHAAgEgEgAINAZQgHgIAAgNQAAgNAHgIQAFgGAIAAQAHAAADADIAFAGIAAgdIAIAAIAAA5IABAQIgHAAIgBgGIAAgCIgFAFQgEAEgGAAQgIAAgGgGgAISgMQgEAGAAAKQAAAKAEAGQADAEAGAAQAHAAACgEQAGgGAAgKQgBgKgEgGQgDgFgHAAQgFAAgEAFgAGCAbQgGgEABgHQAAgMAMgEQAHgBAMgCIAAgCQAAgGgBgCQgDgEgGAAQgKAAgCAJIgHAAQAAgHAEgEQAGgEAJAAQAIAAAFADQAEADABAHIAAAIIAAASQAAAJABAFIgHAAIgBgHQgFAIgLAAQgGAAgFgEgAGMAGQgIADAAAGQABAEADADQACACAFABQAHgBAEgGQADgDgBgJIAAgFIgQAFgAD5AZQgHgIAAgNQABgNAHgJQAGgFAJAAQAKAAAHAJQAEAHAAAKIAAACIgkAAQAAAIADAFQAFAGAIAAQAFAAAEgDIACgFIAIABQgFAOgOAAQgKAAgHgGgAD9gKQgCAEgBAFIAcAAQAAgFgCgEQgEgHgHAAQgHAAgFAHgABaAbQgEgDgBgHIgBgIIAAgeIAHAAIAAAeQAAAIACADQADAEAGAAQAHAAAEgGQACgDAAgIIAAgcIAIAAIAAAjIAAAJIABAHIgIAAIgBgHIgEAFQgDADgGAAQgHAAgFgEgAAiAZQgHgIAAgNQAAgNAIgJQAFgFAKAAQAKAAAGAJQAEAHAAAKIAAACIgjAAQAAAIADAFQAEAGAIAAQAGAAAEgDIACgFIAHABQgFAOgOAAQgJAAgHgGgAAmgKQgCAEgBAFIAbAAQAAgFgCgEQgDgHgIAAQgHAAgEAHgAguAZQgIgIAAgNQAAgNAIgIQAEgGAJAAQAGAAAEADIAEAGIAAgQIgPAAIAAgFIAPAAIAAgIIAIAAIAAAIIAIAAIAAAFIgIAAIAAAsIABAQIgHAAIgBgGIAAgCIgEAFQgFAEgFAAQgJAAgFgGgAgpgMQgEAGgBAKQABAKAEAGQADAEAGAAQAGAAADgEQAFgGAAgKQAAgKgEgGQgEgFgGAAQgGAAgDAFgAkXAbQgFgEAAgHQAAgMAMgEQAHgBANgCIAAgCQAAgGgCgCQgDgEgGAAQgKAAgBAJIgIAAQAAgHAEgEQAGgEAJAAQAJAAAEADQAFADAAAHIAAAIIAAASQABAJABAFIgIAAIgBgHQgEAIgLAAQgHAAgFgEgAkNAGQgHADAAAGQAAAEADADQADACAEABQAIgBAEgGQACgDAAgJIAAgFIgRAFgAlNAZQgHgJAAgMQAAgNAHgIQAHgGAJAAQAJAAAGAGQAIAIgBANQABAMgIAJQgGAGgJAAQgJAAgHgGgAlHgLQgFAFAAAKQAAAJAFAGQADAFAHAAQAGAAAEgFQAFgGAAgJQAAgKgFgFQgEgFgGgBQgHABgDAFgAoLAbQgEgDgCgHIAAgIIAAgeIAHAAIAAAeQABAIABADQADAEAGAAQAHAAAEgGQACgDAAgIIAAgcIAIAAIAAAjIAAAJIABAHIgIAAIAAgHIgFAFQgDADgHAAQgGAAgFgEgApDAZQgHgIAAgNQAAgNAIgJQAGgFAJAAQAKAAAGAJQAEAHABAKIAAACIgkAAQAAAIADAFQAEAGAIAAQAGAAAEgDIACgFIAHABQgEAOgPAAQgKAAgGgGgAo/gKQgCAEgBAFIAbAAQAAgFgCgEQgDgHgIAAQgHAAgEAHgAiMAZQgHgFAAgKQAAgIAHgFIAHgIIgFgHQgDgFAAgFQAAgGAEgEQAFgEAHAAQAGAAAEADQAFAEAAAHQAAAGgFAGIgHAHIAPATQADgEAAgJIAGAAIAAACQABAKgFAIIAJANIgIAAIgGgHIgGAFQgGACgGAAQgKAAgFgFgAiHAAQgFAFABAFQAAAGADADQAEAFAHAAQAIAAAGgHIgRgVIgHAEgAiCgiQgEACAAADQAAAFAEAEIADAGIAHgGQADgEAAgFQAAgDgCgCQgCgBgEgBQgDABgCABgAKYAeIAAgeQABgIgCgDQgCgFgHAAQgHAAgEAGQgDAEAAAGIAAAeIgHAAIAAgiIgBgNIgBgEIAHAAIABAHQAGgJAKAAQAIAAAEADQAEAEABAGIAAAKIAAAegAFLAeIAAgeQABgIgCgDQgCgFgHAAQgHAAgEAGQgDAEAAAGIAAAeIgHAAIAAgiIgBgNIgBgEIAHAAIABAHQAGgJAKAAQAIAAAEADQAEAEABAGIAAAKIAAAegADdAeIAAgzIAIAAIAAAzgADFAeIgWgdIAWgWIAJAAIgVAWIAXAdgACnAeIAAhJIAIAAIAABJgAAFAeIAAgzIAIAAIAAAzgAjEAeIAAgeQAAgIgCgDQgBgFgIAAQgHAAgEAGQgCAEAAAGIAAAeIgIAAIAAgiIAAgNIgBgEIAHAAIABAHQAGgJAKAAQAHAAAFADQADAEABAGIAAAKIAAAegAlpAeIAAgeQABgIgCgDQgDgFgGAAQgIAAgDAGQgDAEAAAHIAAAdIgHAAIAAhJIAHAAIAAAbQAGgHAJAAQAGAAAEADQAFACACAHIAAALIAAAegAmgAeIgWgdIAWgWIAJAAIgVAWIAXAdgAm+AeIAAhJIAHAAIAABJgApgAeIAAgzIAIAAIAAAzgAqkAeIAAgjIgHAAIAAgGIAHAAIAAggIALAAIAPABQAOACAGAKQAIAKAAAOQgBAOgHAJQgIALgMABIgQABgAqcAXIAGAAIALgBQAEgBAFgDQAEgCACgEQAFgHAAgLQAAgNgHgJQgEgGgJgBIgOgBIgDAAIAAAZIASAAIAAAGIgSAAgArJgUIgJALIgDgCIAHgLIgNgFIACgEIANADIAAgNIAFAAIAAANIANgDIACAEIgOAFIAIALIgDACgAEQgcIgHgIIgIAIIgGAAIAKgMIAHAAIAKAMgAA5gcIgIgIIgHAIIgHAAIAKgMIAHAAIAKAMgAotgcIgHgIIgHAIIgGAAIAJgMIAIAAIAJAMgAkIgdIAAgDIABgDIACgBIABgBIABgBIABgBIAAgCIgBgBIgEgBIgCABQgBAAAAABQAAAAgBAAQAAABAAAAQAAABAAABIgEAAIABgDIABgDQACgCAFgBQAEABACABIACACIABAEIgBACIgBABIgCABIgCACIgCACIAAACgAGMgeIAJgMIAIAAIgLAMgADdgiQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQABAAAAAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAABQABAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQgBABgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBAAAAgAAFgiQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQABABAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAQgBABAAAAQgBAAgBAAQAAABgBAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAgApggiQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQABABAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAQgBABAAAAQgBAAgBAAQAAABgBAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAgAA+gnIgLgMIAIAAIAJAMgAongnIgLgMIAIAAIAJAMg");
	this.shape.setTransform(73.15,5.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,146.3,10.4);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.514,1],-14.5,-4.6,14.7,4.7).s().p("AjwD8IC+pUIEjBeIi+JTg");
	this.shape.setTransform(24.125,34.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.3,69);


(lib.Symbol1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.bg1();
	this.instance.parent = this;
	this.instance.setTransform(-9,-32,0.35,0.3499);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-9,-32,336,528.8);


(lib.Symbol27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_4 copy
	this.instance = new lib.Symbol31("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(11.65,47.65,1,1,0,0,0,6.3,0);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(11).to({_off:false},0).to({x:6.65,alpha:1},14,cjs.Ease.get(1)).wait(1496));

	// Layer_4
	this.instance_1 = new lib.Symbol31("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(128.55,47.65,1,1,0,0,0,6.3,0);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(11).to({_off:false},0).to({x:133.55,alpha:1},14,cjs.Ease.get(1)).wait(1496));

	// Layer_2 copy
	this.instance_2 = new lib.Symbol30copy("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(79.6,73.45,1,1,0,0,0,87.8,14.7);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(11).to({_off:false},0).to({x:63.1,alpha:1},10,cjs.Ease.get(1)).to({x:64.6,y:73.55},8,cjs.Ease.get(1)).wait(1492));

	// Layer_2
	this.instance_3 = new lib.Symbol30("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(49.6,73.45,1,1,0,0,0,87.8,14.7);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(11).to({_off:false},0).to({x:66.1,alpha:1},10,cjs.Ease.get(1)).to({x:64.6,y:73.55},8,cjs.Ease.get(1)).wait(1492));

	// Layer_3
	this.instance_4 = new lib.Symbol29("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(63.45,64.25,1,1,0,0,0,45.6,10.1);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(5).to({_off:false},0).to({y:46.65,alpha:1},10,cjs.Ease.get(1)).to({y:48.25},8,cjs.Ease.get(1)).to({_off:true},1442).wait(56));

	// Layer_1
	this.instance_5 = new lib.Symbol28("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(63.7,29.2,1,1,0,0,0,63.7,13.2);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({y:11.6,alpha:1},10,cjs.Ease.get(1)).to({y:13.2},8,cjs.Ease.get(1)).to({_off:true},1446).wait(57));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.1,-0.8,264.3,126.89999999999999);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AukDLIAAmVIdJAAIAAGVg");
	mask.setTransform(37.775,14.325);

	// Layer_3
	this.instance = new lib.Symbol2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-84.1,14.65,1,1,0,0,0,24.1,34.5);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:158.8,y:19.05},23,cjs.Ease.get(1)).wait(67));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.5,-5.9,186.6,40.5);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(43.35,7.65,0.4,0.4,0,0,0,43.4,7.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:7.6,scaleX:1.1,scaleY:1.1,x:43.4,y:7.6,alpha:1},11,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(1944));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.4,-18.7,241.6,53);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol3("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(73,4.75,1,1,0,0,0,73.2,5.2);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},9,cjs.Ease.get(1)).wait(2516));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.2,-0.4,146.29999999999998,10.4);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_215 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(215).call(this.frame_215).wait(110));

	// logo
	this.instance = new lib.Symbol13("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(271.5,443.5,1,1,0,0,0,15.5,15.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(325));

	// Layer_12
	this.instance_1 = new lib.Symbol18();
	this.instance_1.parent = this;
	this.instance_1.setTransform(161.4,370.1,1,1,0,0,0,42.4,10.1);
	this.instance_1.alpha = 0.8008;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(141).to({_off:false},0).wait(184));

	// cta
	this.instance_2 = new lib.Symbol11("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(156.05,374.7,0.85,0.85,0,0,0,43.6,7.9);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(44).to({_off:false},0).wait(281));

	// Layer_4
	this.instance_3 = new lib.Symbol1("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(160.2,410.2,1,1,0,0,0,73.2,5.2);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(64).to({_off:false},0).wait(261));

	// t
	this.instance_4 = new lib.Symbol27("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(157.4,65.95,0.9,0.9,0,0,0,63.8,13.3);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(9).to({_off:false},0).wait(316));

	// bg2
	this.instance_5 = new lib.Symbol15("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(155.3,299.9,1.2,1.2,0,0,0,159.2,299.9);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(112).to({_off:false},0).to({regY:300,scaleX:1,scaleY:1,x:155.2,y:300,alpha:1},20,cjs.Ease.get(1)).to({_off:true},84).wait(109));

	// bg1
	this.instance_6 = new lib.Symbol1copy("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(146.05,297.9,1.2,1.2,0,0,0,150,299.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({regY:300,scaleX:1,scaleY:1,x:150,y:300},17,cjs.Ease.get(1)).to({_off:true},120).wait(188));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44.7,-154.7,403.2,728.2);


// stage content:
(lib._320x480 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.parent = this;
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(115.3,139.7,243.2,394.50000000000006);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 320,
	height: 480,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg1.jpg?1714639552345", id:"bg1"},
		{src:"images/bg2.jpg?1714639552345", id:"bg2"},
		{src:"images/logo.png?1714639552345", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;