(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,200,200);


(lib.Symbol28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEF8F0").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Symbol27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiSCeQgPgEgKgHQgKgGgFgIQgFgKAAgIQAAgNAHgIQAIgJANgEQgHgFgEgFQgEgHAAgKQAAgIAFgJQAHgJAMgGQgOgHgIgNQgIgKAAgRQAAgOAGgLQAFgLAJgHQAKgIAOgDQANgEAPgBQAXABATAIIA1AAIAAASQAAAEgDADQgDACgFACIgOADQACAIAAAKQAAANgFALQgFAKgKAIQgKAHgNAEQgNAFgQgBQgJAAgJgBQgHAEAAAFQAAAGAGACQAFACAHACIATABIAVABQALAAAKADQALACAIAFQAIAFAFAIQAFAJAAANQAAAMgGAKQgGAMgLAJQgMAJgQAFQgQAGgWAAQgVAAgPgEgAiRBhQgEAEAAAHQAAAFACADQACAEAFACQAFADAHACQAIABALAAQAMAAAJgBQAIgCAFgDQAFgDACgEQADgEgBgEQAAgGgCgCIgJgFQgEgCgHAAIgPgCIgQAAIgQgCQgGAEgEAFgAiFgrQgHAGAAANQAAAMAHAHQAHAHAOAAQAPAAAIgHQAGgHAAgMQAAgNgGgGQgIgIgPAAQgOAAgHAIgAAECdIAAjtIAeAAQAKAAACAIIAEAPIALgLQAGgFAIgEQAGgDAJgCQAIgCAJAAQAOAAANAGQAMAHAJALQAIAMAFARQAGASAAAVQgBATgFASQgGASgKAMQgKANgOAGQgOAIgSgBQgPAAgKgDQgLgFgIgIIAABIgABFgqQgJAFgIALIAABOQAIAIAHADQAIACAJAAQAJAAAIgCQAGgEAGgHQAFgHADgLQACgLAAgPQAAgOgCgLQgCgKgFgHQgEgGgGgDQgGgDgHAAQgNAAgJAEgAK6BkQgGgCgDgFQgEgDgCgGQgCgFgBgGQABgFACgFQACgFAEgEQADgEAGgDQAFgBAGAAQAGAAAGABIAJAHQADAEACAFQACAFABAFQgBAGgCAFQgCAGgDADQgFAFgEACQgGABgGAAQgGAAgFgBgAG7BfQgQgHgMgMQgMgMgHgRQgGgRAAgVQAAgVAGgRQAHgRAMgNQAMgLAQgHQARgGAVAAQATAAARAGQARAHAMALQAMANAGARQAGARABAVQgBAVgGARQgGARgMAMQgMAMgRAHQgRAGgTAAQgVAAgRgGgAHBghQgKAOAAAcQAAAcAKAOQAKAOAWAAQAUAAAKgOQAKgOAAgcQAAgcgKgOQgKgOgUAAQgWAAgKAOgAoSBfQgRgHgMgMQgMgMgHgRQgGgRAAgVQAAgVAGgRQAHgRAMgNQAMgLARgHQARgGAUAAQAUAAARAGQARAHALALQANANAGARQAGARAAAVQAAAVgGARQgGARgNAMQgLAMgRAHQgRAGgUAAQgUAAgRgGgAoNghQgKAOAAAcQAAAcAKAOQALAOAVAAQAVAAAJgOQALgOgBgcQABgcgLgOQgJgOgVAAQgVAAgLAOgAriBhQgMgFgHgKQgIgJgEgMQgEgNABgPIAAhxIAvAAIAABxQAAAPAIAIQAGAJAOAAQAKAAAJgEQAJgFAIgIIAAiAIAwAAIAACzIgeAAQgJAAgCgIIgEgNIgLAKQgFAEgHADQgHADgHACQgIACgJgBQgPAAgLgEgAwhBiQgKgDgGgHQgHgGgDgKQgDgJAAgNIAAhgIgRAAQgEAAgDgCQgCgCAAgFIAAgUIAcgFIAKguQACgJAJABIAZAAIAAA3IAvAAIAAAhIgvAAIAABdQABAIADAEQADAFAHAAIAGgBIAEgCIADgCIAEgBIADABIADAEIAPAXQgLAHgMAFQgNADgOAAQgLAAgKgDgAQpBjIAAhyQAAgOgHgJQgHgJgOABQgKgBgIAFQgKAFgIAHIAACBIgwAAIAAizIAeAAQAJAAACAIIAEAMIALgJQAGgFAGgDQAHgDAIgBQAHgCAJAAQAPAAALAFQALAFAJAJQAHAJAEAMQAEAOAAAOIAABygAM1BjIhHizIAnAAQAGgBADADQAEADABADIAeBZIAGASIAEARIAEgRIAFgSIAghZQABgDADgDQAEgDAFABIAmAAIhHCzgAJYBjIAAizIAwAAIAACzgAE7BjIAAhyQgBgOgGgJQgIgJgOABQgJgBgJAFQgKAFgIAHIAACBIgwAAIAAkEIAwAAIAABjIAMgJQAFgEAGgDQAGgCAHgBQAIgCAHAAQAPAAAMAFQALAFAIAJQAIAJADAMQAFAOAAAOIAABygAkHBjIAAhyQAAgOgHgJQgHgJgOABQgKgBgJAFQgJAFgIAHIAACBIgwAAIAAizIAdAAQAKAAACAIIAEAMIALgJQAGgFAGgDQAHgDAHgBQAIgCAJAAQAPAAAMAFQAKAFAJAJQAHAJAEAMQAEAOAAAOIAABygAtYBjIAAhyQAAgOgGgJQgIgJgOABQgJgBgJAFQgJAFgJAHIAACBIgvAAIAAkEIAvAAIAABjIAMgJQAFgEAGgDQAGgCAHgBQAHgCAIAAQAQAAALAFQALAFAIAJQAIAJADAMQAFAOAAAOIAABygAJkhpQgFgCgEgEQgEgEgCgGQgDgEAAgHQAAgGADgFQACgFAEgEQAEgFAFgCQAGgCAGAAQAGAAAFACQAGACAEAFQAEAEACAFQADAFAAAGQAAAHgDAEQgCAGgEAEQgEAEgGACQgFACgGAAQgGAAgGgCg");
	this.shape.setTransform(127.45,31.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFCC66","#FF915C"],[0,0.502],-126.8,0,126.8,0).s().p("AzBE4QgyAAAAg1IAAoFQAAg1AyAAMAmDAAAQAyAAAAA1IAAIFQAAA1gyAAg");
	this.shape_1.setTransform(126.825,31.175);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,253.7,62.4);


(lib.Symbol25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#007E9E").s().p("AMVCaIAAgPQABgIAOAAQANAAAAAIIAAAPQAAAHgNAAQgOAAgBgHgAhtBkQgKgKAAgUIAAhqQABgHANAAIAEAAQANAAAAAHIAABmQAAAJAEAFQADAFAKAAQAJAAAGgFQAHgFAEgHIAAhoQAAgHAOAAIAEAAQANAAAAAHIAABjIABAaIACALQAAADgEABIgJADIgJABQgEAAgCgEQgBgEgCgMQgHAKgKAGQgKAHgMAAQgSAAgKgLgAL4BiQgLgMAAgVQAAgUAKgMQAKgLARgFQAQgGAWABIAAgMQAAgHgEgHQgGgGgMAAQgLAAgJACIgNAFIgIACQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAAAQgCgEgBgEIgBgHQABgDAGgEQAIgEALgCQAMgEALAAQAaAAANANQANAMAAAUIAAA/QAAATACAHIABAMQAAACgFACQgDACgGAAIgIABQgEAAgBgEIgEgNQgHAIgIAFQgJAGgNAAQgUAAgKgMgAMVAoQgKAHAAAQQAAALAFAGQAEAGAJAAQAJAAAHgEQAHgEAEgIIAAglQgZABgKAGgAK0BqQgHgCgGgJQgEgIgBgPIAAhaIgKAAQgGAAAAgLIAAgDQAAgLAGABIAKAAIAFgeQABgIAJAAIAFAAQAGABACACQADABAAAEIAAAeIARAAQAHgBAAALIAAADQAAALgHAAIgRAAIAABXQAAAJACAEQACADAGABIAHgBIADgBQABAAAAAAQABAAAAABQABAAAAABQABAAAAABIACAIIAAAFQAAADgEACIgJAEIgKABQgIAAgIgEgAEaAhQAAgnAQgUQAPgTAbAAQAbABANATQAMAUAAAkQAAANgLAAIhEAAQABAVAHALQAIAKAQAAQAKgBAHgCIAMgFIAHgDQADAAABADIADAHIAAAGQAAAEgGAEQgHAFgLADQgKADgLAAQg9AAAAhNgAFAgLQgGALgBAWIAyAAQAAgrgYAAQgLAAgIAKgABUBqQgIgCgGgJQgEgIAAgPIAAhaIgKAAQgHAAAAgLIAAgDQAAgLAHABIAKAAIADgeQABgIAKAAIAFAAQAFABADACQADABAAAEIAAAeIARAAQAHgBAAALIAAADQAAALgHAAIgRAAIAABXQAAAJACAEQACADAFABIAIgBIADgBQABAAAAAAQABAAAAABQABAAAAABQABAAAAABIACAIIAAAFQAAADgDACIgJAEIgKABQgJAAgHgEgAkBAhQAAgnAQgUQAPgTAbAAQAbABANATQAMAUAAAkQAAANgLAAIhEAAQABAVAHALQAIAKAQAAQAKgBAHgCIAMgFIAHgDQADAAABADIADAHIAAAGQAAAEgGAEQgHAFgLADQgKADgLAAQg9AAAAhNgAjbgLQgGALgBAWIAyAAQAAgrgYAAQgLAAgIAKgAOJBsQgHAAgDgCQgCgBAAgDIAAiKQAAgDACgCQADgCAHAAIAFAAQAGAAAEACQADACAAADIAACKQAAADgDABQgEACgGAAgAJCBsQgIAAgDgCQgDgBAAgDIAAhmQAAgIgEgGQgEgFgKAAQgHAAgHAFQgGAGgDAFIAAADIAABmQAAADgDABQgDACgHAAIgEAAQgIAAgCgCQgEgBAAgDIAAhmQAAgIgDgGQgFgFgJAAQgGAAgFACQgEAEgEADIgEAIIAABoQAAADgEABQgCACgIAAIgDAAQgIAAgDgCQgDgBAAgDIAAhkQAAgSgBgHIgCgNQAAgCAEgBIAJgDIAJAAQAEgBACAFIADAQQAIgKAIgHQAKgFAMgBQALABAJAFQAKAFADANQAHgLAJgGQAKgHAMAAQAPAAALAKQALAKAAAVIAABqQgBADgDABQgCACgIAAgADrBsQgHAAgDgCQgDgBgBgDIAAhmQAAgIgDgGQgFgFgKAAQgGAAgGACQgFAEgDADIgGAIIAABoQAAADgCABQgEACgGAAIgFAAQgHAAgDgCQgDgBABgDIAAjMQAAgHAMgBIAFAAQANABgBAHIAABNQAGgIAKgGQAJgFAMgBQAQAAALAKQALAKAAAVIAABqQAAADgDABQgDACgHAAgAkwBsQgIAAgDgCQgCgBgBgDIAAiKQABgDACgCQADgCAIAAIADAAQAIAAACACQADACAAADIAACKQAAADgDABQgCACgIAAgAl0BsQgGAAgEgCQgDgBAAgDIAAhmQAAgIgEgGQgFgFgKAAQgGAAgGACQgEAEgEADIgFAIIAABoQAAADgDABQgDACgHAAIgEAAQgHAAgDgCQgDgBAAgDIAAjMQAAgHANgBIAEAAQANABAAAHIAABNQAGgIAJgGQAKgFAMgBQAPAAAMAKQAKAKABAVIAABqQgBADgCABQgEACgGAAgAopBsQgIAAgDgCQgDgBAAgDIAAhmQAAgIgEgGQgEgFgKAAQgHAAgHAFQgGAGgDAFIAAADIAABmQAAADgDABQgDACgHAAIgEAAQgIAAgCgCQgDgBgBgDIAAhmQAAgIgEgGQgEgFgJAAQgGAAgFACQgFAEgDADIgEAIIAABoQAAADgDABQgEACgHAAIgEAAQgHAAgDgCQgCgBAAgDIAAhkQAAgSgCgHIgCgNQAAgCAFgBIAJgDIAIAAQAEgBACAFIAEAQQAHgKAIgHQAKgFAMgBQAKABAKAFQAJAFAFANQAGgLAJgGQAKgHAMAAQAPAAALAKQALAKAAAVIAABqQAAADgEABQgCACgIAAgAr8BsQgHAAgEgCQgCgBAAgDIAAiKQAAgDACgCQAEgCAHAAIAEAAQAHAAADACQADACAAADIAACKQAAADgDABQgDACgHAAgAtfBsQgNAAAAgGIAAipIgnAAQgGAAgBgLIAAgFQABgLAGAAIBuAAQAGAAAAALIAAAFQAAALgGAAIgnAAIAACpQAAAGgOAAgAFjg7QgDgCgDgFIgJgPIgJAPQgCAFgDACIgKABQgHAAAAgEIABgEIABgFIAJgVQADgEAFgCQAEgBAIAAQAIAAAFABQAFACACAEIAJAVIACAFIABAEQAAAEgIAAIgJgBgAi4g7QgDgCgDgFIgJgPIgJAPQgCAFgDACIgKABQgHAAAAgEIABgEIABgFIAJgVQADgEAFgCQAEgBAIAAQAIAAAFABQAFACACAEIAJAVIACAFIABAEQAAAEgIAAIgJgBgAr7g7QgDgBgEgGIgNgRIgFgHQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQABAAAAAAQABgBABAAIAKgBQAJAAAFABQAEADABADIAJAVIACAFIACAEQgBAEgHAAIgKgBgAOAhAQgEgBABgEIAAgTQgBgDAEgCQADgCAIAAQAJAAADACQADACABADIAAATQgBAEgDABQgDACgJAAQgIAAgDgCgAk6hAQgDgBgBgEIAAgTQABgDADgCQADgCAJAAQAIAAADACQADACAAADIAAATQAAAEgDABQgDACgIAAQgJAAgDgCgAjPhtQgDgDAAgCQAAgCAFgDIAGgHQAEgEAAgGQAAgEgDgDQgCgBgEAAIgGABIgEABQgCAAgDgEQgCgEAAgCQgBgCAIgDQAGgDAHAAQAJAAAIAFQAIAEAAANQAAAGgDAGQgEAGgEAEQgEAFgEACIgGADQgDAAgDgDg");
	this.shape.setTransform(92.25,16.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,184.5,32.2);


(lib.Symbol23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF915C").s().p("AAfBWIgBgBIgCgBQgJgCgGgIQgFgHAAgKIAAh9QAAgDgCgCQgDgDgDAAQgGAAgBAIIAAB9QAAAKgFAHQgGAIgJACIgEABIgCgJIAEgBQAFgBAFgFQADgFAAgHIAAh9QABgHAEgFQAFgFAGAAIABAAQAGAAAEAFQAGAFAAAHIAAB9QAAAHADAFQAEAFAGABIABAAIADABQgBAKgBAAIgBAAg");
	this.shape.setTransform(26.05,9.0262);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AidC0IgCgBQgEgBABgEQABgEAEAAIAAAAQAfAHASgOQARgMAKgeQAFgSAFglIABgHIACgIIgLAIQgKAFgOAFIAAAAIgRAOQgOAUAGAbQABADgFABIgBABQgDAAgBgDQgHgeARgXIgMAJQgIAGgDAFQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIgCgBIgBAAQgEgCADgEIABgBQAEgHAHgGQAQgOAXgGIACgBIAEgBQAcgKAIgSIABgCQACgJADgEIAAgBQgHACgHAAIgJgBIgDAAQgHgCgIABQgQABgGANQgBAEgDAAIgCgBQgEgCACgEQAHgQAQgDIACAAQgIgHgDgDQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBIACgDQAEgCACADQACAEAHAFQAGAEAIADIACABIAKAAQANAAASgNIAJgGQAHgFAJgDIADAAQAGgCAEgFQAEgFAAgGIAAh+QAAgIAEgEQAFgGAGAAIABAAQAHAAAEAGQAFAEAAAIIAAB+QAAAGAEAFQAEAFAGACIABAAIACAAQAOAEALAKQATANAMAAIAKAAIAFgBQANgEAHgMQADgDAEACQAEACgDAFQgFAFgFAFIABAAQARAEAGAPQACAEgEACIgCABQgDAAgBgEQgGgNgPgBIgJAAIgHABIAAAAIgBAAIgLABIAAAAQgHAAgHgCIAAABIAEAJIACACIABADIAAABQAHAQAPAMIAAAAQATAOATgEQAEgCABAFQABAFgEABIgLABQgUgBgRgPIgGgEIgEgFIABAFIABAHQAGAkAFARQAKAeAPAOIAGAGQgDgCgCADQgDAEAEADIgIgHQgRgQgKgeIgGgcQgFAYgOAOQAAAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAgBAAQgDgDADgEQASgRgBgoIgBgLIgCgVQgDgMgDgHQgGgJgHgHIgCgCIgHgDQgHgFgIgDIgBAAIgCAAQgJgDgGgHQgGgIAAgJIAAh+QAAgEgCgCQgCgCgDAAQgIgBAAAJIAAB+QAAAJgFAIQgFAHgJADIgEAAQgHADgGADIgBABIgIAEIgBABQgIAIgFAJIgFAOIAAABIAAACIgCAXIgBALQABApAPAQQADAEgDADQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgDgBQgNgOgEgcQgEAVgDAMQgKAggTANQgQALgWAAIgRgBg");
	this.shape_1.setTransform(24.475,18.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#007E9E").s().p("AAPA1IABgUIgDAAQgNAAgKgBIgCATQgBAFgDAAIgBAAQgEgBAAgEIABgVQgOgFgOgHQgEgBACgFIACgCQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABABQAMAGANAEIACgaQgPgFgLgIQgEgDADgDQACgEADACIABAAQAKAHALAFIADgnQABgEAEAAQAFABgBAEIgDAoQAMADAPAAIADgpQAAgEAFgBQAEABAAAFIgDAnIAOgCIAEAAQAFgBABAEQABAFgFABIgPACIgDAAIgCABIgCAYIAQgDQAFgBABAEQABAFgEABQgKACgKABIgBAUQAAAFgFAAQgEgBAAgEgAgKAXQANADAOgBIABgZIgBAAQgOAAgLgDg");
	this.shape_2.setTransform(43.0866,38.15);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF915C").s().p("ADJDLIgIgCQgzgLgsgXQgrgXgPgXQgOgXgChKIAChcIAAgEQABgtAEgXIABgBQAIACAHAFIAGAFIADABQAHAHAFAKQADAGADAMIADAVIABAMQAAAngRARQgDAEADACQAAAAAAABQABAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABgBAAAAQAOgNAEgYIAHAcQAKAeAQAPIAIAHQAMAIAOAFIgCAaQgMgDgNgHQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDACQgBAEADACQAOAHAPAEIgCAVQAAAFAFAAIAAAAQAEAAABgEIABgUQAMACAMAAIAEAAIgCAUQAAAEAFABQAEAAAAgFIACgUQAKgBAJgDQAEgBgBgEQgBgEgEABIgRADIACgZIADgBIACAAIAQgDQAEgBgBgEQgBgFgEABIgEABIgOACIACgoQAAgEgEgBQgFAAAAAFIgCApQgPAAgNgDIACgoQABgEgFgBQgEAAgBAEIgCAmQgMgEgJgHIgBAAIgHgGQgPgOgJgcQgFgSgGgkIgBgHIgBgEIAEAEIAFAFQASAPAUAAIAKgBQAFgBgBgFQgBgEgFABQgTAEgSgOIgBAAQgOgLgHgRIgBgBIgBgDIgBgCIgEgJIgBgBQAIADAGAAIABAAIAKgBIABAAIABAAIAHgCIAIAAQAQACAGANQABADADAAIACgBQADgCgBgEQgHgPgQgEIgCAAQAGgFAEgGQADgEgEgCQgEgDgCAEQgIAMgMAEIgFABIgKABQgMAAgTgPQgLgJgOgEQALgqAagIQAlgMAvA0QAaAbAUAlIAMAYQALAZAJAcQAfBegLBDQgJA9gnAAIgEAAgAj4ChIgEgTQgHgsALg3QAFgeALggQAchYAyg1QAvg0AlAMQAbAIAKAqQgIACgIAFIgJAGQgSAPgMAAIgKgBIgDgBQgHgCgHgFQgHgFgCgEQgCgEgEADIgCACQAAABAAAAQAAABAAAAQAAABAAAAQAAABABAAQACAFAJAGIgDAAQgQAEgHAPQgBAFAEABIABABQADAAACgDQAGgNAPgCQAJgBAGACIADABIAKABQAGAAAIgDIgBABQgCAEgCAJIgBACQgJATgcAJIgDABIgDABQgWAGgQAOQgHAHgEAGIgBABQgDAEAEACIAAAAIADABQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAgBQAEgGAHgGIAMgJQgQAXAHAdQABADADAAIABAAQAEgBgBgDQgGgbAPgTIAQgPIABAAQANgEALgGIAKgIIgBAIIgBAHQgGAmgFARQgJAdgRAMQgTAOgegGIgBAAQgEgBgBAEQgBAFAFABIACAAIARACQAWAAAPgLQATgOAKgfQAEgMAEgVQADAcANANIADABQABAAAAAAQABAAAAAAQAAAAABAAQAAgBABAAQADgCgDgEQgQgQAAgoIABgMIABgXIABgCIAAgBIAEgNQAGgKAHgHIACgBIAIgGIABgBQAGgDAHgCIAAABQAEAWABAuIAAAEQACBDAAAZQgCBKgOAXQgOAXgsAXQgjASgoALIgUAFIgNACQggAAgLgqgACgBWIABgaQAMADAOAAIACAAIgCAaIgEAAQgMAAgLgDg");
	this.shape_3.setTransform(26.0352,31.754);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.5,0.5,51.1,51.6);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#007E9E").s().p("AgEBnQgJgKgBgUIAAhuQAAgHAOAAIADAAQAOAAAAAHIAABpQAAAKAEAFQAEAFAKAAQAIAAAHgFQAHgFAGgIIAAhrQgBgHANAAIAHAAQAHAAADgEQADgCAAgFQAAgGgEgFQgEgEAAgDQAAgCADgCIAFgFIAGgCQAEAAADAEIAFAKQACAGAAAEQAAAOgIAIQgFAFgJACIAABgQABATABAIIACAMQgBADgEABIgJADIgJABQgEAAgCgFIgEgQQgHAKgKAHQgKAGgNAAQgSAAgKgLgArvBvQgJgDgGgEQgFgEgBgFIACgHIAGgHQACgDACAAIAFACIAKAFQAFADAHAAQALAAAFgFQAFgEAAgKQAAgKgHgGQgHgFgLgGQgOgHgJgKQgIgKgBgRQAAgUAOgMQANgMATAAIAQABQAIACAGADQAFAEAAAEIgCAHIgDAIQgDADgCAAIgHgDQgGgDgIAAQgJAAgFAEQgGAEABAHQgBAJAIAGQAHAFAIAFQAQAIAJAKQAJAKAAAUQAAAVgOANQgNAMgVAAQgMAAgJgDgAGDBlQgMgMAAgWQAAgUAKgMQALgMARgGQASgFAWAAIAAgMQABgIgGgGQgFgHgNAAQgLAAgJADIgOAFIgIACQgBAAAAAAQgBAAAAgBQgBAAAAgBQgBAAAAgBIgDgIIAAgHQAAgDAHgEQAIgEALgDQAMgDAMAAQAbAAANANQAOAMAAAVIAABBQAAATACAJIABALQAAADgEACQgFACgFAAIgIABQgEAAgCgEIgEgOQgGAJgKAFQgJAGgNAAQgUAAgLgNgAGhAqQgLAGABASQgBALAGAGQAEAGAJAAQAJAAAIgEQAGgEAFgJIAAglQgaAAgKAHgAFFBuQgJgDgFgIQgFgJAAgPIAAi0QAAgEADgCQADgCAHAAIAFAAQAHAAADACQADACAAAEIAACxQAAAJACAEQACADAGAAIAHAAIAFgBQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIACAIIAAAFQAAAEgDACIgKAEIgKABQgJAAgHgEgACFBlQgMgMAAgWQABgUAJgMQALgMASgGQARgFAXAAIAAgMQAAgIgGgGQgFgHgNAAQgKAAgKADIgOAFIgIACQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAAAgBgBIgCgIIAAgHQAAgDAHgEQAIgEALgDQAMgDAMAAQAbAAANANQAOAMAAAVIAABBQAAATABAJIACALQgBADgEACQgEACgGAAIgIABQgEAAgCgEIgEgOQgGAJgJAFQgKAGgNAAQgTAAgMgNgACjAqQgKAGAAASQAAALAFAGQAFAGAJAAQAJAAAHgEQAHgEAFgJIAAglQgaAAgLAHgAkBBdQgPgUAAgnQAAgmAPgVQAQgVAeAAQAIAAAJACQAIABAGADQAFADAAADIgBAHIgCAHQgCAEgDAAIgJgCQgHgDgKAAQgRAAgGANQgIAMAAAdQAAAdAIANQAGANARAAQALAAAIgCQAHgDADAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAABIADAHIAAAHQABADgGADQgGAEgIACQgJACgJAAQgeAAgQgVgAqJBdQgPgUAAgnQAAgmAPgVQAPgVAdAAQAWAAANAMQAIgBACgDQADgCAAgFQAAgGgEgFQgEgEAAgDQAAgCACgCIAHgFQADgCADAAQADAAADAEIAFAKQACAFAAAFQAAAOgJAIQgEAFgJACQAMAUAAAjQAAAngPAUQgPAVgcAAQgdAAgPgVgApygIQgGANAAAcQAAAdAGANQAGANAOAAQAOAAAHgNQAHgNgBgdQABgcgHgNQgHgNgOAAQgOAAgGANgALzBwQgIAAgDgCQgDgCAAgDIAAhpQAAgJgEgFQgGgGgKAAQgGAAgGADQgFADgEAEIgFAIIAABrQAAADgDACQgDACgHAAIgFAAQgHAAgDgCQgDgCAAgDIAAjSQAAgIANAAIAFAAQANAAAAAIIAABPQAGgIAKgGQAKgGAMAAQARAAALAKQAMAKAAAVIAABuQAAADgEACQgDACgHAAgAJkBwQgJAAgCgCQgEgCAAgDIAAhpQABgJgFgFQgFgGgKAAQgHAAgFADQgGADgDAEIgGAIIAABrQAAADgCACQgDACgIAAIgEAAQgIAAgDgCQgCgCAAgDIAAhnQAAgSgCgJIgCgMQAAgCAFgCIAJgCIAJgBQAEAAABAFQADAEACAMQAHgKALgHQAKgGAMAAQAQAAALAKQAMAKAAAVIAABuQAAADgDACQgDACgIAAgAhBBwQgIAAgDgCQgDgCAAgDIAAhpQAAgJgFgFQgEgGgLAAQgHAAgFADQgGADgDAEIgFAIIAABrQAAADgDACQgDACgIAAIgDAAQgIAAgDgCQgDgCAAgDIAAjSQAAgIANAAIAEAAQAOAAAAAIIAABPQAGgIAKgGQAKgGAMAAQAQAAAMAKQAMAKgBAVIAABuQAAADgDACQgDACgHAAgAllBwQgHAAgDgCQgDgCAAgDIAAhpQAAgJgFgFQgEgGgJAAQgJAAgGAGQgHAFgDAHIAAACIAABpQAAADgDACQgDACgIAAIgEAAQgHAAgDgCQgEgCAAgDIAAhpQAAgJgDgFQgFgGgKAAQgGAAgFADQgEADgEAEIgFAIIAABrQAAADgDACQgDACgIAAIgDAAQgIAAgDgCQgDgCAAgDIAAhnQAAgSgCgJIgBgMQAAgCAEgCIAJgCIAJgBQAEAAACAFQACAEACAMQAHgKAJgHQALgGAMAAQALAAAKAFQAJAGAFANQAGgKAKgHQAKgHANAAQAPAAALAKQALAKAAAVIAABuQAAADgDACQgEACgGAAgAGxg9QgEgBgEgGIgNgSIgFgHQgBgBAAAAQgBgBAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAgBIALgBQAKAAAFACQADACADAEIAJAWIACAFIABAEQAAAEgIAAIgKgBgApuhAIABgEIACgFIAJgWQACgEAEgCQAEgCAKAAIALABQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABAAABQgBAAAAABIgFAHIgOASQgEAGgDABIgLABQgHAAAAgEgAAAhDQgFgCAAgDIABgFQAEgKAHgFQAHgEAIAAQAHAAAHADIANAFQAGACAFAAQAFAAADgDIAFgFQAAAAABgBQAAgBABAAQAAAAABgBQAAAAAAAAIAHACQAEADAAACQAAACgDAGQgEAHgFAEQgGAFgKAAQgHAAgHgDIgOgFQgFgDgFAAQgGAAgCADIgEAGQgBAAAAABQgBAAAAABQgBAAAAAAQgBAAgBAAIgEgBg");
	this.shape.setTransform(77.25,11.425);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,154.5,22.9);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#007E9E").s().p("AF7CYQgNgKAAgTQAAgNAGgJQAGgJALgGIAAgBQgKgGAAgOQAAgKADgGQAEgHAGgFQgLgGgFgKQgFgLAAgNQAAgYANgNQANgNAXAAQAIAAAIACIApAAQAHgBAAAKIAAAEQAAAKgHAAIgIgBIgGgBIgBACQAHAKAAAPQAAAUgMANQgMAOgWABQgIAAgGADQgFAFAAAHQAAAHAFAEQAFADAIABIAQACQAQADAMAJQALAJAAASQAAAVgPAMQgPAMgdAAQgagBgNgIgAGMBoQgEAHAAAHQAAAUAdAAQAeAAAAgUQAAgIgFgDQgEgEgHgCIgPgCIgPgEQgFAEgEAFgAGUgaQgHAGAAAQQAAAQAHAFQAGAFAKAAQAJAAAHgFQAHgFAAgQQAAgQgHgGQgHgFgJgBQgKABgGAFgAKWCfQgMAAAAgFIABgFIAQgwIgqiQIgBgEQAAgFANAAIAGAAIAIABQADABABADIAZBsIABAAIAXhsQAAgDAEgBIAIgBIAGAAQALAAAAAFIAAACIAAACIg1DFQgBADgEABIgIABgALmCFQgDgCAAgDIABgDIADgGIACgIQACgFAAgJIABgYQAAgJANAAIAFAAQANAAAAAIQAAANgEAKQgDALgFAJQgFAJgFAEQgFAFgEABIgGgBgAkABjQgJgDgGgFQgFgEAAgEQAAgCACgFIAFgHQACgDACAAIAFACIAJAFQAFADAIAAQAJAAAFgEQAGgFAAgJQAAgKgHgFQgHgGgLgGQgNgGgJgKQgIgKAAgQQAAgUANgLQAMgLATAAIAQABQAHACAGACQAFAEAAAEIgCAHIgEAIQgCADgCAAIgHgDQgFgDgJAAQgIAAgFADQgFAEAAAHQAAAKAHAFIAPAJQAPAHAIALQAJAKAAASQAAAVgNAMQgNAMgUAAQgLAAgJgCgAH6BZQgLgMAAgVQAAgUAKgLQAKgMARgFQARgFAWgBIAAgJQAAgKgFgGQgFgGgNAAQgLAAgIADIgOAEIgIADQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAgBQgCgDgBgEIAAgGQAAgEAHgDQAHgEALgEQAMgCALAAQAagBANAMQANANAAAVIAAA+QAAATACAIIABAKQAAADgEACQgEACgFABIgIABQgEAAgCgFIgEgNQgGAIgJAFQgJAGgNAAQgTAAgLgMgAIYAfQgLAHAAARQAAALAFAFQAEAGAKAAQAIAAAHgEQAHgEAFgIIAAgkQgZgBgKAHgACHBiQgHgEgGgIQgFgIAAgOIAAhbIgKAAQgGAAAAgKIAAgEQAAgLAGABIAKAAIAEgeQABgHAKAAIAEAAQAGAAADABQADACAAAEIAAAeIARAAQAHgBAAALIAAAEQAAAKgHAAIgRAAIAABXQAAAKACADQACAEAFgBIAHgBIAEAAQABAAAAAAQABAAAAABQABAAAAABQAAAAABABIABAHIABAGQAAADgEADIgJADIgKABQgIAAgIgDgAgXBZQgLgMAAgVQAAgUAJgLQAKgMAQgFQARgFAWgBIAAgJQAAgKgFgGQgFgGgMAAQgLAAgIADIgOAEIgHADQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBgBgBQgCgDAAgEIgBgGQAAgEAHgDQAHgEAMgEQAKgCAMAAQAagBANAMQANANAAAVIAAA+QAAATABAIIACAKQAAADgFACQgEACgFABIgIABQgEAAgCgFIgDgNQgHAIgJAFQgJAGgMAAQgTAAgKgMgAAFAfQgJAHAAARQAAALAEAFQAEAGAJAAQAJAAAHgEQAHgEAEgIIAAgkQgZgBgKAHgAicBRQgOgTAAgnQAAgkAOgVQAPgTAcAAQAcAAAOATQAOAVAAAkQAAAngOATQgOAUgcAAQgcAAgPgUgAiFgQQgGANAAAaQAAAcAGANQAGAMANAAQAOAAAGgMQAGgNAAgcQAAgagGgNQgGgNgOAAQgNAAgGANgAqGBZQgLgMAAgVQAAgUAKgLQAKgMARgFQARgFAWgBIAAgJQAAgKgFgGQgFgGgNAAQgLAAgIADIgOAEIgIADQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAgBQgCgDgBgEIAAgGQAAgEAHgDQAHgEALgEQAMgCALAAQAagBANAMQANANAAAVIAAA+QAAATACAIIABAKQAAADgEACQgEACgFABIgIABQgEAAgCgFIgEgNQgGAIgJAFQgJAGgNAAQgTAAgLgMgApoAfQgLAHAAARQAAALAFAFQAEAGAKAAQAIAAAHgEQAHgEAFgIIAAgkQgZgBgKAHgAFFBkQgHAAgDgCQgDgCAAgEIAAhjQAAgLgEgFQgFgFgKAAQgGAAgGADQgFACgDAFIgFAHIAABnQAAAEgDACQgDACgHAAIgEAAQgIAAgDgCQgCgCAAgEIAAhiQAAgTgCgIIgBgLQAAgDAEgCIAJgCIAIAAQAEAAACAEIAEAPQAHgJAKgHQAKgFAMAAQAPAAAMAJQAKAKAAAUIAABqQAAAEgDACQgDACgHAAgAlmBkQgIAAgDgCQgDgCAAgEIAAhjQAAgLgEgFQgEgFgJAAQgIAAgHAFQgGAFgDAGIAAAEIAABkQAAAEgDACQgDACgHAAIgEAAQgHAAgDgCQgDgCAAgEIAAhjQAAgLgEgFQgFgFgJAAQgGAAgEADQgFACgEAFIgEAHIAABnQAAAEgDACQgDACgHAAIgEAAQgIAAgDgCQgCgCAAgEIAAhiQAAgTgCgIIgBgLQAAgDAEgCIAJgCIAIAAQAEAAACAEIAEAPQAHgJAJgHQAJgFAMAAQALAAAJAEQAKAGAEAMQAGgJAKgHQAJgGAMAAQAPAAALAJQALAKAAAUIAABqQAAAEgDACQgDACgHAAgArPBkQgNAAAAgIIAAipIgnAAQgHAAAAgKIAAgGQAAgKAHAAIBtAAQAHAAAAAKIAAAGQAAAKgHAAIgnAAIAACpQAAAIgNAAgAAEhGIABgFIACgEIAKgVQABgFAEgBQAFgCAJAAIAKABQABAAABABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBABIgFAIIgNAQQgEAGgDABIgKABQgIAAAAgDgApJhEQgEgBgCgGIgJgOIgJAOQgDAGgDABIgJABQgIAAAAgDIABgFIACgEIAJgVQACgFAFgBQAFgCAIAAQAIAAAFACQAEABACAFIAJAVIACAEIACAFQAAADgJAAIgIgBgApZh4QgEgBgDgEIgNgSIgGgIQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQABAAAAgBIAKgBQAKAAAEACQAEACACAEIAJAVIACAGIABADQAAAEgIAAQgGAAgDgCg");
	this.shape.setTransform(77.875,16.05);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,155.8,32.1);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF915C").s().p("ALzCfQgYggAAhCQAAhBAYggQAXgfAuAAQAtAAAXAfQAYAgAABBQAABCgYAgQgXAggtAAQguAAgXgggAMQgKQgMAWAAAxQAAAyAMAYQANAXAbAAQAbAAAMgXQANgYAAgyQAAgxgNgWQgMgYgbAAQgbAAgNAYgABbCsQgWgTABgkIAAitQAAgEADgDQAFgCAJAAIAFAAQAJAAAFACQADADAAAEIAACuQAAATAMALQALAKAUAAQAVAAALgKQAMgLAAgTIAAiuQAAgJARAAIAHAAQAJAAADgEQADgEAAgEQAAgIgEgGQgFgGAAgDQAAgDAEgDIAHgFIAHgCQAEAAADAFQAEAEACAHQACAGAAAGQAAAPgJAKQgEAGgLACIAACpQAAAkgVATQgWATgoAAQgoAAgVgTgAokCgQgXggAAhDQAAhAAYggQAZggAzAAQAMAAAKACQALACAGACQAIADAAAHQAAAHgDAIQgDAHgEAAIgOgCQgHgCgPAAQghAAgOAWQgOAWAAAyQAAA0ANAWQAOAXAeAAIANgBIALgDIAAhJIgeAAQgIAAAAgNIAAgHQAAgOAIAAIA4AAQAMAAAAANIAABnQAAAEgCADQgCAEgEADQgKAGgQAEQgQAEgQAAQgvAAgXgfgAvSCsQgWgTAAgkIAAitQAAgEAEgDQAFgCAJAAIAFAAQAJAAAEACQAEADAAAEIAACuQAAATAMALQALAKAUAAQAVAAALgKQALgLAAgTIAAiuQABgJARAAIAFAAQAJAAAEACQAEADAAAEIAACtQAAAkgWATQgVATgoAAQgoAAgVgTgAPSC9QgJAAgEgCQgEgCAAgFIAAjsQAAgEAEgDQAEgCAJAAIAGAAQAJAAAEACQADADAAAEIAADsQAAAFgDACQgEACgJAAgAKYC9QgJAAgFgCQgEgCAAgFIAAhpIhPAAIAABpQAAAFgDACQgFACgJAAIgFAAQgKAAgDgCQgEgCAAgFIAAjsQAAgEAEgDQADgCAKAAIAFAAQAJAAAFACQADADAAAEIAABiIBPAAIAAhiQAAgEAEgDQAFgCAJAAIAFAAQAJAAAEACQAEADAAAEIAADsQAAAFgEACQgEACgJAAgAFpC9QgIAAgEgCQgEgCAAgFIAAjoQAAgMAMAAIA4AAQBHAAAABJQAABMhHAAIgcAAIAABfQAAAFgFACQgDACgJAAgAGBAzIAcAAQARAAAIgKQAHgJAAgXQAAgUgHgKQgIgKgRAAIgcAAgAgIC9QgJAAgEgCQgEgCAAgFIAAhpIhPAAIAABpQAAAFgEACQgEACgJAAIgGAAQgJAAgDgCQgFgCAAgFIAAjsQAAgEAFgDQADgCAJAAIAGAAQAJAAAEACQAEADAAAEIAABiIBPAAIAAhiQAAgEAEgDQAEgCAJAAIAGAAQAHAAAEACQAFADAAAEIAADsQAAAFgFACQgEACgHAAgAkDC9QgPAAAAgJIAAjTIgyAAQgHAAgBgNIAAgHQABgNAHAAICJAAQAJAAgBANIAAAHQABANgJAAIgwAAIAADTQAAAJgQAAgAqEC9QgIAAgDgBQgEgCgCgFIhHiSIgEgLIgEgNIgCAAIABAMIABANIAACQQgBAFgDACQgEACgJAAIgFAAQgJAAgEgCQgDgCAAgFIAAjsQAAgJAQAAIAJAAQAIAAAEACQAEACACAEIBHCRIAFAMIADAMIACAAIgBgMIgBgNIAAiPQAAgEAFgDQADgCAJAAIAFAAQAJAAAEACQADADAAAEIAADsQAAAJgQAAgANPhQQgDAAgDgDIgQgPIgRAPQgEADgDAAIgIABQgLAAAAgEIACgFIAFgHIANgSQADgEAFgCQAEgCALAAQAJAAAEACQAFACADAEIAOASIAEAHIACAFQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBABQgCABgGAAIgIgBgAMviEQgFgEAAgDQAAgCAGgDIAJgHQAFgFgBgGQABgEgEgCQgEgCgEAAQgGAAgEABIgFABQgCAAgDgEQgEgFAAgEQAAgDAJgDQAJgDAKAAQALAAALAFQAKAGgBAOQAAAHgDAHQgFAGgGAFQgFAGgGACIgHADQgDAAgDgDg");
	this.shape.setTransform(100.05,19.125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,200.1,38.3);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.logo();
	this.instance.setTransform(-222,-1,0.105,0.105);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FCAF17").s().p("AgNBBIgBAAIgEgBQgIgCABgHIABgFIABAAIAAgBIAAAAQAHgKAVgNIAagSQACgDgGgDIgugTIAAgBIgBABQABAGAIALQAIAJADADQABABAAAAQABAAABABQAAAAABAAQAAAAAAAAQACgBAAgFIAAgCIgBgMIAMAGIgBAJIgBABQgCAKgGAAQgGAAgFgHQgOgOgGgOQgEgKALABQAUADAgALQATAHgBAIQAAAGgHAHIgtAeIgDADIACAAIAbgCIABAAQABAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAIgNgJIADgCIAQAJQAGAFgJAFQgHADgPADQgOADgHAAIgCAAgAguAGQgHgDABgEQAAgEAQgVQAggnAJABQAGABADAJQADAKABAbIgOgEIgCgRQAAgBgBgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIgIAGIgKALQgGAAgCACQgBACABAEIgGAGQgLAKAAABQAAACAGADIAmAVIgDADg");
	this.shape.setTransform(46.6258,6.2754);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#860052").s().p("AC3AaQgFgEAAgFQAAgFADgCQAEgHAQgBIAHgBIAAAAQAAgLgKAAQgIgBgBAGIgHgDIABAAQAEgJAKABQAJAAAEADQAFAFAAAHIAAAVIACAIIgIAAIgBgGIgFAFQgFACgFAAQgGAAgEgDgADEAJQgKABAAAHQAAAGAJAAQAIAAADgHQACgCAAgHgACPAWQgEgGAAgJQAAgJAEgHQAGgHAKAAQAMAAAFAJIgHACQgDgFgHAAQgNAAABAQQAAARANAAQAHAAADgFIAGACQgFAJgMAAQgKAAgGgHgABgAFQAAgJAHgGQAFgGAIAAQAOAAAEAQIABAIIgfAAQgBAQAOAAQAFAAAEgFIAHABQgEAJgNAAQgUAAAAgYgABoACIAYAAQgBgMgMAAQgJAAgCAMgAANAFQAAgJAHgGQAFgGAIAAQAOAAAEAQIABAIIgfAAQAAAQANAAQAFAAAEgFIAHABQgFAJgMAAQgUAAAAgYgAAVACIAXAAQAAgMgMAAQgKAAgBAMgAhFAaQgFgEAAgFQAAgFACgCQADgGARgCIAHgBIAAAAQAAgLgKAAQgIgBgBAGIgGgDIAAAAQAEgJALABQAIAAAFADQAEAFAAAHIAAAVIACAIIgHAAIgCgGQgIAHgGAAQgGAAgEgDgAg5AJQgJABAAAHQAAAGAIAAQAJAAADgHQABgCAAgHgAA4AcIAAgqIAIAAIAAAHQAEgJAJAAQALAAAEAKIAAAiIgHAAIAAgfQgCgFgIAAQgFAAgDACQgDAEAAAFIAAAZgAgfAcIAAgHIAggqIggAAIAAgHIApAAIAAAHIggAqIAgAAIAAAHgAhgAcIAAgrIAHAAIAAAIQAEgIALAAIAAAIQgKAAgDAFQgCACAAAIIAAAUgAh2AaIgBgHIAAgbIgHAAIAAgHIAHAAIAAgKIAIgDIAAANIAIAAIAAAHIgIAAIAAAYQAAAHADAAIAFgBIAAAGIgHAAQgGAAgCgCgAikATIAIAAQADAEAIAAQALAAgBgHQAAgFgMgDQgQgDAAgJQAAgNARABQAMAAAEAIIgHADQgBgGgJAAQgJAAAAAGQAAAFAKABQATAEAAAKQAAAFgEAFQgGADgJAAQgNABgFgKgAitAcIgHgRIgVAAIgHARIgIAAIAWg4IAIAAIAVA4gAjHAEIAAAAIARAAIgIgWg");
	this.shape_1.setTransform(20.25,9.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-222,-1,274,21);


(lib.Symbol26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol27("synched",0);
	this.instance.setTransform(126.8,31.2,1,1,0,0,0,126.8,31.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(19).to({scaleX:1.1,scaleY:1.1,x:126.75},0).wait(20));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.7,-3.1,279,68.6);


(lib.Symbol24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol25("synched",0);
	this.instance.setTransform(92.6,-7.9,1,1,0,0,0,92.3,16.1);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:17.9,alpha:1},10,cjs.Ease.get(1)).to({y:16.1},8,cjs.Ease.get(1)).wait(100).to({startPosition:0},0).to({_off:true},1).wait(848));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.3,-24,184.5,58);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol23("synched",0);
	this.instance.setTransform(25.6,25.8,1,1,0,0,0,25.6,25.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},15,cjs.Ease.get(1)).wait(203).to({startPosition:0},0).to({_off:true},1).wait(3760));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.5,0.5,51.1,51.6);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.instance = new lib.Symbol21("synched",0);
	this.instance.setTransform(127.35,100.3,1,1,0,0,0,77.3,11.4);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(26).to({_off:false},0).to({x:98.15},14,cjs.Ease.get(1)).to({x:99.35},6,cjs.Ease.get(1)).wait(172).to({startPosition:0},0).to({_off:true},1).wait(1777));

	// Layer_2
	this.instance_1 = new lib.Symbol20("synched",0);
	this.instance_1.setTransform(71.6,66.05,1,1,0,0,0,77.9,16.1);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(26).to({_off:false},0).to({x:100.8},14,cjs.Ease.get(1)).to({x:99.6},6,cjs.Ease.get(1)).wait(172).to({startPosition:0},0).to({_off:true},1).wait(1777));

	// Layer_1
	this.instance_2 = new lib.Symbol19("synched",0);
	this.instance_2.setTransform(100.05,27.1,0.3,0.3,0,0,0,100.2,19.2);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regX:100,regY:19,scaleX:1.15,scaleY:1.15,y:19.1,alpha:1},15,cjs.Ease.get(1)).to({startPosition:0},11,cjs.Ease.get(1)).to({regY:19.1,scaleX:1,scaleY:1,x:100},14,cjs.Ease.get(1)).wait(178).to({startPosition:0},0).to({_off:true},1).wait(1777));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.9,-2.8,230.1,114.6);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_218 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(218).call(this.frame_218).wait(1));

	// logo
	this.instance = new lib.Symbol13("synched",0);
	this.instance.setTransform(253.5,27.5,1,1,0,0,0,15.5,15.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},14,cjs.Ease.get(1)).wait(205));

	// phoi
	this.instance_1 = new lib.Symbol22("synched",0);
	this.instance_1.setTransform(149.6,200.8,1,1,0,0,0,25.6,25.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(219));

	// cta
	this.instance_2 = new lib.Symbol26();
	this.instance_2.setTransform(150.8,131.2,1,1,0,0,0,126.8,31.2);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(121).to({_off:false},0).to({alpha:1},19,cjs.Ease.get(1)).wait(79));

	// Layer_10
	this.instance_3 = new lib.Symbol24("synched",0);
	this.instance_3.setTransform(151.3,70.1,1,1,0,0,0,92.3,16.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(100).to({_off:false},0).wait(119));

	// bg copy
	this.instance_4 = new lib.Symbol28("synched",0);
	this.instance_4.setTransform(150,125,1,1,0,0,0,150,125);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(85).to({_off:false},0).to({alpha:1},16,cjs.Ease.get(1)).wait(118));

	// Layer_5
	this.instance_5 = new lib.Symbol17("synched",0);
	this.instance_5.setTransform(150.55,59.05,1,1,0,0,0,100,19.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(219));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEF8F0").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(219));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


// stage content:
(lib._300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,125,150,125);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/logo.png?1700144278247", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;