(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bg1 = function() {
	this.initialize(img.bg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,1220);


(lib.bg2 = function() {
	this.initialize(img.bg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,465,940);


(lib.bg3 = function() {
	this.initialize(img.bg3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,651);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,200,200);


(lib.Tween4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.514,1],-7.6,-4.8,7.6,4.7).s().p("AjICZID5mQICYBgIj5GOg");
	this.shape.setTransform(-0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-20.1,-24.7,40.2,49.5);


(lib.Tween3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.514,1],-7.6,-4.8,7.6,4.7).s().p("AjICZID5mQICYBgIj5GOg");
	this.shape.setTransform(-0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-20.1,-24.7,40.2,49.5);


(lib.Symbol33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AG4CDIgcABIAAgFQAJgBAEgBQAEgCABgEIAAgHIAAiPQAAgLgEgDQgDgDgLAAIAAgEQASgCAOgEQADAIABAQQALgXAUgBQAUAAANAUQANATAAAeQAAAdgNATQgMAUgVAAQgMAAgIgIQgEgFgFgJIAAA3IABAJQADAGANAAIAAAFIgbgBgAHMgoQgLANAAAkQAAA+AcAAQAbAAAAg7QAAg+gcAAQgJAAgHAKgAh+CDIgcABIAAgFQAJgBAEgBQAEgCABgEIAAgHIAAiPQAAgLgEgDQgDgDgLAAIAAgEQASgCAOgEQADAIABAQQALgXAUgBQAUAAANAUQANATAAAeQAAAdgNATQgMAUgVAAQgMAAgIgIQgEgFgFgJIAAA3IABAJQADAGANAAIAAAFIgbgBgAhqgoQgLANAAAkQAAA+AcAAQAbAAAAg7QAAg+gcAAQgJAAgHAKgAnvBSIgUgiIhOiGIAACKQAAAJACADQADAFAPACIAAAGIgYgBIgYABIAAgGQAKgCAEgBQAFgDABgGIAAgHIAAiTQgEgFgFgBIgLgCIAAgHIAUABIASgBIBTCNIAAh0IgBgLQgEgGgPgBIAAgHIAZACIAXgCIAAAHQgJABgFABQgFADAAAFIgBAIIAACngAKwA7QgMgUAAgcQAAgeANgUQAOgTAWAAQAVAAANAUQAMAUAAAcQAAAdgNAUQgNAUgWABQgWgBgNgUgALDgpQgLAPAAAlQAAA9AbABQALgBAHgKQAJgQAAgjQAAg+gbAAQgJAAgHAKgANjBLQgEgFAAgHQAAgGAEgFQAEgFAGAAQAGAAAEAFQAEAFAAAGQAAAHgEAFQgEAEgGAAQgGAAgEgEgAB3BFQgKgKAAgQQAAgZAbgOQAQgGAVgDIAAgRQAAgOgEgFQgFgJgMAAQgJAAgHAGQgEAEAAAHIAAACIAAAEQAAAMgKAAQgIAAAAgJQAAgMALgLQAMgKARgBQAMAAAKAHQAMAHADAOQABAHAAAMIAAA4QAAAOACAFQACAGAGAAIAGgBIAAAHQgIACgGAAQgKABgFgJQgDgFgBgKQgEAKgFAEQgJAKgOAAQgPAAgJgKgACRALQgRAKAAAUQAAANAGAGQAFAHAKAAQAPAAAGgRQADgIAAgQIAAgYQgRADgLAGgAk6BFQgKgKAAgQQAAgZAcgOQAQgGAUgDIAAgRQAAgOgEgFQgFgJgLAAQgKAAgGAGQgEAEAAAHIAAACIAAAEQAAAMgKAAQgIAAAAgJQAAgMAKgLQANgKARgBQAMAAAJAHQAMAHADAOQACAHAAAMIAAA4QAAAOABAFQACAGAGAAIAGgBIAAAHQgIACgFAAQgLABgEgJQgDgFgBgKQgFAKgFAEQgIAKgPAAQgPAAgJgKgAkfALQgRAKAAAUQAAANAGAGQAFAHAJAAQAQAAAFgRQADgIAAgQIAAgYQgRADgKAGgArbA2QgFALgFAEQgJAJgOAAQgUAAgKgPQgGgLAAgUIAAg/IgBgLQgDgGgNAAIAAgEQATgCARgGIAABdQAAAQAEAIQAGAJAMAAQAOAAAHgMQAFgHAAgSIAAg8QAAgIgCgDQgCgGgOAAIAAgEQATgCASgGIAAAKQAHgKAAgIIgCAAQgKgDADgLQACgKAIAAQAMAAAAAOQAAANgLAPIgEAFIgFAEIAABfQAAAGACADQACADAGAAIAIABIAAAFQgTACgPAFIgBgZgAtoA/QgCgGAAgKIgBgOIAAhNIgPAAIAAgJQAGgBAFgCQANgIAFgfIAGAAIAAApIAdAAIAAAKIgdAAIAABQQAAARADAGQADAJAJAAQAGAAAKgGIAAAJQgNAIgLAAQgSAAgGgQgAMvBLIgbACIAAgFQAIAAAEgDQAEgBABgFIABgGIAAhYQAAgIgCgDQgCgEgGgBIgIgBIAAgEQAUgCARgGIAAB1QAAAGACADQACAFAOABIAAAFIgcgCgAJ6BLQgKAAgQACIAAgFQAHAAAEgDQAEgBABgFIAAgGIAAhEQAAgQgEgHQgFgKgNAAQgNAAgHALQgFAHAAARIAABCIABAJQADAFAMABIAAAFQgQgCgKAAQgLAAgQACIAAgFQAIAAAEgDQAEgBABgFIABgGIAAiNQAAgHgCgEQgCgEgGAAIgIgBIAAgFQATgCASgGIAABKQAMgSATgBQAUAAAKASQAGAKAAAVIAABCQAAAGABADQADAFANABIAAAFQgQgCgLAAgAE6BLQgLAAgPACIAAgFQAHAAAEgDQAEgBABgFIAAgGIAAhEQAAgQgEgHQgFgKgNAAQgNAAgHALQgFAHAAARIAABCQAAAGABADQADAFAMABIAAAFQgQgCgLAAQgKAAgQACIAAgFQAIAAAEgDQAEgBABgFIAAgGIAAhWIAAgKQgBgGgGgBIgKgBIAAgEQAUgEAMgFQACAIABARQANgXAUAAQAUAAAKASQAGAKAAAVIAABCIABAJQADAFANABIAAAFQgQgCgLAAgABDBLQgKAAgQACIAAgFQAHAAAEgDQAEgBABgFIAAgGIAAhEQAAgQgEgHQgFgKgNAAQgNAAgHALQgFAHAAARIAABCIABAJQADAFAMABIAAAFQgQgCgKAAQgKAAgQACIAAgFQAIAAAEgDQAEgBABgFIABgGIAAiNQAAgHgCgEQgCgEgGAAIgIgBIAAgFQATgCARgGIAABKQAMgSATgBQAUAAAKASQAGAKAAAVIAABCQAAAGABADQADAFANABIAAAFQgQgCgLAAgAltBLQgLAAgQACIAAgFQAIAAAEgDQAEgBAAgFIABgGIAAhEQAAgQgEgHQgGgKgMAAQgNAAgIALQgEAHAAARIAABCIABAJQADAFALABIAAAFQgPgCgLAAQgLAAgQACIAAgFQAJAAAEgDQAEgBABgFIAAgGIAAiNQAAgHgBgEQgCgEgHAAIgHgBIAAgFQATgCASgGIAABKQALgSAUgBQATAAAKASQAGAKAAAVIAABCQAAAGACADQADAFANABIAAAFQgQgCgLAAgALphHIgXgWIgWAWIgHAAIAYgiIAMAAIAYAigACxhHIgXgWIgXAWIgGAAIAYgiIAMAAIAYAigAkNhNIgigjIAUAAIAUAjgArqhNIgigjIAUAAIAUAjgAMlhTQgEgEAAgHQAAgHAEgEQAEgEAGAAQAFAAAEAEQAEAFAAAGQAAAHgEAEQgEAEgFABQgGgBgEgEgALphgIAUgkIAUAAIgiAkg");
	this.shape.setTransform(125.175,9.65);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(36.1,-3.6,178.20000000000002,26.5);


(lib.Symbol32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AM1CCIgZACIAAgGQAIAAADgCQAEgCABgEIAAgHIAAg3QgEAJgEAFQgHAIgMAAQgSAAgLgUQgLgTAAgdQAAgdAMgUQALgTASAAQASAAAKAXQABgPACgJQALAEARACIAAAEIgDABQgIAAgCAEQgDADAAAJIAACPIABAKQADAFAMAAIAAAGIgYgCgAMEgoQgJAOAAAkQAAA8AYAAQAZAAAAg+QAAg6gYAAQgJAAgHAKgAPWCCIAAgOQAIAAAFgCQAKgEAGgSIAHgVIghhtQgCgIgEgCQgDgCgHgBIAAgFIAWABIAWgBIAAAFIgGABQgFABAAAEIACAIIAXBQIAXhPIACgIQAAgFgFgBIgHgBIAAgFIAQABIATgBIAAAFIgKADQgEADgDAIIgpCIQgGATgIAHQgIAFgKAAIgDAAgAIQB+QgCgDAAgGQAAgFACgEQADgEAFAAQAEAAADAEQACAEAAAFQAAAFgCAEQgDAEgEAAQgFAAgDgEgAvgB+QgDgDAAgGQAAgFADgEQACgEAFAAQAEAAADAEQACAEAAAFQAAAFgCAEQgDAEgEAAQgFAAgCgEgAyYBRIgSgiIhFiFIAACJQAAAJABADQADAGAOABIAAAHIgWgCIgVACIAAgHQAJgBADgCQAFgDAAgFIABgIIAAiTQgEgEgEgCIgLgCIAAgHIATABIAQgBIBKCNIAAhzQAAgJgCgDQgCgGgOgBIAAgHIAWACIAVgCIAAAHQgJABgEACQgEACgBAGIAAAIIAACmgAGHA5QgKgUAAgaQAAgaAKgTQAKgXAUAAQALAAAHAIQAEAEAEAKIAAgmIggAAIAAgIIAgABIAAgEQAAgIgBgEQgCgEgGAAIgCgBIgEAAIAAgEQARgDAQgFIAAAgIAOAAIAAAIIgOAAIAAB4IAAAMQABAFAFABIAEABIAGAAIAAAFIgRAEIgMADIgCgLIgBgLQgJAXgSAAQgUAAgLgWgAGQAKQAAAZAEARQAGATAOAAQAIAAAGgJQAJgNAAglQAAg9gYAAQgXAAAAA7gAA/A5QgKgUAAgaQAAgaAKgTQAKgXAUAAQALAAAHAIQAEAEAEAKIAAgmIggAAIAAgIIAgABIAAgEQAAgIgBgEQgCgEgGAAIgCgBIgEAAIAAgEQARgDAQgFIAAAgIAOAAIAAAIIgOAAIAAB4IAAAMQABAFAFABIAEABIAGAAIAAAFIgRAEIgMADIgCgLIgBgLQgJAXgSAAQgUAAgLgWgABIAKQAAAZAEARQAGATAOAAQAIAAAGgJQAJgNAAglQAAg9gYAAQgXAAAAA7gAOiA1QgEAKgFAGQgIAJgNAAQgRAAgJgQQgGgKAAgUIAAhAQAAgIgBgDQgCgEgGgBIgGAAIAAgFQARgCAQgFIAABcQAAARADAHQAFAJALAAQANAAAGgMQAEgHAAgSIAAg8QAAgIgCgDQgBgEgGgBIgHAAIAAgFQARgCAQgFIAABxIABAJQACADAGABIAHAAIAAAFQgSACgMAGIgBgagAJfA7QgLgSAAgeQAAggAMgTQAMgTATAAQANAAAJAMIAGgOIAEAAIAAAuIgFAAQgCgNgDgHQgDgIgGgEQgFgEgGAAQgOAAgGASQgGARAAAaQAAA7AZAAQAUAAAEgkIAJAAQgBAPgFAKQgJAVgUAAQgTAAgMgUgAH4A6QgLgTAAgdQAAgeAMgTQAMgUAUAAQATAAALAUQALAUAAAcQAAAdgMAUQgLAVgUAAQgTAAgMgVgAIIgqQgJAPAAAlQAAA+AYAAQAKAAAGgLQAIgPAAgkQAAg+gYAAQgIAAgHAKgAguA1QgEAKgEAGQgJAJgMAAQgSAAgJgQQgFgKAAgUIAAhAQAAgIgCgDQgCgEgFgBIgHAAIAAgFQARgCAQgFIAABcQAAARAEAHQAFAJALAAQAMAAAGgMQAEgHAAgSIAAg8QAAgIgBgDQgCgEgFgBIgHAAIAAgFQARgCAQgFIAABxIABAJQACADAGABIAHAAIAAAFQgSACgMAGIgCgagARIA8QgMgTAAggQAAgdAMgUQALgSAUAAQAOAAALAMQAOAQAAAkIhAAAIgBAGQAAAYAHARQAGAQAQAAQAQAAAHgRQAEgIABgLIAIAAQgBAQgHALQgKASgUAAQgVAAgLgSgAROgDIAvAAQgCgwgVAAQgVAAgDAwgACtBFQgIgLAAgQQAAgZAYgNQAOgHATgDIAAgQQAAgOgEgGQgEgJgKAAQgJAAgGAGQgDAEAAAHIAAACIAAAEQAAANgJAAQgHAAAAgKQAAgMAJgKQALgLAPAAQALAAAJAGQAKAHADAOQABAHAAAMIAAA4QAAAOACAFQABAGAGAAIAFgBIAAAIQgHACgFAAQgJAAgEgJQgDgFgBgKQgEAKgEAFQgIAJgNAAQgNAAgJgJgADFAKQgPAKAAAVQAAAMAFAHQAFAGAIAAQAOAAAFgQQADgJAAgQIAAgYQgPADgKAGgAijA1QgEALgFAFQgIAJgNAAQgRAAgJgQQgGgKAAgVIAAg/IgBgLQgCgFgMAAIAAgFQARgCAQgGIAABdQAAARADAHQAFAJALAAQAMAAAGgMQAFgHAAgSIAAg8QAAgIgCgDQgCgFgMAAIAAgFQARgCAQgGIAAAKQAHgKAAgIIgDAAQgIgDACgLQACgJAIAAQAKAAAAANQAAANgKAPIgEAFIgEAFIAABeIABAJQACADAGABIAHAAIAAAFQgRACgNAFIgBgZgAonA8QgMgTAAggQAAgdAMgUQALgSAUAAQAOAAALAMQAOAQAAAkIhAAAIgBAGQAAAYAHARQAGAQAQAAQAQAAAHgRQAEgIABgLIAIAAQgBAQgHALQgKASgUAAQgVAAgLgSgAohgDIAvAAQgCgwgVAAQgVAAgDAwgAreA+QgCgGgBgKIAAgOIAAhNIgOAAIAAgJQAGAAAEgDQAMgHAEgfIAGAAIAAAoIAZAAIAAAKIgZAAIAABQQAAARACAGQADAJAIAAQAFAAAJgGIAAAJQgLAIgKAAQgQAAgFgQgAv3BFQgIgLAAgQQAAgZAYgNQAOgHATgDIAAgQQAAgOgEgGQgEgJgKAAQgJAAgGAGQgDAEAAAHIAAACIAAAEQAAANgJAAQgHAAAAgKQAAgMAJgKQALgLAPAAQALAAAJAGQAKAHADAOQABAHAAAMIAAA4QAAAOACAFQABAGAGAAIAFgBIAAAIQgHACgFAAQgJAAgEgJQgDgFgBgKQgEAKgEAFQgIAJgNAAQgNAAgJgJgAvfAKQgPAKAAAVQAAAMAFAHQAFAGAIAAQAOAAAFgQQADgJAAgQIAAgYQgPADgKAGgATyBLQgKAAgOACIAAgGQAHAAADgCQAEgCAAgFIABgGIAAhDQAAgRgEgHQgEgKgMAAQgLAAgHALQgEAIAAAQIAABCIABAJQADAGAKAAIAAAGQgOgCgKAAQgJAAgOACIAAgGQAHAAAEgCQADgCABgFIAAgGIAAhWIAAgKQgBgGgGgBIgIAAIAAgFQASgDALgFQABAHABARQALgWASAAQASAAAJARQAFAKAAAVIAABCIABAJQADAFAMABIAAAGQgOgCgKAAgAEhBLIgZACIAAgGQAIAAADgCQAEgCABgFIAAgGIAAhYIgBgLQgCgEgGgBIgHAAIAAgFQASgCAPgFIAAB0QAAAHACACQACAFAMABIAAAGIgYgCgAlHBLQgJAAgOACIAAgGQAGAAADgCQAEgCABgFIAAgGIAAhHQAAgOgDgGQgEgKgLAAQgVAAAAAhIAABEIABAJQACAGALAAIAAAGQgOgCgJAAQgJAAgOACIAAgGQAGAAAEgCQADgCABgFIAAgGIAAhGQAAgPgDgHQgEgJgKAAQgNAAgGAMQgDAIAAAQIAABBIABAJQACAGALAAIAAAGQgOgCgKAAQgJAAgOACIAAgGQAHAAADgCQAEgCABgFIAAgGIAAhWIAAgKQAAgFgDgBIgMgBIAAgFQASgDALgGQACAMAAAMIAIgMQAJgJAMAAQATAAAIAWIAHgMQAJgKANAAQATAAAHARQAEAJAAASIAABGQAAAHACACQACAFAMABIAAAGQgOgCgKAAgApYBLQgKAAgOACIAAgGQAHAAADgCQAEgCAAgFIABgGIAAhDQAAgRgEgHQgFgKgLAAQgLAAgHALQgEAIAAAQIAABCIABAJQACAGALAAIAAAGQgOgCgKAAQgJAAgPACIAAgGQAIAAADgCQAEgCABgFIAAgGIAAiMQAAgIgBgEQgCgEgGAAIgGgBIAAgFQARgCAQgFIAABKQAKgTARAAQASAAAJARQAFALAAAUIAABCQAAAHABACQADAFAMABIAAAGQgPgCgJAAgAtIBLQgJAAgOACIAAgGQAGAAAEgCQADgCABgFIAAgGIAAhDQAAgRgDgHQgFgKgLAAQgMAAgGALQgFAIAAAQIAABCIABAJQADAGAKAAIAAAGQgOgCgJAAQgKAAgOACIAAgGQAIAAADgCQAEgCAAgFIABgGIAAhWIgBgKQAAgGgGgBIgJAAIAAgFQASgDALgFQACAHAAARQAMgWASAAQASAAAIARQAGAKAAAVIAABCIABAJQACAFAMABIAAAGQgOgCgKAAgAwkBLQgJAAgOACIAAgGQAGAAAEgCQADgCABgFIAAgGIAAhDQAAgRgDgHQgFgKgLAAQgMAAgHALQgEAIAAAQIAABCIABAJQADAGAKAAIAAAGQgOgCgJAAQgKAAgOACIAAgGQAHAAAEgCQAEgCAAgFIABgGIAAiMQAAgIgCgEQgCgEgFAAIgHgBIAAgFQARgCAQgFIAABKQAKgTASAAQARAAAJARQAFALAAAUIAABCQAAAHACACQACAFAMABIAAAGQgOgCgKAAgAR6hIIgUgVIgVAVIgGAAIAWghIALAAIAVAhgAIrhIIgUgVIgVAVIgGAAIAWghIALAAIAVAhgAn1hIIgUgVIgVAVIgGAAIAWghIALAAIAVAhgAvBhIIgUgVIgVAVIgGAAIAWghIAKAAIAWAhgAEYhUQgEgEAAgHQAAgGADgEQAEgFAFAAQAFAAADAFQAEAEAAAGQAAAHgEAEQgDAFgFAAQgFAAgDgFgADNhbQgGgFgEAAQgHAAgDANIgFgCQADgLAEgFQAEgGAGAAQAHAAAGAGQAIAHAFAAQAGAAADgNIAEABQgBAMgFAGQgEAFgGABIAAAAQgGAAgJgJgASJhgIgfgjIASAAIASAjg");
	this.shape.setTransform(109.525,3.175);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19.4,-10,257.9,26.4);


(lib.Symbol30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg3();
	this.instance.parent = this;
	this.instance.setTransform(-6,-19,0.9769,0.977);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6,-19,312.6,636);


(lib.Symbol29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AnpCmQgEgEAAgHQAAgHAEgEQAEgFAGAAQAGAAADAFQAEAEAAAHQAAAGgEAFQgDAFgGAAQgGAAgEgFgAGLBPQgNgYAAghQAAghAMgXQAPgdAcAAQAPAAAKAKQAFAGAGALIAAgvIgtAAIAAgKIAtABIAAgFQAAgKgCgEQgCgFgIgBIgEgBIgGAAIAAgGQAZgCAVgHIAAAoIAUAAIAAAKIgUAAIAACXIABAOQABAGAGACIAGABIAJABIAAAGQgNABgKADQgKACgHADIgDgOIgCgOQgMAdgZAAQgcAAgPgdgAGXAVQAAAgAGAUQAIAZATAAQAMAAAJgMQANgQAAguQgBhNgiAAQggAAAABKgAiLBTQgQgYAAglQAAgkAPgYQAPgZAZAAQAQAAAKALQAFAFAFALIAAg9QAAgKgBgEQgDgFgHgBIgKgBIAAgGQAYgCAWgHIAADJQgBAKACAEQACAGAFACIAOACIAAAGQgZADgPAGIgFgcQgMAdgZAAQgZAAgPgZgAiBAVQAAAgAGAUQAEALAHAHQAHAHAJAAQAMAAAJgMQAMgQAAguQAAhNgjAAQgfAAAABKgAtMBbQgUgRgJgiQgHgYAAgcQAAg1AWgiQALgSARgJQAOgHARAAQAcAAAUAVIALgVIAFAAIAABFIgHAAQgNg6goAAQgfAAgNAfQgOAeAAAwQAAAsANAdQANAgAgAAQATAAAOgPQAQgRADgjIALAAQgBAagJATQgIASgRAKQgOAKgTAAQgYAAgUgRgAoLBRQgQgYAAgkQAAglARgZQARgYAbAAQAaAAAQAZQAPAZAAAjQAAAlgPAYQgQAagbAAQgcAAgQgagAn0gsQgNATAAAuQAABNAhAAQAOAAAIgOQAMgSAAgtQAAhNghAAQgMAAgJAMgAMKBLQgGANgGAGQgMAMgSAAQgYAAgMgTQgIgNAAgaIAAhPQAAgKgCgEQgCgFgIgBIgJgBIAAgGQAXgCAXgHIAAB0QAAAVAEAIQAHAMAQAAQARAAAJgPQAFgKAAgVIAAhLQAAgKgCgEQgDgFgHgBIgKgBIAAgGQAYgCAWgHIAACNQAAAJACADQADAEAHABIALAAIAAAHQgZACgRAHQgCgKAAgWgANUBlQgFgGgBgIQABgJAFgGQAFgFAHAAQAHAAAFAFQAFAGAAAIQAAAJgFAGQgFAFgHAAQgIAAgEgFgAIlBeQgMgNAAgUQAAgfAigRQAUgJAZgEIAAgUQAAgRgFgIQgGgKgOAAQgMAAgIAHQgFAFAAAJIAAADIAAAFQAAAPgMAAQgKAAAAgLQAAgQANgNQAPgNAVAAQAPAAAMAHQAPAJADASQACAIAAAQIAABGQAAARADAHQACAHAHAAIAIgBIAAAJQgLADgGAAQgNAAgGgLQgDgHgCgMQgFAMgGAGQgLAMgSAAQgSAAgMgMgAJGAVQgVAMAAAaQAAAQAHAIQAHAIALAAQAUAAAGgVQAEgKAAgUIAAgfQgVAFgNAHgAAMBeQgMgNAAgUQAAgfAhgRQAUgJAZgEIAAgUQAAgRgEgIQgGgKgPAAQgLAAgJAHQgEAFgBAJIAAADIAAAFQAAAPgMAAQgKAAAAgLQAAgQANgNQAQgNAVAAQAPAAALAHQAPAJAEASQACAIAAAQIAABGQAAARACAHQACAHAHAAIAIgBIAAAJQgKADgHAAQgMAAgGgLQgEgHgBgMQgGAMgGAGQgLAMgRAAQgTAAgLgMgAAsAVQgUAMAAAaQAAAQAHAIQAHAIALAAQAUAAAGgVQADgKAAgUIAAgfQgVAFgNAHgAD/BmQgOAAgTACIAAgHQAJAAAFgCQAEgDABgFIABgIIAAhVQAAgVgFgIQgGgNgQAAQgRAAgJAOQgFAJAAAVIAABTQAAAIABADQAEAHAOAAIAAAHQgTgCgOAAQgNAAgTACIAAgHQAKAAAEgCQAGgDABgFIAAgJIAAhrIAAgMQgCgIgHgBIgMgBIAAgGQAZgEAOgGQADAJABAVQAQgbAZAAQAYAAAMAVQAIANAAAZIAABTQAAAJACADQAEAHAPAAIAAAHQgTgCgNAAgAkaBmQgOAAgTACIAAgHQAJAAAFgCQAFgDAAgFIABgIIAAhVQAAgVgFgIQgGgNgQAAQgRAAgIAOQgHAJABAVIAABTQgBAIACADQADAHAPAAIAAAHQgUgCgNAAQgNAAgTACIAAgHQAKAAAEgCQAGgDAAgFIABgJIAAhrIgBgMQAAgIgJgBIgLgBIAAgGQAZgEAOgGQADAJABAVQAQgbAZAAQAYAAAMAVQAIANAAAZIAABTQAAAJACADQADAHAQAAIAAAHQgTgCgNAAgApOBmQgNAAgUACIAAgHQAJAAAFgCQAEgDABgFIABgIIAAhVQAAgVgEgIQgIgNgPAAQgQAAgKAOQgFAJAAAVIAABTQAAAIABADQAEAHAOAAIAAAHQgTgCgOAAQgNAAgTACIAAgHQAKAAAEgCQAGgDABgFIAAgJIAAivQAAgKgBgEQgDgFgHgBIgKgBIAAgGQAYgCAWgHIAABcQAOgXAYAAQAYAAAMAVQAIANAAAZIAABTQAAAJACADQAEAHAQAAIAAAHQgUgCgNAAgAJthSIgcgaIgcAaIgJAAIAfgpIAOAAIAeApgABUhSIgdgaIgcAaIgIAAIAfgpIANAAIAfApgAKDhsIgqgsIAZAAIAZAsgAA4iVQgHgGgGAAQgJAAgGAPIgFgCQADgOAFgGQAHgIAIAAQAJAAAIAIQAMAJAGAAQAJAAAFgQIAFABQgCAPgHAHQgFAHgIABIgBAAQgIAAgNgLg");
	this.shape.setTransform(73.6,9.175);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.5,-7.9,176.2,34.2);


(lib.Symbol28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Ai8BoQgUgQgJgjQgHgXAAgeQAAgzAVgjQALgSARgIQAPgIARAAQAcAAATAVIALgVIAGAAIAABGIgHAAQgNg7goAAQgfAAgNAgQgOAeAAAvQAAAsANAdQANAgAfAAQAUABAOgQQAQgQACgkIALAAQgBAbgIASQgJASgQALQgPAJgSAAQgYAAgUgRgAE1B5IAAg7IAHAAQACAPAEAJQAFALAJAGQAIAGALAAQAOAAAJgKQAIgIAAgNQAAgNgKgHQgFgFgRgJIgXgMQgUgMAAgYQAAgWANgMQANgNATAAQARAAAOAMIAFgPIAGAAIAAA2IgHAAQgEgpgcAAQgNAAgIAKQgIAIAAALQAAAKAHAGQAEAFAPAHIAUAKQAOAHAHAIQAKALAAARQAAAVgNAOQgOAQgWAAQgUAAgRgPIgHAQgAC0B5IAAg7IAHAAQACAPAEAJQAFALAJAGQAIAGALAAQAOAAAJgKQAIgIAAgNQAAgNgKgHQgFgFgRgJIgXgMQgUgMAAgYQAAgWANgMQANgNATAAQARAAAOAMIAFgPIAGAAIAAA2IgHAAQgEgpgcAAQgNAAgIAKQgIAIAAALQAAAKAHAGQAEAFAPAHIAUAKQAOAHAHAIQAKALAAARQAAAVgNAOQgOAQgWAAQgUAAgRgPIgHAQgAG8ByQgFgGAAgIQAAgJAFgFQAGgGAHAAQAHAAAFAGQAFAFAAAIQAAAJgFAGQgFAGgHAAQgIAAgFgGgAAvBrQgNgNAAgTQAAggAjgRQATgJAagDIAAgUQAAgSgFgHQgGgKgOAAQgMAAgIAGQgFAGAAAIIAAADIAAAFQAAAOgNABQgKAAAAgLQAAgQAOgNQAPgNAVAAQAPAAAMAHQAOAKAEARQACAIAAAPIAABHQAAARACAHQACAIAIgBIAHgBIAAAJQgKADgHAAQgMAAgGgLQgEgHgBgMQgGANgFAFQgLANgSAAQgTAAgLgNgABQAiQgVANAAAZQAAAQAHAIQAHAJALAAQAUgBAGgUQAEgLAAgUIAAgeQgVAEgNAHgAgQBzIgiACIAAgGQALgBAEgCQAFgDABgFIABgIIAAiwQAAgKgCgEQgCgFgIgBIgKAAIAAgHQAYgCAWgHIAADUQAAAIACAEQADAGAQABIAAAGIghgCgAnZB0IAAgIQANgBAFgCQAGgEABgGIAAgKIAAipQAAgLgBgEQgEgHgUgBIAAgJICEAAIAGA0IgHAAQgGgWgHgJQgHgKgQAAIgsAAIAABgIArAAQAJAAADgDQAFgGABgUIAIAAIAABEIgIAAQAAgQgEgHQgEgGgLgBIgqAAIAABVQAAAKABACQAEAJAPgBIAWAAQARAAAIgHQAKgKAGgcIAHAAIgHA4gAk+AfIAAgQIBOAAIAAAQg");
	this.shape.setTransform(62.775,-7.75);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(15.4,-19.8,94.8,24.200000000000003);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(8,-8,0.17,0.17);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1208));

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AnoGjIAAtFIPRAAIAANFg");
	this.shape.setTransform(25.0647,10.6269,0.8201,0.8188);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1208));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15,-23.7,80.2,68.7);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjQBgIAAh0IgBgVIgBgKIAPAAQABAGAAAKQAKgSARAAQAOAAAKAJQAPAQAAAdQAAAcgNAQQgKAKgPAAQgRAAgLgRIAAA6gAi5gfQgJAMAAAUQAAAUAJALQAHAKALAAQAKAAAGgIQAJgMAAgUQAAgWgKgMQgFgIgLAAQgKAAgHAJgAKdAvQgKgJAAgSIAOAAQACAXAVAAQAJAAAFgFQAGgFAAgJQAAgIgFgEQgFgCgSgGQgPgEgEgGQgHgHAAgLQABgOAJgIQAKgHAOAAQATAAAJANQAFAHABALIgPAAQgBgJgDgEQgFgGgKAAQgIAAgGAFQgFAEAAAHQAAAGAEAEQAFADANAFQAPAEAGADQALAHABAQQAAAOgJAJQgKAJgRAAQgQAAgLgIgAJDAvQgKgJAAgSIANAAQACAXAVAAQAJAAAFgFQAHgFAAgJQAAgIgGgEQgEgCgSgGQgPgEgFgGQgGgHAAgLQAAgOAKgIQAJgHAPAAQATAAAJANQAEAHABALIgOAAQgBgJgDgEQgGgGgJAAQgJAAgGAFQgEAEAAAHQgBAGAFAEQAEADAOAFQAPAEAFADQAMAHAAAQQAAAOgJAJQgJAJgRAAQgRAAgKgIgAHhAxQgKgJABgPQAAgWAXgIQAMgFAYgEIAAgFQAAgKgEgFQgEgGgMAAQgSAAgEARIgOAAQABgNAIgIQAKgJARAAQAQAAAJAHQAHAGABANIABAOIAAAmQAAATACAJIgNAAQgCgGAAgIQgJAQgUAAQgNAAgJgGgAH0AFQgNAHAAAMQgBAIAGAGQAFAFAJAAQAOAAAHgNQAEgHAAgQIAAgKQgVADgKAFgAFAAlQgRgVAAgjQAAgoAVgVQAPgPAVAAQALAAAKAEQAJAEAGAJQAIAKACAQIgPAAQgGgdgZAAQgSAAgLAQQgLARAAAcQAAAeANASQAKANARAAQAUAAAIgRQAEgJABgMIAPAAQgCATgHAMQgMAVgaAAQgZAAgQgSgAADAxQgJgJAAgPQAAgWAWgIQANgFAXgEIAAgFQAAgKgDgFQgFgGgMAAQgSAAgDARIgOAAQACgNAGgIQAKgJASAAQAPAAAKAHQAHAGABANIAAAOIAAAmQABATACAJIgNAAQgCgGgBgIQgJAQgUAAQgNAAgIgGgAAVAFQgNAHAAAMQAAAIAFAGQAFAFAJAAQAOAAAHgNQAEgHAAgQIAAgKQgVADgKAFgAn+AxQgKgJAAgPQAAgWAXgIQANgFAXgEIAAgFQABgKgEgFQgFgGgMAAQgSAAgDARIgPAAQACgNAHgIQAKgJASAAQAPAAAKAHQAGAGACANIABAOIAAAmQgBATADAJIgNAAQgCgGgBgIQgIAQgVAAQgNAAgIgGgAnrAFQgOAHAAAMQAAAIAFAGQAFAFAJAAQAOAAAIgNQADgHAAgQIAAgKQgVADgJAFgAGwA1IAAiTIAOAAIAACTgACWA1IAAiSIBMAAIAAAOIg8AAIAAAyIA3AAIAAAOIg3AAIAAA1IA+AAIAAAPgAgsA1IAAg6QAAgSgDgGQgFgLgMAAQgNAAgIANQgEAIAAAPIAAA5IgPAAIAAiTIAPAAIAAA4QALgPARAAQAKAAAJAFQAIAGADAMIABAYIAAA7gAkvA1IAAg/IgBgNQgCgRgQAAQgOAAgGALQgEAHAAAOIAAA9IgOAAIAAg9QAAgRgCgFQgFgKgMAAQgGAAgGADQgFADgDAGQgDAHAAAOIAAA8IgPAAIAAhHIAAgWIgCgLIAOAAQACAGAAAJQAIgRAUAAQAUAAAHASQAJgSAVAAQATAAAGANQADAGAAAKIABAOIAAA/gAovA1IAAg6QAAgSgDgGQgEgLgNAAQgNAAgHANQgFAIAAAPIAAA5IgOAAIAAiTIAOAAIAAA4QALgPASAAQAKAAAIAFQAJAGADAMIAAAYIAAA7gAqQA1Ig7hMIA4hGIASAAIg4BFIA+BNgArbA1IAAiSIAQAAIAACSgADsADIAAgLIA4AAIAAALgAAWhDIARgYIAPAAIgXAYgAnrhDIARgYIAOAAIgWAYg");
	this.shape.setTransform(37,-1.975);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0066CC").s().p("As4C1IAAlpIZxAAIAAFpg");
	this.shape_1.setTransform(37.3673,-2.5298,1.1009,0.9862);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-53.4,-20.4,181.6,35.8);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AEnB+IgcABIAAgFQAJgBAEgBQAEgCABgEIAAgHIAAiPQAAgLgEgEQgDgBgLgBIAAgEQASgCAQgEQABAIABAQQAMgYAVAAQAVAAAOAUQANAUAAAdQAAAdgNATQgNAUgVAAQgNAAgJgJQgEgEgFgJIAAA3QAAAGABADQADAFAOABIAAAFIgdgBgAE8gtQgLANABAkQAAA+AdAAQAcAAAAg7QAAg+gdAAQgKAAgIAKgAmLA9QgRgNgHgbQgHgTAAgWQABgqARgdQAKgOAPgGQAMgHAOAAQAYABAPAQIAJgQIAFAAIAAA3IgGAAQgKgvgiAAQgaAAgLAaQgLAYAAAmQAAAjAKAWQALAaAaAAQARAAALgLQAOgOACgdIAKAAQgBAWgIAPQgHAOgNAJQgNAHgPAAQgUAAgRgOgAJxAxQgFAKgEAFQgLAKgOAAQgVAAgKgQQgGgKgBgVIAAg/QABgIgCgDQgCgEgGgBIgJgBIAAgEQAUgCATgFIAABcQAAAQAEAIQAGAJANAAQAPAAAGgMQAFgHAAgSIAAg8QAAgIgBgDQgCgEgHgBIgIgBIAAgEQAUgCASgFIAABxQABAGABADQACADAHABIAIAAIAAAFQgUACgPAFQgBgIgBgRgAKvBGQgDgFAAgHQAAgGADgFQAFgFAGAAQAGAAAEAFQAEAFAAAGQAAAHgEAFQgEAEgGAAQgHAAgEgEgAohAxQgFALgFAEQgKAJgPAAQgVAAgKgPQgGgLAAgUIAAg/QgBgHgBgEQgCgFgOgBIAAgEQATgCATgGIAABdQAAAQAEAIQAGAJANAAQAOAAAHgMQAFgHAAgSIAAg8QAAgIgCgDQgCgFgOgBIAAgEQATgCAUgGIAAAKQAHgLAAgHIgDAAQgJgDACgLQACgKAJAAQANAAgBAOQAAANgLAPIgFAEIgEAFIAABfQgBAGACADQACADAHAAIAIABIAAAFQgUACgPAFIgBgZgAq0A6QgCgGgBgKIAAgOIAAhNIgQAAIAAgJQAHgBAFgCQAOgIAFgeIAGAAIAAAnIAeAAIAAALIgeAAIAABQQAAARACAGQAEAJAJAAQAGAAAKgGIAAAIQgMAJgMAAQgSAAgHgQgAHyBGQgLAAgQACIAAgFQAHgBAEgCQAEgCABgEIAAgGIAAhEQAAgQgEgHQgFgLgOABQgNgBgIAMQgFAIAAAPIAABDQAAAHABACQAEAGALAAIAAAFQgQgCgLAAQgLAAgQACIAAgFQAJgBADgCQAFgBAAgFIAAgGIAAiNQAAgHgBgEQgCgEgGgBIgIAAIAAgFQATgCATgGIAABKQAMgSAVgBQAUAAAKASQAHAKgBAUIAABDQABAGABADQADAFAOABIAAAFQgRgCgLAAgAClBGQgMAAgQACIAAgFQAIgBADgCQAEgCACgEIAAgGIAAhEQAAgQgEgHQgGgLgNABQgOgBgHAMQgGAIAAAPIAABDQABAHABACQADAGAMAAIAAAFQgQgCgMAAQgKAAgRACIAAgFQAJgBAEgCQAEgBABgFIAAgGIAAiNQAAgHgBgEQgCgEgHgBIgIAAIAAgFQAUgCASgGIAABKQANgSAUgBQAVAAAKASQAGAKAAAUIAABDQAAAGABADQADAFAOABIAAAFQgQgCgLAAgAAcBGQgMAAgQACIAAgFQAIgBAEgCQADgCABgEIAAgGIAAhEQAAgQgDgHQgGgLgMABQgOgBgHAMQgGAIAAAPIAABDQABAHABACQADAGAMAAIAAAFQgQgCgLAAQgMAAgQACIAAgFQAJgBAEgCQAEgBABgFIAAgGIAAhWIAAgKQgBgGgGgBIgLgBIAAgEQAWgDAMgFIADAYQANgXAUAAQAVAAAKASQAGAKAAAUIAABDQAAAGACADQADAFAOABIAAAFQgSgCgKAAgAhxBGIgcACIAAgFQAJgBAEgCQAEgBABgFIABgGIAAhYQgBgIgBgDQgDgEgFgBIgIgBIAAgEQAUgCARgFIAAB0QABAGABADQAEAFANABIAAAFIgdgCgAi2BGQgMAAgQACIAAgFQAIgBAEgCQAEgCABgEIAAgGIAAhEQAAgQgDgHQgGgLgNABQgOgBgIAMQgFAIAAAPIAABDQAAAHACACQADAGALAAIAAAFQgPgCgMAAQgLAAgRACIAAgFQAJgBAFgCQADgBABgFIAAgGIAAiNQAAgHgBgEQgCgEgHgBIgIAAIAAgFQAVgCASgGIAABKQANgSATgBQAVAAALASQAFAKAAAUIAABDQAAAGACADQADAFAOABIAAAFQgRgCgLAAgAJQhOQABgGACgDQACgFAFgFQAFgGAAgGQAAgKgJAAQgMAAgBAOIgFAAQAAgOAKgFQAFgCAFgBQAIABAFADQAGAFAAAJQABAHgGAFIgGAFIgGAFQgDAFgBAEgAh/hSIAWgjIAUAAIgjAjgAoyhSIgjgjIAVAAIAVAjg");
	this.shape.setTransform(71.2,12.75);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,142.4,25.5);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ABfCHIgYABIAAgFQAHgBADgBQAEgCABgFIABgGIAAiPQAAgMgFgDQgCgCgJAAIAAgFQAQgCAMgDIADAYQAKgYASAAQASAAAMAUQAMATgBAdQAAAegLATQgLAUgSAAQgMAAgHgJQgEgEgEgJIAAA3IABAJQADAFALABIAAAFIgYgBgABxgkQgKANABAjQAAA/AZAAQAYAAAAg8QAAg9gaAAQgHAAgHAKgAQ+CDQgEgEAAgGQAAgFAEgDQACgEAEAAQAFAAACAEQADADABAFQgBAGgDAEQgCADgFAAQgEAAgCgDgAgtCDQgDgEAAgGQAAgFADgDQADgEAEAAQAEAAADAEQACADABAFQgBAGgCAEQgDADgEAAQgEAAgDgDgAqlCDQgEgEAAgGQAAgFAEgDQADgEADAAQAFAAACAEQADADABAFQgBAGgDAEQgCADgFAAQgDAAgDgDgAO5BTIAAijQgBgIgBgDQgCgEgFgBIgHAAIAAgFQASgCAPgGIAABNQAEgJAEgEQAHgIAMAAQARAAAMATQALAUAAAcQAAAegMAUQgMATgRAAQgUAAgJgZIgJAZgAPXgpQgGAFgCAJQgGARABAaQgBAZAFAPQADAJAGAGQAFAEAGAAQAJAAAHgKQAJgPAAgkQAAg8gZAAQgGAAgFAFgAMmBAQgMgSAAgfQAAgfANgUQAMgSASAAQANAAAKAMIAFgPIAFAAIAAAuIgGAAQgCgMgDgIQgDgHgFgEQgGgFgGAAQgOAAgGATQgGARAAAaQAAA7AZAAQAVAAAEglIAJAAQgCAPgFALQgJAUgTAAQgUAAgLgTgAK9A9QgKgSAAgdQAAgbAKgTQAMgWAWAAQAOAAAJAKQAGgJABgJIgBAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAAAQgJgDABgLQADgJAHAAQALAAgBAOQABAMgLAPIgBACIgCADQAOAUAAAhQAAAbgLAUQgLAWgVAAQgVAAgLgWgALPglQgKAPAAAkQAAA+AYAAQAZAAgBg9QABg+gZAAQgJAAgFAKgAq+A9QgLgSABgdQgBgbALgTQAMgWAVAAQAOAAAJAKQAHgJAAgJIAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQgIgDABgLQACgJAIAAQAKAAAAAOQAAAMgKAPIgBACIgCADQAOAUgBAhQAAAbgKAUQgLAWgWAAQgUAAgLgWgAqtglQgJAPAAAkQAAA+AXAAQAZAAAAg9QAAg+gZAAQgIAAgGAKgAvxA/QgMgUABgdQAAgdAMgUQAMgTATAAQATAAAMAUQALAUAAAcQAAAdgLAUQgMAUgUAAQgUAAgLgUgAvgglQgKAPAAAkQAAA+AYAAQAKAAAGgLQAIgPAAgjQAAg+gYAAQgIAAgGAKgAQnBJQgIgKgBgQQAAgZAagOQANgHATgCIAAgRQgBgOgDgGQgFgIgJAAQgJAAgGAGQgDAEAAAGIAAADIAAAEQgBAMgIAAQgIAAABgJQAAgNAJgKQALgLAQAAQAKAAAJAGQAKAIADAOIABATIAAA4QAAANACAGQABAGAFAAIAGgBIAAAHQgHACgFAAQgJAAgFgIQgCgGgBgKQgEAKgEAFQgIAKgNAAQgNAAgJgKgAQ/APQgPAJAAAVQAAAMAGAHQAEAHAIAAQAOAAAFgRQACgIABgRIAAgYQgQADgJAHgAKFA6QgEAKgFAFQgIAJgNAAQgRAAgKgPQgFgLAAgUIAAg/QAAgIgBgDQgCgGgNAAIAAgEQARgDARgFIAABdQgBAQAEAHQAFAKALAAQANAAAFgMQAEgIAAgRIAAg8IgBgLQgCgGgMAAIAAgEQARgCAQgGIAAAJQAHgKAAgIIgCAAQgJgCACgLQACgKAHAAQALAAAAAOQAAANgKAOIgEAFIgEAFIAABeQAAAHACADQABADAGAAIAHABIAAAFQgRACgNAFIgBgZgAG0BDQgCgGgBgKIAAgOIAAhOIgNAAIAAgIQAFgBAFgCQAMgIAEgfIAFAAIAAAoIAaAAIAAAKIgaAAIAABRQABARABAGQADAJAIAAQAGAAAIgGIAAAIQgLAJgJAAQgRAAgFgQgAhEBBQgLgUgBgfQABgeALgTQAMgTAUAAQAOAAALAMQANAQAAAlIhAAAIAAAGQAAAXAHARQAGARAQAAQAQAAAIgSQADgIABgLIAHAAQgBAQgGAMQgKASgUAAQgVAAgMgSgAg9ABIAvAAQgCgvgUAAQgWAAgDAvgAmqA6QgMgbAAgoQAAgtANgaQALgYAWAAQAOAAAKALQAMALAFAaQAFAVgBAZQABAmgLAbQgLAcgZAAQgWAAgLgZgAmYhUQgMATAAA4QABAmAGAYQAEAKAFAGQAFAGAHAAQAbAAAAhVQAAgpgHgXQgHgWgOAAQgIAAgHAMgAofA/QgFgKgBgRIAHAAQABAMADAGQAIAOAPAAQAPAAAJgQQAHgOAAgVQAAgVgHgNQgIgNgOAAQgRAAgKAVIgHgBIANhbIA/AAIgDATIg4AAIgHA2QAMgPASAAQATAAALAQQAMARAAAbQAAAagLATQgNAVgXAAQgVAAgKgUgAtRBDQgCgGgBgKIAAgOIAAhOIgNAAIAAgIQAGgBAEgCQAMgIAEgfIAFAAIAAAoIAZAAIAAAKIgZAAIAABRQAAARACAGQADAJAIAAQAGAAAIgGIAAAIQgKAJgLAAQgPAAgGgQgAkEBEQgGgMgBgTQABgTAHgNQAJgMANAAQANAAAHAMQAIANAAATQAAATgIANQgHANgOAAQgNAAgJgOgAj7ALQgCAKAAAQQAAAmAPAAQAPAAAAgmQAAglgPAAQgJAAgEALgAIABPQgJAAgPACIAAgGQAHAAAEgCQADgBABgFIAAgHIAAhWIAAgKQgBgGgFgBIgJgBIAAgFQARgCAMgEIACAaQACgIAEgGQAJgLALAAQAIAAAGAHQAFAGAAAJQAAAGgDAEQgDAEgDAAQgEAAgDgDQgCgCAAgEIAAgGIABgDQAAgDgCgCQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAQgKAAgGARQgDALAAARIAAA6QAAAHABADQADAFAMAAIAAAGQgPgCgKAAgAFJBPIgYACIAAgGQAHAAADgCQAEgBABgFIAAgHIAAhXIgBgLQgCgEgFgBIgHgBIAAgEQARgCAQgGIAAB0QAAAHABADQACAFAMAAIAAAGIgYgCgAEOBPQgLAAgOACIAAgFQAHgBADgCQAEgCABgEIAAgGIAAhEQAAgQgDgHQgFgLgLAAQgMAAgGAMQgFAHAAAQIAABDIABAJQADAFAKABIAAAFQgOgCgKAAQgJAAgOACIAAgGQAIAAADgCQAEgBAAgFIAAgHIAAiMQAAgIgBgDQgBgEgHgBIgGAAIAAgFQARgCAQgGIAABKQALgTAQAAQATAAAIASQAGAKAAAUIAABCQgBAHACADQADAFAMAAIAAAGQgPgCgJAAgAh1BPIgZACIAAgGQAIAAADgCQAEgBABgFIAAgHIAAiMQAAgIgBgDQgCgEgGgBIgGAAIAAgFQARgCAQgGIAACpIABAKQADAFAMAAIAAAGIgZgCgAsFBPQgKAAgPACIAAgGQAIAAAEgCQADgBABgFIAAgHIAAhWIAAgKQgBgGgGgBIgJgBIAAgFQASgCAMgEIACAaQACgIAEgGQAIgLALAAQAJAAAFAHQAFAGAAAJQAAAGgCAEQgDAEgEAAQgEAAgDgDQgCgCAAgEIABgGIAAgDQAAgDgCgCQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAQgKAAgFARQgDALgBARIAAA6QABAHABADQADAFAMAAIAAAGQgQgCgJAAgAwiBPQgJAAgOACIAAgFQAGgBAEgCQADgCABgEIAAgGIAAhEQAAgQgDgHQgFgLgMAAQgLAAgHAMQgEAHAAAQIAABDIABAJQADAFAKABIAAAFQgOgCgJAAQgKAAgPACIAAgGQAJAAACgCQAFgBAAgFIABgHIAAiMQgBgIgBgDQgCgEgFgBIgHAAIAAgFQARgCAQgGIAABKQALgTARAAQARAAAKASQAEAKAAAUIAABCQAAAHACADQACAFAMAAIAAAGQgOgCgKAAgAk8BQIBVi5IAJAAIhVC5gAlBgfQgHgMAAgTQAAgUAIgMQAJgNANAAQAMAAAIANQAIANAAATQAAASgIANQgIANgNAAQgNAAgJgNgAk4hYQgDAKAAAQQAAAmAQAAQAPAAAAgmQAAgmgPAAQgJAAgEAMgAgRhEIgUgVIgVAVIgGAAIAWghIAKAAIAXAhgAu+hEIgVgVIgUAVIgGAAIAWghIAKAAIAWAhgAE9hJIASgjIASAAIgeAjgALThKIASgjIASAAIgfAjgAvSh3QgFgFgEAAQgHAAgEANIgDgCQACgLADgFQAFgGAGAAQAGAAAHAGQAIAHAFAAQAGAAADgNIAEABQgCAMgEAGQgEAFgGABIAAAAQgGAAgKgJg");
	this.shape.setTransform(114.35,13.625);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,228.7,27.3);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Au5BnIAAg9IAGAAQAHAyAlAAQARAAAKgLQAJgKAAgPQAAgRgLgKIgZgPQgdgPgHgIQgLgLAAgUQgBgXAOgNQANgNAWAAQATAAAOAOIAIgQIAEAAIAAA0IgFAAQgDgPgGgJQgKgSgTAAQgPAAgIALQgJAKAAANQAAAQAOAKIAZAPQAVAKAIAHQAPANAAAYQAAAYgOAPQgOAOgXAAQgWAAgRgQIgKASgALBBmIgKgdIgehYQgDgJgEgCQgEgBgIgBIAAgFIAbABIAagBIAAAFIgHABQgGABAAAFIACAGIAbBUIAbhTIACgIQAAgEgEgBIgIgBIAAgFIATABIATgBIAAAFQgIABgDACQgFACgCAJIgeBWIgKAegAHoBmIAAgvIAFAAQACAMAEAIQAEAIAHAFQAIAFAJAAQALAAAIgIQAHgHAAgKQAAgLgIgGIgTgKIgTgKQgRgKAAgUQgBgQALgKQALgKARAAQAOAAAMAJIAFgMIADAAIAAArIgFAAQgDgggYAAQgLAAgHAIQgGAGAAAJQAAAHAFAGQAEADAMAGIARAIQANAGAFAHQAIAIAAAOQAAARgKALQgMAMgTAAQgQAAgOgLIgHAMgAF8BmIAAgvIAFAAQACAMAEAIQAEAIAHAFQAIAFAIAAQAMAAAIgIQAHgHAAgKQAAgLgIgGIgTgKIgTgKQgRgKAAgUQgBgQALgKQALgKARAAQAOAAAMAJIAFgMIADAAIAAArIgFAAQgDgggYAAQgLAAgHAIQgGAGAAAJQAAAHAFAGQAEADAMAGIARAIQANAGAFAHQAIAIAAAOQAAARgKALQgMAMgTAAQgQAAgOgLIgHAMgABFBZQgRgOgIgbQgFgTAAgXQgBgpATgcQAJgOAOgHQAMgGAPAAQAYAAAQAQIAJgQIAEAAIAAA3IgFAAQgLgugiAAQgaAAgLAZQgMAYAAAlQAAAkALAXQAMAaAaAAQAQAAAMgMQAOgOABgcIAKAAQgCAVgGAPQgIAPgOAIQgMAHgPAAQgVAAgQgNgAMYBQQgMgTAAgcQAAgdANgSQAOgWAZAAQAPAAAMALQAHgKAAgIIAAgBQgBAAAAABQAAAAgBAAQAAAAAAAAQAAgBgBAAQgKgCADgLQACgKAJAAQANAAgBAOQAAANgMAOIgCADIgCACQAQAUAAAhQAAAcgMATQgNAXgYAAQgZAAgNgWgAMtgTQgLAPAAAlQAAA+AcAAQAcAAAAg+QAAg9gcAAQgLAAgGAJgAkcBMQgFAKgFAGQgKAJgOAAQgVAAgKgQQgHgKAAgUIAAhAQAAgIgBgDQgCgEgHgBIgIAAIAAgFQAUgCASgFIAABcQAAARAFAHQAGAJANAAQAOAAAHgMQAFgHAAgSIAAg8QAAgIgCgDQgCgEgHgBIgHAAIAAgFQATgCATgFIAABxQAAAHABACQACADAHABIAJAAIAAAFQgVACgOAGQgCgIAAgSgAsuBQQgLgTAAgcQAAgdAMgSQAOgWAZAAQAQAAALALQAHgKAAgIIAAgBQAAAAgBABQAAAAAAAAQgBAAAAAAQAAgBAAAAQgKgCACgLQADgKAIAAQANAAAAAOQAAANgNAOIgCADIgBACQAQAUAAAhQAAAcgNATQgNAXgYAAQgYAAgOgWgAsZgTQgLAPAAAlQAAA+AcAAQAcAAAAg+QAAg9gcAAQgKAAgHAJgAELBcQgKgLAAgQQAAgZAdgNQARgIAVgDIAAgQQAAgNgEgGQgFgJgMAAQgKAAgHAGQgEAEAAAHIAAACIAAAEQAAAMgKAAQgJAAAAgJQAAgMALgKQANgLASAAQAMAAALAGQALAHAEAOQACAHAAALIAAA5QgBAOACAFQACAGAGAAIAHgBIAAAIQgJACgFAAQgMAAgEgJQgDgFgBgKQgFAKgFAFQgJAJgPAAQgPAAgLgJgAEnAhQgRAKAAAVQAAAMAGAHQAGAGAJAAQAQAAAGgQQADgJAAgQIAAgYQgRADgMAGgAmlBMQgGALgFAFQgJAJgPAAQgUAAgLgQQgHgKABgVIAAg/QAAgHgCgEQgCgFgOAAIAAgFQATgCATgGIAABdQAAARAEAHQAFAJAOAAQAOAAAHgMQAFgHAAgSIAAg8QAAgIgCgDQgCgFgOAAIAAgFQATgCAUgGIAAAKQAHgKAAgIIgDAAQgJgDACgLQACgJAJAAQAMAAAAANQAAANgLAPIgFAFIgEAFIAABeQAAAGABADQACADAHABIAJAAIAAAFQgVACgPAFIgBgZgAOdBiIgcACIAAgGQAJAAAEgCQAEgCABgFIAAgGIAAhYQABgIgCgDQgDgEgGgBIgIAAIAAgFQAVgCARgFIAAB0QAAAHACACQADAFAOABIAAAGIgdgCgADVBiIgcACIAAgGQAJAAAEgCQAEgCABgFIAAgGIAAiMQABgIgCgEQgDgEgGAAIgIgBIAAgFQAVgCARgFIAACpQAAAHACACQADAFAOABIAAAGIgdgCgAolBiQgLAAgQACIAAgGQAHAAAFgCQADgCABgFIAAgGIAAhEQABgQgEgHQgGgKgNAAQgNAAgJALQgEAIAAAPIAABDQgBAHACACQADAGAMAAIAAAGQgQgCgLAAQgMAAgQACIAAgGQAJAAAEgCQAEgCABgFIAAgGIAAiMQAAgIgCgEQgCgEgGAAIgIgBIAAgFQAUgCATgFIAABKQAMgTAUAAQAVAAAKARQAGALAAATIAABDQAAAHACACQADAFAOABIAAAGQgSgCgLAAgAipBjIAAgHQALgBAEgCQAFgCABgGIAAgIIAAiGQAAgJgBgDQgEgGgQgBIAAgHIBvAAIAEAqIgFAAQgFgTgFgHQgHgHgOAAIglAAIAABMIAlAAQAHAAACgCQAGgFAAgQIAHAAIAAA2IgHAAQAAgMgDgGQgEgFgKAAIgjAAIAABEQAAAHACACQACAHANAAIASAAQAQAAAGgGQAJgJAEgVIAGAAIgGAtgAgnAeIAAgNIBAAAIAAANgAsNg1IABgJIAIgLQAFgGAAgGQAAgKgKAAQgMAAAAAOIgFAAQAAgNAJgGQAFgCAGAAQAIAAAEADQAHAFAAAJQAAAHgFAGIgGAEIgGAGQgDAEgCAFgAMxg4IAWgjIAUAAIgjAjgAOTg9QgEgEAAgHQAAgGAEgEQAEgFAGAAQAFAAAEAFQAFAEAAAGQAAAHgFAEQgEAFgFAAQgGAAgEgFgAnFhHQgFgEgFAAQgJAAgEAMIgFgBQADgMAFgFQAFgGAHAAQAHAAAIAGQAKAIAFAAQAHgBAEgMIAEABQgCALgFAGQgEAGgHAAIgBAAQgHAAgLgJg");
	this.shape.setTransform(95.4,10.275);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,190.8,20.6);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg2();
	this.instance.parent = this;
	this.instance.setTransform(-1,-6,0.6489,0.6489);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-6,301.8,610);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg1();
	this.instance.parent = this;
	this.instance.setTransform(0,-5,0.5016,0.5016);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-5,301,612);


(lib.Symbol31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.instance = new lib.Symbol33("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(150.4,39.5,1,1,0,0,0,124.4,10.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:123.1,alpha:1},11,cjs.Ease.get(1)).to({x:124.4},11,cjs.Ease.get(1)).wait(1633));

	// Layer_1
	this.instance_1 = new lib.Symbol32("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(98.9,11.45,1,1,0,0,0,108.6,11.2);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:126.2,alpha:1},11,cjs.Ease.get(1)).to({x:124.9},11,cjs.Ease.get(1)).wait(1633));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.1,-9.7,285.20000000000005,61.3);


(lib.Symbol27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.instance = new lib.Symbol28("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(73,34.75,0.4,0.4,0,0,0,62.2,8.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:8.3,scaleX:1.05,scaleY:1.05,x:72.95,y:7.15,alpha:1},9,cjs.Ease.get(1)).to({regY:8.2,scaleX:1,scaleY:1,x:73,y:8.7},9,cjs.Ease.get(1)).wait(1350));

	// Layer_1
	this.instance_1 = new lib.Symbol29("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(73.5,50.55,0.4,0.4,0,0,0,73.5,8.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(5).to({_off:false},0).to({regX:73.4,regY:8.6,scaleX:1.05,scaleY:1.05,y:35.1,alpha:1},9,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,y:36.5},9,cjs.Ease.get(1)).wait(1345));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18.7,-22.4,185,80);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Au7C7IAAl1Id3AAIAAF1g");
	mask.setTransform(38.175,4.05);

	// Layer_2
	this.instance = new lib.Tween3("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-84.65,4.45,1.3691,1.8299,0,0,0,-0.2,0.1);

	this.instance_1 = new lib.Tween4("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(159.25,11.85,1.5945,2.1152);

	var maskedShapeInstanceList = [this.instance,this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},23).wait(67));
	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true,regX:0,regY:0,scaleX:1.5945,scaleY:2.1152,x:159.25,y:11.85},23,cjs.Ease.get(1)).wait(67));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57.4,-14.7,191.20000000000002,37.5);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(43.35,7.65,0.4,0.4,0,0,0,43.4,7.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:7.6,scaleX:1.1,scaleY:1.1,x:43.4,y:7.6,alpha:1},11,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(1944));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.1,-23.1,199.79999999999998,39.3);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.instance = new lib.Symbol6("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(149.65,188.25,1,1,0,0,0,71.2,12.8);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({y:162.35,alpha:1},9,cjs.Ease.get(1)).to({y:163.75},8,cjs.Ease.get(1)).wait(948));

	// Layer_2
	this.instance_1 = new lib.Symbol5("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(149.25,152.7,1,1,0,0,0,114.4,13.6);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(6).to({_off:false},0).to({y:126.8,alpha:1},9,cjs.Ease.get(1)).to({y:128.2},8,cjs.Ease.get(1)).to({_off:true},952).wait(2));

	// Layer_1
	this.instance_2 = new lib.Symbol4("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(150.45,115.55,1,1,0,0,0,95.4,10.2);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:89.65,alpha:1},9,cjs.Ease.get(1)).to({y:91.05},8,cjs.Ease.get(1)).to({_off:true},956).wait(4));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(34.9,79.5,228.70000000000002,121.5);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_241 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(241).call(this.frame_241).wait(1));

	// logo
	this.instance = new lib.Symbol13("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(140.5,573.5,1,1,0,0,0,15.5,15.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1,startPosition:14},13,cjs.Ease.get(1)).wait(229));

	// Layer_12
	this.instance_1 = new lib.Symbol18();
	this.instance_1.parent = this;
	this.instance_1.setTransform(154.4,471.1,1,1,0,0,0,42.4,10.1);
	this.instance_1.alpha = 0.7695;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(240).to({_off:false},0).wait(2));

	// cta
	this.instance_2 = new lib.Symbol11("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(156.55,476.1,1.05,1.05,0,0,0,43.4,7.7);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(205).to({_off:false},0).wait(37));

	// Layer_6
	this.instance_3 = new lib.Symbol31("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(148.4,117.1,1,1,0,0,0,124.4,25.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(182).to({_off:false},0).wait(60));

	// Layer_5
	this.instance_4 = new lib.Symbol30("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(150.55,298.95,1.2,1.2,0,0,0,152.5,300.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(165).to({_off:false},0).to({scaleX:1,scaleY:1,x:150.5,y:298.9,alpha:1},16,cjs.Ease.get(1)).wait(61));

	// Layer_10
	this.instance_5 = new lib.Symbol3("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(58.4,21.6,1,1,0,0,0,58.4,21.6);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(91).to({_off:false},0).to({_off:true},93).wait(58));

	// Layer_7
	this.instance_6 = new lib.Symbol2("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(248,501,1.2,1.2,0,0,0,232.5,470);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(74).to({_off:false},0).to({scaleX:1,scaleY:1,x:232.5,y:470,alpha:1},16,cjs.Ease.get(1)).to({_off:true},94).wait(58));

	// Layer_3
	this.instance_7 = new lib.Symbol27("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(149,139.2,1,1,0,0,0,72,22.2);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(14).to({_off:false},0).to({_off:true},156).wait(72));

	// Layer_8
	this.instance_8 = new lib.Symbol1("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(150,299.85,1.2,1.2,0,0,0,150,299.9);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({regY:300,scaleX:1,scaleY:1,y:300,alpha:1},13,cjs.Ease.get(1)).to({_off:true},157).wait(72));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-39.6,-84.9,375.1,763.1999999999999);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.parent = this;
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(120.1,234.1,211.20000000000002,434.29999999999995);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg1.jpg?1701237037952", id:"bg1"},
		{src:"images/bg2.jpg?1701237037952", id:"bg2"},
		{src:"images/bg3.jpg?1701237037952", id:"bg3"},
		{src:"images/logo.png?1701237037952", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;