(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bg1 = function() {
	this.initialize(img.bg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,900,1800);


(lib.bg2 = function() {
	this.initialize(img.bg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,305,605);


(lib.bg3 = function() {
	this.initialize(img.bg3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,900,1779);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,200,200);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg3();
	this.instance.setTransform(-1,1,0.34,0.34);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,1,306,604.8);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AO9BgQgRgPgIgfQgGgXAAgaQAAgwASggQAJgQAPgIQAMgHAPAAQAYAAARATIAJgSIAEAAIAAA/IgFAAQgLg2gjAAQgaAAgLAdQgMAcAAArQAAApALAaQAMAeAaAAQAQAAANgNQAOgQABghIAKAAQgBAZgHARQgIARgOAJQgMAIgQAAQgVAAgQgPgAiGBvIAAg1IAGAAQACANAEAJQAEAJAHAGQAIAGAJAAQAMAAAIgJQAHgJAAgLQAAgMgJgHQgEgEgPgIIgTgMQgSgLAAgVQAAgUALgLQALgMARAAQAOAAANAKIAEgNIAEAAIAAAxIgFAAQgEglgYAAQgLAAgHAJQgGAHAAAKQAAAKAFAFQAEAEANAHIARAJQAMAHAGAHQAIAKAAAQQAAATgLANQgLAOgUAAQgRAAgOgNIgGAOgAl2BZQgOgWAAgjQAAggANgXQAOgWAUAAQAOAAAIAJQAEAFAFALIAAg5QAAgJgBgEQgCgEgHgBIgIgBIAAgFQAVgCASgHIAAC5IABANQABAGAFABIAMACIAAAFQgWADgMAGIgEgaQgLAagVAAQgVAAgNgWgAluAgQAAAdAGATQADAKAGAGQAGAGAIAAQAKAAAHgKQAKgPAAgqQAAhHgdAAQgbAAAABEgAKVBgQgSgQgIgeQgFgXAAgbQAAgxASgeQATgfAgAAQAYAAASATIAKgTIAFAAIAABAIgGAAQgEgTgGgKQgGgMgJgHQgLgGgMAAQgTAAgMAQQgSAYAAA8QAABmAxAAQAQAAATgNIAAg2QAAgHgBgCQgDgGgQgBIAAgIQASACALAAQAMAAASgCIAAAIQgLABgEACQgDACAAAFIgBAGIAAA1QgeAXgcAAQgVAAgRgPgApdBZQgOgVAAgkQAAgkAPgWQAPgVAWAAQAPAAALANIAHgQIAEAAIAAA0IgFAAQgDgOgDgIQgEgJgGgFQgHgFgHAAQgQAAgIAVQgHATAAAfQAABEAeAAQAYAAAFgqIAKAAQgCASgFALQgLAYgXAAQgXAAgOgWgADJBZQgPgWAAgkQAAgiAPgWQANgVAXAAQASAAAMANQARATAAAqIhNAAIAAAGQAAAcAIATQAIATATAAQASAAAJgUQAEgJABgNIAKAAQgBASgIANQgMAVgYAAQgZAAgNgVgADQAQIA4AAQgCg2gZAAQgZAAgEA2gAjxBZQgOgWAAgkQAAgiAOgWQAOgVAWAAQASAAANANQAQATABAqIhNAAIAAAGQAAAcAHATQAIATATAAQATAAAJgUQADgJACgNIAKAAQgCASgHANQgNAVgYAAQgZAAgNgVgAjqAQIA4AAQgCg2gZAAQgZAAgEA2gAnsBZQgPgWAAgkQAAgiAPgWQAOgVAWAAQASAAAMANQARATAAAqIhMAAIAAAGQAAAcAHATQAIATATAAQASAAAJgUQAEgJABgNIAKAAQgBASgIANQgMAVgYAAQgZAAgNgVgAnlAQIA4AAQgCg2gZAAQgZAAgEA2gAs2BZQgOgWAAgkQAAgiAOgWQAOgVAXAAQARAAANANQAQATABAqIhNAAIAAAGQAAAcAHATQAIATATAAQATAAAJgUQADgJACgNIAKAAQgCASgHANQgNAVgYAAQgZAAgNgVgAsvAQIA4AAQgCg2gYAAQgaAAgEA2gAGSBqQgLAAgQACIAAgGQAHAAAEgDQAEgCABgFIABgHIAAhPQAAgSgEgIQgGgMgNAAQgOAAgIANQgFAJAAARIAABOQAAAHABADQADAGANABIAAAGQgRgCgLAAQgLAAgSACIAAgGQAJgBAEgCQAFgCABgFIAAgHIAAhjIAAgLQgBgHgHgBIgKgBIAAgFQAVgEANgGIADAcQANgZAWAAQAUAAALATQAGAMAAAWIAABOQAAAIACADQADAFAOABIAAAGQgRgCgMAAgAqzBqQgLAAgSACIAAgGQAJgBAEgCQAEgCABgFIAAgHIAAhjIAAgMQgBgHgHgCIgKAAIAAgGQAUgCAOgFIADAeQADgKAFgHQAJgMANAAQALAAAGAIQAFAHAAALQAAAGgCAEQgDAFgFAAQgFAAgDgDQgDgDAAgEIABgHIAAgDQAAgDgCgDQgCgCgDAAQgMAAgHAUQgEAMAAATIAABEQAAAHACAEQADAFAOABIAAAGQgSgCgLAAgAt3BqQgMAAgUACIAAgIQAJAAAGgDQAFgCABgHIAAgHIgCioIgrCPIgGAXIgHAWIgEAAIg3i8IgGCmIAAADQAAAHACADQADAHARABIAAAIIgagBIgaABIAAgIQALgBAEgCQAFgCABgHIABgJIAFidIAAgBQAAgJgBgDQgEgHgQgBIAAgIIAVABIAZgBIAwChIAwihIAaABIAUgBIAAAIQgLABgEACQgHADAAAMIAAADIADCdQAAAKACADQADAHAQABIAAAIQgUgCgMAAgAMVBrIAAgIQALAAAEgDQAFgCABgHIAAgJIAAicQAAgKgBgDQgDgFgIgCIgJgBIAAgIQAUACAMAAQANAAAUgCIAAAIQgLABgEACQgFADgBAGIAAAJIAACcQAAAIABADQACAHAOAAIASAAQAMAAAGgDQAFgEAEgJQAFgKADgOIAGAAIgGAzgAG9BrIBGiOIgcAAQgJAAgFADQgHAEgFANIgEANIgGAAIAGgpIBWAAIhGCOIAeAAQAMAAAFgFQAKgIAGgZIAFAAIgHAugAAlBrIAAgIQALAAAEgDQAFgCABgHIAAgJIAAibQAAgKgBgDQgEgHgQgBIAAgIIBEAAQANAAAIADQAIACAHAHQAPAOAAAbQAAAigcANQAKADAHAEQAIAGAFALQAGAMAAAQQAAAWgLAQQgKARgTAEQgIACgOAAgABQBRQAAAKADADQADADAKAAIAJAAQAQAAAJgKQALgNAAgaQAAgZgJgMQgIgLgUAAIgYAAgABQgJIARAAQANAAAHgDQAQgKAAgfQAAgWgHgLQgHgKgRAAIgWAAgAglAcIAAgOIBCAAIAAAOg");
	this.shape.setTransform(115.075,-351.125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(9.9,-362.2,210.4,22.19999999999999);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg2();
	this.instance.setTransform(4,21);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4,21,305,605);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.logo();
	this.instance.setTransform(-112,0,0.165,0.165);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(282).to({_off:true},1).wait(925));

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AmSFOIAAqbIMlAAIAAKbg");
	this.shape.setTransform(-95.55,16.45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(282).to({_off:true},1).wait(925));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-135.8,-16.9,80.60000000000001,66.8);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiSBWIAAhnIAAgUIgCgIIAOAAIABANQAKgQARAAQANAAAJAIQAPAPAAAaQAAAYgNAOQgJAKgOAAQgRAAgKgPIAAA0gAh8gbQgJAKAAASQAAARAIALQAHAIALAAQAKAAAGgHQAIgLAAgSQAAgSgKgMQgEgGgKAAQgLgBgGAJgAIXAsQgKgIAAgOQAAgTAWgHQAMgFAXgEIAAgDQAAgLgDgDQgFgGgLAAQgSAAgDAPIgOAAQABgLAIgIQAJgIARAAQAPAAAJAHQAGAFACAMIAAAMIAAAiQAAASADAHIgNAAQgCgFgBgHQgIAOgTAAQgMAAgIgFgAIoAEQgNAGAAAMQAAAGAGAGQAEAEAIAAQAOAAAHgLQAEgGAAgPIAAgJQgVAEgJADgAG2AnQgNgNAAgZQAAgXANgPQAKgLAOAAQALAAAHAFQAFADAEAIIAAgdIgcAAIAAgJIAcAAIAAgOIANAAIAAAOIANAAIAAAJIgNAAIAABQQAAAWACAGIgNAAQgCgFAAgFIAAgDQgDAGgFAEQgHAFgLAAQgPAAgKgKgAHAgcQgIALAAASQAAASAIALQAGAHAKAAQALAAAGgHQAIgLAAgSQAAgSgIgKQgGgJgLABQgKAAgGAHgAEqAsQgJgHgCgLIAAgPIAAg4IANAAIAAA4QAAAOADAFQAFAHALAAQAMAAAHgKQAEgHAAgNIAAg0IAOAAIAABAIAAAPQAAAIACAFIgOAAQgCgFAAgHQgDAGgEADQgHAGgKgBQgMABgIgGgADKAsQgKgHgBgLIgBgPIAAg4IANAAIAAA4QAAAOAEAFQAEAHAMAAQAMAAAHgKQADgHAAgNIAAg0IAOAAIAAAGIABgBIAEgEQACgDABgDIgBAAIgEgBQgDgEABgFQABgEADgCQAEgBADAAQAEACACAEQACADgCAGQgDALgPALIAAAxIAAAKIAAAFQAAAIACAFIgNAAIgBgGIgBgGQgDAGgEADQgHAGgLgBQgLABgIgGgAA3AsQgKgIAAgOQAAgTAVgHQANgFAWgEIAAgDQAAgLgDgDQgFgGgLAAQgSAAgCAPIgOAAQABgLAIgIQAJgIARAAQAPAAAIAHQAHAFABAMIABAMIAAAiQAAASACAHIgNAAIgCgMQgIAOgTAAQgMAAgIgFgABIAEQgNAGAAAMQAAAGAFAGQAFAEAIAAQAOAAAHgLQADgGAAgPIAAgJQgUAEgJADgAmvAsQgKgIAAgOQAAgTAWgHQAMgFAXgEIAAgDQAAgLgDgDQgFgGgLAAQgSAAgCAPIgPAAQACgLAHgIQAJgIARAAQAPAAAJAHQAHAFABAMIAAAMIAAAiQAAASADAHIgNAAQgCgFAAgHQgIAOgUAAQgMAAgIgFgAmeAEQgMAGAAAMQAAAGAFAGQAEAEAIAAQAOAAAHgLQAEgGAAgPIAAgJQgUAEgKADgAJvAvIAAhcIAOAAIAABcgAAJAvIAAg0QAAgQgDgFQgEgKgLABQgNgBgHAMQgEAHAAAOIAAAyIgOAAIAAiDIAOAAIAAAyQAKgOARAAQAJAAAHAFQAJAFACALQACAGAAAPIAAA1gAjrAvIAAg4IAAgMQgCgOgQAAQgMgBgHALQgDAFAAANIAAA2IgOAAIAAg2QAAgPgCgFQgEgIgMAAQgGgBgFADQgFADgDAFQgDAGAAANIAAA1IgOAAIAAg/IAAgUIgCgJIANAAQACAFAAAHQAJgPASAAQATAAAGAQQAKgQATAAQASAAAGANQADAFABAIIAAANIAAA4gAncAvIAAg0QAAgQgDgFQgFgKgLABQgOgBgGAMQgEAHAAAOIAAAyIgPAAIAAiDIAPAAIAAAyQAJgOARAAQALAAAHAFQAJAFACALQABAGAAAPIAAA1gAo5AvIg4hEIA1g+IASAAIg1A+IA7BEgAp/AvIAAiCIAOAAIAACCgAIyhAQgGgEgDAAQgFAAgBAIIgHgBQAEgQAJAAQAFAAAGAEQAGAEADAAQAFAAABgIIAHABQgBAGgDAFQgDAFgGAAQgEAAgHgEgABIg8IAQgVIAPAAIgVAVgAmdg8IAQgVIAOAAIgVAVgAJvhEQgDgCAAgFQAAgEADgDQADgDAEAAQAEAAACADQAEACAAAFQAAAEgCADQgDADgFAAQgFAAgCgDg");
	this.shape.setTransform(44.275,7.95);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0066CC").s().p("Ar5CuIAAlcIXzAAIAAFcg");
	this.shape_1.setTransform(45.475,7.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30.7,-10,152.4,34.9);


(lib.Symbol10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AD2BtQgDgDAAgEQAAgFADgDQADgEADAAQAEAAAEAEQACADAAAFQAAAEgCADQgEAFgEAAQgDAAgDgFgAhdBtQgEgDAAgEQAAgFAEgDQACgEAEAAQAEAAADAEQACADAAAFQAAAEgCADQgDAFgEAAQgEAAgCgFgAB6AzQgLgRAAgcQAAgZALgRQAKgSARAAQAKAAAHAIIAHALIAAgsQAAgHgBgDQgBgDgGgBIgGAAIAAgFQAQgCAPgEIAACPIABALQABAEAEABIAJABIAAAFQgRACgKAFIgEgVQgIAVgRAAQgQAAgLgRgACAAGQAAAXAFAOQACAIAFAFQAFAFAGAAQAJAAAFgJQAIgMAAggQAAg3gXAAQgWAAAAA1gAKfAvQgKgQABgZQAAgZAKgRQALgUAUABQANAAAKAJQAFgJAAgIIAAAAIgCAAQgIgCACgKQACgIAHAAQALAAgBAMQAAAMgKANIgCABIgBADQANASAAAdQAAAZgKARQgLAVgTAAQgUAAgLgVgAKvgoQgIAMAAAiQAAA3AWAAQAYAAAAg3QAAg3gXAAQgIAAgHAJgAHaAyQgLgRAAgbQAAgcANgRQALgRARABQANAAAIAKIAGgMIADAAIAAAoIgEAAQgCgLgDgHQgDgGgFgEQgFgEgGAAQgNAAgGAQQgGAQABAXQgBA1AYAAQATAAAFghIAIAAQgCANgEAKQgJATgSAAQgTAAgLgSgAFEAxQgKgRAAgaQAAgbALgRQAMgRATAAQARAAALARQAKASAAAZQAAAbgKARQgMATgSAAQgTgBgLgSgAFUgoQgJAMAAAiQAAA3AXAAQAJAAAGgKQAIgNAAggQAAg3gXAAQgIAAgGAJgAgTAyQgLgRAAgbQAAgcAMgRQALgRARABQAMAAAJAKIAFgMIAFAAIAAAoIgGAAQgCgLgCgHQgDgGgFgEQgGgEgGAAQgMAAgFAQQgGAQAAAXQAAA1AXAAQATAAAEghIAJAAQgCANgFAKQgIATgTAAQgQAAgMgSgAh1AxQgKgRAAgaQAAgbALgRQALgRATAAQASAAALARQAKASAAAZQAAAbgKARQgMATgSAAQgTgBgLgSgAhlgoQgJAMAAAiQAAA3AXAAQAIAAAHgKQAIgNAAggQAAg3gXAAQgJAAgFAJgAiqAsQgFAJgEAGQgJAIgLAAQgRAAgIgPQgGgIAAgTIAAg4IgBgLQgBgDgFgBIgHAAIAAgFQAQgBAPgFIAABSQAAAPAEAHQAFAJAJgBQAMAAAGgKQAEgIAAgOIAAg2QAAgIgBgDQgCgDgFgBIgHAAIAAgFQAQgBAQgFIAABlIABAIQACADAFABIAHAAIAAAFQgQABgNAGIAAgYgAk+AyQgLgRAAgbQAAgcANgRQALgRARABQAMAAAJAKIAGgMIADAAIAAAoIgEAAIgFgSQgDgGgFgEQgGgEgFAAQgNAAgGAQQgGAQAAAXQAAA1AYAAQAUAAAEghIAIAAQgCANgEAKQgJATgSAAQgSAAgMgSgAs/AyQgMgRAAgbQAAgcANgRQALgRASABQAMAAAIAKIAHgMIADAAIAAAoIgFAAQgCgLgDgHQgDgGgFgEQgFgEgGAAQgNAAgGAQQgFAQgBAXQAAA1AYAAQAUAAAEghIAIAAQgCANgDAKQgJATgTAAQgSAAgLgSgAM4A+QgEgEAAgGQAAgFAEgEQADgFAFAAQAEAAAEAFQAEAEAAAFQAAAGgEAEQgEAFgEAAQgFAAgDgFgADhA7QgJgKAAgOQAAgXAYgMQANgFASgDIAAgPQAAgNgDgFQgFgHgKAAQgHAAgGAFQgEAEAAAFIAAADIABADQAAALgJAAQgHAAAAgIQAAgMAKgIQAKgKAOAAQALAAAHAFQALAHACAMQABAHAAALIAAAxQABANABAEQACAGAFAAIAEgBIAAAGQgGACgFABQgJAAgDgIQgDgGgBgIQgEAJgEAFQgIAIgMAAQgMAAgIgIgAD4AGQgPAIAAAUQAAALAGAFQADAGAJAAQANAAAFgPQACgHAAgPIAAgUQgOACgJAFgAnWA7QgIgKAAgOQgBgXAYgMQAOgFARgDIAAgPQAAgNgEgFQgDgHgKAAQgIAAgGAFQgDAEgBAFIAAADIABADQAAALgJAAQgHAAAAgIQAAgMAJgIQALgKAOAAQALAAAHAFQALAHACAMQACAHAAALIAAAxQAAANABAEQABAGAGAAIAEgBIAAAGQgGACgFABQgIAAgFgIQgCgGgBgIQgDAJgFAFQgHAIgNAAQgMAAgIgIgAm/AGQgPAIAAAUQAAALAFAFQAFAGAIAAQANAAAFgPQACgHAAgPIAAgUQgPACgIAFgAMMBAIgYABIAAgEQAIgBADgBQAEgCABgFIAAgFIAAhOIgBgLQgCgDgFgBIgIAAIAAgFQARgBAPgFIAABoIABAIQACAFAMABIAAAEIgXgBgAJyBAIgXABIAAgEQAHAAADgCQADgCABgFIAAgFIAAg8QAAgQgDgFQgFgKgKAAQgLABgGAJQgFAHAAAPIAAA7IABAIQADAFAKABIAAAEIgXgBIgWABIAAgEQAHgBADgBQAEgCAAgFIABgFIAAh+QAAgHgCgDQgBgDgGgBIgGAAIAAgFQAQgCAPgEIAABCQALgRAPAAQARAAAJAQQAFAIAAATIAAA7IABAIQACAFALABIAAAEIgWgBgAoCBAIgXABIAAgEQAHgBADgBQAEgCABgFIAAgFIAAh+QAAgHgBgDQgCgDgFgBIgHAAIAAgFQARgCAPgEIAACXQgBAGACACQACAFALABIAAAEIgXgBgApvBAIgXABIAAgEQAHgBADgBQAEgCABgFIAAgFIAAhOIgBgLQgCgDgFgBIgHAAIAAgFQAQgBAPgFIAABoIABAIQADAFALABIAAAEIgXgBgAqoBAIgWABIAAgEQAGAAADgCQAEgCAAgFIAAgFIAAg8QAAgQgDgFQgEgKgLAAQgLABgGAJQgEAHAAAPIAAA7IABAIQADAFAKABIAAAEIgXgBIgWABIAAgEQAGgBAEgBQADgCAAgFIABgFIAAh+IgBgKQgCgDgGgBIgFAAIAAgFQAPgCAQgEIAABCQAJgRARAAQARAAAIAQQAFAIAAATIAAA7IABAIQADAFALABIAAAEIgXgBgAhFhDIgTgUIgTAUIgGAAIAVgfIAKAAIAUAfgAp2hFIACgIIAHgKQADgFAAgFQABgJgIAAQgKAAgBANIgDAAQgBgNAJgEQADgCAGAAQAGAAADADQAFAEAAAHQABAIgFAEIgEAEIgFAGQgDADgBAEgAmwhJIgcgfIAQAAIARAfgAMEhOQgFgEAAgGQAAgFAFgFQADgDAEAAQAFAAADADQADAFABAFQgBAGgDAEQgDADgFABQgEgBgDgDg");
	this.shape.setTransform(94.55,-311.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(10.2,-323,168.70000000000002,22.69999999999999);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AijBuQgDgDAAgFQAAgGADgDQADgCADAAQAEAAADACQADADAAAGQAAAFgDADQgDADgEAAQgDAAgDgDgAASAwQgJgSAAgYQAAgWAJgRQAKgVATAAQALAAAGAHQADAEAFAJIAAgiIgfAAIAAgIIAfAAIAAgCQAAgIgCgCQgBgEgGgBIgCAAIgEAAIAAgEQAQgDAPgEIAAAcIANAAIAAAIIgNAAIAABrIABAKQAAAFAFACIAEAAIAFABIAAADIgPAEIgMADIgCgKIgBgKQgIAVgRAAQgUAAgKgUgAAaAGQAAAWAFAPQAFASANgBQAIABAGgIQAJgMAAghQAAg3gYAAQgWAAAAA1gAKIAxQgKgRAAgbQAAgaALgRQAMgRASgBQASAAALASQAKASAAAZQAAAagKASQgMASgSAAQgTAAgLgSgAKYgpQgJAOAAAgQAAA4AXAAQAJAAAGgKQAIgNAAggQAAg3gXAAQgJAAgFAIgAHNAyQgLgRAAgbQAAgcANgRQALgRASAAQAMAAAJALIAFgNIAEAAIAAAqIgFAAQgCgMgCgGQgDgIgGgDQgFgEgGAAQgNAAgFARQgGAPAAAXQAAA1AYAAQATAAAEghIAIAAQgBANgFAKQgIASgTAAQgSAAgMgRgAi6AxQgLgRAAgbQAAgaAMgRQALgRATgBQASAAAKASQALASAAAZQAAAagLASQgLASgTAAQgTAAgKgSgAirgpQgJAOAAAgQAAA4AXAAQAJAAAGgKQAIgNAAggQAAg3gXAAQgIAAgGAIgAIlA6QgJgJAAgOQAAgXAYgLQANgHASgCIAAgPQAAgMgDgGQgFgHgKAAQgHAAgGAFQgEAEAAAGIAAABIABAEQAAAMgJAAQgHAAAAgJQAAgLAJgJQALgKAOAAQAKAAAIAFQALAHACAMQABAHAAAKIAAAzQAAAMACAFQACAFAEAAIAFgBIAAAHIgLABQgJAAgEgHQgCgFgBgJQgEAKgEADQgHAJgNAAQgMAAgIgJgAI8AGQgPAJAAASQAAALAFAGQAEAGAIAAQAOAAAFgPQACgHAAgOIAAgWQgOADgJAFgAFrBBIgWABIAAgGQAGAAADgCQAEgCAAgDIAAgFIAAg9QAAgQgDgFQgEgJgLAAQgLAAgGAKQgEAGAAAPIAAA8IABAIQACAEAKAAIAAAGIgWgBIgXABIAAgGQAHAAADgCQAEgBAAgEIABgGIAAh9IgBgKQgCgEgFgBIgHAAIAAgFQAQgBAQgFIAABCQAKgRAQAAQAQAAAJAQQAFAIAAATIAAA7QAAAHABACQADAEALAAIAAAGIgXgBgAD7BBIgXABIAAgGQAHAAADgCQADgCABgDIAAgFIAAg9QAAgQgDgFQgFgJgKAAQgLAAgHAKQgEAGAAAPIAAA8IABAIQADAEAKAAIAAAGIgXgBIgWABIAAgGQAHAAADgCQAEgBABgEIAAgGIAAhNIgBgJQAAgFgGgBIgIgBIAAgEQARgCAKgFIADAWQAKgUARAAQARAAAJAPQAFAJAAATIAAA7QAAAHABACQACAEAMAAIAAAGIgXgBgACIBBIgXABIAAgGQAIAAADgCQADgBABgEIAAgGIAAhPIgBgJQgCgEgFgBIgHAAIAAgEQARgDAPgEIAABoQAAAHABACQACAEAMAAIAAAGIgYgBgAhPBBIgXABIAAgGQAHAAAEgCQADgBABgEIAAgGIAAhPIgBgJQgCgEgFgBIgHAAIAAgEQARgDAPgEIAABoQAAAHABACQACAEAMAAIAAAGIgYgBgAjoBBIgWABIAAgGQAGAAADgCQADgBABgEIAAgFIAAhAQAAgOgCgEQgEgJgLAAQgUAAAAAdIAAA+IABAIQACAEAKAAIAAAGIgWgBIgVABIAAgGQAGAAADgCQADgBABgEIAAgFIAAg/QAAgOgDgGQgEgJgJABQgMAAgGALQgDAGAAAPIAAA7IABAIQACAEAKAAIAAAGIgWgBIgXABIAAgGQAHAAADgCQAEgBABgEIAAgGIAAhNIAAgJQAAgEgDgBIgMgCIAAgEQASgDAKgEQACAKAAAMQAEgIAEgEQAIgIAMAAQASAAAHAUQAEgIADgDQAIgJANAAQASAAAHAPQAEAIAAARIAAA+QAAAHABACQACAEAMAAIAAAGIgXgBgAnCBBIgXABIAAgGQAHAAADgCQADgBABgEIAAgGIAAhPIgBgJQgBgEgGgBIgGAAIAAgEQAQgDAPgEIAABoQAAAHABACQADAEALAAIAAAGIgXgBgAn7BBIgWABIAAgGQAGAAADgCQAEgCAAgDIAAgFIAAg9QAAgQgDgFQgEgJgLAAQgLAAgGAKQgEAGAAAPIAAA8IABAIQACAEAKAAIAAAGIgWgBIgXABIAAgGQAHAAADgCQAEgBAAgEIABgGIAAh9IgBgKQgCgEgFgBIgHAAIAAgFQARgBAPgFIAABCQAKgRAQAAQAQAAAJAQQAFAIAAATIAAA7QAAAHABACQADAEALAAIAAAGIgXgBgAptBAQgMAAgPACIAAgHIAJgBQAFgBAAgEQAAgDgDgGIglhCIgJALIAAA2QAAAHABAEQADAEAMABIAAAHQgNgCgLAAQgKAAgQACIAAgHQAJAAADgCQAEgCABgGIAAgGIAAh6QAAgJgBgCQgCgEgGgBIgIgBIAAgGIAaABIAZgBIAAAGQgIABgEABQgEADgBAFIAAAHIAAA5IAvg/QADgDAAgDQAAgDgFgBIgIgBIAAgGIAWABIAVgBIAAAGQgIAAgEACQgGADgHAIIgkAwIAuBOQAHALAFADQAFACAHAAIAAAHQgQgCgLAAgACChFIACgIIAGgJQAEgFAAgFQAAgKgHAAQgKAAgBAMIgEAAQAAgLAIgGQAEgCAFAAQAGABADADQAGAEAAAIQAAAHgFAEIgDAEIgGAFQgDAEAAAEgAhXhOQgEgEAAgGQAAgFAEgEQADgEAFgBQAEABADAEQAEAEAAAFQAAAGgEAEQgDAEgEAAQgFAAgDgEgAnLhOQgDgEAAgGQAAgFADgEQADgEAFgBQAFABADAEQAEAEAAAFQAAAGgEAEQgDAEgFAAQgFAAgDgEg");
	this.shape.setTransform(86.775,-353.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(15,-364.9,143.6,22.69999999999999);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.514,1],-14.5,-4.6,14.7,4.7).s().p("AjwD8IC+pUIEjBeIi+JTg");
	this.shape.setTransform(24.125,34.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.3,69);


(lib.Symbol1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.bg1();
	this.instance.setTransform(0,-1,0.3356,0.3355);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(245).to({_off:true},1).wait(4054));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-1,302,603.9);


(lib.Symbol25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMyBwIgXABIAAgEQAHAAADgCQAEgCAAgDIABgGIAAh6QAAgKgEgDQgCgBgJgBIAAgEQAPgCALgDQACAIABANQAJgUAQAAQAQAAALARQAKAQAAAZQAAAZgKAQQgKARgQAAQgLABgGgIIgIgLIAAAvQAAAFACADQACAEALABIAAAEIgWgBgANCgiQgJALAAAeQAAA2AXAAQAWAAAAgzQAAg0gXAAQgIgBgFAJgAFnBwIgXABIAAgEQAHAAADgCQAEgCAAgDIABgGIAAh6QAAgKgEgDQgCgBgJgBIAAgEQAPgCALgDQACAIABANQAJgUAQAAQAQAAALARQAKAQAAAZQAAAZgKAQQgKARgQAAQgLABgGgIIgIgLIAAAvQAAAFACADQACAEALABIAAAEIgWgBgAF3giQgJALAAAeQAAA2AXAAQAWAAAAgzQAAg0gXAAQgIgBgFAJgAroBwIgWABIAAgEQAHAAADgCQADgCABgDIAAgGIAAgvIgHALQgHAIgKgBQgRAAgKgRQgKgQAAgZQAAgZALgQQAKgRAQAAQARAAAIAUQABgNACgIQALADAPACIAAAEIgDAAQgHAAgCADQgCAEAAAIIAAB6IABAIQACAEALABIAAAEIgWgBgAsUghQgIALAAAgQAAAzAVAAQAXAAAAg2QAAgxgWAAQgIgBgGAKgApWBwIAAgMQAHAAAEgBQAKgEAFgQIAGgSIgdhdQgCgHgEgCIgJgBIAAgGIAUABIAVgBIAAAGIgGAAQgFABAAADIACAHIAUBEIAWhEIACgGQAAgEgFgBIgHAAIAAgGIAPABIARgBIAAAGIgIABQgFADgCAHIglB0QgFAQgIAHQgHAEgJAAIgDAAgAvxBtQgCgEAAgEQAAgFACgDQADgDAEAAQADAAADADQADADAAAFQAAAEgDAEQgDADgDAAQgEAAgDgDgAA7BGIgQgdIg+hzIAAB3QAAAIABACQADAEANABIAAAGIgUgBIgTABIAAgGQAIAAADgCQAEgCABgFIAAgGIAAh/QgDgDgEgBIgKgCIAAgGIARAAIAOAAIBCB5IAAhkIgBgKQgCgEgNgBIAAgGIAUABIATgBIAAAGIgLACQgEADgBAEIAAAGIAACPgAxtAxQgJgRAAgWQAAgWAJgRQAJgTASAAQAKAAAHAHIAHALIAAgfIgdAAIAAgHIAdAAIAAgDIgBgKQgCgDgFgBIgDAAIgDAAIAAgEQAQgDAOgEIAAAcIAMAAIAAAHIgMAAIAABmIAAAKQABAEAEACIAEAAIAFABIAAADIgPAEIgLADIgCgKIgBgKQgIAUgQAAQgSAAgKgTgAxlAKQAAAVAEAOQAFAQAMAAQAIABAGgIQAIgLAAggQAAg1gXABQgUAAAAAzgAP6AyQgKgQAAgZQAAgZALgRQALgRASAAQARABAKARQAKAQAAAZQAAAYgKARQgLASgSAAQgRAAgLgSgAQJgjQgIANAAAfQAAA1AVAAQAJAAAGgKQAHgMAAgeQAAg1gVAAQgIgBgGAJgAiCAuQgEAKgEADQgIAJgLgBQgQAAgIgNQgFgJAAgRIAAg2IgBgKQgCgEgLgBIAAgDQAPgDAPgEIAABPQAAAPADAFQAEAJAKAAQAMAAAFgKQAEgIAAgOIAAgzIgBgKQgCgEgLgBIAAgDQAPgDAPgEIAAAIQAGgIAAgHIgCAAQgIgCACgKQABgIAHAAQAKgBAAAMQAAALgJANIgEAEIgDAFIAABQIABAIQABACAGABIAGABIAAADQgPADgMAEIgBgWgAnuA0QgLgQAAgbQAAgZALgRQAKgQASAAQANAAAKAKQAMAOABAfIg7AAIAAAFQAAAVAGAOQAGAOAOAAQAOAAAHgPQADgHABgJIAIAAQgBANgGAKQgKAQgSAAQgTAAgKgQgAnpgCIArAAQgCgpgSAAQgUAAgDApgAqFAuQgEAJgEAEQgIAJgLgBQgQAAgIgNQgFgJAAgRIAAg2IgBgKQgCgDgFgBIgGgBIAAgDQAPgCAPgFIAABPQAAAPADAFQAEAJAKAAQAMAAAFgKQAEgIAAgOIAAgzIgBgKQgCgDgFgBIgGgBIAAgDQAPgCAPgFIAABhIABAIQABACAGABIAGABIAAADQgQADgLAEIgBgWgAupAzQgLgPAAgaQAAgbAMgRQALgQAQAAQAMAAAJAKIAFgLIADAAIAAAnIgEAAQgCgLgDgHQgDgGgEgEQgFgDgGAAQgMAAgGAPQgFAQAAAWQAAAyAXAAQASAAADgfIAIAAQgBANgEAIQgIASgSAAQgRAAgLgRgAwHAyQgKgQAAgZQAAgZALgRQALgRASAAQARABAKARQAKAQAAAZQAAAYgKARQgLASgSAAQgRAAgLgSgAv4gjQgIANAAAfQAAA1AVAAQAJAAAGgKQAHgMAAgeQAAg1gVAAQgIgBgGAJgAItA7QgIgIAAgOQAAgWAWgLQANgGARgCIAAgPQAAgLgDgFQgFgIgJABQgHAAgGAEQgDAEAAAFIAAADIAAADQAAALgIAAQgHAAAAgJQAAgKAJgJQAKgJAOAAQAJAAAIAFQAKAHACALIABAQIAAAxQAAALACAFQABAFAFAAIAFgBIAAAHIgLABQgIAAgEgHQgCgFgBgIQgEAIgEAEQgHAJgMgBQgMABgHgJgAJCAKQgNAHAAATQAAAKAFAFQAEAGAHAAQANAAAEgOQADgHAAgOIAAgVQgOADgJAGgADOA7QgIgIAAgOQAAgWAXgLQANgGAQgCIAAgPQAAgLgDgFQgEgIgJABQgIAAgFAEQgEAEAAAFIAAADIAAADQAAALgIAAQgGAAAAgJQAAgKAJgJQAJgJAOAAQAKAAAIAFQAJAHADALIABAQIAAAxQAAALABAFQACAFAFAAIAFgBIAAAHIgLABQgJAAgEgHQgCgFgBgIQgEAIgDAEQgHAJgMgBQgMABgIgJgADkAKQgOAHAAATQAAAKAFAFQAEAGAIAAQAMAAAFgOQACgHAAgOIAAgVQgNADgJAGgAj0A2QgCgFgBgJIAAgMIAAhCIgMAAIAAgIQAFAAAEgCQALgHADgaIAFAAIAAAiIAXAAIAAAJIgXAAIAABFQAAAPACAEQADAIAHAAQAFAAAIgFIAAAHQgKAIgJgBQgPAAgEgNgARhBBIgWABIAAgFQAGAAAEgCQADgBABgEIAAgGIAAhKIgBgKQgCgDgFgBIgGgBIAAgDQAQgDAOgEIAABjIABAJQACAEALAAIAAAFIgWgBgAPOBBIgVABIAAgFQAGAAADgCQADgCABgDIAAgFIAAg6QAAgPgDgFQgEgJgKAAQgLAAgGAJQgEAHAAAOIAAA5QAAAGABACQACAEAKAAIAAAFIgWgBIgVABIAAgFQAHAAADgCQADgBABgEIAAgGIAAh3IgBgKQgCgDgFgBIgGAAIAAgFQAQgBAOgFIAAA/QAJgQAQAAQAQAAAIAPQAFAJAAARIAAA4QAAAGABADQACAEALAAIAAAFIgWgBgALMBBIgVABIAAgFQAFAAAEgCQADgCAAgDIABgFIAAg6QAAgPgDgFQgFgJgKAAQgKAAgHAJQgDAHAAAOIAAA5IABAIQACAEAJAAIAAAFIgVgBIgVABIAAgFQAGAAADgCQAEgBAAgEIABgGIAAhJIgBgIQAAgGgFgBIgIAAIAAgEQAQgCAKgFQABAHABAOQAKgTARAAQAQAAAIAPQAEAIAAASIAAA4QAAAGACADQACAEALAAIAAAFIgWgBgAIDBBIgVABIAAgFQAGAAADgCQADgCABgDIAAgFIAAg6QAAgPgDgFQgEgJgKAAQgLAAgGAJQgEAHAAAOIAAA5QAAAGABACQACAEAKAAIAAAFIgWgBIgVABIAAgFQAHAAADgCQADgBABgEIAAgGIAAh3IgBgKQgCgDgFgBIgGAAIAAgFQAQgBAOgFIAAA/QAJgQAQAAQAQAAAIAPQAFAJAAARIAAA4QAAAGABADQACAEALAAIAAAFIgWgBgAClBBIgWABIAAgFQAGAAAEgCQADgCAAgDIABgFIAAg6QAAgPgDgFQgFgJgKAAQgKAAgHAJQgEAHAAAOIAAA5QAAAGACACQACAEAJAAIAAAFIgVgBIgWABIAAgFQAHAAADgCQAEgBAAgEIABgGIAAh3IgBgKQgCgDgFgBIgGAAIAAgFQAPgBAOgFIAAA/QAKgQAQAAQAQAAAIAPQAEAJAAARIAAA4QAAAGACADQACAEALAAIAAAFIgWgBgAlUBBIgVABIAAgFQAFAAAEgCQADgCAAgDIABgFIAAg6QAAgPgDgFQgFgJgKAAQgKAAgHAJQgDAHAAAOIAAA5IABAIQACAEAJAAIAAAFIgVgBIgVABIAAgFQAGAAADgCQAEgBAAgEIABgGIAAhJIgBgIQAAgGgFgBIgIAAIAAgEQAQgCAKgFQABAHABAOQAKgTARAAQAQAAAIAPQAEAIAAASIAAA4QAAAGACADQACAEALAAIAAAFIgWgBgAQog9IgSgSIgTASIgFAAIAUgcIAJAAIAUAcgAJcg9IgSgSIgTASIgFAAIAUgcIAJAAIAUAcgAnAg9IgTgSIgSASIgGAAIAUgcIAJAAIAUAcgAvYg9IgTgSIgSASIgGAAIAUgcIAJAAIAUAcgADyhCIgbgeIAQAAIAQAegAiPhCIgbgeIAQAAIAQAegARZhHQgEgEAAgFQAAgGADgDQAEgFAEAAQAFAAADAFQADADAAAGQAAAFgDAEQgDADgFAAQgEAAgDgDgAmzhSIgcgeIAQAAIARAegAQohTIAQgeIAQAAIgbAeg");
	this.shape.setTransform(114.275,11.35);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,228.6,22.7);


(lib.Symbol24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ak9BiQgGgFgDgGQgEgHAAgIQAAgSATgIIgGgEQgEgEAAgGQAAgNAVgGQgIgDgFgFQgKgJAAgRQAAgQAJgKQAKgKAQAAQAMAAAIAHIAbAAIAAAJIgTAAQAFAJAAALQAAATgNAJQgGAEgPAFIgOAFQgHADAAAFQAAAEAEABIAOACQAWACAJAEQAIAEAEAJQADAGAAAHQAAAIgDAHQgDAHgFAFQgMAKgUAAQgQAAgMgHgAk6A7QgIAFAAAKQAAALAJAGQAKAHAOAAQAOAAAJgHQAIgFAAgLQAAgVgiAAQgNAAgJAFgAkvgqQgFAIAAAOQAAAMAEAIQAFAIAKAAQAKAAAEgIQAFgIAAgNQAAgegTAAQgJAAgFAJgAGSApQgIgRAAgWQAAgWAIgQQAKgUASAAQAKAAAGAHIAHAMIAAggIgdAAIAAgHIAdAAIAAgDIgBgKQgBgDgGgBIgCAAIgEAAIAAgEQAQgCAOgFIAAAcIANAAIAAAHIgNAAIAABmIABAKQABAEADACIAEAAIAGABIAAAEIgPADIgMADIgBgJIgBgKQgIAUgRAAQgSAAgKgUgAGaACQAAAVAEAOQAFARANAAQAIAAAFgIQAIgLAAggQAAg0gWAAQgVAAAAAzgAEvAmQgEAJgEAFQgIAIgLAAQgQAAgIgOQgFgIAAgSIAAg2IgBgKQgCgDgFgBIgGAAIAAgEQAPgCAPgFIAABPQAAAPADAGQAEAIAKAAQAMAAAFgKQAEgHAAgPIAAgzIgBgKQgCgDgFgBIgGAAIAAgEQAPgCAPgFIAABhIABAIQABADAGAAIAGABIAAAEQgQACgLAEIgBgWgADEAmQgEAKgEAEQgHAIgMAAQgQAAgIgOQgFgJAAgRIAAg2IgBgKQgCgEgLAAIAAgEQAQgCAOgFIAABPQAAAPADAGQAFAIAKAAQALAAAGgKQADgHAAgPIAAgzIgBgKQgCgEgLAAIAAgEQAQgCAOgFIAAAIQAGgIAAgHIgCAAQgIgCACgKQACgIAHAAQAJAAAAAMQAAAKgJANIgDAFIgEAEIAABQIABAIQACADAFAAIAHABIAAAEQgQACgMAEIgBgWgAAGAsQgJgQAAgaQAAgbAKgRQALgPARAAQAMAAAIAKIAFgMIAEAAIAAAnIgFAAQgBgLgDgGQgDgHgFgDQgFgEgFAAQgNAAgFAQQgGAPAAAWQAAAyAXAAQASAAAEgfIAIAAQgBANgFAJQgIARgSAAQgRAAgLgQgAirAsQgKgQAAgaQAAgbALgRQALgPARAAQAMAAAIAKIAFgMIAEAAIAAAnIgFAAQgBgLgDgGQgDgHgFgDQgFgEgFAAQgNAAgFAQQgGAPAAAWQAAAyAXAAQASAAAEgfIAIAAQgBANgFAJQgIARgSAAQgRAAgLgQgAndAmQgEAJgEAFQgIAIgLAAQgQAAgIgOQgFgIAAgSIAAg2IgBgKQgCgDgFgBIgGAAIAAgEQAPgCAPgFIAABPQAAAPADAGQAEAIAKAAQAMAAAFgKQAEgHAAgPIAAgzIgBgKQgCgDgFgBIgGAAIAAgEQAPgCAPgFIAABhIABAIQABADAGAAIAGABIAAAEQgQACgLAEIgBgWgApqAsQgKgQAAgaQAAgbALgRQALgPARAAQAMAAAIAKIAFgMIAEAAIAAAnIgFAAQgBgLgDgGQgDgHgFgDQgFgEgFAAQgNAAgFAQQgGAPAAAWQAAAyAXAAQASAAAEgfIAIAAQgBANgFAJQgIARgSAAQgRAAgLgQgAH3A0QgIgJAAgOQAAgWAWgKQANgGARgDIAAgOQAAgMgDgFQgFgHgJAAQgHAAgGAFQgDADAAAGIAAACIAAADQAAALgIAAQgHAAAAgIQAAgLAJgIQAKgKAOAAQAJAAAIAFQAKAHACALIABARIAAAwQAAALACAFQABAFAFAAIAFgBIAAAHIgLABQgIAAgEgHQgCgFgBgIQgEAJgEAEQgHAIgMAAQgMAAgHgIgAIMACQgNAIAAASQAAAKAFAGQAEAFAHAAQANAAAEgOQADgHAAgOIAAgUQgOADgJAFgAhYA0QgIgJAAgOQAAgWAXgKQANgGAQgDIAAgOQAAgMgDgFQgEgHgJAAQgIAAgFAFQgEADAAAGIAAACIAAADQAAALgIAAQgGAAAAgIQAAgLAJgIQAJgKAOAAQAKAAAIAFQAJAHADALIABARIAAAwQAAALABAFQACAFAFAAIAFgBIAAAHIgLABQgJAAgEgHQgCgFgBgIQgEAJgDAEQgHAIgMAAQgMAAgIgIgAhCACQgOAIAAASQAAAKAFAGQAEAFAIAAQAMAAAFgOQACgHAAgOIAAgUQgNADgJAFgAJfA5IgWABIAAgEQAHgBADgBQADgCABgEIAAgFIAAhLIgBgKQgBgDgGgBIgGAAIAAgEQAQgCAOgFIAABkIABAIQADAEAKABIAAAEIgWgBgAlqA5IgVABIAAgEQAGAAADgCQADgCABgEIAAgFIAAg6QAAgOgDgGQgEgJgKAAQgLAAgGAKQgEAGAAAOIAAA5IABAIQACAEAKABIAAAEIgVgBIgWABIAAgEQAHgBADgBQADgCABgEIAAgFIAAhKIAAgIQgBgFgFgBIgIgBIAAgEQARgCAJgFQACAHAAAOQALgTAQAAQAQAAAIAPQAFAJAAARIAAA5QAAAGABACQACAEALABIAAAEIgWgBgAhEhKIAQgeIAQAAIgbAegAnqhKIgcgeIAQAAIARAegAJXhPQgDgEAAgFQAAgGADgDQADgEAFAAQAEAAADAEQADADAAAGQAAAFgDAEQgDAEgEAAQgFAAgDgEgAIThVQgFgEgDAAQgHAAgDAKIgEgBQACgJAEgFQAEgFAFAAQAGAAAGAFQAHAHAFAAQAFgBADgLIAEABQgCAKgEAFQgEAFgFABQgFAAgJgIg");
	this.shape.setTransform(162.425,9.725);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(99.5,-0.8,125.9,21.1);


(lib.Symbol16copy2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AgZAAIAzAA");
	this.shape.setTransform(150.525,22.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiKBkQAMgOAKgPQANgUAHgPQgIADgGAAQgQAAgKgOQgNgQAAgZQAAgaAMgQQALgRATAAQAQAAAMAPQAMAQAAAcQAAAZgNAbQgLAUgWAbIgOARgAh2g/QgGAEgCAIQgFAMAAAUQABAXAFAOQAGANAMAAQAXAAAAgvQAAgzgXgBQgHABgEAEgAj3BkQAMgOALgPQANgUAGgPQgHADgHAAQgQAAgJgOQgNgQAAgZQAAgaALgQQAMgRASAAQARAAAMAPQAMAQAAAcQAAAZgOAbQgKAUgXAbIgOARgAjjg/QgFAEgDAIQgEAMAAAUQAAAXAGAOQAFANAMAAQAXAAAAgvQAAgzgXgBQgHABgEAEgAptBFQgEAKgEAEQgJAJgMAAQgQgBgJgOQgFgIgBgTIAAg4IgBgKQgBgFgMAAIAAgEQAQgDAPgEIAABSQABAPADAHQAEAIALAAQAMAAAGgLQAEgGAAgQIAAg1QAAgHgCgDQgCgFgLAAIAAgEQAQgCAPgFIAAAIQAHgIAAgIIgCAAQgJgCACgJQACgKAHABQAKgBAAAMQAAAMgJANIgDAFIgFAEIAABTQAAAHACACQABADAGABIAHAAIAAAEQgRACgMAFIgBgXgAJcBFQgLgYAAgkQgBgnAMgXQAMgWAVAAQANAAAKAKQALAKAFAXQAEATAAAVQAAAjgKAYQgLAYgWABQgXAAgKgXgAJtg6QgKASAAAxQAAAjAGAVQADAJAFAGQAFAEAHAAQAZAAAAhLQAAglgGgUQgHgTgNgBQgJAAgGAKgAHvBFQgLgYAAgkQAAgnAMgXQALgWAWAAQAMAAAKAKQALAKAGAXQADATAAAVQAAAjgKAYQgKAYgXABQgWAAgLgXgAIBg6QgLASAAAxQAAAjAGAVQAEAJAEAGQAGAEAGAAQAZAAAAhLQABglgHgUQgGgTgNgBQgJAAgGAKgAGDBFQgLgYAAgkQAAgnAMgXQALgWAWAAQAMAAAKAKQALAKAFAXQAEATAAAVQAAAjgKAYQgKAYgXABQgWAAgLgXgAGVg6QgLASAAAxQAAAjAGAVQAEAJAEAGQAGAEAGAAQAZAAAAhLQABglgHgUQgGgTgNgBQgJAAgGAKgAFNBXQgDgDAAgHQAAgFADgFQAEgDAFAAQAEAAAEADQAEAFgBAFQABAHgEADQgEAFgEAAQgFAAgEgFgADoBFQgMgYAAgkQAAgnAMgXQALgWAVAAQANAAALAKQAKAKAGAXQADATAAAVQABAjgLAYQgKAYgXABQgWAAgKgXgAD5g6QgLASAAAxQAAAjAGAVQAEAJAEAGQAFAEAHAAQAaAAgBhLQAAglgGgUQgHgTgNgBQgIAAgGAKgAB7BFQgMgYAAgkQAAgnANgXQAKgWAWAAQANAAAKAKQALAKAFAXQAEATAAAVQAAAjgKAYQgKAYgYABQgVAAgLgXgACMg6QgLASAAAxQAAAjAHAVQADAJAFAGQAFAEAGAAQAaAAAAhLQAAglgHgUQgGgTgNgBQgJAAgGAKgAAPBFQgMgYAAgkQAAgnANgXQAKgWAWAAQANAAAKAKQALAKAFAXQAEATAAAVQAAAjgKAYQgKAYgYABQgVAAgLgXgAAgg6QgLASAAAxQAAAjAHAVQADAJAFAGQAFAEAGAAQAaAAAAhLQAAglgHgUQgGgTgNgBQgJAAgGAKgAgmBXQgEgDAAgHQAAgFAEgFQADgDAFAAQAFAAADADQAEAFAAAFQAAAHgEADQgDAFgFAAQgFAAgDgFgAmbBXQgEgDABgHQgBgFAEgFQAEgDAEAAQAFAAAEADQADAFAAAFQAAAHgDADQgEAFgFAAQgEAAgEgFgArlBNQgCgFgBgIIAAgOIAAhEIgMAAIAAgIQAFAAAEgDQALgGAFgcIAEAAIAAAkIAZAAIAAAJIgZAAIAABIQAAAPACAFQADAIAIAAQAFAAAJgGIAAAIQgLAHgJABQgQgBgFgOgAluBaIAAgPQAYggANgWQANgVAFgMQAGgMAAgKQAAgLgGgIQgHgIgKAAQgHAAgGAEQgGAEgEAHQgDAHgCANIgHAAQACgWAGgKQAFgIAJgFQAIgEAKAAQAOAAAKAJQAGAGADAHQADAIAAAIQAAAQgMAVQgNAUgmA0IBAAAIgBASgAoJBaIAAgPQAXggANgWQANgVAFgMQAGgMAAgKQAAgLgGgIQgGgIgLAAQgHAAgGAEQgGAEgEAHQgDAHgCANIgHAAQACgWAGgKQAFgIAJgFQAIgEAKAAQAPAAAJAJQAGAGADAHQADAIAAAIQAAAQgNAVQgMAUglA0IBAAAIgCASgAK+AAQgHgMAAgPQAAgQAHgKQAGgNAMgBQAIABADAEQADACADAGIAAgWIgUAAIAAgEIAUAAIAAgDIgBgGQgBgCgEgBIgCAAIgCAAIAAgDQAKgBALgDIAAATIAIAAIAAAEIgIAAIAABGIAAAGQABADACABIADAAIADAAIAAAEIgKACIgIACIgBgHIAAgFQgGAMgMAAQgMAAgGgMgALDgbQAAAOADAKQADALAJAAQAFAAAEgGQAFgHABgUQAAglgQAAQgOAAAAAjgAp7gwIgdgeIASAAIARAeg");
	this.shape_1.setTransform(77.8,18.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2.1,8.2,152.1,20);


(lib.Symbol6copy2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnPBcIAAg3IAEAAQAGAuAdgBQANAAAHgKQAHgJAAgNQAAgQgIgIQgFgFgOgIQgWgOgGgHQgJgLAAgRQAAgUALgMQAKgMARAAQAPAAALANIAFgOIAEAAIAAAuIgFAAQgCgNgEgIQgIgQgPAAQgLgBgHAKQgHAJAAAMQAAAOALAJIAUANQAQAKAGAFQAMAMAAAWQAAAVgLAOQgLANgSgBQgRAAgOgOIgHAQgAGHBPQgNgMgGgYQgEgRAAgVQAAglAOgYQAHgNALgGQAJgGAMAAQASAAANAPIAHgPIADAAIAAAyIgEAAQgJgqgaABQgUAAgJAVQgIAWAAAiQAAAfAIAVQAJAXAUAAQANAAAJgKQALgNABgZIAHAAQgBATgFANQgGANgKAIQgKAGgMAAQgQAAgNgMgACoBPQgOgMgGgXQgEgSAAgWQAAgmAOgWQAOgZAZAAQASAAAOAPIAIgPIADAAIAAAyIgEAAQgDgOgFgJQgEgJgIgFQgHgFgJAAQgPAAgJAMQgPAUAAAtQAABPAmAAQANABAOgKIAAgqIgBgHQgCgEgNgCIAAgFIAXABIAXgBIAAAFQgJABgDACQgCABAAAEIAAAFIAAApQgYASgVAAQgRAAgMgMgAlkBHQgIgRAAgZQAAgZAJgQQALgUATAAQANAAAIAKQAGgJAAgIIgBAAQgIgCABgKQACgJAHAAQAKAAgBANQAAALgJANIgBADIgCACQAMARAAAdQAAAZgJASQgKAUgTAAQgTAAgLgUgAlUgRQgIANAAAhQAAA3AWAAQAWAAAAg3QAAg3gWAAQgIABgGAIgAA1BEQgEAJgEAEQgIAJgLAAQgQAAgIgOQgFgJAAgSIAAg5IAAgKQgCgEgFAAIgGAAIAAgFQAPgBAOgGIAABTQAAAPADAGQAEAJAKAAQAMAAAFgLQAEgHAAgQIAAg1IgBgKQgCgEgFAAIgGAAIAAgFQAPgBAPgGIAABlIABAJQACADAFAAIAGAAIAAAFQgQACgLAEIgBgWgAg0BEQgEAJgEAFQgIAIgLAAQgQAAgIgOQgGgJAAgSIAAg5IAAgKQgCgEgLAAIAAgFQAPgCAOgFIAABTQAAAPAEAGQAEAJAKAAQALAAAGgLQAEgHAAgPIAAg2IgBgKQgCgEgLAAIAAgFQAPgBAPgGIAAAIQAFgIAAgHIgCAAQgHgDACgJQABgJAHAAQAKAAAAAMQAAALgJANIgEAGIgDAEIAABTIABAJQABACAGABIAGAAIAAAFQgPACgMAEIgBgWgAiXBYIgVABIAAgFQAGAAADgCQADgCABgEIAAgGIAAg9QAAgOgDgFQgFgKgKAAQgKAAgGAKQgEAHAAANIAAA8IABAJQACAEAKABIAAAFIgWgBIgVABIAAgGQAHAAADgBQADgCABgEIAAgGIAAh9IgBgKQgCgDgFgBIgGgBIAAgEQAPgCAPgFIAABCQAJgQAQAAQAQAAAIAPQAFAJAAARIAAA8IABAJQACAEALAAIAAAGIgWgBgAEJBYIAAgGQAIgBADgCQAEgBABgGIAAgHIAAh4QAAgJgBgCQgCgEgGgCIgHAAIAAgHQAPACAKABQAJgBAPgCIAAAHIgLACQgEADgBAEIAAAIIAAB4QAAAGABACQACAHAKgBIAOAAQAJAAAFgCQAEgDADgHQAEgIACgMIAFAAIgFApgAlLgvIACgIIAGgKQAEgFAAgFQAAgKgHAAQgKAAgBANIgDAAQAAgMAHgFQAEgCAFAAQAFAAAEADQAFAFAAAHQAAAHgEAFIgEADIgFAGQgDADAAAFgAhNg/QgEgFgEABQgGAAgEALIgDgBQACgLADgEQAEgFAGgBQAGABAFAFQAIAHAEAAQAGgBADgMIADACQgBAKgEAFQgEAFgFABQgGAAgJgIg");
	this.shape.setTransform(52.075,12.75);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(5.7,3.6,92.8,18.4);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol22("synched",0);
	this.instance.setTransform(152.5,170.9,1.3,1.3,0,0,0,152.5,208.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1,scaleY:1,y:208.4,alpha:1},17,cjs.Ease.get(1)).wait(43).to({startPosition:0},0).to({_off:true},1).wait(3830));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-47,-98.7,397.8,786.2);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol20("synched",0);
	this.instance.setTransform(104.7,11.1,1,1,0,0,0,104.7,11.1);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},12,cjs.Ease.get(1)).wait(76).to({startPosition:0},0).to({_off:true},1).wait(29).to({_off:false},0).wait(9).to({startPosition:0},0).to({_off:true},1).wait(6).to({_off:false},0).wait(146).to({startPosition:0},0).to({_off:true},1).wait(2459));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(9.9,-362.2,210.4,22.19999999999999);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Ar3CvIAAleIXvAAIAAFeg");
	mask.setTransform(40.425,12.25);

	// Layer_3
	this.instance = new lib.Symbol2("synched",0);
	this.instance.setTransform(-59.1,7.15,1,1,0,0,0,24.1,34.5);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:141.55,y:9.55},23,cjs.Ease.get(1)).wait(67));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-35.6,-5.3,152.1,35.1);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.setTransform(43.35,7.65,0.4,0.4,0,0,0,43.4,7.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:7.6,scaleX:1.1,scaleY:1.1,x:43.4,y:7.6,alpha:1},11,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(131).to({startPosition:0},0).to({_off:true},1).wait(1812));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-38.1,-11.8,167.6,38.400000000000006);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol10("synched",0);
	this.instance.setTransform(27.3,11.8,1,1,0,0,0,62.3,11.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:63.8,alpha:1},11,cjs.Ease.get(1)).to({x:62.3},9,cjs.Ease.get(1)).wait(52).to({startPosition:0},0).to({_off:true},1).wait(38).to({_off:false},0).wait(9).to({startPosition:0},0).to({_off:true},1).wait(6).to({_off:false},0).wait(146).to({startPosition:0},0).to({_off:true},1).wait(916));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24.8,-323,205.20000000000002,22.69999999999999);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol4("synched",0);
	this.instance.setTransform(16.9,11.8,1,1,0,0,0,51.9,11.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:52.9,alpha:1},11,cjs.Ease.get(1)).to({x:51.9},9,cjs.Ease.get(1)).wait(53).to({startPosition:0},0).to({_off:true},1).wait(32).to({_off:false},0).wait(9).to({startPosition:0},0).to({_off:true},1).wait(6).to({_off:false},0).wait(149).to({startPosition:0},0).to({_off:true},1).wait(423));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-20,-364.9,204.1,384.09999999999997);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol17("synched",0);
	this.instance.setTransform(154.05,172.75,1.3,1.3,0,0,0,160,226.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1,scaleY:1,x:154,y:203.7,alpha:1},17,cjs.Ease.get(1)).wait(130).to({startPosition:0},0).to({_off:true},1).wait(4152));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-48.7,-94.6,396.5,786.4);


(lib.Symbol23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol25("synched",0);
	this.instance.setTransform(79.15,38.4,1,1,0,0,0,114.3,11.3);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5).to({_off:false},0).to({x:114.9,alpha:1},11,cjs.Ease.get(1)).to({x:113.15},9,cjs.Ease.get(1)).wait(22).to({startPosition:0},0).to({_off:true},1).wait(1361));

	// Layer_1
	this.instance_1 = new lib.Symbol24("synched",0);
	this.instance_1.setTransform(112.3,10.6,1,1,0,0,0,113.1,11);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:1},16,cjs.Ease.get(1)).wait(31).to({startPosition:0},0).to({_off:true},1).wait(1361));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-35.1,-1.2,264.3,51);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol16copy2("synched",0);
	this.instance.setTransform(72.3,32.2,1,1,0,0,0,100.9,8);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5).to({_off:false},0).to({x:104.5,alpha:1},11,cjs.Ease.get(1)).to({x:103.8},9,cjs.Ease.get(1)).wait(80).to({startPosition:0},0).to({x:123.8,alpha:0},9,cjs.Ease.get(1)).wait(57).to({startPosition:0},0).to({_off:true},1).wait(740));

	// Layer_1
	this.instance_1 = new lib.Symbol6copy2("synched",0);
	this.instance_1.setTransform(61.5,11.8,1,1,0,0,0,96.5,11.8);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:97.25,alpha:1},11,cjs.Ease.get(1)).to({x:96.5},9,cjs.Ease.get(1)).wait(151).to({startPosition:0},0).to({_off:true},1).wait(740));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.3,3.6,206.4,48.8);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_282 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(282).call(this.frame_282).wait(1));

	// logo
	this.instance = new lib.Symbol13("synched",0);
	this.instance.setTransform(261.5,566.5,1,1,0,0,0,15.5,15.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(283));

	// Layer_12
	this.instance_1 = new lib.Symbol18();
	this.instance_1.setTransform(104.4,149.1,1,1,0,0,0,42.4,10.1);
	this.instance_1.alpha = 0.8008;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(175).to({_off:false},0).wait(108));

	// cta
	this.instance_2 = new lib.Symbol11("synched",0);
	this.instance_2.setTransform(100.5,151.8,1,1,0,0,0,43.5,7.8);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(130).to({_off:false},0).wait(153));

	// Layer_6
	this.instance_3 = new lib.Symbol23("synched",0);
	this.instance_3.setTransform(144.6,73.45,1.03,1.03,0,0,0,113.2,11.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(235).to({_off:false},0).wait(48));

	// Layer_7
	this.instance_4 = new lib.Symbol5("synched",0);
	this.instance_4.setTransform(122.55,67.4,1.04,1.04,0,0,0,96.7,11.9);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(111).to({_off:false},0).wait(172));

	// Layer_13
	this.instance_5 = new lib.Symbol21("synched",0);
	this.instance_5.setTransform(150.5,205.4,1,1,0,0,0,152.5,208.4);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(222).to({_off:false},0).wait(61));

	// Layer_8
	this.instance_6 = new lib.Symbol1("synched",0);
	this.instance_6.setTransform(150,300,1,1,0,0,0,150,300);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(98).to({_off:false},0).to({_off:true},148).wait(37));

	// Layer_10
	this.instance_7 = new lib.Symbol9("synched",0);
	this.instance_7.setTransform(83.3,459.8,1,1,0,0,0,62.3,11.8);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(16).to({_off:false},0).wait(73).to({startPosition:111},0).to({x:113.3,alpha:0,startPosition:127},10,cjs.Ease.get(1)).to({_off:true},147).wait(37));

	// Layer_5
	this.instance_8 = new lib.Symbol3("synched",0);
	this.instance_8.setTransform(67.9,471.8,1,1,0,0,0,51.9,11.8);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(12).to({_off:false},0).wait(74).to({startPosition:106},0).to({x:99.15,alpha:0,startPosition:122},10,cjs.Ease.get(1)).to({_off:true},150).wait(37));

	// Layer_4
	this.instance_9 = new lib.Symbol19("synched",0);
	this.instance_9.setTransform(125.25,434.9,1,1,0,0,0,104.7,11.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(89).to({startPosition:118},0).to({alpha:0,startPosition:134},10,cjs.Ease.get(1)).to({_off:true},147).wait(37));

	// Layer_8 copy
	this.instance_10 = new lib.Symbol1copy("synched",0);
	this.instance_10.setTransform(150,300,1,1,0,0,0,150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({_off:true},246).wait(37));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-49,-101.7,397.8,793.5);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,299,152,303.9);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg1.jpg?1700847286077", id:"bg1"},
		{src:"images/bg2.jpg?1700847286077", id:"bg2"},
		{src:"images/bg3.jpg?1700847286077", id:"bg3"},
		{src:"images/logo.png?1700847286077", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;